### PR TITLE
Members of internal types should not be public

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

Autofix GU0073: Member of non-public type should be internal.

https://github.com/GuOrg/Gu.Analyzers/blob/master/documentation/GU0073.md

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by rjmholt** [comment]
From https://github.com/PowerShell/PowerShell/pull/13425#issuecomment-674141211:

Generally I personally prefer public methods on internal and private classes; a class/object has a public API and private methods, internal implies a secondary API and muddies thinking around the cohesion and contract around a class. More than that, keeping members `public` is arguably *DRY*er, since the API represented by the class now has its exposure controlled by a single keyword at the class level.

However, in PowerShell there is a consideration that once you have an object, any public member on it is visible to PowerShell (even if the class itself is internal), which drives a lot of the other classes that have internal members on everything. So there is an externally appreciable difference between an internal type with public members and an internal type with internal members. While we don't consider an internal change like that to be breaking, it's still a change that could affect users.

**Comment by iSazonov** [comment]
> it's still a change that could affect users

If you say about reflection it is never public contract.

**Comment by rjmholt** [comment]
> If you say about reflection it is never public contract.

Agreed. My question is that there's a change being made, but for what benefit?

**Comment by xtqqczze** [comment]
This PR will require more effort before it can be built successfully.

I think the only benefit is in code review (verifying a method is not public API), so if this change could affect users I think it may not bring value. I wonder what other maintainer's think.

**Comment by iSazonov** [comment]
In my opinion, it is better to follow the principle of minimum visibility.

**Comment by SeeminglyScience** [comment]
Echoing @rjmholt's point, I see *a lot* of members "accidently" surfaced to PowerShell like this.  Say you have an API like this:

```csharp
public abstract class Food { }

internal class Apple : Food
{
    public int SeedCount { get; set; }
}

public static class Store
{
    public static Food GetFood()
    {
        return new Apple();
    }
}
```

If you call `[Store]::GetFood() | Get-Member`, the user has no way of knowing `SeedCount` isn't something they're supposed to be able to use.  Making a blanket change like this is pretty dangerous.

I took a quick glance over some of the changes and pretty quickly found one example of this, the formatting objects like `FormatStartData`.  There's no way to know that all of those properties are not part of breaking change contracts.  I've definitely seen code relying on these.

**Pull request closed without merging**
