### PR TITLE
Add raw output to invoke-restmethod for when you don't want any parsing. 

### PR DESCRIPTION
**Pull request by paulgmiller**
Still missing a unittest. but rest seems pretty simple.

### CODE REVIEW

**Comment by paulgmiller** [comment]
Hmm in manually testing seems to take -rawoutput but I don't see it in the help.

**Comment by SteveL-MSFT** [comment]
Trying to understand the use case of why someone would use this instead of just `invoke-webrequest` if they want to parse it themselves?

**Comment by joeyaiello** [comment]
Yeah, this seems like redundant behavior on top of `Invoke-WebRequest` to me. Both `HtmlWebResponseObject` (in Windows PowerShell) and `BasicHtmlWebResponseObject` (in PowerShell Core) contain the `RawContent` property, and `Invoke-WebRequest` supports all the same web request methods. 

@paulgmiller Do you have a scenario where `Invoke-WebRequest` doesn't fulfill your needs?

**Comment by TravisEz13** [comment]
Waiting on a response to:
>@paulgmiller Do you have a scenario where `Invoke-WebRequest` doesn't fulfill your needs?

**Comment by TravisEz13** [comment]
Closing because of no response.  Please re-open with an answer.  Thanks

**Pull request closed without merging**
