### PR TITLE
Allow non-default encodings to be used in user's script/code

### LINKED ISSUE #18537: "IBM437 is not supported encoding name" exception when saving Excel workbook on daily PS 7.3 build
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Saving Excel workbook with *ImportExcel* module on latest daily build of PS 7.3 throws following exception:
*(It works correctly on PowerShell 7.3.0 GA and PowerShell 7.2.7 or PowerShell 5.1)*
```powershell
PSMessageDetails      :
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "SaveAs" with "1" argument(s): "Error saving file ---"
                         ---> System.InvalidOperationException: Error saving file ---
                         ---> System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
                           at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
                           at System.Text.EncodingTable.GetCodePageFromName(String name)
                           at System.Text.Encoding.GetEncoding(String name)
                           at OfficeOpenXml.Packaging.Ionic.Zip.ZipOutputStream..ctor(Stream stream, Boolean leaveOpen)
                           at OfficeOpenXml.Packaging.ZipPackage.Save(Stream stream)
                           at OfficeOpenXml.ExcelPackage.Save()
                           --- End of inner exception stack trace ---
                           at OfficeOpenXml.ExcelPackage.Save()
                           at CallSite.Target(Closure, CallSite, ExcelPackage, Object)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\runtime\Operations\MiscOps.cs:line 1659
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\CallInstruction.Generated.cs:line 504
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:line 338
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:line 338
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\Interpreter.cs:line 101
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\LightLambda.Generated.cs:line 82
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\runtime\CompiledScriptBlock.cs:line 2435
                           at System.Management.Automation.CommandProcessorBase.Complete() in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\CommandProcessorBase.cs:line 593
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : InvalidOperationException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Close-ExcelPackage, C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.8.2\Public\Close-ExcelPackage.ps1: line 25
                        at Export-KBExcelNodeStatusReport<End>, <No file>: line 1001
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}

```

### Expected behavior

```console
The Excel workbook should be saved without exception like on PowerShell 7.3.0 GA and PowerShell 7.2.7, or PowerShell 5.1
```

### Actual behavior

```console
An exception is thrown.
```

### Error details

```console
PSMessageDetails      :
Exception             : System.Management.Automation.MethodInvocationException: Exception calling "SaveAs" with "1" argument(s): "Error saving file ---"
                         ---> System.InvalidOperationException: Error saving file ---
                         ---> System.ArgumentException: 'IBM437' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method. (Parameter 'name')
                           at System.Text.EncodingTable.InternalGetCodePageFromName(String name)
                           at System.Text.EncodingTable.GetCodePageFromName(String name)
                           at System.Text.Encoding.GetEncoding(String name)
                           at OfficeOpenXml.Packaging.Ionic.Zip.ZipOutputStream..ctor(Stream stream, Boolean leaveOpen)
                           at OfficeOpenXml.Packaging.ZipPackage.Save(Stream stream)
                           at OfficeOpenXml.ExcelPackage.Save()
                           --- End of inner exception stack trace ---
                           at OfficeOpenXml.ExcelPackage.Save()
                           at CallSite.Target(Closure, CallSite, ExcelPackage, Object)
                           --- End of inner exception stack trace ---
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\runtime\Operations\MiscOps.cs:line 1659
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\CallInstruction.Generated.cs:line 504
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:line 338
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:line 338
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\Interpreter.cs:line 101
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\LightLambda.Generated.cs:line 82
                           at System.Management.Automation.PSScriptCmdlet.RunClause(Action`1 clause, Object dollarUnderbar, Object inputToProcess) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\runtime\CompiledScriptBlock.cs:line 2435
                           at System.Management.Automation.CommandProcessorBase.Complete() in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\CommandProcessorBase.cs:line 593
TargetObject          :
CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : InvalidOperationException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Close-ExcelPackage, C:\Program Files\WindowsPowerShell\Modules\ImportExcel\7.8.2\Public\Close-ExcelPackage.ps1: line 25
                        at Export-KBExcelNodeStatusReport<End>, <No file>: line 1001
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.3
PSEdition                      Core
GitCommitId                    7.3.0-preview.3-461-g9f459c05f617fe530dac340aa546d198724d85da
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1, 6.0.0, 6.1.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

exception

### PR DESCRIPTION
**Pull request by daxian-dbw**
## PR Summary

Fix #18537

Fix the regression to allow non-default encodings to be used in user's script/code.

Move the registration of `CodePagesEncodingProvider` to the static constructor of `AutomationEngine`, which is before the `AutomationEngine` constructor is called, which calls into `iss.Bind(...)` that may run user code.

Also, almost right after creating an `AutomationEngine` instance in `LocalRunspace.DoOpenHelper()`, `InitialSessionState.BindRunspace` will be called, which will try loading modules (could be custom modules) that are specified in the `InitialSessionState` instance.

In fact, `Encoding.GetEncoding('IBM437')` doesn't really work consistently as of today (7.2 or 7.3), here is a simple repro:
```
## Running this from 7.2.x or 7.3.0 fails because no module loading gets triggered, and thus, the call
## to `GetDefaultEncoding()` doesn't happen as early as when `PSReadLine` is auto-loaded at startup.
pwsh -noprofile -c "[System.Text.Encoding]::GetEncoding('IBM437').WebName"
```
You will get this failure:

image

So, this PR is to make it a consistent, predictable behavior.

## PR Context

The root cause of the regression is:
- before the change of #18356, `Encoding.RegisterProvider` will be called on the first time retrieving the default encoding by `GetDefaultEncoding()`, which happens when loading the `PSReadLine` module on startup. So, the encoding provider gets registered early enough for `GetEncoding("IBM437")` to work in user script/code. 
- after #18356, `Encoding.RegisterProvider` won't be called until `GetOEMEncoding()` is called, which happens pretty late -- until you run a cmdlet that accesses `EncodingConversion`. So, the encoding provider is not registered when `GetEncoding("IBM437")` is used in user script/code.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Comment by iSazonov** [comment]
I did not found an API being out of AutomationEngine which could depend on `Encoding.RegisterProvider`, nevertheless please confirm.

**Comment by daxian-dbw** [comment]
I called it out in the PR description: `iss.Bind(...)` in its constructor may run user code -- binding provider and etc.

**Comment by iSazonov** [comment]
@daxian-dbw Please look CI MacOS fails.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@SeeminglyScience Please review.

**Comment by kilasuit** [comment]
@daxian-dbw just an FYI - I had to do more investigation into this PR than was needed due to you doing a little bit of clean up without it being associated to a commit, particularly when looking at `/src/System.Management.Automation/utils/EncodingUtils.cs` in this PR as by using the GitHub Web UI it just looks like there was code being removed that could not be easily accounted for, but could have been with a commit message for that file. Whilst I get that you'll likely have been entirely within vscode for this PR you should in future remember that it's not just vscode that we can look at PRs going forward.

**Comment by daxian-dbw** [comment]
@kilasuit Thanks for the feedback!
@SeeminglyScience Can you please review when you get a chance? Thanks!

**Comment by iSazonov** [comment]
@SeeminglyScience Friendly ping!

**Review by SeeminglyScience — APPROVED** [review]
Sorry for the delay, LGTM!

**Comment by iSazonov** [comment]
Great! 👍

**Pull request merged**
