### PR TITLE
Update changelog for alpha.10

### PR DESCRIPTION
**Pull request by andyleejordan**
/cc @PowerShell/powershell-maintainers 

Resulting merge commit should be v6.0.0-alpha.10 tag.

### CODE REVIEW

**Comment by andschwa** [comment]
Actually, I'd posit that we tag the tip of master currently. Then build and post packages and merge this (along with documentation updates for version name).

**Comment by bgelens** [comment]
Installed x64 Win10 MSI. PSVersionTable shows dirty git commit id.
image

**Comment by vors** [comment]
Cc @daxian-dbw 
We may need to re-create this msi and maybe other packages.
We should add a check for that in `Starr-PSPackage`.

**Comment by daxian-dbw** [comment]
Ah, it's probably because I had to change `Get-PackageVersionAsMajorMinorBuildRevision` in build.psm1 to get the right version before running `Start-PSPackage`.

**Comment by andschwa** [comment]
Ha, it's not the first time that's happened. Since the PSVersionTable does just read from a file, you can modify powershell.version in the publish directory and overwrite the GitCommitId not have -dirty. Kind of cheating but sometimes necessary.

**Comment by daxian-dbw** [comment]
I have uploaded new `.msi` and `.zip` packages that fix the GitCommitId. But they are not digitally signed :(

**Pull request merged**
