### PR TITLE
Treat unbound command parameters as command arguments

### PR DESCRIPTION
**Pull request by AndrewGaspar**
This addresses some of the problems reported in Issue #2912. It fixes native tab completion for tokens that begin with a single "Dash" (defined by CharTraits.IsDash), but it does not fix native tab completion for the '--' token.

### CODE REVIEW

**Review by lzybkr — CHANGES_REQUESTED** [review]
The code change looks good - it even fixes a corner case of completing filenames that start with a `-`.

Can you add a test in test\powershell\Language\Parser\ExtensibleCompletion.Tests.ps1?

**Comment by AndrewGaspar** [comment]
Was having issues running the tests - finally figured out it was because I didn't sync the submodules. Should have read the README more carefully. :)

**Comment by AndrewGaspar** [comment]
Pretty sure this is an infrastructure failure. Can we re-run?

**Review by powercode — COMMENTED** [review]
I think we should take a stab at fixing double dash '--' at the same time.
Also common in native commands.

https://github.com/powercode/PowerShell/commits/native-arg-hyphen seems to work, but I haven't tested it properly.

**Review by lzybkr — APPROVED** [review]

**Comment by lzybkr** [comment]
@powercode - these changes seem fine to me and I see no reason to not merge. If you want to fix double hypen in another PR, that would be great.

**Comment by AndrewGaspar** [comment]
Let's just merge and close the PR. Double hyphen can be done another time.

**Pull request merged**
