### PR TITLE
Revert "Pull PSReadLine from PSGallery"

### LINKED ISSUE #5973: Nightly Builds failing after #5759
#5759 changes were merged without any `[feature]` tags for full testing. Now nightly and PR builds are failing.

Again, I'm asking that we start running feature tests by default in PRs. Trying to determine what is and is not a feature affecting change is proving to be pointless. If you are concerned about quick README updates, add a README tag to bypass feature tests. Otherwise, they should be on by default, IMO.

https://ci.appveyor.com/project/PowerShell/powershell-f975h

```none
TEST FAILURES
Description: Validate Update-Help for module 'PSReadLine'
Name:        Validate Update-Help from the Web for all PowerShell Core modules...Validate Update-Help for module 'PSReadLine'
message:
Expected: {1}
But was:  {0}
stack-trace:
at line: 157 in C:\projects\powershell-f975h\test\powershell\engine\Help\UpdatableHelpSystem.Tests.ps1
157:     $helpFilesInstalled.Count | Should Be $expectedHelpFiles.Count
Description: Validate Update-Help for module 'PSReadLine'
Name:        Validate Update-Help -SourcePath for all PowerShell Core modules...Validate Update-Help for module 'PSReadLine'
message:
Expected: {1}
But was:  {0}
stack-trace:
at line: 157 in C:\projects\powershell-f975h\test\powershell\engine\Help\UpdatableHelpSystem.Tests.ps1
157:     $helpFilesInstalled.Count | Should Be $expectedHelpFiles.Count
```

https://travis-ci.org/PowerShell/PowerShell/jobs/331386328

```none
TEST FAILURES
Description: Validate Update-Help from the Web for all PowerShell Core modules./
Name:        Validate Update-Help for module 'PSReadLine'
message:
Expected: {1}
But was:  {0}
stack-trace:
at line: 157 in /home/travis/build/PowerShell/PowerShell/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
157:     $helpFilesInstalled.Count | Should Be $expectedHelpFiles.Count
Description: Validate Update-Help -SourcePath for all PowerShell Core modules./
Name:        Validate Update-Help for module 'PSReadLine'
message:
Expected: {1}
But was:  {0}
stack-trace:
at line: 157 in /home/travis/build/PowerShell/PowerShell/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
157:     $helpFilesInstalled.Count | Should Be $expectedHelpFiles.Count
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input: 
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 352 in /home/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
352:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input:  -IntERactive
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 352 in /home/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
352:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input:  -i
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 352 in /home/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
352:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input w/ initial command
message:
Expected string length 7 but was 4. Strings differ at index 4.
Expected: {PS> 1+1}
But was:  {PS> }
---------------^
stack-trace:
at line: 372 in /home/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
372:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Redirected input explicit prompting (-File -)
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 388 in /home/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
388:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Redirected input no prompting (-Command -)
message:
Expected string length 1 but was 0. Strings differ at index 0.
Expected: {2}
But was:  {}
-----------^
stack-trace:
at line: 399 in /home/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
399:             $process.StandardOutput.ReadLine() | Should Be "2"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Redirected input w/ nested prompt
message:
Expected string length 29 but was 4. Strings differ at index 4.
Expected: {PS> $host.EnterNestedPrompt()}
But was:  {PS> }
---------------^
stack-trace:
at line: 432 in /home/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
432:             $process.StandardOutput.ReadLine() | Should Be "PS> `$host.EnterNestedPrompt()"
```

https://travis-ci.org/PowerShell/PowerShell/jobs/331386331

```none
TEST FAILURES
Description: Validate Update-Help from the Web for all PowerShell Core modules./
Name:        Validate Update-Help for module 'PSReadLine'
message:
Expected: {1}
But was:  {0}
stack-trace:
at line: 157 in /Users/travis/build/PowerShell/PowerShell/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
157:     $helpFilesInstalled.Count | Should Be $expectedHelpFiles.Count
Description: Validate Update-Help -SourcePath for all PowerShell Core modules./
Name:        Validate Update-Help for module 'PSReadLine'
message:
Expected: {1}
But was:  {0}
stack-trace:
at line: 157 in /Users/travis/build/PowerShell/PowerShell/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
157:     $helpFilesInstalled.Count | Should Be $expectedHelpFiles.Count
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input: 
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 352 in /Users/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
352:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input:  -IntERactive
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 352 in /Users/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
352:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input:  -i
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 352 in /Users/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
352:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input w/ initial command
message:
Expected string length 7 but was 4. Strings differ at index 4.
Expected: {PS> 1+1}
But was:  {PS> }
---------------^
stack-trace:
at line: 372 in /Users/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
372:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Redirected input explicit prompting (-File -)
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 388 in /Users/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
388:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Redirected input no prompting (-Command -)
message:
Expected string length 1 but was 0. Strings differ at index 0.
Expected: {2}
But was:  {}
-----------^
stack-trace:
at line: 399 in /Users/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
399:             $process.StandardOutput.ReadLine() | Should Be "2"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Redirected input w/ nested prompt
message:
Expected string length 29 but was 4. Strings differ at index 4.
Expected: {PS> $host.EnterNestedPrompt()}
But was:  {PS> }
---------------^
stack-trace:
at line: 432 in /Users/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
```

PR build failures: 
* https://travis-ci.org/PowerShell/PowerShell/jobs/331469515#L4276
* https://travis-ci.org/PowerShell/PowerShell/jobs/331469516#L3427

### PR DESCRIPTION
**Pull request by adityapatwardhan**
Reverts PowerShell/PowerShell#5759

This change causes Console test failures in non-windows platforms. The failures are for interactive use with redirected stdin.

closes  #5973

### CODE REVIEW

**Comment by daxian-dbw** [comment]
See the failures in https://travis-ci.org/PowerShell/PowerShell/builds/331938151?utm_source=github_status&utm_medium=notification

**Review by daxian-dbw — APPROVED** [review]

**Comment by daxian-dbw** [comment]
@adityapatwardhan Can you please use [feature] tag to trigger the full test run?

**Comment by adityapatwardhan** [comment]
@TravisEz13 All checks have passed.

**Comment by TravisEz13** [comment]
was an issue filed in PSReadline?

**Comment by adityapatwardhan** [comment]
PSReadline Issue: https://github.com/lzybkr/PSReadLine/issues/625

**Comment by daxian-dbw** [comment]
We should help fix that issue if possible so that we can switch to the 2.0.0 PSReadline ASAP.

**Comment by it-praktyk** [comment]
Do I understand correctly that after resolving the issue: lzybkr/PSReadLine#625 a code introduced by https://github.com/PowerShell/PowerShell/commit/beffdcf94d00b51d9339bb26dbc0e477cd147c92 will be reused?

I'm asking because based on it I started work (as a continuation/replacement of #4618) to pull Pester from PowerShell Gallery too.

**Comment by lzybkr** [comment]
@it-praktyk - I think it's reasonable to assume my approach should be used for other modules like Pester.

**Pull request merged**
