### PR TITLE
Revert "Bump System.Text.Encodings.Web from 4.6.0-preview6.19303.8 to 4.6.0-preview.19113.10"

### PR DESCRIPTION
**Pull request by TravisEz13**
This was a downgrade.

### CODE REVIEW

**Comment by TravisEz13** [comment]
@PoshChan Please remind me in 30 minutes

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 30 minutes ago

**Comment by TravisEz13** [comment]
@PoshChan Please remind me in 15 minutes

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 15 minutes ago

**Review by adityapatwardhan — APPROVED** [review]

**Pull request merged**
