### PR TITLE
Enable CA1830: Prefer strongly-typed Append and Insert method overloads on StringBuilder

### PR DESCRIPTION
**Pull request by xtqqczze**
https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1830

### CODE REVIEW

**Comment by xtqqczze** [comment]
@iSazonov Can you approve?

**Review by iSazonov — APPROVED** [review]

**Comment by xtqqczze** [comment]
`/home/vsts/.dotnet/sdk/5.0.100-rc.2.20479.15/NuGet.targets(131,5): error : Failed to retrieve information about 'PowerShellGet' from remote source 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='PowerShellGet'&semVerLevel=2.0.0'. [/home/vsts/work/1/s/src/Modules/PSGalleryModules.csproj]
`

**Comment by xtqqczze** [comment]
@iSazonov Please restart tests.

**Comment by xtqqczze** [comment]
Build failures are due to PowerShell Gallery unavailability, see #13946.

**Comment by xtqqczze** [comment]
closing and reopening to restart tests

**Comment by xtqqczze** [comment]
@iSazonov Could you merge?

**Pull request merged**
