### PR TITLE
Update CachedReflectionInfo class with parameter types

### LINKED ISSUE #9016: Review CachedReflectionInfo class to validate method overloades and unused types
Please review the code under [Compiler.cs](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/parser/Compiler.cs) and look at all the methods we cache. We need to specify the parameters too when we do `GetMethod` on a type so we explicitly load a particular overload.

See #9015 

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.1.3
PSEdition                      Core
GitCommitId                    6.1.3
OS                             Microsoft Windows 10.0.18845
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Related #9016

Use GetMethod overload which allow to specify types of parameters.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@iSazonov I replied to your comment in the issue https://github.com/PowerShell/PowerShell/issues/9016#issuecomment-469052955. The update should focus on operations with public members of public types. I don't see a need to do the same for internal types. And furthermore, maybe we can ignore such operations on public interfaces too.

**Comment by iSazonov** [comment]
@daxian-dbw Thanks! I already have done. It was a lot of work. 
Seem there is very few public methods. So I leave this at your discretion.

One additional thought. While I was working on it, it turned out that these changes are very sensitive, while the diagnosis is very scanty. If someone changes an internal api, then pwsh can fall with a non-informative error and it will be very difficult to find the cause of the problem. The change doesn't add more information in error message but reduces the likelihood of conflicts and as a result simplify diagnostic.

**Comment by daxian-dbw** [comment]
@iSazonov I appreciate the effort you put behind this PR, thanks!
I'm not too worried about the internal types. Say you are adding an overload to one of the methods used here, then you definitely need to understand what the existing method is used for. Therefore, you will see how it's used in `CachedReflectionInfo` and gets it updated appropriately as part of your new code.

I'm mainly worried about the .NET public types, because we have no control on changes to them in future version of .NET Core.

**Comment by iSazonov** [comment]
> then you definitely need to understand what the existing method is used for.

Yes, but some our namespace is so large that we have the same problem as with public.

So you request is to leave only public (without interfaces)?

Additional: looking how difficult to make signatures for reflection I am thinking about request to enhance .Net Core like:
```c#
 static readonly MethodInfo stringIndex =  typeof(System.String).GetMethod("public int IndexOf(char value, StringComparison comparisonType)")
``

**Comment by iSazonov** [comment]
@daxian-dbw I found only one public type.

**Review by daxian-dbw — APPROVED** [review]
Thank you @iSazonov for making so much effort on this!
Sorry that I didn't make my intention clear enough in the issue, which caused you to spend some effort in vain :(

**Comment by iSazonov** [comment]
@daxian-dbw It was a useful mindful exercise. :-) Besides, I learned that refletion is sometimes very confusing.
What do think make sense ask Core team add something like:
```c#
 static readonly MethodInfo stringIndex =  typeof(System.String).GetMethod("public int IndexOf(char value, StringComparison comparisonType)")
```
or
```c#
 public delegate int IndexOfDelegate(char value, StringComparison comparisonType)
 static readonly MethodInfo stringIndex =  typeof(System.String).GetMethod(IndexOfDelegate)
```

**Comment by daxian-dbw** [comment]
I don't think they will accept these proposals. The reflection APIs have been there for a long time, and I double they will do any enhancement on them now.

> static readonly MethodInfo stringIndex =  typeof(System.String).GetMethod("public int IndexOf(char value, StringComparison comparisonType)")

This means the string has to be parsed to the real signature, meaning that the compiler-ish thing needs to kick in ... that's a lot work for not much value.

> public delegate int IndexOfDelegate(char value, StringComparison comparisonType)

This means you have to define a delegate for the reflection operation, it's almost same as constructing the `type[]` you need for the call.

**Pull request merged**
