### PR TITLE
Display com method signature with argument names

### PR DESCRIPTION
**Pull request by nbkalex**
# PR Summary
This adds relevant information about com object method signature: argument names.
Not showing argument names can be misleading when calling a method with multiple arguments.

## PR Context
I'm implementing com objects for PowerShell usage.
Calling most of the com object methods with more then 1 argument of the same type  from PowerShell was not so intuitive even if the method name describes very well the implementation.
IMO, showing argument names would improve a lot the experience in using com objects.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by iSazonov** [comment]
@nbkalex Please add PR summary and context, and tests.

**Comment by iSazonov** [comment]
@nbkalex Please add tests before we start code review. If you need help feel free to ask.

**Comment by nbkalex** [comment]
@iSazonov I don't have enough time these days to study your testing infrastructure. It would be nice if someone can contribute to this PR writing tests.

**Comment by iSazonov** [comment]
I added new test.

**Comment by nbkalex** [comment]
I checked out the function signature in the Shell type library and it looks good

**Comment by iSazonov** [comment]
CI Windows temporary failed - waiting Azure team solution.

**Review by adityapatwardhan — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
@nbkalex Thank you for your contribution!

**Comment by nbkalex** [comment]
Thank you. More will come :)
Thank you @iSazonov. Wouldn't be ready without your help :)

**Pull request merged**
