### PR TITLE
Fix docker tests

### PR DESCRIPTION
**Pull request by TravisEz13**
- remove `OpenSUSE` and `amazonlinux` as they are not community images and not published.

### CODE REVIEW

**Comment by adityapatwardhan** [comment]
@TravisEz13  Can you add in the description why openSUSE and AmazonLinux were removed?

**Review by daxian-dbw — APPROVED** [review]
@adityapatwardhan AmazonLinux and openSUSE are removed because we don't publish docker images for these 2 distros for now.

**Comment by daxian-dbw** [comment]
@TravisEz13 I think we should always target the mater branch, and cherrypick commits to 6.0.0 branch, right?

**Comment by TravisEz13** [comment]
Marking for GA so we can test docker correctly for GA

**Pull request merged**
