### PR TITLE
Make UseAbbreviationExpansion and TempDrive non-experimental features

### LINKED ISSUE #4216: Provide a platform-agnostic way to determine the temp. directory, e.g., via an automatic variable.
<sup>Related: #3442 and #4215</sup>

The various supported platforms have different native ways to determine the directory in which to store temporary files and directories:

* Windows:
    * `$env:TEMP`
* macOS:
    * `$env:TMPDIR`
* Linux:
    * `/tmp`

Currently, there is no platform-agnostic way to refer to this directory, which is cumbersome.

An automatic variable, say `$TEMP`, could provide this abstraction.

Environment data
----------------

```powershell
PowerShell Core v6.0.0-beta.3
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

As discussed in @PowerShell/powershell-committee, we are taking the Abbreviation Expansion and TempDrive experimental features out of experimental status.

Removed all the experimental feature wrappers.  Also updated an unrelated tab-completion test for ErrorRecord to be more reliable.  It seems that sometimes an error shows up in $error that is not what the test expects.  So fix is to check against the specific exception we expect rather than the top of the $error stack as that might change between the test and using $error[0].

Some manual perf tests using `Get-Command` and `TabExpansion2` indicates that abbreviation expansion doesn't add any noticeable perf difference.  Most of the time seems to be enumerating the commands available.

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/4216

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [X] [Documentation needed] https://github.com/MicrosoftDocs/PowerShell-Docs/pull/4422(https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 2 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/assets/README.md.https://www.microsoft.com/en-us/legal/intellectualproperty/permissions should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 113
113:                                 throw "retry of URL failed with error: $($_.Message)"

```
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/cmdlet-example/command-line-simple-example.md.https://www.microsoft.com/net/core#linuxubuntu should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 113
113:                                 throw "retry of URL failed with error: $($_.Message)"

```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-macos`
TabCompletion.Miscellaneous completion tests.Input 'try { 1/0 } catch {};$error[0].' should successfully complete
```powershell
Expected 'CategoryInfo' to be found in collection @('Data', 'ErrorRecord', 'HelpLink', 'HResult', 'InnerException', 'Message', 'Source', 'StackTrace', 'TargetSite', 'WasThrownFromThrowStatement'), but it was not found.
at <ScriptBlock>, /Users/vsts/agent/2.152.1/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1: line 577
577:             $res.CompletionMatches.CompletionText | Should -Contain $expected
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-linux`
TabCompletion.Miscellaneous completion tests.Input 'try { 1/0 } catch {};$error[0].' should successfully complete
```powershell
Expected 'CategoryInfo' to be found in collection @('Data', 'ErrorRecord', 'HelpLink', 'HResult', 'InnerException', 'Message', 'Source', 'StackTrace', 'TargetSite', 'WasThrownFromThrowStatement'), but it was not found.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1: line 577
577:             $res.CompletionMatches.CompletionText | Should -Contain $expected
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-windows`
TabCompletion.Miscellaneous completion tests.Input 'try { 1/0 } catch {};$error[0].' should successfully complete
```powershell
Expected 'CategoryInfo' to be found in collection @('Data', 'ErrorRecord', 'HelpLink', 'HResult', 'InnerException', 'Message', 'Source', 'StackTrace', 'TargetSite', 'WasThrownFromThrowStatement'), but it was not found.
at <ScriptBlock>, D:\a\1\s\test\powershell\Host\TabCompletion\TabCompletion.Tests.ps1: line 577
577:             $res.CompletionMatches.CompletionText | Should -Contain $expected
```

**Review by daxian-dbw — APPROVED** [review]
Did you get a chance to check the overhead added to regular command completion after enabling `PSUseAbbreviationExpansion`?

**Review by iSazonov — APPROVED** [review]

**Comment by SteveL-MSFT** [comment]
@daxian-dbw yes, I had that in the PR description above.  No measure-able difference.  Most of the time is spent in the code enumerating the commands, the code to check against the abbreviation is very small in comparison.

**Pull request merged**
