### PR TITLE
WIP - Add README reference to Command Line Rosetta Stone

### PR DESCRIPTION
**Pull request by mikemaccana**
## PR Summary

A modern version of the traditional Unix Rosetta Stone, which is maintained, includes Powershell, and has more detail than the table below.

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [x] Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [`NA`] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [`NA`] Issue filed - Issue link:
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [`NA`] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [`NA`] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

### CODE REVIEW

**Review by TravisEz13 — DISMISSED** [review]

**Comment by alexandair** [comment]
@TravisEz13 @joeyaiello Most of PowerShell commands in Command Line Rosetta Stone are not applicable to PowerShell Core.

**Comment by iSazonov** [comment]
I can not open the site in the latest IE version. 😕

**Comment by daxian-dbw** [comment]
@TravisEz13 Like @alexandair mentioned, some commands there don't work with PowerShell Core, like `Get-WmiObject` and `*-EventLog` commands, as well as `[Environment]::OSVersion`, which doesn't give the correct OS version.

**Comment by TravisEz13** [comment]
I looked at CommandLine Rosetta stone... you can make changes, but I didn't look and see if you could add a new option.

**Review by TravisEz13 — CHANGES_REQUESTED** [review]
I don't think the commands are correct for PowerShell core.

**Comment by iSazonov** [comment]
I suggest postponing this change until they become relevant.

**Comment by TravisEz13** [comment]
Thanks, if you are going to do the edits.  Ping here and hopefully a few people can verify.

**Comment by TravisEz13** [comment]
Please remove WIP from title when the feedback has been addressed.

**Comment by mikemaccana** [comment]
Chasing this up, sorry about the delay but it's been hard finding docs on a few of the items. Summarising:

 - WMI commands removed and replaced with CIM https://github.com/certsimple/rosetta-stone

 - `Test-Connection` should be there in 6 but still seems to be missing, despite https://github.com/PowerShell/PowerShell/issues/1146. Maybe waiting on a new release. Does nayone know?

 - With things like `Resolve-DnsName` in PowerShell 6 - after reading https://docs.microsoft.com/en-us/powershell/scripting/whats-new/what-s-new-in-powershell-core-60?view=powershell-6#backwards-compatibility-with-windows-powershell, should I wait for the `DnsClient` and `NetTCPIP` module to be ported to Powershell 6? Will they be included in 6.1? or is there a better, cross platform solution we should promote instead?

Thanks.

**Comment by mikemaccana** [comment]
@TravisEz13 if you could let me know what you think re: above I can make any/all necessary changes.

**Comment by daxian-dbw** [comment]
> `Test-Connection` should be there in 6 but still seems to be missing, despite #1146. Maybe waiting on a new release. Does anyone know?

The original `Test-Connection` implementation was removed in https://github.com/PowerShell/PowerShell/pull/5277 to make way for @iSazonov's new implementation (PR #5328). However, the new `Test-Connection` didn't make in 6.0.

**Comment by mikemaccana** [comment]
Thanks @daxian-dbw I'll leave `Test-Connection` in so it's updated when 6.1 is out. Do you (or @TravisEz13 ) know about `Resolve-DnsName` per my comment above?

**Comment by TravisEz13** [comment]
@mikemaccana `Resolve-DnsName` is missing, at least on non-windows platforms.

**Pull request closed without merging**
