### PR TITLE
Use 'RequireAdminOnWindows' tag in Set-Date tests

### LINKED ISSUE #3099: Set-Date don't work and admin-elevated test is silently skipped
1. Currently `Set-Date` tests is silently skipped during elevated test phase in Start-PSPester because the tests use `Test-IsElevated` function instead of `RequireAdminOnWindows` tag.
2. Really if we manually run the test - one is failed:
```powershell
PS > Start-PSPester -Path \test\powershell\Modules\Microsoft.PowerShell.Utility\Set-Date.Tests.ps1 -binDir "C:\Program Files\PowerShell\6.0.0.15"
VERBOSE: Running pester tests at '\test\powershell\Modules\Microsoft.PowerShell.Utility\Set-Date.Tests.ps1'
with tag 'CI' and ExcludeTag 'Slow'

Describing Set-Date
 [-] Set-Date should be able to set the date in an elevated context 850ms
   Expected: the expression not to throw an exception. Message was {The parameter is incorrect}
       from \test\powershell\Modules\Microsoft.PowerShell.Utility\Set-Date.Tests.ps1:11 char:22
       +         { get-date | set-date } | Should not throw
       +                      ~~~~~~~~
   at line: 11 in \test\powershell\Modules\Microsoft.PowerShell.Utility\Set-Date.Tests.ps1
   11:         { get-date | set-date } | Should not throw
 [!] Set-Date should produce an error in a non-elevated context 90ms
Tests completed in 940ms
Passed: 0 Failed: 1 Skipped: 1 Pending: 0
```
The command is manually executed failed too (I tested on Windows 10 with PS Core beta 15):
```powershell
PS > get-date | set-date
set-date : The parameter is incorrect
At line:1 char:12
+ get-date | set-date
+            ~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-Date], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.SetDateCommand

PS > get-date

Saturday, February 4, 2017 9:09:32 PM


PS > set-date

cmdlet Set-Date at command pipeline position 1
Supply values for the following parameters:
Date: 2/4/2017
set-date : The parameter is incorrect
At line:1 char:1
+ set-date
+ ~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Set-Date], Win32Exception
    + FullyQualifiedErrorId : System.ComponentModel.Win32Exception,Microsoft.PowerShell.Commands.SetDateCommand
```

- [ ] So in [Set-Date.Tests.ps1](https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Utility/Set-Date.Tests.ps1) the test must be marked by `RequireAdminOnWindows` tag in order to run in admin-elevated phase.
And we could remove `Test-IsElevated` from the tests and from `Test.Helpers.psm1`.

/cc @JamesWTruher @vors 

- [ ] `Set-Date`  requires a fix (for Windows only?).

/cc @andschwa

### PR DESCRIPTION
**Pull request by stknohg**
## PR Summary

Fix #3099

Currently `Set-Date.Tests.ps1` dose not have `RequireAdminOnWindows` tag, so CI tests requiring elevated privilege are always skipped.
Using `RequireAdminOnWindows` tag instead of `Test-Elevated` function, I fix the problem.

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [x] Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [x] Issue filed - Issue link: [Set-Date don't work and admin-elevated test is silently skipped](https://github.com/PowerShell/PowerShell/issues/3099)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

### CODE REVIEW

**Comment by stknohg** [comment]
I've heard that CI tests on Linux/macOS are always run as sudo.
But it seems to be that CI tests on Linux/macOS is run as normal user.

**Comment by iSazonov** [comment]
@TravisEz13 Could you please clarify - do we run Unix tests under sudo?

**Review by TravisEz13 — DISMISSED** [review]

**Comment by TravisEz13** [comment]
Currently, yes all Linux tests run under `sudo`

**Comment by stknohg** [comment]
@TravisEz13 @iSazonov Thank you. I will correct and push the code.

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
I mentioned this in #5645 as a test case to fix when a similar tag is added for Linux.

**Comment by iSazonov** [comment]
Oh, I was sure we automatically under sudo on Unix.

**Comment by TravisEz13** [comment]
Please use WIP in the title of the PR if we are waiting for the author to update the PR.  Blocked should be used for issue where progress cannot be made (for example, we are waiting for another project.)

**Comment by TravisEz13** [comment]
The Linux tests should probably be skipped until a similar tag is added for Linux.  Add a comment with a link to the issue to say why.  https://github.com/PowerShell/PowerShell/issues/5645

**Comment by iSazonov** [comment]
I suppose it should be pending not skip.

**Comment by stknohg** [comment]
@iSazonov I don't think so.

It will take some time to fix #5645.  
This Pull Request improves all tests on Windows, improves partially on Linux/macOS immediately.
The rest correction should be done with #5645.

**Comment by TravisEz13** [comment]
skip is appropriate where a test works on one platform and not another.  Pending is where a test just doesn't work.

**Comment by iSazonov** [comment]
Skip is appropriate for tests which _normally_ shouldn't be executed.
Pending is appropriate for tests which _we should fix_.

**Review by adityapatwardhan — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
@stknohg Thank you for your contribution.

**Pull request merged**
