### PR TITLE
Revert change to have SetLocation() treat wildcarded path as literal if it exists

### LINKED ISSUE #6927: Changes in wildcard expansion logic
This issue is opened to discuss the change made in #5839 and its possible consequences.
Originally made to fix #5752 (avoid wildcard expansion in working folder path when opening new session), it also has other effects that require more careful evaluation.
*(following is the copy of my original comment)*

Something with implemented fix still bothers me.
When started playing with v6.1.0-preview.2, I realized that `Get-ChildItem` is also affected by this change.
And everything else using wildcard expansion now has added complexity - conditional branch with try-catch *(what kind of performance overhead it might also have, btw?)*

```
PS C:\ps_test> Get-ChildItem


    Directory: C:\ps_test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       24.05.2018      2:03                [ab]a
d-----       24.05.2018      2:03                aa
d-----       24.05.2018      2:03                ba


PS C:\ps_test> Get-ChildItem [ab]a


    Directory: C:\ps_test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       24.05.2018      2:03                [ab]a


PS C:\ps_test> Get-ChildItem [abc]a


    Directory: C:\ps_test


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       24.05.2018      2:03                aa
d-----       24.05.2018      2:03                ba
```

While this might even make it work as expected more times than before, it has an increased [level of surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). It might make issues caused by the use of `-Path` instead of `-LiteralPath` to show up less frequently but will make them harder to trace when they finally show up.
Using wildcards by default and literal path as an option was a major design mistake, imo. This patch makes a step back, but in a way that makes it less predictable. Is it OK to have more "magic"?

I also wonder why it was made in this way instead of just calling `Set-Location` with `-LiteralPath` when initializing a session? Working folder is by definition a literal path. It would've kept behavior changes to minimum.

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

This reverts commit 7459b5463904b7849320b7e834fda4e3274acd05.
Left the added tests as `Pending`.

Fix https://github.com/PowerShell/PowerShell/issues/6927

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
I wonder that Travis CI failed.

**Comment by anmenaga** [comment]
Historically, any change in 'namespaces' code has a high-risk of regressions in this high-traffic code path.
It is probably a good idea to have a green `[feature]` test pass on any such changes.

**Comment by SteveL-MSFT** [comment]
The test failure appears to be a symptom of https://github.com/PowerShell/PowerShell/issues/7032

**Comment by iSazonov** [comment]
@SteveL-MSFT We have a fix #7033

**Comment by SteveL-MSFT** [comment]
@iSazonov picked up #7033 fix, build is passing, can you review?

**Review by iSazonov — APPROVED** [review]
Leave a comment

**Review by rjmholt — APPROVED** [review]

**Review by BrucePay — APPROVED** [review]
LGTM

**Comment by iSazonov** [comment]
@TravisEz13 The commit has a description but multi-line - sorry that I missed it.

**Pull request merged**
