### PR TITLE
update to latest package references, runtime framework, and SDK

### PR DESCRIPTION
**Pull request by TravisEz13**
## PR Summary

update to latest package references, runtime framework, and SDK

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by anmenaga — APPROVED** [review]

**Comment by bergmeister** [comment]
Should we not also update the `RuntimeFrameworkVersion` in [PowerShell.Common.props](https://github.com/PowerShell/PowerShell/blob/master/PowerShell.Common.props) [here](https://github.com/PowerShell/PowerShell/blob/master/PowerShell.Common.props#L97) and in [test/Test.Common.props](https://github.com/PowerShell/PowerShell/blob/master/test/Test.Common.props) [here](https://github.com/PowerShell/PowerShell/blob/master/test/Test.Common.props#L8) to `2.1.2`?

**Review by daxian-dbw — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
They need to be updated here too: https://github.com/PowerShell/PowerShell/blob/master/tools/packaging/packaging.psm1#L1525-L1532

**Comment by TravisEz13** [comment]
@adityapatwardhan  more than what I changed was out of date.  I updated the script to read from the csproj.  I verified the script to get the data.

**Review by iSazonov — APPROVED** [review]
Leave a comment

**Comment by TravisEz13** [comment]
Thanks @iSazonov

**Pull request merged**
