### PR TITLE
Cleanup updatablehelpsystem and enable XSD validation on MAML help content

### PR DESCRIPTION
**Pull request by iSazonov**
## PR Summary

Related #3565 and #4357.

Easily review commit by commit:
- Remove old code for WebClient - currently HTTPClient is main in CoreFX.
- Restore XML Schema support - currently we have the API in CoreFX.
- Reorder `using` statements.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
Tests failed with "The Help content XSD file cannot be found in C:\projects\powershell\src\powershell-win-core\bin\Release"

I see that Windows PowerShell has `Schemas` directory in home folder.

Should we restore this or remove schemas support?

**Comment by adityapatwardhan** [comment]
@iSazonov Thanks for this PR. We should bring back the schema files as XSD validation seems to be supported in CoreCLR now.

**Comment by iSazonov** [comment]
@adityapatwardhan Please point me where I can get this files from. Can I copy them to the repo from Windows PowerShell directory?

**Comment by iSazonov** [comment]
@adityapatwardhan Schemas added.

**Review by adityapatwardhan — APPROVED** [review]
Please update the title to mention `enable XSD validation of maml help`

**Pull request merged**
