### PR TITLE
Update PowerShellGet to 2.0.0

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

Update version of PowerShellGet to 2.0.0

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by anmenaga** [comment]
I think @TravisEz13 mentioned to me that there is some functionality in VSTS to detect these things...

**Review by anmenaga — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
PackageManagement tests are part of `Feature` tests. Please push an empty commit with `[Feature]`.

**Comment by TravisEz13** [comment]
It looks like the PowerShellGet tests need to be updated.

**Comment by daxian-dbw** [comment]
The `Package Reference` from `package.tests.ps1` fails because `NJsonSchema` updates the revision number again. The revision number is incremented about every week.

I updated to the latest review in PR #7834. At the same time, we need to think about how to not get interrupted too much by this special package.

**Comment by SteveL-MSFT** [comment]
@daxian-dbw should we special case NJsonSchema to only look at major.minor?

**Comment by bmanikm** [comment]
@SteveL-MSFT I have updated the PowerShellGet tests, it looks like the new test failures are not related to  PowerShellGet, please take a look at the new test failures.

**Comment by TravisEz13** [comment]
rebased the PR to pick up fixes for test failures

**Comment by adityapatwardhan** [comment]
Rebase and pushed to update package references.

**Review by adityapatwardhan — APPROVED** [review]

**Pull request merged**
