### PR TITLE
Upgrade StyleCopAnalyzers to v1.2.0-beta.304

### PR DESCRIPTION
**Pull request by xtqqczze**
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/releases/tag/1.2.0-beta.304

Follow-up to #14293.

### CODE REVIEW

**Comment by xtqqczze** [comment]
@iSazonov Can we use dependabot to check for StyleCopAnalyzers updates?

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
> @iSazonov Can we use dependabot to check for StyleCopAnalyzers updates?

Why not? :-)

/cc @RDIL Thoughts?

**Comment by RDIL** [comment]
> > @iSazonov Can we use dependabot to check for StyleCopAnalyzers updates?
> 
> Why not? :-)
> 
> /cc @RDIL Thoughts?

Assuming the language is supported, there should be no problem.

**Comment by xtqqczze** [comment]
Who could submit PR for dependabot check?

**Comment by RDIL** [comment]
What language is `.props` @xtqqczze ?

**Comment by xtqqczze** [comment]
> What language is `.props` @xtqqczze ?

MSBuild

**Comment by RDIL** [comment]
> > What language is `.props` @xtqqczze ?
> 
> MSBuild

I'll check if dependabot supports it.

**Comment by xtqqczze** [comment]
Closed in favour of #14354.

**Pull request closed without merging**
