### PR TITLE
WIP:Add adapter to run Start-PSPester via vscode

### PR DESCRIPTION
**Pull request by nohwnd**
# PR Summary

Add an adapter that takes invocation from InvokePesterStub in vscode, and calls Start-PSPester. On the vscode side you would need this to be added. Ideally the interface of InvokePesterStub would get a bit more refined, because this would become a public api. I can probably provide that.

```powershell
# this would be added to VSCode options
$CustomPesterInvoker = "build\Start-PSPesterAdapter"

if ($CustomPesterInvoker) {
    $invoker = Get-Command $CustomPesterInvoker -ErrorAction Stop

    & $invoker -ScriptPath $ScriptPath -TestName $TestName -LineNumber $LineNumber -All:$All -MinimumVersion5:$MinimumVersion5 -Output $(if ($pesterModule.Version -lt "5.0.0") { $pester4Output } else { $Output })
    return
}
```

## PR Context

@TylerLeonhardt was interested in running PowerShell repo Pester tests via VSCode code lens. 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
I don't _think_ we need this. We just need to [configure VS Code to use your local build of PowerShell in the Integrated Console](https://docs.microsoft.com/en-us/powershell/scripting/components/vscode/using-vscode?view=powershell-7#adding-your-own-powershell-paths-to-the-session-menu).

Then CodeLens will use that local build when it runs `Invoke-Pester`.

**Comment by nohwnd** [comment]
@TylerLeonhardt but how will you get all the setup that start-pspester does? for example automatically building the underlying bits and filtering tests? When invoking via Invoke-Pester all of this would be skipped.

**Comment by TylerLeonhardt** [comment]
> For example automatically building the underlying bits and filtering tests?

Yeah I mean, you'll need to build the code already because you'll need to start the PowerShell extension with the built pwsh.exe so that the debugger APIs are hooked up properly.

And from a filtering perspective the CodeLens _is_ your filter is it not? Choosing to run 1 Describe, 1 Context or 1 It block.

**Comment by nohwnd** [comment]
Okay, if that works for you :) I would still rather see it work in a way that you can press the Debug button and it will build your pwsh.exe run it with the test and attach a debugger to it in a way the VSCode would understand. That way when you make changes in the compiled code you don't need to remember to run the build manually before triggering the test. But maybe I just don't fully understand the dependencies that are at play here. Feel free to abandon this PR 🙂

**Comment by TylerLeonhardt** [comment]
> I would still rather see it work in a way that you can press the Debug button and it will build your pwsh.exe run it with the test and attach a debugger to it in a way the VSCode would understand. 

I like this idea, but it makes it a bit more complex because now Start-PSPester will need to:

* build the pwsh.exe
* start the pwsh.exe (but don't run tests yet)
* attach to the process and debug the runspace that will run the tests (default runspace)
* start running the tests in the built pwsh.exe

So if we still want to go through with this (which I admit has value - the building is nice!) then this PR should also handle starting the pwsh.exe with:

```pwsh
Wait-Debugger
Invoke-Pester ...
```

**Comment by nohwnd** [comment]
```powershell
Wait-Debugger
Invoke-Pester 
```

I tried when we started talking about this, that but it did not attach to the VSCode debugger, instead it triggered the console debugger. Do I need to load some module before waiting for debugger to allow VSCode debugger to attach? I was starting a new pwsh process in from VSCode.

**Comment by adityapatwardhan** [comment]
@nohwnd Is this still being worked on?

**Comment by TylerLeonhardt** [comment]
I need to write a bunch of stuff on this. This is waiting on me.

**Comment by adityapatwardhan** [comment]
@TylerLeonhardt Should I assign this to you if you are working on this?

**Comment by TylerLeonhardt** [comment]
Yeah go for it

**Comment by TylerLeonhardt** [comment]
It's my fault. Let's just close this for now because I need to think about it some more. If I have time, later, we can reopen.

**Pull request closed without merging**
