### PR TITLE
Optimize Images!  

### PR DESCRIPTION
**Pull request by RDIL**
## PR Summary

My pal @ImgBotApp optimized all the images present in the repository.  

## PR Checklist

- [X] [PR has a meaningful title]
- [X] [Summarized changes]
- [X] [Change is not breaking]
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header]
- [X] This PR is ready to merge and is not [Work in Progress]
- **Testing - New and feature**
    - [X] Can be tested right away

### CODE REVIEW

**Comment by RDIL** [comment]
why did PowerShell-CI-linux — #PR-7874-20180926.01 fail :(

**Comment by RDIL** [comment]
Wait that's not my code thats failing

**Comment by iSazonov** [comment]
@RDIL Please rebase to get latest commits and pass CIs.

**Comment by RDIL** [comment]
I think I did it...

**Comment by RDIL** [comment]
That’s odd, some checks are still failing :(

**Comment by iSazonov** [comment]
@RDIL Please revert the file test/powershell/Modules/Microsoft.PowerShell.Security/TestData/CatalogTestData/TestImage.gif

**Comment by RDIL** [comment]
...

**Review by TravisEz13 — APPROVED** [review]

**Comment by iSazonov** [comment]
@RDIL Thanks for your contribution!

**Comment by RDIL** [comment]
:D

**Pull request merged**
