### PR TITLE
Combine Web Cmdlet Partial Class Files

### PR DESCRIPTION
**Pull request by markekraus**
Reference #5610 

This moves the partial class into a single file each. This code is purposely not sorted and the formatting is left alone to make this easier to review. There are cleanup actions planned in the referenced Issue.

### CODE REVIEW

**Comment by markekraus** [comment]
@iSazonov let me know if this is easier to work with.

**Comment by iSazonov** [comment]
Yes, it is more easy. I spent one hour to review the code. Thanks.

**Comment by iSazonov** [comment]
Doc tests failed again on WMF links. I think we could run doc tests with separate test tag. And maybe run some tests on demand by test tag.

**Review by iSazonov — APPROVED** [review]
LGTM.

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Comment by TravisEz13** [comment]
I restarted the mac tests, but they failed in webCmdLets.  If they fail again, can you investigate @markekraus

**Comment by markekraus** [comment]
It looks like it has been too long since the last commit to restart the the CI. I will push an empty commit.

**Comment by markekraus** [comment]
@TravisEz13 all passing now :)

**Comment by iSazonov** [comment]
😄 Our tests resemble a pinball machine in a casino.

**Pull request merged**
