### PR TITLE
Fix deviceguard test failure

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
investigating deviceguard failure.  only failing on AppVeyor.

### CODE REVIEW

**Comment by daxian-dbw** [comment]
The DeviceGuard test is still failing:
```
[-] Test for DeviceGuard properties 107ms
   Expected {0} to be greater than {0}
   at line: 1392 in C:\projects\powershell\test\powershell\Modules\Microsoft.PowerShell.Management\Get-ComputerInfo.Tests.ps1
   1392:                     $observed.DeviceGuardRequiredSecurityProperties.Count | Should BeGreaterThan 0
```

**Comment by adityapatwardhan** [comment]
If this is the only failure blocking daily builds, should we mark this test as pending on Windows, till we figure out the root cause. We have not had a successful daily build in about 19 days.

**Comment by SteveL-MSFT** [comment]
@adityapatwardhan good idea, I'll submit that as a different PR so I can keep investigating this

**Comment by iSazonov** [comment]
@SteveL-MSFT Maybe close the PR?

**Pull request closed without merging**
