### PR TITLE
WIP: Add progress to FileSystemProvider for `Copy-Item`

### LINKED ISSUE #18637: `Copy-Item` add support "report progress"
### Summary of the new feature / enhancement

when copy many files to remote computer ,  it's slow and nothing is report to user

### Proposed technical implementation details (optional)

```powershell
Copy-Item -Path ./* -Destination "D:/Dir" -ToSession $session -Recurse -Force -ReportProgess

Copy-Item -Path ./* -Destination "D:/Dir" -ToSession $session -Recurse -Force -ReportProgess  -ReportStyle "minimal |  filename | full"
```

-  `minimal`  (the default)  is only show a progress of total transfer
-  `filename`   will only show a progress of current processing file, 
-  `full`   will show a total progress bar and a mini progress bar for current file , and leave a log of filename to user when it's done

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

`Copy-Item` for FileSystemProvider already has progress for copying to/from PSSession, but nothing for local copies.  So for a large copy, the cmdlet just sits until it completes (although `-Verbose` could be used, but it's noisy and not the right way to get progress).  Change here is to have two progress bars, one when copying a file and another when copying a directory.  For directories, we can get the number of files within the directory and show percent complete.  However, we cannot get the total files/folders when used recursively (without incurring a huge up front cost to enumerate it all) so the progress doesn't show the total operation percent complete, but does indicate what is happening.

Screen-Recording-2022-12-05-at-4

## PR Context

Fix https://github.com/PowerShell/PowerShell/issues/18637

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by kilasuit** [comment]
for me there is far to much movement in the UI for this to be of any use
It needs some static elements to be of real use as things stand from the clip shared

**Comment by MartinGC94** [comment]
Nice. I was a little worried that this would impact the performance, but I tested it with a lot of small files (2.4GB, spread across 8613 files) and the performance stayed the same (around 8.8 seconds). Robocopy is still faster at around 6.1 seconds but that's hard to compete with.

**Comment by SteveL-MSFT** [comment]
The initial copy found a bunch of hash files in the "hidden" `.git` folder, so that's the hex numbers you see at the start.  However, under normal circumstances if copying lots of folders or larger files, then the content won't jump around so much.

**Comment by iSazonov** [comment]
It seems to me that such things are not useful in the sense that they do not solve the problems that they should.
If you have to constantly copy files, then after the first admiration comes the annoyance of useless flickering on the screen.
Does anyone really have time to read and remember file names in this progress bar? Really helps you? Really?

The main thing the progress bar is for is the frozen screen. When a user gets worried that the process is frozen? Usually it is 5-15 seconds. This means that there is no point in displaying the progress bar before this time has elapsed.

The second purpose of the progress bar is to show useful information for the user. 
Here we have two things (related to the frozen screen problem).
First, it makes no sense to show file names if you copy many small files. It is enough to show number of copied files (and probably total time/size of copying).
Second, there are situations of long copying of a large file. In this case it makes sense to display the file name and the copying progress to avoid the frozen screen problem - the last does not exist now.

I would like to have an API that allows to do such things OOB and save (module) developers (see for ex., ADUC or EMS (Exchange Server)) from duplication.

**Comment by SteveL-MSFT** [comment]
See if https://github.com/PowerShell/PowerShell/pull/18735 is preferred although there is a bigger perf penalty

**Pull request closed without merging**
