### PR TITLE
Rename -Not parameter to -IsNullOrEmpty in Where-Object cmdlet.

### PR DESCRIPTION
**Pull request by sethvs**
## PR Summary

**-Not** parameter is very ambiguous.
Is it better to rename it to **-IsNullOrEmpty**?

Also, **ParameterSetName** is changed to 'IsNullOrEmpty'.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by sethvs** [comment]
**Test-Connection.TraceRoute.TraceRoute works** AppVeyor test failed.
Should we restart tests?

**Comment by iSazonov** [comment]
`-Not` parameter was approved in #6464 - should we rename it?

/cc @SimonWahlin @SteveL-MSFT

**Comment by mklement0** [comment]
@iSazonov:

No, `-IsNullOrEmpty` is not appropriate, because `-Not` has a wider scope, applying to `[bool]` values too:

```powershell
[pscustomobject] @{ Foo = $False } | Where-Object -Not Foo   # OK, passes the input object through
```

**Comment by sethvs** [comment]
@mklement0 
Concerning creating an alias **-IsNullOrEmpty** for **-Not** parameters https://github.com/PowerShell/PowerShell/pull/6796#issuecomment-385997555 - this is IMO a totally different meaning and it will be even more confusing than now.

Agree, **-IsNullOrEmpty** is not ideal for [bool], but **-Not** has far wider meaning.
For example, it seems totally natural to use it like this:

```
ps | where name -Not -Eq 'pwsh'
```

So I think there should be better parameter name.

**Comment by iSazonov** [comment]
`Where-Object` is a bool filter - I don't see any problem with `-Not`.

**Comment by daxian-dbw** [comment]
I agree with @mklement0. `-Not` also applies to the numeric value 0:
```powershell
[pscustomobject] @{ Foo = 0 } | Where-Object -Not Foo
```
I don't see a problem with `-Not`. It aligns with the `-Not` operator, which is consistent.

**Comment by sethvs** [comment]
OK.
Not totally convinced but closing.

**Pull request closed without merging**
