### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
Added section for Community Dashboard

### CODE REVIEW

**Comment by iSazonov** [comment]
The link open "Page 5" - So conceived?

**Comment by SteveL-MSFT** [comment]
@iSazonov that seems to be a behavior of PowerBI.  I actually rearranged the pages so that "Page 1" showed first, but it seems to default to the most recently edited page.

**Comment by iSazonov** [comment]
Thanks! I think this is not a problem.

**Comment by joeyaiello** [comment]
Looks good, but maybe you could add a link to your blog explaining why and how it works? 

> For more information on how and why we built this dashboard, check out [this blog post](https://blogs.msdn.microsoft.com/powershell/2017/01/31/powershell-open-source-community-dashboard/).

**Comment by iSazonov** [comment]
@SteveL-MSFT I don't want open an Issue. It seems the dashboard sums by month for all years. I see this on Page 1 (Top community contributorsover last 30 days ) in "PRs Opened" and "PR Comments" columns.

**Comment by zjalexander** [comment]
@iSazonov ..........oh. hm. let me look into that. good catch!

**Pull request merged**
