### PR TITLE
Add HelpUri for Get-Uptime

### LINKED ISSUE #2659: Add helpuri to Get-Uptime cmdlet
Per discussion on #2517 (specifically [here](https://github.com/PowerShell/PowerShell/pull/2517#issuecomment-259549690) ) we need to adde HelpUri to this cmdlet.

### PR DESCRIPTION
**Pull request by daxian-dbw**
Fix #2659 
Got the fwlink from @TaraMeyer:
>Here’s your fwlink:  https://go.microsoft.com/fwlink/?linkid=834862.  When you’re ready to get the content for this new cmdlet published on MSDN and supported via updatable help- please reach out to JP, or myself.  Please keep in mind this link will not work correctly until the associated content is provided and published.

/cc @iSazonov

### CODE REVIEW

**Comment by iSazonov** [comment]
Good news! Thanks!

LGTM.

**Comment by Francisco-Gamino** [comment]
@daxian-dbw Please add this fwlink to https://github.com/PowerShell/PowerShell/blob/master/test/powershell/engine/Help/assets/HelpURI/V3Cmdlets.csv

**Comment by daxian-dbw** [comment]
@Francisco-Gamino Done.

**Comment by Francisco-Gamino** [comment]
LGTM. Thanks @daxian-dbw .

**Pull request merged**
