### PR TITLE
Add 'TimeToLive' and 'Hops' aliases to MaxHops parameter of Test-Connection cmdlet.

### LINKED ISSUE #7849: Add 'TimeToLive' and 'Hops' aliases to MaxHops parameter of Test-Connection cmdlet.
It would be useful to add the following aliases to **MaxHops** parameter of `Test-Connection` cmdlet:

**TimeToLive**
It is the similar parameter's name from **Windows PowerShell** `Test-Connection` cmdlet .

**Hops**
Similar parameter's name from `Test-NetConnection` cmdlet.

### PR DESCRIPTION
**Pull request by sethvs**
## PR Summary

Fix #7849 

Add the following aliases to **MaxHops** parameter of `Test-Connection` cmdlet:

**TimeToLive**
It is the similar parameter's name from **Windows PowerShell** `Test-Connection` cmdlet .

**Hops**
Similar parameter's name from `Test-NetConnection` cmdlet.

Fix **MaxHops** parameter summary.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed - Issue link: powershell/powershell-Docs#2956
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by sethvs** [comment]
Hm. I haven't touched NJsonSchema.

**Review by adityapatwardhan — APPROVED** [review]

**Comment by iSazonov** [comment]
@sethvs Please update NJsonSchema package version. It is not related to the PR but it come from our new common test.

**Comment by sethvs** [comment]
Should I update Markdig.Signed Version?

**Comment by iSazonov** [comment]
Feel free to update.

**Comment by anmenaga** [comment]
@adityapatwardhan is it something that requires "User-facing Documentation needed"
or alternative aliases will be automatically included in the help?

**Comment by sethvs** [comment]
@SteveL-MSFT Rebased.

**Comment by sethvs** [comment]
@anmenaga The help for **PowerShell Core 6.1** `Test-Connection` now is almost similar to **Windows PowerShell 5.1** `Test-Connection`. It should be massively reworked.

**Comment by adityapatwardhan** [comment]
@anmenaga Yes, we need to file an issue according to the template for updating the docs.

**Comment by sethvs** [comment]
@anmenaga @adityapatwardhan Created issue and PR in powershell-Docs repo.

**Comment by iSazonov** [comment]
@sethvs The PR still contains other's commits. Please rebase properly.

**Pull request merged**
