### PR TITLE
Unregister the event handler from 'AppDomain.CurrentDomain.ProcessExit' when uninitializing AMSI

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Unregister the event handler from `AppDomain.CurrentDomain.ProcessExit` when uninitializing AMSI.

The event handler was registered when opening a Runspace, but not unregistered when closing.
In the hosting scenario, every time a Runspace is opened/closed, an instance of the `EventHandler` will be left behind linked to the `AppDomain.CurrentDomain`. In a dump file provided by a partner team, there are 588017 such `EventHandler` instances leaked.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by daxian-dbw** [comment]
I tried to add a test, but I cannot find a way to get the `EventHandler` methods from the `event` member `AppDomain.ProcessExits` ...

**Review by iSazonov — COMMENTED** [review]
I wonder that
internal static void WinCloseSession()
and
internal static void WinUninitialize()
is not under `#if !UNIX ... #endif`

Can we use a global static counter for test?

**Comment by daxian-dbw** [comment]
I can get the invocation method list in .NET, but not in .NET Core. The following works in Windows PowerShell
```powershell
$f = [System.AppDomain].GetFields([System.Reflection.BindingFlags]::Instance -bor [System.Reflection.BindingFlags]::NonPublic -bor [System.Reflection.BindingFlags]::GetField) | ? name -eq '_processExit'
$v = $f.GetValue([System.AppDomain]::CurrentDomain)
$v.GetInvocationList()

Method                                                          Target
------                                                          ------
Void DisposeOnShutdown(System.Object, System.EventArgs)
Void CurrentDomain_ProcessExit(System.Object, System.EventArgs)
Void SingletonDomainUnload(System.Object, System.EventArgs)     {System.EventHandler}
```

So at least I can add a test when porting this change to Windows PowerShell.

**Review by TravisEz13 — APPROVED** [review]

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by iSazonov** [comment]
@daxian-dbw I got it:
```powershell
$f = [System.AppContext].GetFields([System.Reflection.BindingFlags]::Instance -bor [System.Reflection.BindingFlags]::NonPublic -bor [System.Reflection.BindingFlags]::GetProperty -bor [System.Reflection.BindingFlags]::Static) | ? name -eq 'ProcessExit'
$v = $f.GetValue([System.AppDomain]::CurrentDomain)
# or $f.GetValue([System.AppContext]::ProcessExit)

$v.GetInvocationList()
```

**Comment by daxian-dbw** [comment]
@iSazonov This is very strange, and feels to me may randomly stop working in future .NET Core 😄

**Comment by iSazonov** [comment]
@daxian-dbw AppContext is public API and the property is static - it is not likely that this public API will be changed.

**Comment by daxian-dbw** [comment]
Ahh, I thought it was `[System.AppDomain]`. Just realized you were using `[System.AppContext]`.
> $f.GetValue([System.AppDomain]::CurrentDomain)

This is wrong, should pass in `$null` as argument. I will submit a test for this change then.

**Comment by daxian-dbw** [comment]
Hmm, I cannot write a Pester test for this, because the leak won't happen as long as a Runspace still opens. Need to do it in xUnit.

**Comment by iSazonov** [comment]
> This is wrong, should pass in $null as argument.

I don't understand your thought. It seem works well in the example I posted.

**Comment by daxian-dbw** [comment]
It's a static field, so should pass `null` when calling `GetValue`. Your code works but that may be because the dotnet implementation just ignored the passed in argument, which could change to check for `null` in future.

**Comment by iSazonov** [comment]
Sorry, if I noisy but I always wonder how in-depth you look.
Do you mean that `[System.AppDomain]::CurrentDomain` can be null? I see it is non-nullable and initialized with `new AppDomain()`.
Also we can use `$f.GetValue([System.AppContext]::ProcessExit)` as I mentioned in example above.

**Comment by daxian-dbw** [comment]
I was not clear in my above statement. Today, you can pass anything to `$f.GetValue()` when it's a static field. For example:
```
PS:32> $f = [System.AppContext].GetFields([System.Reflection.BindingFlags]::NonPublic -bor [System.Reflection.BindingFlags]::GetProperty -bor [System.Reflection.BindingFlags]::Static) | ? name -eq 'ProcessExit'
PS:33> $f.GetValue("fff")

Target Method
------ ------
       Void CurrentDomain_ProcessExit(System.Object, System.EventArgs)
```
It may be because today the .net implementation ignore the argument when the field is static, but this could change in future so that exception would be thrown if the passed in argument is not null.

**Comment by iSazonov** [comment]
Thanks for clarify! 
It would be a breaking change which is incredible for dotnet runtime.

**Pull request merged**
