### PR TITLE
Batch merge builds together while a merge build is running

### PR DESCRIPTION
**Pull request by TravisEz13**
## PR Summary

Batch merge builds together while a merge build is running 

## PR Context  

Help keep agents available for CI runs.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.  
- **User-facing changes**
    - [x] Not Applicable
    - **OR**  
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by adityapatwardhan — APPROVED** [review]

**Comment by iSazonov** [comment]
@TravisEz13 Could you please add more info about benefits of the change for my education?

**Comment by vexx32** [comment]
@iSazonov See here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=vsts&tabs=yaml#continuous-integration-ci

I could be missing some nuances also, but it appears that they're looking to batch together builds that originate from the same PR in order to allow Azure to queue a batch job if someone pushes a bunch of commits in quick succession; it will simply build them as one, shortening the overall build time. 🙂

**Comment by iSazonov** [comment]
@vexx32 Thanks. I still don't understand how it works really.

**Comment by TravisEz13** [comment]
This does not batch PR builds.  This batches merge (or as Azure DevOps calls them CI builds)  while a merge build is in progress.

So if we merge PR A and a merge build starts.

Then we merge PR B and C while the build for PR A is still running, the next build will build B & C.

The feature @vexx32 mentioned is on by default.

**Comment by vexx32** [comment]
Appreciate the clarification, looks like I gotta brush up on the yml spec once again. 😄

**Pull request merged**
