### PR TITLE
Use TLS 1.2 in Start-PSBootStrap Without Breaking HTTPS

### PR DESCRIPTION
**Pull request by markekraus**
## PR Summary

Fixes breaking changes made in #6235 
ref #6233

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [X] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
I'd prefer set TLS12 only for GitHub request and then revert to SystemDefault.

**Comment by vors** [comment]
Hey @markekraus you beat me! I did the @iSazonov suggestion in #6237 , can you review it please?

**Comment by markekraus** [comment]
@iSazonov We would need to update this all over the place.. I believe turning on tls 1.2 is fine as a boot strap operation in general.

**Comment by markekraus** [comment]
Yes but we have a bunch of helper function etc that rely on iwr calls to github. So as a bootstrap operation, it makes complete sense to just enable TLS 1.2 for the session. my method doesn't break any of the current settings, it just makes 1.2 enabled as a possibility.

**Comment by iSazonov** [comment]
I am afraid to change this setting at all because it has unpredictable changes in the future on system level. The best thing would be to use a parameter `-Protocol` out of this, but if we want it to work on Windows PowerShell version, it's best to make a fix only for broken line.

**Comment by vors** [comment]
> unpredictable changes in the future on system level.

I think it's scoped to the current session only.

I'm with Ilya on the desire to have idempotent scripts, but since we already have more severe side effects (installing software, changing PATH) I'm ok with leaving it as is - don't see real case scenarios where people may hit problems because of adding TLS12 support flag.

**Comment by vors** [comment]
@iSazonov @markekraus just wanted to thank you guys for engaging so quickly and point out the problems. Sorry again for the rushing the changes thru the PR -- we got a little bit too excited and that was one of the small changes that I was comfortable to merge without waiting for others review. We will avoid rushing in the next 2 days. Thank you!

**Comment by tylerl0706** [comment]
@markekraus would you mind explaining this change a little more? I'm curious.

**Comment by markekraus** [comment]
@tylerl0706 Settings in `System.Net.ServicePointManager` affect several APIs in .NET at the appdomain level. When you set `ServicePointManager.SecurityProtocol` to `SslProtocols.Tls12` that means that those APIs will ONLY work with TLS 1.2. In PowerShell, the largest affect is on `Invoke-WebRequest` and `Invok-RestMethod`. With the original change, if I ran `Start-PSBootStrap` in my PowerShell session, I would break my ability access sites that still operate on TLS 1.0. I wouldn't have a clue as to why they stopped working. My change takes the existing `ServicePointManager.SecurityProtocol` and ensures that `SslProtocols.Tls12`  is added to it. This effectively switches on TLS 1.2 without disabling any of the current Settings. 


For example, in my profile I have this:


```powershell
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor [System.Security.Authentication.SslProtocols]::Tls12 -bor [System.Security.Authentication.SslProtocols]::Tls11
```

This turns on TLS 1.1 and TLS 1.2 as I work with several APIs that are TLS 1.1 or 1.2 only.

Running this

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [System.Security.Authentication.SslProtocols]::Tls12
```

Would have no affect on my current settings. but running

```powershell
[Net.ServicePointManager]::SecurityProtocol = [System.Security.Authentication.SslProtocols]::Tls12
```

Would break all of my TLS 1.1 APIs for the current PowerShell Session.

Does that answer your question?

**Comment by TravisEz13** [comment]
@markekraus  I was reviewing the other fix after the fact and was going to ask for this.  Thanks.

**Pull request merged**
