### PR TITLE
Change `Clear-Host` back to using $RAWUI and `clear` to work over remoting

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

Based on feedback from @BrucePay `[Console]::Clear()` only works locally and need to revert to using `$RAWUI` to clear the screen on Windows and `clear` command to clear on non-Windows so it works over remoting

This reverts part of the change in https://github.com/PowerShell/PowerShell/pull/8603

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]

**Comment by iSazonov** [comment]
Maybe simply fallback to RawUI:
```
try {
    [Console]::Clear
} catch {
    # Use RawUI
}
```

**Comment by SteveL-MSFT** [comment]
@iSazonov there's interest to convert this to a C# cmdlet and extend it, so let's defer any enhancements to that effort

**Comment by iSazonov** [comment]
> convert this to a C# cmdlet

@SteveL-MSFT Could you please open new Issue for this work? It seems this will be a breaking change and we will need PowerShell Committee approve.

**Comment by SteveL-MSFT** [comment]
@iSazonov it's implicitly part of https://github.com/PowerShell/PowerShell/issues/8606 since the way `Clear-Host` is currently implemented it's impossible to extend

**Pull request merged**
