### PR TITLE
Clean Up Full CLR Code From Web Cmdlets

### LINKED ISSUE #5373: Format data for BasicHtmlWebResponseObject contains ParsedHtml and Forms properties
PowerShell Core (currently) only supports basic parsing on Web Cmdlets. All of the code which contains the actual `Forms` and `ParsedHtml`properties are behind `#if !CORECLR` so these properties do not exist on any of the core types. However, The `Forms` and `ParsedHtml` properties are defined in the format data.

I believe [the decision](https://github.com/PowerShell/PowerShell/issues/3267#issuecomment-286917402) was that HTML processing would no longer be handled by the `WebResponseObject` and instead would be part of a separate cmdlet. 

Over the course of the past few months have fielded a lot of confused questions about this. I think it would help clarify that this is not supported in Core if the formatting data was updated to match object and remove the dummy `Forms` and `ParsedHtml` properties it adds.

Offending code

https://github.com/PowerShell/PowerShell/blob/fe3e44f3055ccd57e19ce1d29a5320e2f3891705/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L1263

https://github.com/PowerShell/PowerShell/blob/fe3e44f3055ccd57e19ce1d29a5320e2f3891705/src/System.Management.Automation/FormatAndOutput/DefaultFormatters/PowerShellCore_format_ps1xml.cs#L1268

Steps to reproduce
------------------

```powershell
$result = iwr 'https://www.bing.com/'
$result
```

Expected behavior
-----------------
`Forms` and `ParsedHtml` should not be shown
```none
StatusCode        : 200
StatusDescription : OK
Content           : <!DOCTYPE html PUBLIC #snip
RawContent        : HTTP/1.1 200 OK #snip
Headers           : {[Cache-Control, System.String[]], #snip
Images            : {@{outerHTML=<img id= #snip
InputFields       : {@{outerHTML=<input clas #snip
RawContentLength  : 124089
RelationLink      : {}
```

Actual behavior
---------------
`Forms` and `ParsedHtml` are shown
```none
StatusCode        : 200
StatusDescription : OK
Content           : <!DOCTYPE html PUBLIC #snip
RawContent        : HTTP/1.1 200 OK #snip
Forms             :
Headers           : {[Cache-Control, System.String[]], #snip
Images            : {@{outerHTML=<img id= #snip
InputFields       : {@{outerHTML=<input clas #snip
ParsedHtml        :
RawContentLength  : 124089
RelationLink      : {}
```

Environment data
----------------

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.9
PSEdition                      Core
GitCommitId                    v6.0.0-beta.9
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by markekraus**
closes #5373
reference #4357
reference #3267

* Removes/normalizes `#ifdef` code for Full CLR
* Removes Full CLR files already marked for removal in `Microsoft.PowerShell.Commands.Utility.csproj`
* Makes `-UseBasicParsing` parameter hidden.
* Removes logic for `-UseBasicParsing` as the cmdlets now always basic parsing https://github.com/PowerShell/PowerShell/issues/3267#issuecomment-286917402
* Removes Format data for `HtmlWebResponseObject` 
* removes phantom properties  `Forms` and `ParsedHtml` from format data for `BasicHtmlWebResponseObject`

### CODE REVIEW

**Comment by iSazonov** [comment]
@markekraus Could you please review all files and add a newline at EOF?

**Comment by markekraus** [comment]
@iSazonov All of the files I modified in the PR have a newline EOF. Some of them did not have one before and just ended with `#endif`.

**Comment by SteveL-MSFT** [comment]
@markekraus does it make sense to move the files in `common` and `CoreCLR` to the parent and get rid of those subdirs?

**Comment by markekraus** [comment]
@SteveL-MSFT If it were up to me. I would combine the core partials and the common partials and move them all to the parent webcmdlet folder. It would definitely make these a lot easier to work on since there is no FullCLR to contend with. I'm not sure if it makes sense to do that and this cleanup in the same PR, though. But I would definitely want it that way, whether in this PR or another.

**Comment by iSazonov** [comment]
I believe it is more easily and faster to review small PRs.
The PR LGTM and I vote to merge now.

**Comment by markekraus** [comment]
@iSazonov do you think I should do the merging of partials in one PR and then the file moves in another? otherwise... it will just look like I created new classes in parent folder and deleted old ones. Hard to see how they were put together. I could just do them as 2 commits in the same PR too.

**Comment by SteveL-MSFT** [comment]
@markekraus use `git mv` and git will report the file was just moved

**Comment by markekraus** [comment]
@SteveL-MSFT  as an example, I want to take `WebCmdlet\Common\BasicHtmlWebResponseObject.Common.cs` and `WebCmdlet\CoreCLR\BasicHtmlWebResponseObject.CoreClr.cs`, and combine them to `WebCmdlet\BasicHtmlWebResponseObject.cs`

**Comment by SteveL-MSFT** [comment]
@markekraus I see, if you're combing files, I agree you should do that as a separate PR.

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by markekraus** [comment]
@SteveL-MSFT for clarity, should I do 1 PR for combining, and another PR for the move? Or just do both in 1 PR (with 2 commits)?

**Comment by SteveL-MSFT** [comment]
@markekraus I think you can just do 1 PR for combining/move and have them as separate commits

**Comment by SteveL-MSFT** [comment]
@markekraus can you resolve the merge conflict?  As discussed in the issue, we'll defer further clean-up work and should merge this once the merge conflict is resolved

**Comment by markekraus** [comment]
@SteveL-MSFT conflict resolved, but I just realized I never ran Feature tests in this PR. so running now.

**Comment by markekraus** [comment]
The one of the fails (`EventResource`) in AppVeyor is appearing in all builds, not just this one. I assume it's a known issue. 

The other is a timeout fail from httpbin.org (I will get those tests all moved over to `WebListener` someday).

As for Travis CI, it seems to be having unrelated issues

**Comment by iSazonov** [comment]
Yes, we are waiting #5379 to pass CI AppVeyor.

**Comment by markekraus** [comment]
@iSazonov al tests pass now

**Pull request merged**
