### PR TITLE
Demo PR for PowerShell Summit

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

Force some test failures to demo @PoshChan 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@PoshChan please retry linux

**Comment by PoshChan** [comment]
@SteveL-MSFT, successfully started retry of `PowerShell-CI-Linux`

**Comment by SteveL-MSFT** [comment]
@PoshChan please retry macos

**Comment by PoshChan** [comment]
@SteveL-MSFT, successfully started retry of `PowerShell-CI-macOS`

**Comment by SteveL-MSFT** [comment]
@PoshChan please retry linux

**Comment by PoshChan** [comment]
@SteveL-MSFT, successfully started retry of `PowerShell-CI-Linux`

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 2 failures in `PowerShell-CI-linux`
minishell for native executables.Streams from minishell.gets a hashtable object from minishell
```powershell
This is a mock test failure
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 24
24:             throw "This is a mock test failure"

```
Format-List.Should have the same output whether choosing alias or not
```powershell
Expected strings to be the same, but they were different.
Expected length: 29
Actual length:   24
Strings differ at index 0.
Expected: 'This is a forced test failure'
But was:  '\ntestName : testValue\n\n\n'
-----------^
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Format-List.Tests.ps1: line 22
22:         $actual | Should -Be "This is a forced test failure"
```

**Comment by SteveL-MSFT** [comment]
@PoshChan please retry linux

**Comment by PoshChan** [comment]
@SteveL-MSFT, successfully started retry of `PowerShell-CI-Linux`

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 2 failures in `PowerShell-CI-linux`
minishell for native executables.Streams from minishell.gets a hashtable object from minishell
```powershell
This is a mock test failure
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Host/ConsoleHost.Tests.ps1: line 24
24:             throw "This is a mock test failure"

```
Format-List.Should have the same output whether choosing alias or not
```powershell
Expected strings to be the same, but they were different.
Expected length: 29
Actual length:   24
Strings differ at index 0.
Expected: 'This is a forced test failure'
But was:  '\ntestName : testValue\n\n\n'
-----------^
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Format-List.Tests.ps1: line 22
22:         $actual | Should -Be "This is a forced test failure"
```

**Pull request closed without merging**
