### PR TITLE
Enable IDE0048: AddRequiredParentheses

### PR DESCRIPTION
**Pull request by xtqqczze**
https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0047-ide0048

### CODE REVIEW

**Comment by iSazonov** [comment]
Default is `always_for_clarity` for arithmetic, relational, and other binary operators.

**Review by iSazonov — APPROVED** [review]

**Comment by xtqqczze** [comment]
This PR did not fix all IDE0048 violations, see #13936. Since the severity was set to warning, the build should not have completed!

**Comment by iSazonov** [comment]
Is it a bug in the Roslyn analyzer?

**Comment by xtqqczze** [comment]
> Is it a bug in the Roslyn analyzer?

No `EnforceCodeStyleInBuild` was not enabled.

**Pull request merged**
