### PR TITLE
Upgrade StyleCopAnalyzers to v1.2.0-beta.312

### PR DESCRIPTION
**Pull request by xtqqczze**
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/releases/tag/1.2.0-beta.312

Supercedes #14333.

Follow-up to #14293.

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]

**Comment by xtqqczze** [comment]
@iSazonov I asked about using dependabot for StyleCopAnalyzers at dotnet/runtime#45779.

**Comment by iSazonov** [comment]
> @iSazonov @RDIL I asked about using dependabot for StyleCopAnalyzers at [dotnet/runtime#45779](https://github.com/dotnet/runtime/pull/45779).

They are large team and they can track manually.

We don't configure dependabot to auto-merge so I am ok if dependabot will create new PRs but only if new versions are not released frequently (monthly?).

**Comment by xtqqczze** [comment]
> > @iSazonov @RDIL I asked about using dependabot for StyleCopAnalyzers at [dotnet/runtime#45779](https://github.com/dotnet/runtime/pull/45779).
> 
> They are large team and they can track manually.
> 
> We don't configure dependabot to auto-merge so I am ok if dependabot will create new PRs but only if new versions are not released frequently (monthly?).

I think releases may be more frequent until C# 9.0 support is complete. But generally releases happen less often, see https://github.com/DotNetAnalyzers/StyleCopAnalyzers/releases.

**Review by daxian-dbw — APPROVED** [review]

**Review by Steg17 — COMMENTED** [review]
👍🏻

**Pull request merged**
