### PR TITLE
Add Path alias to -FilePath parameters and others for several commands

### PR DESCRIPTION
**Pull request by KevinMarquette**
## PR Summary
- Add alias `Path` to the `-FilePath` parameter of `Start-Process`, `Set-TraceSource`, `Tee-Object`, `Trace-Command`,`Register-ScheduledJob`, `Set-ScheduledJob`,`Invoke-WSManAction`, `Set-WSManInstance`,`New-WSManInstance`
- Add alias `Path` to the `-BinaryPathName` parameter of `New-Service`
- Add alias `Path` to the `-DestinationPath` parameter of `Save-Help`
- Add alias `Path` to the `-SourcePath` parameter of `Update-Help`

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [x] Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission): https://github.com/PowerShell/PowerShell-Docs/pull/2148
    - [X] Issue filed - Issue link: https://github.com/PowerShell/PowerShell-Docs/issues/2147
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [NA] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [NA] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

### CODE REVIEW

**Comment by KevinMarquette** [comment]
Changed title to WIP because of build failure

**Comment by iSazonov** [comment]
I think that aliases should be added _only_ to solve some specific scenarios - what is the scenarios? In all other cases, this may cause problems now or in the future when it is necessary to remove these aliases and this will be an breaking change.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this.  We would be concerned about making any general rules here, but reviewing the specific cmdlets listed we are ok with the proposed change.

**Review by dantraMSFT — APPROVED** [review]
This looks good to me but the cmdlet docs should be updated to reflect the new aliases.

**Comment by KevinMarquette** [comment]
I added tests where the cmdlets already had some tests. Several of those cmdlets have no tests at all. I would like to work on some of those as a separate work effort.

I have a pull request out for the documentation of these changes.

**Review by SteveL-MSFT — APPROVED** [review]
LGTM - @KevinMarquette can you open an issue to track test coverage for the cmdlets without any?  Thanks!

**Pull request merged**
