### PR TITLE
spelling fixes: demos

### PR DESCRIPTION
**Pull request by jsoref**
This should be fairly uncontroversial.

This is PR 1 of N:
- false
- journal
- my
- specify
- utility

### CODE REVIEW

**Comment by mirichmo** [comment]
@KrisBash I think this was your demo. Please review these changes

**Comment by jsoref** [comment]
@mirichmo: if it's easier to accept without that change, it's fairly trivial for me to exclude it and leave it for later...

**Comment by TravisEz13** [comment]
@jsoref It might be easier to separate out the Apache demo changes, since the rest seem non-functional.

**Comment by jsoref** [comment]
@TravisEz13: done

**Comment by KrisBash** [comment]
LGTM

**Pull request merged**
