### PR TITLE
Add completion for Requires statements

### PR DESCRIPTION
**Pull request by MartinGC94**
# PR Summary
This adds completion for the various parameters and their values for #requires statements.  
For example: `#requires -PSEdition Core -RunAsAdministrator`  

The following parameters are supported:

- Version
- Modules
- PSEdition
- RunAsAdministrator

The following parameters are not supported because they have been deprecated or don't work:

- PSSnapin 
- ShellId 
- Assembly 

Most of the help text has been taken from the official docs but I took some creative liberties for the PSEditions text.  

I'm not sure how strict the completion should be.  
Currently it will prevent some basic mistakes like adding parameters after `RunAsAdministrator` but there's no special checks for randomly inserted characters so if for example you type: `#requires blabla -<Tab>` it will still complete to the next parameter.

## PR Context
The easier the requires statements are to use, the more likely it is that people will use them. The Modules parameter in particular is hard to use without looking up the documentation due to the hashtable keys you have to remember when specifying a version.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by rjmholt** [comment]
Please convert out of draft, change the title and ping me when this PR is ready for review

**Comment by MartinGC94** [comment]
@rjmholt ping pong, this PR is now ready for review.

**Comment by rjmholt** [comment]
I was writing a review of this, but realised it would be easier (given editor assistance) to open a PR on your branch.

I've done the following things:

- Moved the requires completions into their own method, subordinate to the `if` block
- Changed some style bits, like where `&&` and `||` are hung in an expression and how `var` is used
- Tried to eliminate as many allocations as I can without going crazy on the readability
- Moved some more declarative data into readonly statics
- Changed one or two of the approaches to the actual completion itself, particularly with module spec keys

**Comment by rjmholt** [comment]
One thing this PR needs though is more tests; there should essentially be a test to cover each block in the logic

**Comment by MartinGC94** [comment]
Thanks for the great feedback, this is a good learning experience.  
I've added more tests and made some minor changes so I hope it's good now.

**Comment by rjmholt** [comment]
@MartinGC94 this is great work! Thanks so much for your contribution. Hopefully in the PR I submitted to your branch you were able to read it commit by commit to get a sense of the particular changes?

**Comment by rjmholt** [comment]
The static analysis is for existing code

**Review by rjmholt — APPROVED** [review]

**Pull request merged**
