### PR TITLE
Add IDE analyzer rule IDs to comments

### PR DESCRIPTION
**Pull request by xtqqczze**
Follow-up to #13835.

### CODE REVIEW

**Comment by xtqqczze** [comment]
@iSazonov Could you merge?

**Comment by xtqqczze** [comment]
`PowerShell-CI-static-analysis` failure caused by transient network issues.

**Comment by kilasuit** [comment]
@xtqqczze can you add a description to this PR as right now this to me doesn't explain why this should be merged, there is no link to an issue etc so there is no context to this PR other than what is in files changed - a recommended best practice for when raising a PR

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@xtqqczze Please resolve merge conflicts.

**Comment by xtqqczze** [comment]
@iSazonov rebased, can you merge soon to avoid more merge conflicts

**Pull request merged**
