### PR TITLE
Update Third Party Notices

### PR DESCRIPTION
**Pull request by TravisEz13**
## PR Summary

Update ThirdPartyNotices
  - update the TPN in license.rtf
  - add the additional attributions needed to generate the TPN

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by RDIL — COMMENTED** [review]
Suggestion: add <meta charset=‘utf-8’> to the head of the html file just for best practices.

**Comment by RDIL** [comment]
* meant to say add <meta charset=‘utf-8’> to head

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by TravisEz13** [comment]
@RDIL 	What part of the Head specifically is missing?  I can give this feedback to the teams that generates this.
Existing head section:
```html
<head><title>THIRD PARTY SOFTWARE NOTICES AND INFORMATION</title><style>pre{white-space:pre-wrap;background:#eee;padding:24px}</style></head>
```

**Comment by RDIL** [comment]
Stuff such as meta tags like (charset, description, etc) (can’t say the raw
tags because I’m on mobile now)

**Comment by TravisEz13** [comment]
@dabutvin Can you see the feedback about the TPN at https://github.com/PowerShell/PowerShell/pull/8415#issuecomment-445943157 
Is there somewhere I can file these issues?

**Comment by dabutvin** [comment]
The generator we are using here is based on a project from amzn and we should probaly fix the default html template if there are issues with it or improvements to be had.

https://github.com/amzn/tiny-attribution-generator/blob/master/default-htmltemplate.hbs#L4-L17

Feel free to open issues and/or PRs over there.

Also, after looking at your changes here, if you would prefer to keep the notice file in TXT format there is an option to generate in TXT instead of HTML - there's a new toggle switch on the generator you can switch

**Comment by RDIL** [comment]
Done.

**Review by PaulHigin — APPROVED** [review]

**Comment by TravisEz13** [comment]
thanks for the heads up that we can generate `txt` now @dabutvin. I updated the PR.

**Comment by TravisEz13** [comment]
Verified license is readable in MSI.

**Review by RDIL — APPROVED** [review]
Gets my approval now even if it means nothing.

**Review by adityapatwardhan — APPROVED** [review]

**Comment by iSazonov** [comment]
@TravisEz13 What is right `CL-` label for the PR?

**Comment by TravisEz13** [comment]
I believe this fixes https://github.com/PowerShell/PowerShell/issues/6463

**Pull request merged**
