### PR TITLE
Add links to diffs on Github in changelog

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

Provide links to the Github compare view for each release.

## PR Context

This change provides for an easy method to access Github's compare features.

Commit 8a1d8944fd0fe212ac7604e2ffd23d295e0c0359 from #11644 is included in this branch to ensure an straightforward merge.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by xtqqczze** [comment]
We should investigate why Github issues are not being hyperlinked in the changelog.

**Comment by xtqqczze** [comment]
Markdown-link test failure is unrelated.

**Comment by xtqqczze** [comment]
`PowerShell-CI-static-analysis` failure is unrelated, #11653 will fix.

**Comment by iSazonov** [comment]
Look great!

Maybe add diffs based on previous major and minor version like 7.0 - 6.0 and 6.2.0 - 6.0.0  ?

**Comment by daxian-dbw** [comment]
@PoshChan Please retry static

**Comment by PoshChan** [comment]
@daxian-dbw, successfully started retry of `PowerShell-CI-static-analysis`

**Review by daxian-dbw — APPROVED** [review]
Looks good to me, but I would like to get sign-off from other maintainers too.

**Review by iSazonov — APPROVED** [review]
LGTM.

As I mentioned above perhaps we could add diffs based on 6.0.0 (later on 7.0.0) for major and minor versions so that users can get a list of the commits from 6.0 to 6.1, from 6.0 to 6.2, from 6.0 to 7.0 and so on.
We can add this in follow PR.

**Comment by iSazonov** [comment]
@xtqqczze Please rebase to pass CI static.

**Comment by daxian-dbw** [comment]
The failure in static build is new and is related to the changes in this PR.

**Comment by iSazonov** [comment]
Perhaps rebase helps.

**Comment by xtqqczze** [comment]
@daxian-dbw rebase passed checks

**Comment by iSazonov** [comment]
@TravisEz13 @adityapatwardhan Have you any objections or we can merge?

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
@xtqqczze It would be good if you updated the script to generate the change log with these changes:
https://github.com/PowerShell/PowerShell/blob/master/tools/releaseTools.psm1
The file already has new entries that doesn't match your changes.

**Comment by xtqqczze** [comment]
@TravisEz13 Thanks for your suggestion. I will create a follow-up PR to exclude regressions.

**Comment by xtqqczze** [comment]
> 
> 
> @xtqqczze It would be good if you updated the script to generate the change log with these changes:
> https://github.com/PowerShell/PowerShell/blob/master/tools/releaseTools.psm1

@TravisEz13 Please see #11736

**Comment by xtqqczze** [comment]
> As I mentioned above perhaps we could add diffs based on 6.0.0 (later on 7.0.0) for major and minor versions so that users can get a list of the commits from 6.0 to 6.1, from 6.0 to 6.2, from 6.0 to 7.0 and so on.
> We can add this in follow PR.

@iSazonov I'm not sure we would present these additional diffs, so I'll leave this up-for grabs.

**Pull request merged**
