### PR TITLE
Initial Support for Fedora 24

### LINKED ISSUE #1882: Fedora RPM
Please provide RPMs for Fedora too.

The CentOS RPM isn't a workaround because it doesn't work on Fedora 24 at this moment:

```
$ powershell 
Failed to initialize CoreCLR, HRESULT: 0x80131500
```

### PR DESCRIPTION
**Pull request by randomvariable**
Add support for Fedora 24.

This PR adds initial support for the Fedora distribution, starting with Fedora 24.

Until the next release of PowerShell is compiled against .NET 1.1, the Docker release image uses the CentOS 7 build, but loads in the CentOS 7 version of `libicu50` via LD_LIBRARY_PATH.

Closes #1882

### CODE REVIEW

**Comment by randomvariable** [comment]
Not added Fedora to https://github.com/PowerShell/PowerShell/blob/master/docker/launch.sh#L32 as it presumably wont work without an initial image on the Docker Hub?

**Comment by randomvariable** [comment]
OS X build has hung.

**Comment by randomvariable** [comment]
Was lazily trying to get Travis to rerun tests as it hung last time ^

**Comment by randomvariable** [comment]
Tests passed. This is ready for review.

**Comment by xasx** [comment]
afaict, lgtm

**Comment by andschwa** [comment]
@randomvariable for the `launch.sh` question, that should be able to use locally build Docker images, so I think you can add it there no problem. @daxian-dbw will need to update the Docker automated build to get updated images on the hub.

**Review by andyleejordan — APPROVED** [review]
As far as I can tell, this hits all the marks except updated documentation. With Fedora 24 supported, the readme etc. should probably be updated to reflect that, but I approve this.

**Comment by andschwa** [comment]
@randomvariable I imagine you did a test past of the build, and tried out the generated package too?

**Comment by randomvariable** [comment]
It's my default shell right now...

**Comment by mirichmo** [comment]
I reverted this PR because it caused a build break on Ubuntu. Details are in #2970.

**Pull request merged**
