### PR TITLE
Remove $IsCoreClr

### LINKED ISSUE #4904: Missing documentation - What's the purpose of $IsCoreCLR?
This is not an issue but I can't find any information about what's the purpose and usage for this variable:
$IsCoreCLR.

This is not event included in the PowerShell Help documentation.
It's excluded from the "About_Automatic_Variables" help doc.

So, all other $Is* are self-explanatory!

Steps to reproduce
------------------

```powershell
Get-Variable Is*

Name                           Value
----                           -----
**IsCoreCLR                      True**
IsLinux                        False
IsMacOS                        False
IsWindows                      True

Get-Help About_Automatic_Variables

```
Help document has no information about any of the $Is* variables.

$Psver
Environment data
----------------

```powershell
PS C:\Program Files\PowerShell\6.0.0-beta.7> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta
PSEdition                      Core
GitCommitId                    v6.0.0-beta.7
OS                             Microsoft Windows 10.0.16294
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### PR DESCRIPTION
**Pull request by iSazonov**
Fix #4904.

### Fix description
1. `$isCoreCLR` is removed from C# code.
2. `$isCoreCLR = $true` is added in tests because these tests are very different and each one requires a separate conclusion.

### CODE REVIEW

**Comment by iSazonov** [comment]
PowerShellGet depends heavily on $IsCoreCLR - its tests failed.

Should we close the PR until PowerShellGet uses $IsCoreCLR?

**Comment by daxian-dbw** [comment]
I opened the issue https://github.com/PowerShell/PowerShellGet/issues/187 on PowerShellGet repo and also submitted the PR https://github.com/PowerShell/PowerShellGet/pull/188 to update the IsCoreCLR check in their scripts. After the PR gets merged, we still need them to publish a new version of PowerShellGet module that we can use in PowerShell Core.

I also found that they are still running test on powershell-beta.5. I opened https://github.com/PowerShell/PowerShellGet/issues/189 to ask them to update CIs to run on beta.9 powershell core.

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]
Rather than pasting this everywhere.  `$IsCoreCLR` should be replaced with `$PSVersionTable.PSEdition -eq 'Core'`.  For tests that skip on !$IsCoreCLR since we have made the decision to not have a .Net Framework build of PSCore6, we should probably just remove those tests if they really are not applicable to PSCore6.

**Comment by iSazonov** [comment]
@SteveL-MSFT I wonder ` $PSVersionTable.PSEdition -eq 'Core'` is just as dummy as the `$IsCoreCLR = $true` - we don't need to check anything, we only need skip them and need a conclusion on every test.
I didn't remove these tests because I was worried that the situation was like removing `#if CoreCLR` from C# codes - maybe some features we porting later.

**Comment by SteveL-MSFT** [comment]
@iSazonov if the concern is that these tests might be valuable in the future as we port more stuff (or corefx gets richer and we can just enable), then it seems that we should rename usage of $IsCoreClr to something like $NotCurrentlyPorted = $true.

**Comment by daxian-dbw** [comment]
FYI, https://github.com/PowerShell/PowerShellGet/pull/188 has been merged. We still need them to publish  a new module (question asked in https://github.com/PowerShell/PowerShellGet/issues/187).

**Comment by iSazonov** [comment]
The new module will published in weeks - can we wait?

**Comment by SteveL-MSFT** [comment]
At this time, I'm thinking we should just leave `$IsCoreClr` as-is and focus our energy on something else.  I wouldn't block RC for this and wouldn't want to take this breaking change after RC either.

**Comment by SteveL-MSFT** [comment]
At this point, I don't think it's worth additional effort on this.  `$IsCoreClr` is staying.

**Comment by iSazonov** [comment]
@SteveL-MSFT Is this delayed or canceled at all? Should I keep iSazonov:remove-iscoreclr branch?

**Comment by SteveL-MSFT** [comment]
@iSazonov I appreciate the work you've done already, but it seems that your time may be spent on other issues.  I would consider this closed and you can delete your branch.

**Pull request closed without merging**
