### PR TITLE
Changing the PATH for cmake.

### LINKED ISSUE #2019: Build scripts don't detect installed cmake
The provided build scripts are not able to find `cmake`. Both `Start-PSBuild` and `Start-PSBootstrap` say that `cmake` is missing, however choco states differently:
image

On first run the `Start-PSBootstrap` installed `cmake` and `cmake.install`. However, the scripts still can't detect `cmake`. I tried both running powershell as normal and elevated, even rebooted to sort out `%PATH%` issues.

Running Windows 10 build 14905, VS2015 at latest patch level, Chocolatey v0.10.0.

### PR DESCRIPTION
**Pull request by adamdriscoll**
Fixes #2019

### CODE REVIEW

**Comment by adamdriscoll** [comment]
Should we actually use ProgramW6432?

**Comment by rkeithhill** [comment]
Does cmake still get installed in the 64-bit PF dir if you run the build bootstrap from an x86 prompt?  Also, that env var won't be defined on 32-bit Windows, right?   Hey, it's been a while since I've run 32-bit Windows.  Are builds on 32-bit Windows supposed to be supported?

**Comment by adamdriscoll** [comment]
Yep. It does get installed to x86 if run from x86 prompt. So ProgramW6432 would not actually work.

**Comment by kilasuit** [comment]
There are no 32bit packages that have been released (& who still runs the 32bit console anyway?) so I would think that it's not a supported Architecture

**Comment by mirichmo** [comment]
Our overall long term goal is to enable PowerShell on every platform supported by CoreCLR. Right now, we just produce x64 packages, but should be able to generate x86 packages with a few tweaks to the build script. Wow scenarios (x86 binaries on x64 system) are a non-goal at this time unless there is HUGE demand for it.

**Comment by mirichmo** [comment]
Update: I spun up an x86 VM and confirmed that the x86 version of CMake installs to ${env:ProgramFiles}\CMake\bin on that system. 

This change LGTM

**Pull request merged**
