### PR TITLE
Update PSReadLine to 2.0.0-beta3

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

Update PSReadLine shipped with PSCore6 to 2.0.0-beta3

cc @edyoung @jianyunt 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by adityapatwardhan — APPROVED** [review]

**Review by anmenaga — APPROVED** [review]
This seems to be a common pattern:
A dependency package releases a new version, and in-response every time we have to: 1) learn about it 2) manually update our stuff by a PR like this one.
I'm curios if (at least) the discovery part can be automated...

**Comment by anmenaga** [comment]
I've restarted failed 'PowerShell-CI-macos'.

**Review by dantraMSFT — APPROVED** [review]

**Comment by iSazonov** [comment]
@anmenaga @SteveL-MSFT We already have #7646.

**Comment by felixfbecker** [comment]
> This seems to be a common pattern:
> A dependency package releases a new version, and in-response every time we have to: 1) learn about it 2) manually update our stuff by a PR like this one.
> I'm curios if (at least) the discovery part can be automated...

Renovate has (experimental?) support for Nuget: https://renovatebot.com/docs/nuget/
cc @rarkins

**Comment by TravisEz13** [comment]
@felixfbecker We can rarely take anything but revsion updates without making at least packaging changes (at least for windows).  Can Renovate be configured to only take revision changes?

**Comment by felixfbecker** [comment]
What is a revision update? I know you can configure it only update patch/minor/major versions with npm, but I haven't tried with nuget.

**Comment by TravisEz13** [comment]
Yeah, I think Renovate/SemVer calls it patch.  Sorry, I'm used to calling it revision.  I found https://renovatebot.com/docs/configuration-options/#updatetypes, but I also found that it can create separate PRs for each type, which may be a better option.

**Comment by rarkins** [comment]
Currently we classify both patch version updates (e.g. `2.0.0` -> `2.0.1`) as well as unstable bumps (e.g. `2.0.0-beta2` -> `2.0.0-beta3`) as type "patch".

You could configure Renovate to either:
1. Completely ignore minor or major updates (But then you might not even be aware they exist), or
2. Always separate major/minor/patch updates so that you can quickly accept patch updates/revisions while taking longer on any minor/major.

**Comment by felixfbecker** [comment]
Yeah usually you just let it open its PRs, if CI passes, you can merge directly (you can even configure Renovate to automerge if you are confident in your tests), if it doesn't, you can make manual edits on the branch before merging.

**Comment by rarkins** [comment]
I've enabled Renovate on a mirror of this repository so that you can see how it looks without needing to install it directly. Here's an example PR: https://github.com/renovate-mirrors/PowerShell/pull/2

**Pull request merged**
