### PR TITLE
nightly badge being cached by GitHub

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
GitHub CDN requires `cache-control` = `no-cache` header to be present otherwise it (by design) will cache

addresses https://github.com/PowerShell/PowerShell/issues/3150

### CODE REVIEW

**Comment by daxian-dbw** [comment]
> [tv-nightly-image]: https://jimtru1979.blob.core.windows.net/badges/DailyBuildStatus.svg?dummy=unused

Maybe we should remove the `?dummy=unused` part from the last fix attempt.

BTW, I found an issue named `The Cache-Control HTTP header is not enough to prevent GitHub’s CDN caching` when searching Github CDN caching: https://github.com/badges/shields/issues/221, and the corresponding fix of that issue can be found [here](https://github.com/azu/voting-badge/commit/53ef68a0666276d06d5d73bd11997dba6e27f8b5#diff-48108967280cade3bbb7dad305dfd9f9R27)

Quoted from it:
> We're pretty confident that the image caching works. If you're having issues with something like a CI badge, make sure the image has the Cache-Control: no-cache header, and either Expires, Last-Modified or Etag.

Do we need to specify `either Expires, Last-Modified or Etag`? That issue was from 2014, not sure if it's still necessary.

**Review by daxian-dbw — APPROVED** [review]

**Comment by daxian-dbw** [comment]
> https://jimtru1979.blob.core.windows.net/badges/DailyBuildStatus.svg?dummy=unused

The **"?dummy=unused"** was added in PR #3297 as an attempt to fix the cached badge. Shall we remove it along in this PR?

**Comment by daxian-dbw** [comment]
close and reopen the PR to restart the stuck Travis CI.

**Comment by iSazonov** [comment]
I see CodeCover badge is cached too 😕 Can we fix it by the same way as the PR?

**Comment by daxian-dbw** [comment]
It seems the badge issue is still not fixed. Full build failed today while CI builds passed, however, our Travis badge shows CI failed and full build passed.
Here is the failed full build: https://travis-ci.org/PowerShell/PowerShell/jobs/216614572

**Pull request merged**
