### PR TITLE
Improve type inference of array literals and foreach statement variables

### PR DESCRIPTION
**Pull request by SeeminglyScience**
## PR Summary

Improve type inference for `foreach` statement variables by:

1. Inferring strongly typed arrays from explicit array and array literal expressions when elements are of the same inferred type

1. Fix detection of `foreach` variable declaration.  The previous logic was to check if the variable expression's start offset was *after* the end offset of the `foreach` statement, which will never be true in the body

1. Improve inference of what type the "Condition" of a `foreach` statement will enumerate as

Here's some examples of scenarios that now work correctly:

```powershell
foreach ($i in 0, 1, 2) { $i.<tab> }
# CompareTo    GetType      ToByte       ToDecimal    ToInt32      ToSingle     ToUInt16     TryFormat
# Equals       GetTypeCode  ToChar       ToDouble     ToInt64      ToString     ToUInt32
# GetHashCode  ToBoolean    ToDateTime   ToInt16      ToSByte      ToType       ToUInt64
foreach ($i in @{}.GetEnumerator()) { $i.<tab> }
# Key          Name         Value        Deconstruct  Equals       GetHashCode  GetType      ToString
$dict = [System.Collections.Generic.Dictionary[string, string]]::new()
foreach ($i in $dict.GetEnumerator()) { $i.<tab> }
# Key          Value        Deconstruct  Equals       GetHashCode  GetType      ToString
foreach ($i in $dict.GetEnumerator()) { $i.Key.<tab> }
# Length            GetType           PadLeft           ToChar            ToLowerInvariant  ToUpperInvariant
# Clone             GetTypeCode       PadRight          ToCharArray       ToSByte           Trim
# CompareTo         IndexOf           Remove            ToDateTime        ToSingle          TrimEnd
# Contains          IndexOfAny        Replace           ToDecimal         ToString          TrimStart
# CopyTo            Insert            Split             ToDouble          ToType
# EndsWith          IsNormalized      StartsWith        ToInt16           ToUInt16
# Equals            LastIndexOf       Substring         ToInt32           ToUInt32
# GetEnumerator     LastIndexOfAny    ToBoolean         ToInt64           ToUInt64
# GetHashCode       Normalize         ToByte            ToLower           ToUpper
```

~~**Note:** I specifically avoided testing for `IEnumerable<>` directly because some types like `string` are not enumerated by PowerShell.  I know there's more types than `string`, if someone could point me to a full list of types that implement `IEnumerable` but PowerShell doesn't enumerate, I'll add in testing for that as well.~~ Found it, I used [PSEnumerableBinder](https://github.com/PowerShell/PowerShell/blob/0a4f33a872ab811d55ff0f255d87035dbf137fb2/src/System.Management.Automation/engine/runtime/Binding/Binders.cs#L514) for reference.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by BrucePay — APPROVED** [review]
LGTM.

**Comment by vexx32** [comment]
@BrucePay @TravisEz13 (when you guys get back from the holiday break) was there something pending on this PR? 🙂

**Review by TravisEz13 — CHANGES_REQUESTED** [review]

**Comment by SeeminglyScience** [comment]
I got caught up in other projects. I'm planning to address feedback this weekend.

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
@SeeminglyScience 	I think this is complete, but I'm going to hold this PR until 6.3.  We are really close to starting lock down for release and I want to make sure a change like this has plenty of time to get feedback before the release.

My primary reasoning is that there maybe script that make assumptions about our type inferences and break because of this change.  Although this change shouldn't be a breaking change, I think we should be a little cautious.

**Comment by SeeminglyScience** [comment]
@TravisEz13 @iSazonov Is it possible to disable stale bot since this is waiting on 6.2 GA?

**Comment by iSazonov** [comment]
Nevermind. Any comment removes the mark.

**Comment by TravisEz13** [comment]
We have already forked for GA.

**Pull request merged**
