### PR TITLE
Fix RCS1102: Make class static

### PR DESCRIPTION
**Pull request by xtqqczze**
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1102.md

Follow-up to #13897.

### CODE REVIEW

**Comment by xtqqczze** [comment]
WIP until #13897 is merged.

**Comment by xtqqczze** [comment]
@iSazonov Could you please review?

**Comment by iSazonov** [comment]
@xtqqczze Can you add more information why we need this? What are the benefits we get?
This looks like a formal cosmetic change.

**Comment by xtqqczze** [comment]
Closed in favour of #14483.

**Pull request closed without merging**
