### PR TITLE
Fix `Set-Location` to only use filesystem directory (if exists) only if using FileSystem provider

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

While working on getting the Cert provider working on non-Windows.  I noticed that a [fix](https://github.com/PowerShell/PowerShell/pull/5839) I added
previously made the assumption that it was being used only by the FileSystem provider.  Fix is to
add check that it is being used by FileSystem provider before checking if the directory exists
on the file system.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
>  I noticed that a fix I added previously made the assumption 

What is the PR? Please add a link in the PR description.

**Comment by SteveL-MSFT** [comment]
@iSazonov added link to previous PR in description

**Comment by iSazonov** [comment]
@SteveL-MSFT Thanks! Maybe we need use
```c#
Context.SessionState.Path.GetUnresolvedProviderPathFromPSPath(path);
```
to be provider aware?

**Comment by SteveL-MSFT** [comment]
@iSazonov not sure I understand how to apply that to this issue.  In this case, the previous change was to treat a filesystem path as literal if it exists rather than trying to glob.  However, it did this regardless of provider, but it was specifically for the filesystem.

**Comment by iSazonov** [comment]
@SteveL-MSFT I guess the Issue occurs because we have not used right API.
I suggest to consider [GetProviderPath(string path, out ProviderInfo provider)](https://github.com/SteveL-MSFT/PowerShell/blob/6e18896199648284c2cce455f4602dff5b10a29e/src/System.Management.Automation/namespaces/LocationGlobber.cs#L1167)

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you continue the PR?

**Comment by SteveL-MSFT** [comment]
@iSazonov I'm reverting the original change this PR depends on so this PR is no longer relevant.  I'll probably keep the test case and submit it as a separate PR as that is still relevant.

**Pull request closed without merging**
