### PR TITLE
Contributing guidelines: Remove references to Travis CI and AppVeyor

### PR DESCRIPTION
**Pull request by RDIL**
## PR Summary

Since when was Travis-CI used??  I removed it and replaced it with `Azure DevOps` because that isn't there.  

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [X] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by vexx32** [comment]
Travis CI stopped being used maybe a couple months ago? It was used for MacOS and Linux agents before we switched to Azure. 😄

**Comment by RDIL** [comment]
Haha it was a rhetorical question but okay, at least this PR removes it.

**Comment by RDIL** [comment]
*Not to be confused with @TravisEz13*

**Review by adityapatwardhan — APPROVED** [review]

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
I edited your description to clarify this . https://github.com/PowerShell/PowerShell/pull/8617#issuecomment-452772671

We are supposed to give 24 hours for review.  If I don't, merge this by EOD tomorrow, feel free to ping me.

**Comment by RDIL** [comment]
👍

**Comment by RDIL** [comment]
@TravisEz13 its been about a day now.

**Pull request merged**
