### PR TITLE
allow pscustomobject to have property with empty string name

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
Needed to allow convertfrom-json to support json objects that have empty string property names which apparently is used pretty often

Fix https://github.com/PowerShell/PowerShell/issues/1755

### CODE REVIEW

**Comment by PetSerAl** [comment]
How about `ForEach-Object -MemberName ''` or `Add-Member -Name ''`?

**Comment by SteveL-MSFT** [comment]
@PetSerAl great point, will update: ForEach-Object and *-Member cmdlets

**Comment by SteveL-MSFT** [comment]
For now, I'm only going to add support for `Get-Member` and not `Add-Member` as we don't want to promote creation of members with empty string names.

**Comment by lzybkr** [comment]
We considered this before and rejected it, see https://github.com/PowerShell/PowerShell/pull/2820

**Comment by SteveL-MSFT** [comment]
Completely forgot about that discussion almost a year ago.  This is unfortunately not going to make it into 6.0.0 and we'll have to revisit in 6.1.0

**Pull request closed without merging**
