### PR TITLE
WebCmdlets cleanup HttpStatusCode

### PR DESCRIPTION
**Pull request by CarloToso**
# PR Summary
Small cleanup of the methods that accept `(HttpStatusCode code)`: `IsRedirectCode` and `IsRedirectToGet`

### CODE REVIEW

**Comment by xtqqczze** [comment]
What is the justification for these changes?

**Comment by CarloToso** [comment]
The code is more readable, you immediately know what HttpStatusCodes RedirectToGet

**Comment by iSazonov** [comment]
> The code is more readable, you immediately know what HttpStatusCodes RedirectToGet

Rather less readable. It would make sense for hot path, but it doesn't.
I don't see the benefit of this change.

**Comment by CarloToso** [comment]
The change was deemed useless

**Pull request closed without merging**
