### PR TITLE
SetServiceCommand: Add positional parameter attribute

### LINKED ISSUE #4916: Set-Service should accept InputObject service controller
Currently set-service doesn't have a InputObject parameter which accepts the System.ServiceProcess.ServiceController object, while other *-service cmdlets do.

Currently this doesn't work:
```
$a = Get-Service vds
set-service $a -startupType Automatic
````

while start-service and stop-service do work this way
```
$a = Get-Service vds
Stop-Service $a
```
and pipeline does also work 
`Get-Service vds | Set-Service -startupType Automatic`

a work around is this:
```
$a = Get-Service vds
Set-Service $a.ServiceName -startupType Automatic
```

### PR DESCRIPTION
**Pull request by travisty-**
Added a positional parameter attribute to the InputObject parameter,
giving Set-Service behavior similar to the other *-Service cmdlets.

Closes #4916.

### CODE REVIEW

**Comment by adityapatwardhan** [comment]
@travisty- Please add tests for the new scenario at: https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Management/Set-Service.Tests.ps1

**Comment by travisty-** [comment]
Hi @adityapatwardhan @daxian-dbw, tests have been added for this scenario.

**Comment by iSazonov** [comment]
@travisty- Thanks for your contribution!

We should split formatting changes and code changes - this makes it easier to review and support code.
Please remove last commit and push only new test. We welcome improvements in formatting in a separate PR or commit.

Also if new test is under "Feature" CI tag please add `[Feature]` in header of your last commit to run the test in CI.

**Comment by travisty-** [comment]
Thanks for the feedback @iSazonov. I'll submit the formatting improvements in a separate PR.

**Review by iSazonov — APPROVED** [review]

**Review by adityapatwardhan — APPROVED** [review]

**Pull request merged**
