### PR TITLE
Implement `IDisposable` in `NamedPipeClient`

### LINKED ISSUE #18338: CA1816 in `NamedPipeClient.Dispose()`
In `PowerShell-CI-linux`: https://dev.azure.com/powershell/PowerShell/_build/results?buildId=111689&view=logs&j=8579d1dd-da9d-5760-afc4-fb4c05cf5d6d&t=236f801b-8fac-50c5-f817-425a182daa54&l=6000

```log
/home/vsts/work/1/s/test/tools/NamedPipeConnection/src/code/NamedPipeConnection.cs(61,13): warning CA1816: NamedPipeClient.Dispose() calls GC.SuppressFinalize(object), a method that is typically only called within an implementation of 'IDisposable.Dispose'. Refer to the IDisposable pattern for more information. [/home/vsts/work/1/s/test/tools/NamedPipeConnection/src/code/Microsoft.PowerShell.NamedPipeConnection.csproj::TargetFramework=net7.0]
```

cc: @PaulHigin

### PR DESCRIPTION
**Pull request by xtqqczze**
Fix #18338 (CA1816: Call GC.SuppressFinalize correctly).

### CODE REVIEW

**Review by PaulHigin — APPROVED** [review]
This seems to have been an oversight.  Thanks for finding and fixing it.

**Comment by xtqqczze** [comment]
@PaulHigin Can you investigate `PowerShell-CI-windows` failures.

**Comment by xtqqczze** [comment]
restarting CI

**Comment by xtqqczze** [comment]
`PowerShell-CI-windows` were transient, ready for review.

**Pull request merged**
