### PR TITLE
Fix some trivial typos in documentation

### PR DESCRIPTION
**Pull request by stweil**

### CODE REVIEW

**Comment by stweil** [comment]
The Travis CI tests are obviously broken...

**Comment by TravisEz13** [comment]
I restarted the test.  CLA is still required.

**Comment by daxian-dbw** [comment]
Hey @stweil, the Travis CI failure was fixed, could you please sync and rebase? That will get you the fix for the PR CI run.

**Comment by stweil** [comment]
Do you really need a signed CLA even for trivial PRs like this one? I'm not willing to sign English legal texts which are much longer than "my contribution may be used freely". So I'm sorry: either you rethink your process and take this PR as it is (without CLA), or you close the PR without using it.

**Comment by daxian-dbw** [comment]
@stweil I don't think CLA is required for this PR. Thanks for your contribution!

**Pull request merged**
