### PR TITLE
Change CimCmdlets to use AliasAttribute

### LINKED ISSUE #11988: GCIM Alias does not work in PowerShell 7 RC3
The GCIM alias works in WIndows PowerShell 5.1 and points to Get-CImInstance.

This alias is not present in RC3

# Steps to reproduce

```powershell
GCIM -Class WIn32_bios
```

# Expected behavior

```none
PS C:\foo> gcim -class win32_Bios

SMBIOSBIOSVersion : A16
Manufacturer      : Dell Inc.
Name              : Phoenix ROM BIOS PLUS Version 1.10 A16
SerialNumber      : 87Q285J
Version           : DELL   - 15
```

# Actual behavior
PS C:\foo> gcim win32_bios
gcim: The term 'gcim' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Suggestion [4,General]: The most similar commands are: gci, gcm, gc, gcs, gi, gm, icm, gcb, gin.
```none

```

# Environment data

```none
PS C:\foo> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.0-rc.3
PSEdition                      Core
GitCommitId                    7.0.0-rc.3
OS                             Microsoft Windows 10.0.19569
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0, 6.1.0, 6.2.0, 7.0.0-rc.3}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Please return this alias as it's useful at the command line.

### PR DESCRIPTION
**Pull request by thlac**
# PR Summary
Changes CimCmdlets-modude to use AliasAttribute and removed CimCmdletModuleInitialize.cs as its only function was to set the aliases

## PR Context
Should fix #11988

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
- **User-facing changes**
    - [X] Not Applicable
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Review by iSazonov — COMMENTED** [review]
Please test in DefaultCommands.Tests.ps1

**Comment by thlac** [comment]
I saw that and thought that test was only for aliases defined in InitialSessionState.cs, but looking at it again it also says it only checks default loaded modules, the CimCmdlets module is not automatically loaded.

Not sure if I am misunderstanding anything, but the aliases looked to be default, because it was set during the module load, so it's technically the equivalent of the user doing `Set-Alias -Name "gcim" -Value "Get-CimInstance"` when the module loads.

**Comment by iSazonov** [comment]
We have a list of modules in the test and explicitly load the modules.

**Comment by thlac** [comment]
Okay, thanks, just wanted to make sure. I've added tests for them now :)

**Comment by thlac** [comment]
That test doesn't fail locally

**Review by iSazonov — APPROVED** [review]

**Comment by anmenaga** [comment]
@daxian-dbw @SteveL-MSFT Please check this PR. Do you have any theories why alias initialization for `CimCmdlets` module was previously done through manually calling `Set-Alias`? I guess there should be a reason for it looking strange like that...

**Comment by SeeminglyScience** [comment]
> @daxian-dbw @SteveL-MSFT Please check this PR. Do you have any theories why alias initialization for `CimCmdlets` module was previously done through manually calling `Set-Alias`? I guess there should be a reason for it looking strange like that...

So in PSv2, the `AliasAttribute` was decorated with `AttributeUsage(AttributeTargets.Property | AttributeTargets.Field)` so it wasn't yet able to be applied to classes.  In PSv3, `AttributeTargets.Class` was added.  Although the CIM cmdlets were added in the same version, my **guess** is that the additional attribute target was added later in development (or the folks working on CIM just weren't aware of it). If y'all found someone who remembers then feel free to ignore my theory 🙂

**Comment by iSazonov** [comment]
@thlac Thanks for your contribution!

**Pull request merged**
