### PR TITLE
Send-MailMessage: add parameter "ReplyTo"

### PR DESCRIPTION
**Pull request by replicaJunction**
## PR Summary

  

Adds a `-ReplyTo` parameter to Send-MailMessage, which allows users to include the Reply-To field in their e-mail messages.

## PR Context  

Fixes issue #8719.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.  
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**  
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed: MicrosoftDocs/PowerShell-Docs#3602
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by replicaJunction** [comment]
@iSazonov I may need help adding tests for this. I did test interactively, and the reply-to field was correctly populated in an e-mail message, but even the existing Pester tests won't run on my development box since they're hard-coded to run only on Linux.

If I'm reading correctly, it looks like the existing tests actually call a mail server running on the local machine to send a message, and then they read the message back from disk. Could someone with easy access to a Linux device help with Pester tests?

**Comment by iSazonov** [comment]
@replicaJunction You could create new test like existing in  Send-MailMessage.Tests.ps1 and push the commit - then you'll see result in CI (click Detail link).

**Comment by replicaJunction** [comment]
I've added the -ReplyTo parameter to the existing tests, and it looks like they passed.

Regarding the CodeFactor issue above, I wrote the line in question to match the style of the existing code in that switch block. I don't think that issue can be fixed without reformatting the entire block, and I didn't want to clutter up this PR with formatting changes to others' code.

**Review by iSazonov — APPROVED** [review]

**Comment by anmenaga** [comment]
@SteveL-MSFT FYI. Waiting for PowerShell Committee to review this simple new public API.

**Comment by anmenaga** [comment]
Exception for the CodeFactor issue seems reasonable. Merging,..

**Comment by iSazonov** [comment]
@replicaJunction Thanks for your contribution!

**Pull request merged**
