### PR TITLE
Implement `IDisposable` for `ConvertToJsonCommand`

### LINKED ISSUE #15740: Leak CancellationTokenSource in ConvertTo-Json
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

https://github.com/PowerShell/PowerShell/blob/6d08db612e6d1788d0a0ae518583dae9faa6917b/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/ConvertToJsonCommand.cs#L32

We should dispose _cancellationSource.

### PR DESCRIPTION
**Pull request by xtqqczze**
Fix #15740.

cc: @iSazonov

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]
LGTM. I made a minor update to reduce the nesting.

**Comment by xtqqczze** [comment]
@daxian-dbw I looked at the implementation again, and removed the unnecessary `_disposed` bool, as:

* it is safe to call `CancellationTokenSource.Dispose` multiple times 
* we don't check that `_disposed == false` at the beginning of each method (we let `CancellationTokenSource` throw the `ObjectDisposedException` instead)

Feel free to revert to reset to 29cdfb4 if you disagree.

**Comment by daxian-dbw** [comment]
@xtqqczze In that case, you don't really need to follow the exact `IDisposible` pattern to have the `protected virtual void Dispose(bool disposing)` method. This method makes sense only if the type may have derived sub types. You can put `CancellationTokenSource.Dispose` directly in `public void Dispose()` and remove `GC.SuppressFinalize(this)` (calling this method is in case of a sub-type has a finalizer defined. This type doesn't have a finalizer and thus won't be put on the finalizer queue)

**Comment by xtqqczze** [comment]
> @xtqqczze In that case, you don't really need to follow the exact `IDisposible` pattern to have the `protected virtual void Dispose(bool disposing)` method. This method makes sense only if the type may have derived sub types. You can put `CancellationTokenSource.Dispose` directly in `public void Dispose()` and remove `GC.SuppressFinalize(this)` (calling this method is in case of a sub-type has a finalizer defined. This type doesn't have a finalizer and thus won't be put on the finalizer queue)

@daxian-dbw I already considered those changes, but they are only possible if the class is sealed. Since `ConvertToJsonCommand` is currently unsealed and a public API I thought it best not to do that.

**Comment by xtqqczze** [comment]
The sealed class issue reminds me of comments in https://github.com/PowerShell/PowerShell/pull/11820#pullrequestreview-445815117.

**Review by iSazonov — APPROVED** [review]

**Review by daxian-dbw — APPROVED** [review]

**Pull request merged**
