### PR TITLE
Revert 5.1-breaking changes to build\Start-PSBootStrap

### LINKED ISSUE #16330: Start-PSBootstrap fails on PowerShell 5.1
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

*Start-PSBootstrap* fails on PowerShell 5.1 due to use of unsupported type `[System.Management.Automation.SemanticVersion]` in *build.psm1* therefore it is not possible to build latest versions of PowerShell 7 on PowerShell 5.1 anymore.

### Expected behavior

```console
*Start-PSBootstrap* should work on PowerShell 5.1
```

### Actual behavior

```console
*Start-PSBootstrap* throws error on PowerShell 5.1
```

### Error details

```console
Import-Module .\build.psm1
Start-PSBootstrap
Installing PowerShell build dependencies
VERBOSE: Calling Find-Dotnet from Start-PSBootstrap
VERBOSE: In Find-DotNet
ForEach-Object : Unable to find type [System.Management.Automation.SemanticVersion].
At D:\DEVELOPMENT\PowerShellCore\build.psm1:2106 char:81
+ ... *\.\d*)?' | ForEach-Object { [System.Management.Automation.SemanticVe ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Manageme...SemanticVersion:TypeName) [ForEach-Object], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound,Microsoft.PowerShell.Commands.ForEachObjectCommand

$error[0]|fl * -force


PSMessageDetails      :
Exception             : System.Management.Automation.RuntimeException: Unable to find type [System.Management.Automation.SemanticVersion].
                           at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
                           at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.Interpreter.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.LightLambda.RunVoid1[T0](T0 arg0)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipeImpl(ScriptBlockClauseToInvoke clauseToInvoke, Boolean createLocalScope, Dictionary`2 functionsToDefine, List`1
                        variablesToDefine, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis, Pipe outputPipe, InvocationInfo invocationInfo, Object[] args)
                           at System.Management.Automation.ScriptBlock.<>c__DisplayClass57_0.<InvokeWithPipe>b__0()
                           at System.Management.Automation.Runspaces.RunspaceBase.RunActionIfNoRunningPipelinesWithThreadCheck(Action action)
                           at System.Management.Automation.ScriptBlock.InvokeWithPipe(Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object input, Object scriptThis,
                        Pipe outputPipe, InvocationInfo invocationInfo, Boolean propagateAllExceptionsToTop, List`1 variablesToDefine, Dictionary`2 functionsToDefine, Object[] args)
                           at System.Management.Automation.ScriptBlock.InvokeUsingCmdlet(Cmdlet contextCmdlet, Boolean useLocalScope, ErrorHandlingBehavior errorHandlingBehavior, Object dollarUnder, Object
                        input, Object scriptThis, Object[] args)
                           at Microsoft.PowerShell.Commands.ForEachObjectCommand.ProcessRecord()
                           at System.Management.Automation.CommandProcessor.ProcessRecord()
TargetObject          : System.Management.Automation.SemanticVersion
CategoryInfo          : InvalidOperation: (System.Manageme...SemanticVersion:TypeName) [], RuntimeException
FullyQualifiedErrorId : TypeNotFound
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, D:\DEVELOPMENT\PowerShellCore\build.psm1: line 2106
                        at <ScriptBlock>, D:\DEVELOPMENT\PowerShellCore\build.psm1: line 2106
                        at script:Start-NativeExecution, D:\DEVELOPMENT\PowerShellCore\tools\buildCommon\startNativeExecution.ps1: line 22
                        at Get-LatestInstalledSDK, D:\DEVELOPMENT\PowerShellCore\build.psm1: line 2105
                        at Find-Dotnet, D:\DEVELOPMENT\PowerShellCore\build.psm1: line 2259
                        at Start-PSBootstrap, D:\DEVELOPMENT\PowerShellCore\build.psm1: line 2054
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      5.1.19041.1237
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.19041.1237
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Visuals

image

### PR DESCRIPTION
**Pull request by IISResetMe**
Fixes https://github.com/PowerShell/PowerShell/issues/16330

# PR Summary

Runtime updates in #16309 broke `Start-PSBootbootstrap` on Windows PowerShell 5.1 by introducing a hard dependency on the `[SemanticVersion]` type, introduced in 6.0.

This commit replaces the type reference with a PowerShell class that implements the necessary subset of functionality (namely `IComparable`) from `[SemanticVersion]` needed for sorting SDK versions, ostensibly the motivation for introducing this dependency in the first place.

## PR Context

I, like many others, have been building PowerShell >=6 from source with Windows PowerShell 5.1 for years and still occassionally do. Having to manually patch `build.psm1` everytime I want to bootstrap a build from WPS is frustrating. Hence this PR.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by PaulHigin — COMMENTED** [review]
These changes look fine to me.  My only concern is that we now would have to maintain this code, and pick up any bug fixes from dotNet.  Do people agree this is Ok?  I imagine the code is pretty stable, but would still need to be maintained.

**Comment by IISResetMe** [comment]
> These changes look fine to me. My only concern is that we now would have to maintain this code, and pick up any bug fixes from dotNet. Do people agree this is Ok? I imagine the code is pretty stable, but would still need to be maintained.

`SemanticVersion` seems to have been stable since SemVer 2.0 compatibility was introduced in https://github.com/PowerShell/PowerShell/pull/5037 (November 2017) - all subsequent changes has been pure refactoring to take advantage of new runtime/language features or comply with updated QA rules - no behavioral changes have been made as far as I can tell.

**Comment by daxian-dbw** [comment]
I have the similar concern, and thus marked this to be reviewed by maintainer. Also, CIs failed because the build was not successful. I think the failure is related to changes in this PR because I don't see similar failure in other PRs or daily builds.

**Comment by iSazonov** [comment]
The sdk selection logic is "dumb" - get list, sort, pick up first - we don't search required sdk in the list. So we can replace Get-LatestInstalledSDK with one command `dotnet  --version`.

**Comment by IISResetMe** [comment]
> The sdk selection logic is "dumb" - get list, sort, pick up first - we don't search required sdk in the list. So we can replace Get-LatestInstalledSDK with one command `dotnet --version`.

I was a bit perplexed by this logic as well.

I assume that also explains why I get "dotnet (6.0.101) is out of date, downloading dotnet (6.0.100)" every time I bootstrap since installing 6.0.101 on my machine ¯\\_(ツ)_/¯

**Comment by iSazonov** [comment]
> I was a bit perplexed by this logic as well.

@IISResetMe 
:-) The Build.psm1 is very old and it has long been a _monster_, there are contradictions on every line.
It should be cleaned up and simplified a long time ago, use the newer features of the latest versions including source generators,
move the build process to csproj files as much as possible, making it more friendly for other communities which could  issue their distributives,
move the release process into a separate repository as it is essentially an internal MSFT process.
It's impossible to understand why the MSFT team chooses to roam the jungle year after year, but it's their time. :-)

**Comment by adityapatwardhan** [comment]
Please see comments here: https://github.com/PowerShell/PowerShell/issues/16330#issuecomment-1015889793

Closing this PR as PowerShell team Maintainer's have consensus, that this is not required.

**Comment by IISResetMe** [comment]
@adityapatwardhan consensus that it shouldn't be possible to bootstrap a build from Windows PowerShell? Or consensus that there are better ways of maintaining compatibility?

**Pull request closed without merging**
