### PR TITLE
Make linux CI parallel

### PR DESCRIPTION
**Pull request by TravisEz13**
# PR Summary

Make the Linux CI build once and then run the tests on 4 different machines, by tag.

## PR Context

Running in parallel allows us to run all tests in about the same amount of clock time

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
Looks great!

Unelevated tests on all platforms take about 13-14 minutes. Can we split them and run on 2-3 VMs?

**Review by iSazonov — APPROVED** [review]

**Review by RDIL — APPROVED** [review]
LGTM, but I agree with Ilya, the unelevated pspester tests would be better off on different VMs for speed

**Comment by TravisEz13** [comment]
@iSazonov 	We can split them up by folder or another tag.  Folder would be easier.

**Comment by TravisEz13** [comment]
We also need to remove the [feature] tag code.  It causes problems and isn't needed after this PR.  I'll do it in another PR...

**Comment by RDIL** [comment]
@travisez13 I’ll take care of it after this is merged.

**Comment by iSazonov** [comment]
>  Folder would be easier.

It seems we need to put the list in a config file to load-balance VMs.

**Comment by TravisEz13** [comment]
@iSazonov 	That might work... the script would need to see if any folders had been added and run those on some machine designated as a primary machine

**Comment by iSazonov** [comment]
Interesting, can these machines interact so as to receive a test batch and return a report? This would solve the load-balancing problem.

**Comment by TravisEz13** [comment]
@iSazonov 	Interactions between the machines may work sometimes but not consistently.  The machines are only given private IP Addresses and are not guaranteed to be on the same subnet.  I don't think we need that complexity.  It's not needed to create a solution.  The added complexity would add failure cases.

A simpler solution does mean that we would need to manually rebalance occasionally, but I don't think that is a problem.

**Comment by TravisEz13** [comment]
@PoshChan 	please remind me in 4 hours

**Comment by PoshChan** [comment]
@TravisEz13, all requests start with the magic word `Please`.

**Comment by daxian-dbw** [comment]
Come on @PoshChan you are nitpicking the letter case 😆

**Comment by TravisEz13** [comment]
@PoshChan 	Please remind me in 3 hours

**Comment by PoshChan** [comment]
@TravisEz13, all requests start with the magic word `Please`.

**Pull request merged**
