### PR TITLE
Make the build step fail when the curl operation fails.

### PR DESCRIPTION
**Pull request by adelton**
## PR Summary

Without the `pipefail`, the build step always succeeds and the layer gets cached, resulting in confusion during the next step failing and subsequent rebuild attempt.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by adelton** [comment]
We could also just redirect to the target file even if I understand the desire to show its content in the build logs with `tee`.

**Review by TravisEz13 — APPROVED** [review]

**Comment by adelton** [comment]
Ah, on Ubuntu, `/bin/sh` is symlink to `dash`, not `bash`. Sorry about that.

**Comment by TravisEz13** [comment]
@adelton we can change the shell in the docker file and resubmit the PR for the ubuntu images in the PowerShell-Docker repo

**Comment by adelton** [comment]
Do you mean running it all with `bash -c '...'`? That seems like an overkill.

I wonder if showing the result after the `curl` instead piping to `tee` could work? Something like (untested)

```
RUN cd /etc/yum.repos.d && curl -o microsoft.repo https://packages.microsoft.com/config/rhel/7/prod.repo && cat microsoft.repo
```

**Comment by TravisEz13** [comment]
You wouldn't have to put it in front of every command.  You can simply change the shell.  See an example of how to change the shell to PowerShell here: https://github.com/PowerShell/PowerShell/blob/fbbca53f4c50322cef48e5c5ab55ddc04d162bcd/docker/release/nanoserver/Dockerfile#L17

**Comment by adelton** [comment]
I wouldn't want to mess up with Ubuntu's choice of shell. My attempting to change the Ubuntu Dockerfiles was a mistake which I'm sorry for.

**Comment by TravisEz13** [comment]
no problem

**Pull request merged**
