### PR TITLE
Add launchSettings.json for better out of box experience when using Visual Studio

### LINKED ISSUE #9810: Cannot launch pwsh via Visual Studio or bin folder (i.e. not publish folder) any more
# Steps to reproduce

Pre-build PowerShell on the command line
```powershell
Import-Module build.psm1; Start-PSBuild -Clean; Invoke-Item PowerShell.sln
```
Then press `F5` in `Visual studio` with `powershell-win-core` being the startup project

# Expected behavior

Works

# Actual behavior

Crashes:

```
FailFast:
Common Language Runtime detected an invalid program.
   at System.Environment.FailFast(System.String, System.Exception)
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(System.String, System.String[], Int32)
   at Microsoft.PowerShell.ManagedPSEntry.Main(System.String[])

Exception details:
System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at Microsoft.PowerShell.ConsoleControl.WriteConsole(SafeFileHandle consoleHandle, ReadOnlySpan`1 output, Boolean newLine)
   at Microsoft.PowerShell.ConsoleHostUserInterface.WriteToConsole(ReadOnlySpan`1 value, Boolean transcribeResult, Boolean newLine) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHostUserInterface.cs:line 584
   at Microsoft.PowerShell.ConsoleHostUserInterface.WriteLineToConsole(ReadOnlySpan`1 value, Boolean transcribeResult) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHostUserInterface.cs:line 643
   at Microsoft.PowerShell.ConsoleTextWriter.WriteLine(String value) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleTextWriter.cs:line 57
   at Microsoft.PowerShell.ConsoleHostUserInterface.WriteImpl(String value, Boolean newLine) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHostUserInterface.cs:line 722
   at Microsoft.PowerShell.ConsoleHostUserInterface.WriteLine(String value) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHostUserInterface.cs:line 818
   at Microsoft.PowerShell.CommandLineParameterParser.DisplayBanner() in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\CommandLineParameterParser.cs:line 657
   at Microsoft.PowerShell.CommandLineParameterParser.ParseHelper(String[] args) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\CommandLineParameterParser.cs:line 1028
   at Microsoft.PowerShell.CommandLineParameterParser.Parse(String[] args) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\CommandLineParameterParser.cs:line 699
   at Microsoft.PowerShell.ConsoleHost.Start(String bannerText, String helpText, String[] args) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleHost.cs:line 166
   at Microsoft.PowerShell.ConsoleShell.Start(String bannerText, String helpText, String[] args) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ConsoleShell.cs:line 29
   at Microsoft.PowerShell.UnmanagedPSEntry.Start(String consoleFilePath, String[] args, Int32 argc) in C:\Users\cberg\git\PowerShell\src\Microsoft.PowerShell.ConsoleHost\host\msh\ManagedEntrance.cs:line 73

C:\Users\cberg\git\PowerShell\src\powershell-win-core\bin\Debug\netcoreapp3.0\pwsh.exe (process 14660) exited with code -2146232797.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

# Environment data

- .Net Core 3 Preview 5 installed
- Latest Visual  Studio 16.2.0-Preview1 (with preview .net sdk option enabled)
- Win10 1809 (10.0.17763)
- Latest commit on master: `83708a4242befaae0e26d7f33e7ebe2f0091db08`

### PR DESCRIPTION
**Pull request by bergmeister**
# PR Summary

Add launchSettings.json for better out of box experience when using Visual Studio and up minimum Visual Studio version to 16 as .Net Core 3 requires this as a minimum. Launching from the `bin` (instead of publish folder) does not work any more, hence the configuration.
Now one can just use `Ctrl+F5` to launch `pwsh.exe` from Visual Studio and one can then attach after that. The VS console has some known limitations (Unicode characters are not displayed for example) and at startup there are some binding exceptions that are thrown, therefore I would not recommend doing a straight `F5` at the moment but I hope this will get better with .Net Core and VS becoming more mature (at the moment one HAS to use the preview of Visual Studio for .Net Core 3)

Fixes #9810

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by TravisEz13** [comment]
@PoshChan Please remind me in 1 hour

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 1 hour ago

**Comment by TravisEz13** [comment]
@PoshChan please rerun all

**Comment by PoshChan** [comment]
@TravisEz13, did not find any matching pull request checks

**Comment by TravisEz13** [comment]
@PoshChan Please remind me in 1 hour

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 1 hour ago

**Comment by TravisEz13** [comment]
@PoshChan Please retry mac

**Comment by PoshChan** [comment]
@TravisEz13, I do not understand the build target(s) `mac`; I only allow `static`, `windows`, `macos`, `linux`, `all`

**Comment by TravisEz13** [comment]
@PoshChan Please retry macos

**Comment by PoshChan** [comment]
@TravisEz13, successfully started retry of `PowerShell-CI-macOS`

**Comment by TravisEz13** [comment]
@bergmeister I'm fine with this.  Is there a reason it's marked as a draft?

**Comment by bergmeister** [comment]
Ok, the only reason why it was in draft first was because I wanted to manually test that `Start-DevPowerShell` is not affected by this on Linux. I tried doing it in WSL but it seems that `Start-DevPowerShell` does not work in WSL any more. We should raise an issue for this. Can someone else confirm that this issue does not affect non-Windows users please? I have published the PR in the meantime.

**Comment by TravisEz13** [comment]
This issue does affect non-windows users, but it is okay to fix one platform at a time.

**Review by TravisEz13 — APPROVED** [review]

**Pull request merged**
