### PR TITLE
Update recommended WiX toolset link to be generic to WiX 3.x but mention that latest version of 3.11 has to be taken

### PR DESCRIPTION
**Pull request by bergmeister**
## PR Summary

A recent security patch (see [here](https://www.firegiant.com/blog/2017/12/31/wix-v3.10.4-and-wix-v3.11.1-released/) for details) of WiX means that the old download link is now out of date since it points to the exact 3.11.0 release.
This changes the download link to be more generic so that it just point to the release page of Wix version 3 (version 4 already has a separate repo) without being version specific.

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [x] Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [NA] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [NA] Issue filed - Issue link:
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [NA] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [NA] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

### CODE REVIEW

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
FYI, I wrote code to install WIX from the zip file which works well.  the MSI requires .net 2.0.   https://github.com/PowerShell/PowerShell/blob/master/tools/releaseBuild/Images/microsoft_powershell_windowsservercore/wix.psm1

**Comment by bergmeister** [comment]
Thanks. I haven't seen that script yet. Nice one. It's ironic because WiX's slogan is 'when setup isn't just xcopy'. ;-)

**Comment by TravisEz13** [comment]
too bad their setup depends on old components...

**Review by adityapatwardhan — APPROVED** [review]
LGTM

**Pull request merged**
