### PR TITLE
Run CodeFormatter for LocalAccounts

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Fix formatting issues in LocalAccounts module.
Note: the code is excluded from compiling.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by TravisEz13** [comment]
This is unused code

**Comment by iSazonov** [comment]
@TravisEz13 Yes, there a note about this in the PR description. We have a plan to migrate this code to the public API so that good formatting will not be superfluous.

**Comment by TravisEz13** [comment]
When we looked at this, the best way to do this would be to use `net.exe` . Identifying the APIs was not immediately obvious.  

I don't particularly like making changes to code that isn't currently compiling, as we could unknowingly break the code.

**Comment by iSazonov** [comment]
@TravisEz13 This code will _never_ compile in the repo. Using another API also makes the relevant tests useless.
If you still disagree I will close this PR.

**Comment by SteveL-MSFT** [comment]
Since this code isn't currently being built and used, I don't think it make sense to spend time reviewing the changes.  I would suggest closing this PR.  I don't expect this module will be built out of this repo, but it's something we'll have working with PS7, but in Windows.

**Comment by jeffbi** [comment]
Converting this code to use a public API is not a _huge_ undertaking, but it would still be Windows-only and with a fair amount of P/Invoke code. Unless there are new APIs in .NET that would allow it to be cross-platform.

**Comment by SteveL-MSFT** [comment]
@jeffbi I don't think there's value in porting this to use public APIs (which currently means using net.exe...) unless also making it cross platform at the same time.

**Comment by iSazonov** [comment]
There is a public API. Example https://github.com/PowerShell/PowerShell/issues/2996#issuecomment-388333943

**Comment by SteveL-MSFT** [comment]
@iSazonov if that namespace supports the current cmdlet and is cross-platform, that would solve this completely

**Comment by iSazonov** [comment]
@SteveL-MSFT We haven't cross-platform API/package for account management. It seems System.DirectoryServices is only partially ported.
System.DirectoryServices is part of Windows Compatibility Pack. We already added it in the repo.

System.DirectoryServices.AccountManagement is very power. From docs:
```
The System.DirectoryServices.AccountManagement namespace provides uniform access and manipulation of user, computer, and group security principals across the multiple principal stores: Active Directory Domain Services (AD DS), Active Directory Lightweight Directory Services (AD LDS), and Machine SAM (MSAM).
```

**Comment by SteveL-MSFT** [comment]
@iSazonov tried a few things with that namespace and only got `not supported on this platform` on my macBook.  It might be sufficient to remove the private apis, but not for cross platform.  The LocalAccounts module that ships in Windows already works with PSCore6.  I don't think we'd ever ship that module with PS7, but PS7 can just use the one that we ship with PS5.1.

**Comment by iSazonov** [comment]
I see your point. The only problem is that this module will be closed for public development. An alternative is still to make a new module based on System.DirectoryServices.AccountManagement.

**Comment by iSazonov** [comment]
With the new module we could get portable solution calling useradd/groupadd/userdel/groupdel/… utilites on Unixes.

**Comment by SteveL-MSFT** [comment]
@iSazonov you are correct that LocalAccounts module would not be open to external contribution.  My recommendation would be to leave LocalAccounts as it exists today as-is for backwards compatibility and perhaps have a new module that intends to be cross platform.  Maybe call it `AccountManagement`.

**Comment by iSazonov** [comment]
> Maybe call it AccountManagement.

I think the same.

**Pull request closed without merging**
