### PR TITLE
Revert "Add action to label size of PR"

### PR DESCRIPTION
**Pull request by rjmholt**
Reverts PowerShell/PowerShell#13321

The GitHub action is currently failing in new PRs, so we need more configuration to make it work properly it seems.

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]

**Comment by vexx32** [comment]
@SteveL-MSFT is this something PoshChan could handle?

**Comment by daxian-dbw** [comment]
@TravisEz13 Shall we merge this one sooner?

**Comment by TravisEz13** [comment]
Can we give an example of where it's failing?

**Comment by TravisEz13** [comment]
https://github.com/PowerShell/PowerShell/runs/932788471?check_suite_focus=true

looks like its rate limited (even with auth).  We can filter the events to reduce the load.

**Comment by TravisEz13** [comment]
This should help with the problem

**Comment by vexx32** [comment]
That output doesn't read to me as being rate-limited:

```
{ RequestError [HttpError]: Resource not accessible by integration
    at response.text.then.message (/usr/local/share/.config/yarn/global/node_modules/@octokit/request/dist-node/index.js:66:23)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
...
     'x-ratelimit-limit': '15000',
     'x-ratelimit-remaining': '14998',
     'x-ratelimit-reset': '1596216976',
```

Plenty of attempts remaining, and that error doesn't look like "try again later" it reads more "access denied" to me.

**Pull request merged**
