### PR TITLE
Enable IDE0057: UseRangeOperator

### PR DESCRIPTION
**Pull request by xtqqczze**
https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0057

### CODE REVIEW

**Comment by xtqqczze** [comment]
CI failures attributed to #14101.

**Comment by xtqqczze** [comment]
restarting tests

**Comment by xtqqczze** [comment]
PowerShell-CI-windows (Test for Windows Windows Test - ElevatedPesterTests - Others):

```
An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Management.Automation.Remoting.PrioritySendDataCollection.ReadOrRegisterCallback(OnDataAvailableCallback callback, DataPriorityType& priorityType) in D:\a\1\s\src\System.Management.Automation\engine\remoting\fanin\PriorityCollection.cs:line 240
   at System.Management.Automation.Remoting.Client.WSManClientCommandTransportManager.SendOneItem() in D:\a\1\s\src\System.Management.Automation\engine\remoting\fanin\WSManTransportManager.cs:line 3976
   at System.Management.Automation.Remoting.Client.WSManClientCommandTransportManager.OnRemoteCmdSendCompleted(IntPtr operationContext, Int32 flags, IntPtr error, IntPtr shellOperationHandle, IntPtr commandOperationHandle, IntPtr operationHandle, IntPtr data) in D:\a\1\s\src\System.Management.Automation\engine\remoting\fanin\WSManTransportManager.cs:line 3682
```

**Comment by xtqqczze** [comment]
restarting tests

**Comment by iSazonov** [comment]
It is only style rule and doesn't affect performance so I'd prefer to skip the rule.

**Comment by iSazonov** [comment]
I close this until the feature becomes popular and developers will use it extensively.

**Pull request closed without merging**
