### PR TITLE
Configure the issue label bot

### PR DESCRIPTION
**Pull request by TravisEz13**
# PR Summary

Add configuration for the issue label bot so when we enable it, the bot will use our labels.

## PR Context

https://github.com/marketplace/issue-label-bot

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by TravisEz13** [comment]
Examples (check box indicate correct predictions):  
 - [X] https://github.com/PowerShell/PowerShell-Docker/issues/355#issuecomment-572228657
 - [ ] (this was written like a bug) https://github.com/PowerShell/PowerShell-Docker/issues/347#issuecomment-563745443
 - [X] https://github.com/PowerShell/PowerShell-Docker/issues/344#issuecomment-560966106
 - [ ] (written like a bug, but is request for a new image) https://github.com/PowerShell/PowerShell-Docker/issues/343#issuecomment-558865451
 - [X] https://github.com/PowerShell/PowerShell-Docker/issues/341
 

The predictions are only as good as the user input.  I think this is useful as a first level triage.  cc @RDIL  for his input.

**Comment by RDIL** [comment]
So far, from what I have seen, I’m not very optimistic for results here in this repository. Since the bot has the entire GitHub as it’s data set, one single person rating a deduction incorrectly throws off the entire data set by a bit.  I don’t think it’s worth it, and we should most likely stick with issue templates which now have support for adding labels based on which template you use.  If there is a self host option for it, that would most likely work 100x better because it will only be collecting powershell data - but the current hosted one is a no from me.  Of course, this is just my opinion, but I think it can be easily understood.

**Comment by TravisEz13** [comment]
@RDIL have you used it only in the docker repo? or other places?

**Comment by RDIL** [comment]
No, I have not used it in other repositories.

**Comment by TravisEz13** [comment]
@RDIL I understand your concern, but I don't think we have enough data to determine if it's useful from the experiment in the docker repo.  We would get that data much faster from the PowerShell repo.

**Comment by RDIL** [comment]
If you want to give it a try, you can go ahead with it.

**Pull request merged**
