### PR TITLE
Add back 2 transitive dependency packages

### LINKED ISSUE #21324: PowerShell 7.2 and 7.4 bundle deprecated Microsoft.Bcl.AsyncInterfaces 5.0.0.0
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```pwsh
# PS 7.2
## CSharpModule is a PowerShell module written in C# targeting netstandard2.0 and dependent on package PowerShell.Standard.Library 5.1.1 and Microsoft.Bcl.AsyncInterfaces 6.0.0.0

PS> Import-Module /app/CSharpModule.dll
```
```pwsh
# PS 7.4
## CSharpModule is a PowerShell module written in C# targeting netstandard2.0 and dependent on packages PowerShell.Standard.Library 5.1.1 and Microsoft.Bcl.AsyncInterfaces 6.0.0.0 or 7.0.0.0 or 8.0.0.0

PS> Import-Module /app/CSharpModule.dll
```
```pwsh
# The PowerShell 7 install should also bundle the appropriate version of Microsoft.Bcl.AsyncInterfaces for its target framework
## PS 7.2 - .NET 6.0 - Microsoft.Bcl.AsyncInterfaces 6.0.0.0
## PS 7.4 - .NET 8.0 - Microsoft.Bcl.AsyncInterfaces 8.0.0.0
PS> $installDir = [System.IO.Path]::GetDirectoryName((Get-Command pwsh).Location)
PS> $bclLibraryPath = Join-Path $installDir "Microsoft.Bcl.Libarary.dll"
PS> Add-Type -Path $bclLibraryPath
PS> [System.AppDomain]::CurrentDomain.GetAssemblies() | Where { $_.FullName -like "*Microsoft.Bcl.AsyncInterfaces*" } | Select -ExpandProperty FullName
```

I have an example repository that does this these very steps including their results [here](https://github.com/keithallenjackson/powershell-import-tests)

### Expected behavior

```console
## PS 7.2
- Nothing: Successful import

## PS 7.4
- Nothing: Success import

## Bundled Microsoft.Bcl.AsyncInterfaces
Should match the given target .NET version
PS 7.2 (.NET 6.0) -> 6.0.0.0
PS 7.4 (.NET 8.0) -> 8.0.0.0
```

### Actual behavior

```console
## PS 7.2
Failed import

## PS 7.4
Failed Import

## Bundled Microsoft.Bcl.AsyncInterfaces
Microsoft.Bcl.AsyncInterfaces, Version=5.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51
```

### Error details

```console
## PS 7.2
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)

## PS 7.4
Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)

Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)

Could not load file or assembly 'Microsoft.Bcl.AsyncInterfaces, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. Could not find or load a specific file. (0x80131621)

# Bundled Microsoft.Bcl.AsyncInterfaces
(No error, just unexpected version)
```

### Environment data

```powershell
data can be found [here](https://github.com/keithallenjackson/powershell-import-tests/blob/main/bcl-version-data.csv) and [here](https://github.com/keithallenjackson/powershell-import-tests/blob/main/import-test-results.csv)
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #21324

Explicitly put those 2 transitive dependencies back to `Microsoft.PowerShell.SDK.csproj`.
Due to the removal of them, PS v7.4 ships old versions of the assembly `Microsoft.Bcl.AsyncInterfaces.dll` and `Microsoft.Extensions.ObjectPool.dll` comparing to PS v7.3.

After adding back the references, PS will includes the latest stable versions:
 
image

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Comment by iSazonov** [comment]
Interesting, how many dependencies does pwsh have? Is it worth keeping track of this to avoid regression?

**Review by SeeminglyScience — APPROVED** [review]
LGTM!

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Need support

**Review by Moazzem-Hossain-pixel — COMMENTED** [review]
Thanks

**Pull request merged**
