### PR TITLE
Update the target framework for reference assemblies to netcoreapp3.0

### PR DESCRIPTION
**Pull request by adityapatwardhan**
# PR Summary

Update the target framework for reference assemblies to netcoreapp3.0. 

## PR Context

This caused the nuget build to fail.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Review by TravisEz13 — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
@PoshChan 	please remind me in 1 hour

**Comment by PoshChan** [comment]
@adityapatwardhan, your last commit had 12 failures in `PowerShell-CI-macos`
(These are 5 of the failures)

Send-MailMessage DRT Unit Tests.Can send mail message using named parameters with mandatory parameters
```powershell
Expected exactly 'user01@example.com', but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1: line 136
136:         $mail.FromAddress | Should -BeExactly $InputObject.From
```
Send-MailMessage DRT Unit Tests.Can send mail message using named parameters with ReplyTo
```powershell
Expected exactly 'user01@example.com', but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1: line 136
136:         $mail.FromAddress | Should -BeExactly $InputObject.From
```
Send-MailMessage DRT Unit Tests.Can send mail message using named parameters with multiple To
```powershell
Expected exactly 'user01@example.com', but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1: line 136
136:         $mail.FromAddress | Should -BeExactly $InputObject.From
```
Send-MailMessage DRT Unit Tests.Can send mail message using named parameters with multiple Cc
```powershell
Expected exactly 'user01@example.com', but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1: line 136
136:         $mail.FromAddress | Should -BeExactly $InputObject.From
```
Send-MailMessage DRT Unit Tests.Can send mail message using named parameters with multiple Bcc
```powershell
Expected exactly 'user01@example.com', but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1: line 136
136:         $mail.FromAddress | Should -BeExactly $InputObject.From
```

**Comment by PoshChan** [comment]
@adityapatwardhan, your last commit had 12 failures in `PowerShell-CI-windows`
(These are 5 of the failures)

Send-MailMessage Feature Tests.Default Port 25.Can send mail with free-form email address
```powershell
Expected exactly 'user01@example.com', but got $null.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\Send-MailMessage.Tests.ps1: line 247
247:             $mail.FromAddress | Should -BeExactly "user01@example.com"
```
Send-MailMessage Feature Tests.Default Port 25.Can send mail with high priority
```powershell
Expected exactly 'urgent', but got $null.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\Send-MailMessage.Tests.ps1: line 257
257:             $mail.Priority | Should -BeExactly "urgent"
```
Send-MailMessage Feature Tests.Default Port 25.Can send mail with HTML content as body
```powershell
Cannot index into a null array.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\Send-MailMessage.Tests.ps1: line 269
269:             $mail.Headers["content-type"] | Should -BeLike "text/html*"

```
Send-MailMessage Feature Tests.Default Port 25.Can send mail with UTF8 encoding
```powershell
Expected exactly 1, but got 0.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\Send-MailMessage.Tests.ps1: line 283
283:             $mail.MessageParts.Count | Should -BeExactly 1
```
Send-MailMessage Feature Tests.Default Port 25.Can send mail with attachments
```powershell
Expected exactly 3, but got 0.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\Send-MailMessage.Tests.ps1: line 303
303:             $mail.MessageParts.Count | Should -BeExactly 3
```

**Comment by PoshChan** [comment]
@adityapatwardhan, your last commit had 13 failures in `PowerShell-CI-linux`
(These are 5 of the failures)

Error occurred in test script '/home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1'
```powershell
Cannot retrieve the dynamic parameters for the cmdlet. An exception was thrown by a TaskScheduler.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1: line 11
```
Error occurred in test script '/home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Set-Date.Tests.ps1'
```powershell
Too many open files
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Set-Date.Tests.ps1: line 4
```
Error occurred in test script '/home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1'
```powershell
Cannot retrieve the dynamic parameters for the cmdlet. An exception was thrown by a TaskScheduler.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1: line 11
```
Error occurred in test script '/home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Set-Date.Tests.ps1'
```powershell
Too many open files
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Set-Date.Tests.ps1: line 4
```
Invoke-WebRequest tests.Error occurred in Describe block
```powershell
The 'Start-WebListener' command was found in the module 'WebListener', but the module could not be loaded. For more information, run 'Import-Module WebListener'.
At /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1:372 char:24
```

**Comment by PoshChan** [comment]
@adityapatwardhan, this is the reminder you requested 1 hour ago

**Comment by adityapatwardhan** [comment]
@PoshChan 	please rebuild all

**Comment by PoshChan** [comment]
@adityapatwardhan, successfully started rebuild of `PowerShell-CI-static-analysis, PowerShell-CI-Windows, PowerShell-CI-macOS, PowerShell-CI-Linux`

**Comment by adityapatwardhan** [comment]
Merged without waiting for 24 hours as this was breaking package build.

**Pull request merged**
