### PR TITLE
Remove EtwActivity empty constructor and make minor style fixes

### PR DESCRIPTION
**Pull request by RDIL**
# PR Summary
C# isn't my specialty but I think this is unused.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by iSazonov** [comment]
@RDIL I think we can accept only style fixes. The empty static constructors should be returned back because the change slow down PowerShell startup - the constructors postpone class initialization until first using.

@daxian-dbw Thouths?

**Comment by vexx32** [comment]
@isazonov is that so? I never would have guessed that would be the result. Do you know if that deloy-loading behaviour is documented somewhere? I'd like to read up on it!

**Comment by iSazonov** [comment]
@vexx32 Maybe this helps https://stackoverflow.com/questions/9731335/singleton-implementation-with-empty-static-constructor

**Comment by RDIL** [comment]
I’m not totally sure if that applies here, but it may affect this.

**Comment by daxian-dbw** [comment]
An empty static constructor is sometimes used to guarantee that all static initialization happen before any static fields or methods are accessed. Without an explicit static constructor, the inline static field initialization is guaranteed to happen before static fields are accessed but not static methods or instance constructor. See https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1810-initialize-reference-type-static-fields-inline?view=vs-2019#rule-description

For the one in `EtwActivity.cs`, I looked at the code, and it seems safe to remove it.
For the other one in `ComRuntimeHelpers.cs`, let's not change it. Reason: 1) the code was copied from .NET code base and it's not used in PowerShell Core (`ComBinder` not working in .NET Core); 2) I didn't read the code, but the empty static constructor could be there on purpose since it's explicitly suppressing the rule.

**Review by iSazonov — APPROVED** [review]

**Pull request merged**
