### PR TITLE
Added progress bar for `Remove-Item` cmdlet

### LINKED ISSUE #19538: GUI progress bar when Deleting a folder in Powershell
### Summary of the new feature / enhancement

It would be good to have a slider of some GUI element when using the command

` remove-item <directory_name> -recurse -force`

I was trying to delete a directory from PowerShell and it does not show how much the process is done or how much time it will take to complete.

If we had this feature it would be more convenient to delete a file as we would know its progress.

### Proposed technical implementation details (optional)

_No response_

### PR DESCRIPTION
**Pull request by ArmaanMcleod**
# PR Summary

Fixes #19538

Added progress bar for `Remove-Item` cmdlet. 

## PR Context

Currently there is no progress bar when running `Remove-Item -Path somedir -Recurse -Force`. I've included a progress bar similar to `Copy-Item`.

Some reason when using `terminalizer` the progress bar doesn't show up right and overlaps the status activity message. If you run this on its own it displays fine. Couldn't work around this to get a better terminal recording on Windows, open to suggestions 😄.

render1700904643371

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by kilasuit — APPROVED** [review]
Approving based on my testing of the build artifact from this PR, however would still like to have someone else review the code.

**Comment by neo-fetch** [comment]
Any update? Has an alternative been presented somewhere else?

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Review by SeeminglyScience — APPROVED** [review]
LGTM

**Pull request merged**
