### PR TITLE
Enable nullable: System.Management.Automation.Language.ITypeName

### PR DESCRIPTION
**Pull request by powercode**
Tracking issue: #12631.

### CODE REVIEW

**Review by iSazonov — CHANGES_REQUESTED** [review]
Please
- move directives in right place
- `string AssemblyName { get; }` - comment says it can be null.
- add XML comments to non-nullable members like "This never returns null."

**Comment by powercode** [comment]
I think we shall have a discussion before specifying nullness in the documentation.

That doesn't seem to be something that is done anywhere else, and is should anyways be automatically generated based on the type.

**Comment by iSazonov** [comment]
> I think we shall have a discussion before specifying nullness in the documentation.
> 
> That doesn't seem to be something that is done anywhere else, and is should anyways be automatically generated based on the type.

Currently (and unlikely to change in the near future) if there is no "?" then the reader cannot understand whether the type is annotated or not. It is in these cases that I suggest adding the standard comment.

**Comment by powercode** [comment]
Sure, but the vast majority of these types are internal, and the situation is no worst than it has been before.

On the flip side, it puts an extra burden on us working with this, lowering the chance of having it done at all.

**Comment by iSazonov** [comment]
The work is certainly huge and at some point we will no longer remember the details of the work already done - comments will help us.
In addition, we need comments only when there is no "?", if this sign is in the signature, then everything is already obvious - this does not create a lot of additional work. We will wait longer for MSFT team approval than add comments on rare occasions. :-)

**Review by xtqqczze — APPROVED** [review]

**Comment by xtqqczze** [comment]
LGTM, matches what I committed in 46fc9c97cc4b72c8b35ddb8056c2c17b2e242247 before I rebased to focus on a single interface.

**Comment by adityapatwardhan** [comment]
@iSazonov can you update your review?

**Review by rjmholt — APPROVED** [review]

**Review by iSazonov — APPROVED** [review]

**Review by adityapatwardhan — APPROVED** [review]

**Pull request merged**
