### PR TITLE
Disable PackageManagementTests

### PR DESCRIPTION
**Pull request by adityapatwardhan**
Package management tests disabled temporarily to unblock daily builds.

### CODE REVIEW

**Comment by adityapatwardhan** [comment]
@jianyunt @daxian-dbw Can you have a look?

**Comment by vors** [comment]
I think it's better to use a file-level try-finally to disable them.
We had a similar discussion in #2335 and agreed that BeforeAll/AfterAll disabling is too verbose, if we do it for the whole file.

**Comment by daxian-dbw** [comment]
@adityapatwardhan If we are just temporarily disabling those tests, would it be much easier to just `return` at the beginning of those test files? And it would also be much easier to re-enable those tests after moving them to oneget.org (just remove the `return` at the beginning of each test file).

**Comment by vors** [comment]
@daxian-dbw that way we get reporting about skipped / pending tests and it's useful.

**Comment by daxian-dbw** [comment]
@vors Yes, but we are removing them from PS/PS, so it's doesn't matter that we don't keep track of skipping/pending for them. BTW, I chatted with @adityapatwardhan and learnt that @jianyunt asked him to directly delete those tests from PS/PS, which is even better.

**Comment by mirichmo** [comment]
"Waiting on author" then?

**Comment by vors** [comment]
Tests are deleted in the different PR.
I think this PR is obsolete now.

**Pull request closed without merging**
