### PR TITLE
WIP Update PR template to inform about using Drafts instead of WIP

### PR DESCRIPTION
**Pull request by bergmeister**
## PR Summary

WIP only because we wait for the deployment rollout of this feature to reach everyone.
Encourage the usage of the new GitHub draft PR feature over WIP since the new feature will make WIP redundant soon. https://github.blog/2019-02-14-introducing-draft-pull-requests/
Unfortunately one cannot convert existing PRs to drafts at the moment but once the existing WIP PRs are merged, I propose to remove the WIP GitHub app. 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.  
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**  
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by markekraus** [comment]
Should link to the help dos instead of the announcement blog? https://help.github.com/articles/about-pull-requests/#draft-pull-requests

**Comment by bergmeister** [comment]
Yes, good idea

**Comment by TravisEz13** [comment]
Our org doesn't support PR drafts and GitHub says they don't plan on supporting them.  I've asked GitHub to update the documentation.

**Comment by vexx32** [comment]
Could you elaborate, @TravisEz13?

It sounds like you're saying there's a requirement for them to be allowed, but GH have mentioned nothing of the sort that I've been able to find.

Additionally, it appears @TylerLeonhardt was able to submit a draft PR (#8923) to this repo?

**Comment by TylerLeonhardt** [comment]
We should wait like a month or 2 before getting this in. I _just_ got Draft PRs today.

Or perhaps, @bergmeister you should call out that "if you don't have this capability yet, put "WIP" in the title

**Comment by bergmeister** [comment]
I also only got it today, we can definitely wait until the feature has fully rolled out (I was under the impression that the rollout is on a per repository rather than a per user basis, can anyone confirm that?.
Since they haven't implemented the feature to change a published PR back to a draft, I'll put the good ol' WIP tag om again

**Comment by TylerLeonhardt** [comment]
I just hope it wont be as slow as the GitHub Actions rollout 😶

**Comment by TylerLeonhardt** [comment]
> Sends PR to inform about using Drafts instead of WIP

> Uses WIP

😛

**Comment by TravisEz13** [comment]
GitHub is saying that they won't be supporting organizations that are paying on old billing plans and that you must upgrade to a new billing plan to use the feature.

**Comment by TravisEz13** [comment]
Although, I just looked and it seems they changed their mind and didn't email me.

**Comment by bergmeister** [comment]
Well, I am on the free plan and have actually submitted this PR initially as a draft just to get a feeling for myself how it looks like before I published it.
image

**Comment by TravisEz13** [comment]
I emailed back and asked for clarification, but I think we can assume that they decided excluding older billing plans was a bad idea.

**Comment by iSazonov** [comment]
Currently we can put WIP and remove it in any time. Does the Draft feature support switching to draft and reverse in any time?

**Comment by TylerLeonhardt** [comment]
That's a good question. I don't see anything about going from PR -> Draft PR

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
No... Once a Draft PR becomes a real PR you cannot make it a Draft PR.  And a PR created as a real PR, cannot be made a draft.

**Comment by iSazonov** [comment]
@TravisEz13 I sent the feedback to GitHub.

**Review by TylerLeonhardt — APPROVED** [review]
It seems like it's been rolled out to pretty much everyone... so I'm good with this.

**Comment by bergmeister** [comment]
Should we leave some info about 'use WIP for going back to draft state' or just ask the author to do so in special cases?

**Comment by iSazonov** [comment]
I suggest to continue using WIP until we get full-featured Draft.

**Comment by vexx32** [comment]
If it's available we may as well make use of it, and just use WIP alongside until Drafts get more features.

**Comment by TylerLeonhardt** [comment]
@SteveL-MSFT you should probably give an opinion here.

**Comment by TravisEz13** [comment]
Drafts have the advantage that people aren't notified to review.  I think we should suggest people use drafts, and use WIP only to move back to a similar state.

**Comment by SteveL-MSFT** [comment]
I think it's fine to have both Draft and WIP co-existing for now.  Once we see that Drafts are working as a replacement for WIP, we can consider removing WIP support.

**Pull request closed without merging**
