### PR TITLE
Fedora 28 was released, Fedora 26 and 25 were EOL'ed.

### PR DESCRIPTION
**Pull request by adelton**
## PR Summary

Update the Linux installation instructions and container image definitions to match current Fedora versions (27, 28).

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by kilasuit** [comment]
This looks good to me

**Comment by adelton** [comment]
The `compat-openssl10` seems to be needed on latest Fedoras. Without it, the `powershell` rpm installs fine but it then fails in runtime, for example

```
PS /> get-packageprovider                                                       
No usable version of the libssl was found
```

I've updated the PR now -> 4f6ac478567dbb1b18842c6c0e9562829c68a295.

**Review by bergmeister — CHANGES_REQUESTED** [review]
Please pull in upstream chamges and revert the changes in the readme since the installation instructions recently got removed from this repo. You will need to add another pr then to the docs repo for that and only then you can update the readme.

**Comment by adelton** [comment]
Well, the current `README.md` in master is broken -- there are still links to `https://github.com/PowerShell/PowerShell/tree/master/docs/installation/linux.md` on many lines of that table. Should I create separate PR to fix that or is someone working on fixing it already?

**Comment by bergmeister** [comment]
@adelton No, I already have PR #6981 open to fix the links in the Readme, hence why I suggest reverting the changes in the ReadMe and docs/installation/linux.md.
You then open a PR in the docs repo [here](https://github.com/PowerShell/PowerShell-Docs) to update the actual installation doc and once the doc PR is in, you can then add another PR here with the updated readme once the Doc change is live.

**Comment by adelton** [comment]
The new PR in the docs repository has now been filed: https://github.com/PowerShell/PowerShell-Docs/pull/2497

**Comment by adelton** [comment]
Rebased on master, removed the change in `README.md` -> 63a56ae92a3f8c1ad75eacc798e0e8d36c7dc646.

**Comment by bergmeister** [comment]
@adelton There still seems to be a merge conflict in `docker/release/fedora26/Dockerfile`
If it helps, the way how I upstream is:
```
git remote add upstream https://github.com/PowerShell/PowerShell.git # only needed once
g pull upstream master
```

**Comment by adelton** [comment]
Rebased on master -> 6ec3fc8ff611d88c3a46febdd326447ce918f733.

**Review by anmenaga — APPROVED** [review]
LGTM

**Comment by iSazonov** [comment]
@bergmeister Have you comments?

**Comment by bergmeister** [comment]
@iSazonov I don't know what MSFT's process on this is. Do they not need to build and test he image first produced from this changed Dockerfile before approving this PR? Other than that it looks OK to me if it works.

**Comment by TravisEz13** [comment]
@adelton PowerShell/PowerShell-Docker is public now, with a CI system.  I'm not quite ready to accept PRs as we need to split the images into stable and preview images due to various changes in preview.3.  But the biggest changes will be to the paths where the files are located, I just won't merge your change until I've merged the change to split stable and preview.  I'm happy to fix up your PR as long as you give me permissions.  
image

**Comment by adelton** [comment]
I've filed https://github.com/PowerShell/PowerShell-Docker/pull/8 now.

**Comment by adelton** [comment]
Not sure where you need the permission.

**Comment by iSazonov** [comment]
@adelton Please see https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/ and https://blog.github.com/2016-09-07-improving-collaboration-with-forks/

**Comment by TravisEz13** [comment]
Thanks for moving the PR.  I think we can close this one now.

**Pull request closed without merging**
