### PR TITLE
Path fix for git submodule update

### PR DESCRIPTION
**Pull request by coderdad**
When updating the googletest submodule for cmake, the path should be the base script directory or the update with fail.

### CODE REVIEW

**Comment by coderdad** [comment]
Should have included this -- but here's the error when trying to compile in my CentOS 7 docker (preview) instance:

submodule-update_error

**Comment by vors** [comment]
Good point!
`Push-Location`, `Pop-Location` should always go in their own try-finally. This way, if somebody hit `Ctrl+C` during the execution finally block will be executed and directory would not change. Can you, please make this change? For example, check other places where we do the same in `build.psm1`

**Comment by coderdad** [comment]
@vors Awesome idea! I'll do it tonight.

**Comment by vors** [comment]
Closing, since the fix is merged in another PR

**Comment by coderdad** [comment]
Hey @vors -- did I do that wrong? The updating the pull request part? Should it have spawned another? Only done a few PR's, and never modified one before.

**Comment by vors** [comment]
You can simple push to your branch from which you made PR and it will be updated automatically.

**Comment by coderdad** [comment]
Awesome, I really appreciate all the help. Your team is wonderful.

**Pull request closed without merging**
