### PR TITLE
Mark PowerShellAssemblyLoadContextInitializer with static modifier

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

**Breaking change**: this change removes the implicit public constructor for `PowerShellAssemblyLoadContextInitializer`.

Fix [CA1822: Mark members as static](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1822).

**Justification**:
* There appears to be no use case for creating an instance of `PowerShellAssemblyLoadContextInitializer`.
* The class only contains one static method: `SetPowerShellAssemblyLoadContext`

## PR Context

* https://github.com/PowerShell/PowerShell/issues/2291
* https://github.com/PowerShell/PowerShell/blob/master/docs/host-powershell/README.md#special-hosting-scenario-for-native-host
* https://docs.microsoft.com/dotnet/api/system.management.automation.powershellassemblyloadcontextinitializer.setpowershellassemblyloadcontext

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [!] None
    - **OR**
    - [NA] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [NA] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [NA] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [NA] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [NA] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [NS] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by iSazonov** [comment]
> **Breaking change**: this change removes the public constructor for `PowerShellAssemblyLoadContextInitializer`.

@xtqqczze I don't see the change.

**Comment by xtqqczze** [comment]
> > **Breaking change**: this change removes the public constructor for `PowerShellAssemblyLoadContextInitializer`.
> 
> @xtqqczze I don't see the change.

The removed constructor is the _implicit_ parameterless constructor.

**Comment by iSazonov** [comment]
What is benefit of the change?

**Comment by xtqqczze** [comment]
It is a fix for [CA1822: Mark members as static](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1822).

Documentation categorizes this as a performance rule, but I would add it is also a possible correctness issue: we should not allow creation of an instance of `PowerShellAssemblyLoadContextInitializer` when there is no use case.

**Review by iSazonov — APPROVED** [review]

**Comment by anmenaga** [comment]
I'm not sure about this.
On one hand, yes, this is better coding style and small theoretical perf improvement (although not really relevant in this case because, as far as I understand, `static void SetPowerShellAssemblyLoadContext` is expected to be called just once/maybe several times at most per hosting),
on the other hand, this is breaking/changing how this function should be called by PS hosts, which will cause unnecessary additional work to change hosting code.
I don't see enough reasons that would justify making such breaking change.

@daxian-dbw what do you think?

PS. CIs passed for this PR probably because we don't have a test for such hosting scenario that utilizes this API.

**Comment by xtqqczze** [comment]
> on the other hand, this is breaking/changing how this function should be called by PS hosts, which will cause unnecessary additional work to change hosting code.

Correct me if I'm wrong, but the only this could be breaking is if someone attempts to create an instance of `PowerShellAssemblyLoadContextInitializer`. This seems unlikely as examples in [documentation](https://github.com/PowerShell/PowerShell/blob/master/docs/host-powershell/README.md#special-hosting-scenario-for-native-host) treat it as if it were already a static class.

**Comment by anmenaga** [comment]
Oh, sorry. For some reason I thought that it was an instance method. :) Please ignore my previous post.

**Pull request merged**
