### PR TITLE
Support DSC compilation on Linux.

### PR DESCRIPTION
**Pull request by amitsara**
# PR Summary

Linux file paths are case sensitive. DSC compiler was not able to find base schemas because of folder name inconsistency.
Fixed inconsistent naming of folder and schema file extension.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by TravisEz13** [comment]
@amitsara Please be sure to use your own fork in the future.

**Review by TravisEz13 — APPROVED** [review]

**Comment by amitsara** [comment]
Sure, I will keep that in mind in future.

---
In reply to: [499181849](https://github.com/PowerShell/PowerShell/pull/9834#issuecomment-499181849) [](ancestors = 499181849)

**Comment by TravisEz13** [comment]
@PoshChan Please remind me in 24 hours

**Comment by SteveL-MSFT** [comment]
@amitsara are there existing tests that cover this on non-Windows?

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 24 hours ago

**Comment by amitsara** [comment]
I think No, since compilation is completely broken on linux if there were test they might have failed. Powershell has some DSC related tests but i need to revisit them and add more to cover compilation on linux. I am planning to do that in next PR. is that fine?

---
In reply to: [499389951](https://github.com/PowerShell/PowerShell/pull/9834#issuecomment-499389951) [](ancestors = 499389951)

**Comment by amitsara** [comment]
Actually some of the tests failed. Looking into the failures ...

---
In reply to: [499682224](https://github.com/PowerShell/PowerShell/pull/9834#issuecomment-499682224) [](ancestors = 499682224,499389951)

**Comment by amitsara** [comment]
Hi Steve, We have tests to validate DSC compilation on Windows & Linux  but not on Mac. They are failing because of changes in this PR. I am fixing the tests.

---
In reply to: [499683817](https://github.com/PowerShell/PowerShell/pull/9834#issuecomment-499683817) [](ancestors = 499683817,499682224,499389951)

**Comment by amitsara** [comment]
Fixed the test failures

---
In reply to: [499690114](https://github.com/PowerShell/PowerShell/pull/9834#issuecomment-499690114) [](ancestors = 499690114,499683817,499682224,499389951)

**Comment by SteveL-MSFT** [comment]
@amitsara if you're doing it in the next PR, I'm ok with that

**Review by TravisEz13 — APPROVED** [review]

**Pull request merged**
