### PR TITLE
Remove minor versions from `PSCompatibleVersions`

### PR DESCRIPTION
**Pull request by xtqqczze**
Supercedes #18346.

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]

**Review by SteveL-MSFT — APPROVED** [review]

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]
Looks like some tests need to be updated

**Review by daxian-dbw — APPROVED** [review]

**Comment by kilasuit** [comment]
I'd be more willing to see this not remove all minor versions but instead leave the latest minor version

**Review by kilasuit — CHANGES_REQUESTED** [review]
Here I'd prefer to see 

```
private static readonly Version s_psV6Version = new(6,2);
private static readonly Version s_psV7Version = new(7,2);
```

**Comment by kilasuit** [comment]
> Here I'd prefer to see
> 
> ```
> private static readonly Version s_psV6Version = new(6,2);
> private static readonly Version s_psV7Version = new(7,2);
> ```

even then perhaps it should really be 7,3 not 7,2

**Comment by iSazonov** [comment]
> I'd be more willing to see this not remove all minor versions but instead leave the latest minor version

Language breaking change can be introduced only in new _major_ version.

**Comment by SteveL-MSFT** [comment]
@kilasuit the @PowerShell/powershell-committee's position is `7.0` represents 7.x (docs will need to be updated) instead of perpetually updating this list with every yearly release of 7.x.

**Comment by kilasuit** [comment]
@SteveL-MSFT that's fair, just wanted to highlight this possible other viewpoint so that it's mentioned within this PR for full transparency to those coming to this in future

**Review by kilasuit — APPROVED** [review]
Approving based on comments from @SteveL-MSFT

**Comment by daxian-dbw** [comment]
@xtqqczze Can you please fix the failing tests? Some tests need to be updated accordingly.

**Review by SteveL-MSFT — APPROVED** [review]

**Pull request merged**
