### PR TITLE
Fix amazonlinux install script

### PR DESCRIPTION
**Pull request by Geweldig**
# PR Summary
Fixes the check which previously broke installation on amazonlinux

## PR Context
#9071 Introduced changes which broke the install script on amazonlinux, this fixes it.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by Geweldig** [comment]
Requesting review from @DarwinJS.

**Comment by Geweldig** [comment]
# Verified working
- [x] Amazon Linux
`docker run -v -it amazonlinux /bin/bash -c "curl -s https://raw.githubusercontent.com/Geweldig/PowerShell/fix_amazonlinux_install_script/tools/installpsh-amazonlinux.sh | bash ; pwsh"`
- [x] Centos
`docker run -v -it centos /bin/bash -c "curl -s https://raw.githubusercontent.com/Geweldig/PowerShell/fix_amazonlinux_install_script/tools/installpsh-redhat.sh | bash ; pwsh"`
- [x] Fedora
`docker run -v -it fedora /bin/bash -c "curl -s https://raw.githubusercontent.com/Geweldig/PowerShell/fix_amazonlinux_install_script/tools/installpsh-redhat.sh | bash ; pwsh"`
- [ ] Ubuntu
- [ ] Debian
- [ ] MacOS

**Comment by TravisEz13** [comment]
@Geweldig 	I set the amazon linux tests to actually report failures.

**Comment by Geweldig** [comment]
Didn't know it was covered by tests, awesome!

**Comment by TravisEz13** [comment]
I added it after @DarwinJS 	first reported this issue.

**Comment by TravisEz13** [comment]
@Geweldig 	I added debian 9 tests.  It failed, can you investigate?

**Comment by Geweldig** [comment]
Working on it, seems to a problem related to `lsb_release` not being present in every debian install, will have to find a check which can more accurately resolve if you're running on debian.

**Comment by Geweldig** [comment]
@TravisEz13 the main script pulls the install scripts for every release from the master branch, leading me to believe the debian script which is currently on master does not pass the CI. This also makes it difficult to verify the installation correctness using CI, as it won't always use the code which is actually on the branch. Verifying the script manually using the aforementioned docker command does result in a correctly installed version of PowerShell.

**Comment by DarwinJS** [comment]
This is looking good.  I think I may have also tested on crusty old Amazon Linux 1 / Classic (there is no official distinguishing name) - but there is no container for that.

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
@PoshChan 	Please remind me in 23 hours

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 23 hours ago

**Comment by DarwinJS** [comment]
Awesome - thanks it is working now.

**Pull request merged**
