### PR TITLE
remove -computer parameter from get-process

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
Due to bug https://github.com/dotnet/corefx/issues/24357 [Process]::GetProcesses(computer) returns local processes.  Since this previously relied on dotnet remoting, I don't think we should support this and users should use PSRP instead.

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
Although `-ComputerName` works with Get-Service, we should consider removing it from `Get-Service`, `Remove-Service`, and `Set-Service` so that users consistently rely on PSRP and only having that port open

**Comment by joeyaiello** [comment]
We don't have quorum with the @PowerShell/powershell-committee today, but I'm formally acking that I'm okay with this one.

**Comment by iSazonov** [comment]
I'm continuing to use WMI/RPC in a corporate environment.
This is familiar and convenient, as well as meet existing corporate security settings - changing it requires too much expense.
Before removing this I'd prefer to get support `-PSSession` in _all_ the cmdlets.

**Comment by SteveL-MSFT** [comment]
@iSazonov corefx has this in their 2.1.0 milestone so it won't be fixed by the time we get to final.  If PSRP is allowed in your environment, you can always use `Invoke-Command` to run it remotely.  I agree that long term, having an automatic `-PSSession` parameter would be best.

**Comment by iSazonov** [comment]
@SteveL-MSFT Does it make sense to do `automatic  -PSSession  parameter` in 6.1.0 milestone?

**Comment by SteveL-MSFT** [comment]
It's certainly something we could look at.  Perhaps you could open an new issue to track it.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agreed to remove the `-ComputerName` parameter from this and the *-Service cmdlets.  We may reuse that parameter in the future for remoting over PSRP so it was best to remove it now in 6.0.0.

**Comment by iSazonov** [comment]
Should we be consistency and remove the parameter from all cmslets forcing users to use PSRemoting?
```
PS C:\Windows\system32> gcm -ParameterName ComputerName

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          Add-Computer                                       3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Clear-EventLog                                     3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Connect-PSSession                                  3.0.0.0    Microsoft.PowerShell.Core
Cmdlet          Enter-PSSession                                    3.0.0.0    Microsoft.PowerShell.Core
Cmdlet          Get-Counter                                        3.0.0.0    Microsoft.PowerShell.Diagnostics
Cmdlet          Get-EventLog                                       3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Get-HotFix                                         3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Get-Process                                        3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Get-PSSession                                      3.0.0.0    Microsoft.PowerShell.Core
Cmdlet          Get-Service                                        3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Get-WinEvent                                       3.0.0.0    Microsoft.PowerShell.Diagnostics
Cmdlet          Get-WmiObject                                      3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Invoke-Command                                     3.0.0.0    Microsoft.PowerShell.Core
Cmdlet          Invoke-WmiMethod                                   3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Limit-EventLog                                     3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          New-EventLog                                       3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          New-PSSession                                      3.0.0.0    Microsoft.PowerShell.Core
Cmdlet          Receive-Job                                        3.0.0.0    Microsoft.PowerShell.Core
Cmdlet          Receive-PSSession                                  3.0.0.0    Microsoft.PowerShell.Core
Cmdlet          Register-WmiEvent                                  3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Remove-Computer                                    3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Remove-EventLog                                    3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Remove-PSSession                                   3.0.0.0    Microsoft.PowerShell.Core
Cmdlet          Remove-WmiObject                                   3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Rename-Computer                                    3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Restart-Computer                                   3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Send-MailMessage                                   3.1.0.0    Microsoft.PowerShell.Utility
Cmdlet          Set-Service                                        3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Set-WmiInstance                                    3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Show-EventLog                                      3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Stop-Computer                                      3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Test-Connection                                    3.1.0.0    Microsoft.PowerShell.Management
Cmdlet          Write-EventLog                                     3.1.0.0    Microsoft.PowerShell.Management
```

**Comment by SteveL-MSFT** [comment]
@iSazonov it looks like you enumerated the Windows PowerShell cmdlets, but yes, we should remove it from the other cmdlets except the ones specific to remoting.

**Comment by SteveL-MSFT** [comment]
@iSazonov I created https://github.com/PowerShell/PowerShell/issues/5090 as I think only the *-Service ones need it removed, the remaining ones are ok.

**Comment by SteveL-MSFT** [comment]
@anmenaga since this was approved by Committee to proceed, can you review?

**Review by anmenaga — APPROVED** [review]
Change looks ok;
But looking that there is no corresponding test change, it feels strange that there is no existing test for "get-process -computer".
Maybe it is a good idea to run feature tests on this change to be sure that tests won't break...

**Comment by SteveL-MSFT** [comment]
@anmenaga pretty sure this isn't being used in our tests at all since I found this via code coverage analysis, but will run feature tests anyways

**Review by adityapatwardhan — APPROVED** [review]
LGTM

**Comment by SteveL-MSFT** [comment]
@adityapatwardhan can we merge?

**Pull request merged**
