### PR TITLE
Update AppVeyor cache

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

We've been seeing some AppVeyor failures after publishing new version of pwrshplugin.dll.  The cache name wasn't changed and suspicion is that the cache is invalid and needs to be updated.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by bergmeister** [comment]
@steveL-msft
Can you please provide links to the build failures? Can you also please explain how/why this PR would help? Only NuGet packages are being cached and I cannot see how this can be a problem?
Is it related to #7038 ?

**Comment by SteveL-MSFT** [comment]
This should not be related to #7038.  Pwrshplugin.dll is published as psrp.windows nupkg.  Failure was first noticed in our nightly (https://ci.appveyor.com/project/PowerShell/powershell-f975h), but I also see it in my PRs.

**Comment by bergmeister** [comment]
Ok. Thanks for the info. However, if you really suspect that the presence of an older NuGet package is really the culprit then there seems to be an underlying issue (in general or in the test) that should be solved rather than being swept under the carpet by flushing the cache. It might be OK as a quick workaround to get it back to work to unblock things but understanding the failure would still be essential IMHO

**Comment by SteveL-MSFT** [comment]
That binary is pulled into the build from myget as a nupkg and required for WSMan remoting endpoint for PSCore6.  The test that's failing is trying to setup a remoting endpoint and that is failing because of that binary.  The cache needs to be updated everytime we update the nuget dependencies which is the case here.  I don't think anything is being swept under the carpet.

**Comment by SteveL-MSFT** [comment]
Ok, just looked at the nupkg and it was published incorrectly.  May not need this cache change.

**Pull request closed without merging**
