### PR TITLE
Update coding-guidelines to encourage adding code comments

### PR DESCRIPTION
**Pull request by daxian-dbw**
Add the "Code comments" section in coding-guidelines.md to encourage adding code comments.

### CODE REVIEW

**Review by iSazonov — COMMENTED** [review]
Great!
May be add about tests:
" when you are making changes to the code _and tests_,"

**Comment by daxian-dbw** [comment]
@iSazonov Good point. Fixed.

**Comment by daxian-dbw** [comment]
@andschwa can you please take a look at this doc change, and merge it if it looks good?

**Review by andyleejordan — APPROVED** [review]
@daxian-dbw looks great!

**Pull request merged**
