### PR TITLE
Fix ConvertTo-Html single matched column header bug

### PR DESCRIPTION
**Pull request by mirichmo**
This replaces abandoned PR #2184 since the fix looks like it might be worthwhile to include. This PR adds the changes requested in the original PR that held it up from being merged.

PR #2241 included the original tests.

FYI: @TimCurwick

### CODE REVIEW

**Comment by JamesWTruher** [comment]
LGTM

**Review by JamesWTruher — APPROVED** [review]

**Comment by mirichmo** [comment]
The content is the same. I just re-did the commit giving @TimCurwick credit for it.

**Review by adityapatwardhan — APPROVED** [review]
LGTM

**Comment by mirichmo** [comment]
@PowerShell/powershell-maintainers This is ready for merge

**Pull request merged**
