### PR TITLE
Resx - remove trailing white spaces and extra Newline at EOF

### PR DESCRIPTION
**Pull request by iSazonov**
1. Commit - remove trailing white spaces

Motivation - So far we have not been able to use VS Code automatic removing trailing white spaces without the cleanup.

The cleanup is done with @lzybkr script from #3001 

2. Commit - remove extra Newline at EOF

A few days ago in #3576 I saw Resx files without Newline at EOF. Now they're miraculously gone. I don't know who and how to fix it. Now I only found files with extra Newline at EOF. Fixing script is based on script above and attached.

[fix_EOF.txt](https://github.com/PowerShell/PowerShell/files/1085124/fix_EOF.txt)

### CODE REVIEW

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]
We should update https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md with the recommended settings in VSCode for automatic removing of trailing whitespace for resx files

**Comment by lzybkr** [comment]
Just confirming - this PR does not leave files with no newlines at the EOF, right?
It just replaces 2 newlines with 1, or adds 1 if there was none, right?

**Comment by iSazonov** [comment]
> Just confirming - this PR does not leave files with no newlines at the EOF, right?

Yes.

> Just confirming - this PR does not leave files with no newlines at the EOF, right?

Yes. Actually only removes extra Newline at EOF. Resx files without Newline at EOF is not found.

**Comment by iSazonov** [comment]
@SteveL-MSFT 

Maybe better add this to https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/coding-guidelines.md  ?

**Comment by SteveL-MSFT** [comment]
@iSazonov yeah, even better!

**Comment by iSazonov** [comment]
@SteveL-MSFT  I open #4054 

Full description of VS Code is in [using-vscode.md](https://github.com/PowerShell/PowerShell/docs/learning-powershell/using-vscode.md) - so I added recomendations in the document and link from [CONTRIBUTING.md](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md)

**Review by SteveL-MSFT — APPROVED** [review]

**Review by lzybkr — APPROVED** [review]

**Pull request merged**
