### PR TITLE
Update jsonschemanet version testing

### PR DESCRIPTION
**Pull request by gregsdennis**
@daxian-dbw, this is the same as #19610, but I want to use this for testing so I don't gunk up the commit history over there.  Please approve any builds if you need to.  Otherwise, feel free to ignore.

### !!! NOT FOR MERGING !!!

### CODE REVIEW

**Comment by gregsdennis** [comment]
Looks like this is the problem, which is what I suspected:

```
Microsoft.PowerShell.Commands.JsonSchemaReferenceResolutionException: Exception of type 'Microsoft.PowerShell.Commands.JsonSchemaReferenceResolutionException' was thrown.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/assets/valid_schema_definitions.json'.
```

I don't understand this because the file is definitely there.

Adding more logs...

**Comment by gregsdennis** [comment]
More detail:

```
Fetching: /vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/assets/valid_schema_definitions.json
Reading file: /vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/assets/valid_schema_definitions.json
Json.Schema.JsonSchemaException: Cannot resolve base schema from `file://home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/assets/valid_schema_definitions.json#/definitions/name`
```

I'm unsure why this isn't able to find the file.  I'm open to ideas from someone who know linux better.

**Comment by gregsdennis** [comment]
Okay.  It looks like it's a difference in how filename URIs are handled.

```c#
var windowsFilePath = "C:\\Folder\\target.json";
var unixFilePath = "/Folder/target.json";

var windowsFileUri = new Uri($"file:///{windowsFilePath}");
var unixFileUri = new Uri($"file:///{unixFilePath}");

Console.WriteLine(windowsFileUri);
Console.WriteLine(windowsFileUri.AbsoluteUri);
Console.WriteLine(windowsFileUri.AbsolutePath);
Console.WriteLine();
Console.WriteLine(unixFileUri);
Console.WriteLine(unixFileUri.AbsoluteUri);
Console.WriteLine(unixFileUri.AbsolutePath);
Console.WriteLine(unixFileUri.Host);
```

```
file:///C:/Folder/target.json
file:///C:/Folder/target.json
C:/Folder/target.json

file://folder/target.json
file://folder/target.json
/target.json
folder
```

That last line is missing the `folder`.  It's interpreted as the host and not included in the path.

Also interesting is the lower-casing.  Since \*nix operating systems have case-sensitive file systems, I wonder if that's going to cause a problem.

@adityapatwardhan @daxian-dbw I would love to get your thoughts on this.

**Comment by gregsdennis** [comment]
Looks like I might be able to just use `.LocalPath`.

Windows: `C:\Folder\target.json`
\*nix: `\\folder\target.json`

**Comment by gregsdennis** [comment]
Getting closer.  Not sure why it's changing to backslashes.

```
Fetching: file://home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/assets/valid_schema_definitions.json
Reading file: \\home\vsts\work\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\assets\valid_schema_definitions.json
```

**Comment by iSazonov** [comment]
I wonder to see `#/definitions/name` tail:

```JsonSchemaException: Cannot resolve base schema from `file://home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/assets/valid_schema_definitions.json#/definitions/name```

**Comment by gregsdennis** [comment]
No, the fragment is removed before attempting to fetch the file.  Only the base URI is used in the fetching code.  The fragment only is resolved after the file content is retrieved.

**Comment by iSazonov** [comment]
Interesting `file:///var/` vs `file://var/`:
uri

**Comment by gregsdennis** [comment]
Yep... Looks like the problem is in how I build the base URI from a \*nix file path.  I'll push out a release and update here first.  If it works, then I'll apply changes to the other PR and close this.  Then we can all move on.

**Comment by gregsdennis** [comment]
Not sure why _more_ tests are failing, but the URI issue is resolved.  Probably my other error handling changes.

I'm going to just update the package version on the other PR and see what happens there.  The pester tests work locally on that branch with the new version.  Closing this for now.

**Pull request closed without merging**
