### PR TITLE
Remove File.ResolveLinkTarget from IsWindowsApplication

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

As discussed in  #16295 we will not get public API for AppX from Windows team so we should remove our workaround for AppX. See https://github.com/PowerShell/PowerShell/pull/16295#issuecomment-959748719 for details.

As for the symbolic link, it's not well handled in `NativeCommandProcessor` on Windows today, and that's tracked by https://github.com/PowerShell/PowerShell/issues/16171.

(Ideally we would need a public AppX API to detect whether the application is a console one or Windows GUI.)

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Comment by jborean93** [comment]
I still think in leau of a public API for AppExecLinks we should delay the checking of the exe type to after the process has started. This results in Windows doing the resolution for you.

**Comment by daxian-dbw** [comment]
Thanks @jborean93 for finding that workaround -- I learnt something new from you :)

The biggest concern I have with that approach is that we need to call native APIs to start a process, and that may break the native arguments parsing/passing work we have done in 7.2 (the `PSNativeCommandArgumentPassing` experimental feature), because that work depends on the .NET `ProcessStartInfo.ArgumentList`.

**Comment by iSazonov** [comment]
I think the best solution is - we could get an public API we need with AppX module. But WinRT was removed from .Net Runtime and now the module doesn't work in pwsh. So we need primarily new component to plug-in WinRT and than updated AppX module. 
I think it's okay if users get AppX support as a plugin and not in the Engine.

**Pull request merged**
