### PR TITLE
Add vector files for Chibi Avatar

### PR DESCRIPTION
**Pull request by cdhunt**
# PR Summary

Add vector files for Chibi Avatar

## PR Context

https://twitter.com/Steve_MSFT/status/1281310323853586435

### CODE REVIEW

**Comment by cdhunt** [comment]
Here you go, @SteveL-MSFT.

**Review by vexx32 — APPROVED** [review]

**Comment by SteveL-MSFT** [comment]
@cdhunt appreciate the work, but we had already merged a SVG version here: https://github.com/PowerShell/PowerShell/pull/13160

I don't think we need the eps file version.

**Comment by cdhunt** [comment]
Okay. This PR came in 2 days earlier. Was there something else about this PR that was unacceptable?

**Comment by iSazonov** [comment]
@cdhunt Sorry, we have many opened PRs and perhaps Steve took the top but pulled later.

Thanks for your contribution!

**Pull request closed without merging**
