### PR TITLE
Fix NREs in SuspendStoppingPipeline() and RestoreStoppingPipeline()

### LINKED ISSUE #11869: Calling action scriptblock for registered Powershel.Exiting EngineEvent throws NullReferenceException if script block contains 'finally' block
# Steps to reproduce
1. create file `code.ps1` with content:

```
Register-EngineEvent -SourceIdentifier Powershell.Exiting -Action { 
    Write-Host "Start ExitHandler"
    try{   
        try{}
        catch{}
        finally{ }            
    }
    catch{
        # print all exceptions (with all inner)
        # code from the book "Windows Powershell in action 3rd edition, page 534"
        $ErrorRecord = $Error[0]
        $out=""
        $out+= $($ErrorRecord | Format-List -Property * -Force | out-string)
        $out+= $($ErrorRecord.InvocationInfo | Format-List -Property * | out-string)
        $Exception = $ErrorRecord.Exception
        for ($depth = 0; $Exception -ne $null; $depth++)
        {
            $out+= $("$depth" * 80)
            $out+= $($Exception | Format-List -Property * -Force | out-string)
            $Exception = $Exception.InnerException
        }
        Write-Host "$out"
    }
    Write-Host "End ExitHandler"
}
exit 
```
2. Create second file `run_code.ps1` with content (in the same directory):
```
pwsh "${PsScriptRoot}/code.ps1"
```

3.  run file `run_code.ps1`

# Expected behavior
User should see two printed lines
```
Start ExitHandler
End ExitHandler
```

# Actual behavior
User sees exception details similar to this:
```
PSMessageDetails      :
Exception             : System.NullReferenceException: Object reference not set to an instance of an object.
                           at System.Management.Automation.ExceptionHandlingOps.SuspendStoppingPipeline(ExecutionContext context)
                           at System.Management.Automation.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                           at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
TargetObject          :
CategoryInfo          : OperationStopped: (:) [], NullReferenceException
FullyQualifiedErrorId : System.NullReferenceException
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at <ScriptBlock>, ...\code.ps1: line 7
PipelineIterationInfo : {}



MyCommand             :
BoundParameters       : {}
UnboundArguments      : {}
ScriptLineNumber      : 7
OffsetInLine          : 5
HistoryId             : -1
ScriptName            : ...\code.ps1
Line                  :     Write-Host "Start ExitHandler"

PositionMessage       : At ...\code.ps1:7 char:5
                        +     Write-Host "Start ExitHandler"
                        +     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
PSScriptRoot          : ...
PSCommandPath         : ...\code.ps1
InvocationName        :
PipelineLength        : 0
PipelinePosition      : 0
ExpectingInput        : False
CommandOrigin         : Internal
DisplayScriptPosition :


00000000000000000000000000000000000000000000000000000000000000000000000000000000
Message        : Object reference not set to an instance of an object.
Data           : {System.Management.Automation.Interpreter.InterpretedFrameInfo}
InnerException :
TargetSite     : Boolean SuspendStoppingPipeline(System.Management.Automation.ExecutionContext)
StackTrace     :    at System.Management.Automation.ExceptionHandlingOps.SuspendStoppingPipeline(ExecutionContext context)
                    at System.Management.Automation.Interpreter.FuncCallInstruction`2.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
                    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
HelpLink       :
Source         : System.Management.Automation
HResult        : -2147467261

```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      6.2.4
PSEdition                      Core
GitCommitId                    6.2.4
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

The funny thing is that if you comment out line 6 `finally{ }` the code will work.
I was trying to find some more information about what kind of code can/cannot appear in Powershell.Exiting action scriptblock but did not find any restrictions etc.

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Fix #11869

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by PaulHigin — APPROVED** [review]
LGTM

**Comment by vexx32** [comment]
Can we add a regression test?

**Comment by iSazonov** [comment]
> Can we add a regression test?

Repo steps in original issue are too expensive/tricky. I don't know how create simple test.

**Comment by PaulHigin** [comment]
@iSazonov  I agree.  The original repro is too complex.  It is unusual to not have a running pipeline and runspace, but engine events is one case.  Another case might be Action script blocks on debugger breakpoints, but I don't think it is worth searching for another repro.

**Comment by grzegorz-wolszczak** [comment]
Hi guys,

I don't know what are your requirements in terms of regression tests when it comes to starting child shell in tests, but if that would not be an issue then what about a test like that 
```
Describe "Testing if having 'finally' block in Powershell.Exiting engine event throws" {
  It 'Should not throw when having finally block in Powershell.Exiting Action scriptblock' {
  
    # WHEN
    $output = pwsh {  $sc = {
      Register-EngineEvent -SourceIdentifier Powershell.Exiting -Action { 
          try{   
              try{}
              catch{}
              finally{ }            
          }
          catch{
            Write-Host "Exception" -Nonewline
          }
        } | Out-Null
      }
      $sc.Invoke()
    } | Out-String
  
    # THEN
    $output | Should -Not -BeLike "*Exception*"            
  } 
} 
```

**Comment by vexx32** [comment]
We have quite a few tests that start child shells, so that shouldn't be an issue I wouldn't think. Thanks for putting that together! 💖 

It might be a good idea to output the exception details rather than just a string, but that's a very good start, thanks!

**Comment by anmenaga** [comment]
@iSazonov can you please check if that [test prototype](https://github.com/PowerShell/PowerShell/pull/11870#issuecomment-588066257) can be integrated to this PR? Thank you.

**Comment by iSazonov** [comment]
Test was added.

**Pull request merged**
