### PR TITLE
Remove -Force check in ReconcilePreexistingPropertyNames method in Export-Csv.

### PR DESCRIPTION
**Pull request by sethvs**
## PR Summary

Now, when you use `Export-Csv` with **-Append** parameter and new properties don't exist in existing file:
- **-Force:$false**: error is thrown
- **-Force:$true**: cmdlet silently skips adding new properties.

Should we remove **-Force** check in **ReconcilePreexistingPropertyNames** method, so that error is thrown in both cases - when **-Force:$true** and **-Force:$false**.

Or is it better to make cmdlet overwrite existing file with new data if **-Force:$true**?

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by sethvs** [comment]
Can you restart tests?

**Comment by iSazonov** [comment]
I restarted CI Travis MacOs tests.

**Comment by iSazonov** [comment]
@mklement0 Could you please review the change too?

**Comment by mklement0** [comment]
My vote is for not making this change, which is certainly a breaking one:

While the docs don't really say what `-Force` is for - which should definitely be added - _de facto_ it has served to force addition of objects even if they have unrelated / additional properties, which is a useful option to have _if_ applied intentionally (that's where the docs come in).  

Note that the error message you currently get with incompatible properties clearly states that `-Force` can be used to force appending.

@sethvs: 

Please make it clearer up front when your changes will be breaking, and ideally create an _issue_ before starting a PR, ideally by identifying the ["bucket"](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md) that the change falls into.

Also, sometimes there's an alternative to a _breaking_ change: in #6797 you tried to simply _rename_ a parameter, but the better course of action is to add an _alias_.

**Comment by mklement0** [comment]
I've added a docs issue to request documentation of the current behavior: https://github.com/PowerShell/PowerShell-Docs/issues/2392

**Comment by sethvs** [comment]
@mklement0 Agree about -Force.
This is what discussion for.
Closing.

**Comment by mklement0** [comment]
@sethvs: 

Glad to hear it.

The reason I was suggesting creating an issue before submitting a PR is that the issue allows a broader discussion as to _whether_ and _how_ to implement a change / feature _first_.

I know that this PR was simple, but generally you run the risk of wasted effort without having consensus on what should be done first.

**Pull request closed without merging**
