### PR TITLE
Make property names for the color VT sequences consistent with documentations

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

We use the property names 'Light***' such as `LightRed` and `LightGreen` for VT sequences that [are documented](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#text-formatting) as "Bright Foreground \<color\>" and "Bright Background \<color\>", such as 'Bright Red' and 'Bright Green'. This is misleading, we should make the property names consistent with those in the documentation, so it's more intuitive for users to work with VT color in PowerShell.

https://github.com/PowerShell/PowerShell/blob/e98a8c8601b8f15f479e894323beafb9f6a2300c/src/System.Management.Automation/FormatAndOutput/common/PSStyle.cs#L78-L88

## More Context

The names were originally copied from the "command-line-api" repo [from `System.CommandLine.Rendering.Color+Foreground` and `System.CommandLine.Rendering.Color+Background`](https://github.com/dotnet/command-line-api/blob/cfefdc7a44f3682b626a8953976650ed91879e7e/src/System.CommandLine.Rendering/Ansi.cs#L29). Now it's been confirmed that those properties were misnamed in that repo and will be fixed there, see https://github.com/dotnet/command-line-api/issues/1438.

So we should fix in PowerShell as well, before 7.2 GA.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] breaking changes to 7.2 preview versions
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] PR submitted: https://github.com/MicrosoftDocs/PowerShell-Docs/pull/8206

### CODE REVIEW

**Review by bergmeister — APPROVED** [review]
Looks good to me and could not spot a mistake. Due to the property names being public, it is breaking a change as already indicated but I don't think real software depends on it, I imagine only custom user setup. In theory we could leave the old property names and point them to the new ones and send telemetry.

**Comment by JustinGrote** [comment]
Makes sense to me, since it is still preview and anyone working at this level is going to be used to these VT level color sequences, the consistency is appropriate.

**Comment by rkeithhill** [comment]
The `$PSStyle` is only in 7.2 previews, right? I don't see it in my 7.1.x install.  So is this really a breaking change? IMO you have the right to change anything in a preview.  That's why it's called "preview".  Once it hits RC or especially any sort of "go live" designation, then you shouldn't introduce a breaking change unless it meets a very high bar.

**Comment by SteveL-MSFT** [comment]
@rkeithhill it was added in 7.2, we made it stable in preview.10 (or 9?).  My opinion is to either change it now or never.  I'm leaving it to the WG to make a formal decision :)

**Comment by daxian-dbw** [comment]
I will need to reorder the properties, will push another commit soon.

**Comment by rkeithhill** [comment]
Better do it now then IMO.

**Comment by daxian-dbw** [comment]
The names were originally copied from the "command-line-api" repo [from `System.CommandLine.Rendering.Color+Foreground` and `System.CommandLine.Rendering.Color+Background`](https://github.com/dotnet/command-line-api/blob/cfefdc7a44f3682b626a8953976650ed91879e7e/src/System.CommandLine.Rendering/Ansi.cs#L29). Now it's been confirmed that those properties were misnamed in that repo and will be fixed there, see https://github.com/dotnet/command-line-api/issues/1438.

So we should fix in PowerShell as well, before 7.2 GA.

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]

**Review by SteveL-MSFT — APPROVED** [review]

**Review by adityapatwardhan — APPROVED** [review]

**Pull request merged**
