### PR TITLE
Fix version parsing in bootstrapper

### PR DESCRIPTION
**Pull request by nohwnd**
# PR Summary

Some versions of .NET preview were released with version that don't have a number following the preview suffix, and your pattern won't match them correctly. It will include spaces and fail with FormatException when parsing. The pattern is unnecessarily strict about the format, and not properly escaped. Replacing the pattern with simpler one, and trimming whitespace. 

image

The existing pattern `\d*.\d*.\d*(-\w*\.\d*.\d*.\d*)?` does not escape the dots between numbers, and so the last `.` will match space.

image

## PR Context

I have many .NET previews installed and don't want to remove them from my system to be able to build PS.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by nohwnd** [comment]
General question around this, is the version parsed like this on purpose to know the latest exact version installed on the system?

I remember having problems when my version is newer than what PowerShell needs, but I haven't touched this repo for a while, so I don't remember the exact details.

I'd propose using `dotnet --version`, which will look at your global.json and resolve a version based on your settings there, with optional rolling forward (default is upgrade within minor version). Getting the version from that you know that it matches your global json, and can build your solution, even if it is slightly newer. Otherwise, you will get an error, which is also pretty descriptive.

**Comment by nohwnd** [comment]
@iSazonov Friendly ping on this.

**Review by TravisEz13 — APPROVED** [review]

**Comment by daxian-dbw** [comment]
@TravisEz13 I think this one can be superseded by https://github.com/PowerShell/PowerShell/pull/17198

**Comment by nohwnd** [comment]
Yup, it is the same fix. 🙂

**Pull request closed without merging**
