### PR TITLE
Do not wrap objects from Cmdlets in PsObjects

### PR DESCRIPTION
**Pull request by MartinGC94**
# PR Summary
Contributes to https://github.com/PowerShell/PowerShell/issues/5579
Prevents objects created by cmdlets from being wrapped as PsObjects so this: `$TimeSpan = New-TimeSpan` is identical to this: `$TimeSpan = [timespan]::new(0)`.  
I'm not sure where to add tests for this so I could use some help finding the right file.

## PR Context
I ran into this issue while trying to use `Write-SqlTableData` where it failed to write an object with a timespan property to the database because I had created it with `New-TimeSpan`, I had to work around it by using `$Timespan.psobject.BaseObject`.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by MartinGC94** [comment]
I guess there was a reason for wrapping objects after all. Without the PSObject wrap, parameters of type `System.Object` will see the original object without the members added by `Add-Member`. This can be demonstrated like this:

# The "Test" member is missing from the output
$UnwrappedObject = [version]::new()
$UnwrappedObject | Add-Member -MemberType NoteProperty -Name Test -Value Test
ConvertTo-Json $UnwrappedObject

# Because `New-Object` wraps objects as PSObjects this will show the added "Test" member
$WrappedObject = New-Object version
$WrappedObject | Add-Member -MemberType NoteProperty -Name Test -Value Test
ConvertTo-Json $WrappedObject

**Comment by mklement0** [comment]
Note that your observation re `ConvertTo-Json` points to a flaw in the latter rather than being an argument against this PR (which I think is great):

* It unexpectedly honors ETS instance properties only for `[psobject]`-wrapped input objects and objects nested in property values - even though such properties should be honored whether or not such a wrapper is present; see #19185

* Other cmdlets honor ETS instance properties even without `[psobject]` wrappers, such as `Format-Custom`, `Export-CliXml` and `ConvertTo-Csv` / `Export-Csv`:

```powershell
$UnwrappedObject = [version]::new()
$UnwrappedObject | Add-Member -MemberType NoteProperty -Name Test -Value Test

# -> "Test","Major","Minor","Build","Revision","MajorRevision","MinorRevision"
"Test","0","0","-1","-1","-1","-1"
$UnwrappedObject | ConvertTo-Csv
```

**Comment by MartinGC94** [comment]
Good to know but if `ConvertTo-Json` has that issue then it's possible some other commands have this issue as well so it might be an unacceptable breaking change.  
If they ever get around to merging my other PRs (which are more important to me) I might look into this again but for now I'll keep it closed.

**Comment by mklement0** [comment]
Understood, @MartinGC94.

The right way to resolve this is to combine your PR with a systematic review of all built-in cmdlets that perform property enumeration and fix `ConvertTo-Json` as well as any others that exhibit the same bug (possibly in separate PRs to be submitted _before_ this one) - but from what I can tell there may be no others (see next section).

This would avoid a breaking change - while fixing a number of bugs tracked in #5579 (your PR's original intent).

That said, there's still the potential to break _third-party_ cmdlets, though likely only if they use `[object]`- rather than `[psobject]`-typed parameters and / or enumerate properties _recursively_ - see next section.

---

The following cmdlets do _not_ need fixing (whereas `ConvertTo-Json` _does_):

* `Format-Table`, `Format-List`, `Format-Custom`
* `Export-CliXml` / `ConvertTo-CliXml` (as well as the virtually useless `ConvertTo-Xml`)
* `Export-Csv` / `ConvertTo-Csv`
* `ConvertTo-Html`
* `Measure-Object` (with `-Property`)
* `Out-String` / `Out-File` / `Out-Host`

These _may_ be all the ones that matter, though perhaps I'm missing some.

It is worth noting that among these, only `Format-Custom` and `Export-CliXml` / `ConvertTo-CliXml` enumerate properties _recursively_, and that _all_ of them have `[psobject]`-typed `-InputObject` parameters , whereas `ConvertTo-Json` uses `[object]`

  * See also: #5551

**Pull request closed without merging**
