### PR TITLE
Make S.M.A.PowerShell.GetSteppablePipeline method public

### PR DESCRIPTION
**Pull request by KirkMunro**
## PR Summary

PowerShell advanced function authors can create proxy functions in native PowerShell, but PowerShell cmdlet authors cannot create proxy cmdlets in native .NET. The S.M.A.PowerShell.GetSteppablePipeline() method is marked as internal, yet it is useful in both PowerShell and .NET when you want to work with proxy commands. This PR is simply to change the visibility of the GetSteppablePipeline method to public so that binary cmdlet authors don't need to use reflection to get access to this essential method.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [X] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [X] Issue filed - Issue link: https://github.com/PowerShell/PowerShell-Docs/issues/3128
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by KirkMunro** [comment]
Similar to the other PR I submitted earlier, I did not include test fixtures for this PR because I was not sure it needed any. If you want some added, please indicate where (Pester, or in a C# unit test). Thank you.

**Comment by KirkMunro** [comment]
Note: after this PR or #8056 are approved/merged, the other will have to be updated with the latest code and the Pester test that tests tab expansion and counts members on S.M.A.PowerShell will have to be updated (the count will increase by one). Just adding this comment so that I remember to update whichever of these isn't merged once the other one is so that there are no merge conflicts and all tests pass.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and is ok making this public

**Comment by KirkMunro** [comment]
This is not stale, it's just awaiting merge.

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Pull request merged**
