### PR TITLE
Run CodeFormatter for Microsoft.PowerShell.Commands.Management

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Fix formatting issues in Management module with CodeFormatter utility. No manual changes.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by PoshChan** [comment]
@iSazonov, your last commit had 1 failures in `PowerShell-CI-macos`
Task-based PowerShell async APIs.PowerShell::StopAsync.can stop a script that is running asynchronously
```powershell
Expected $true, but got $false.
at <ScriptBlock>, /Users/vsts/agent/2.149.2/work/1/s/test/powershell/engine/Api/TaskBasedAsyncPowerShellAPI.Tests.ps1: line 213
213:                 $ir.IsFaulted | Should -Be $true
```

**Comment by iSazonov** [comment]
@PoshChan Please retry macos

**Comment by PoshChan** [comment]
@iSazonov, successfully started retry of `PowerShell-CI-macOS`

**Comment by iSazonov** [comment]
@PoshChan Please retry windows

**Comment by PoshChan** [comment]
@iSazonov, successfully started retry of `PowerShell-CI-Windows`

**Comment by iSazonov** [comment]
@PoshChan Please retry windows

**Comment by PoshChan** [comment]
@iSazonov, successfully started retry of `PowerShell-CI-Windows`

**Review by SteveL-MSFT — APPROVED** [review]

**Pull request merged**
