### PR TITLE
Invoke-Command: improve handling of variables with $using: expression

### LINKED ISSUE #9204: The $using: scope for remoting quietly accepts scope modifiers, but resolves to $null
Affects both:

* true scope modifiers such as `$global:`
* namespace variable notation such as `$function:`

# Steps to reproduce

Prerequisites:
* enable remoting on the calling machine
* run as admin.

```powershell
# Define a variable and function, both named 'foo'.
function foo { 'func' }; $global:foo = 'var'
# Try to access these definitions remotely via $using
Invoke-Command -ComputerName . { $using:foo; $using:global:foo; $using:function:foo }
```

# Expected behavior

```none
var
var
 'func' 
```

# Actual behavior

```none
var
```

That is, `$using:global:foo` and `$using:function:foo` quietly evaluated to `$null`. 

# Environment data

```none
PowerShell Core 6.2.0-rc.1
Windows PowerShell v5.1 
```

### LINKED ISSUE #16019: In remoting calls, combining the $using: scope with namespace variable notation is quietly ignored
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Possibly related:  #9204

Using namespace variable notation in combination with the `$using:` scope works as expected with _jobs_; e.g.:

```powershell
$env:FOO = 'bar'
# Outputs 'bar', as expected.
Start-Job { $using:env:FOO } | Receive-Job -Wait -AutoRemoveJob
```

By contrast, in the context of _remoting_ it fails quietly (the reference evaluates to `$null`):

```powershell
# Run from an elevated session on a machine with remoting enabled.
$env:FOO = 'bar'
Invoke-Command -ComputerName . { $using:env:FOO }
```

### Expected behavior

`'bar'` should print.

### Actual behavior

Nothing is output.

### Error details

_No response_

### Environment data

```powershell
PowerShell Core 7.2.0-preview.9
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by dwtaber**
# PR Summary

This PR improves `Invoke-Command`'s handling of cases that combine `$using:` expressions with variable namespace notation when the `-ComputerName` parameter is used.
Fixes #9204
Fixes #16019 

## PR Context

When the `-ComputerName` parameter is used, `Invoke-Command` is unable to check which version of PowerShell is available on the remote computer and assumes v2.0. Because PowerShell 2.0 can't parse `$using:` expressions, the `ScriptBlock` is modified before sending, with `$using:` variables renamed to replace the `$using:` expression with `$__using_`.  Currently, the code that renames these variables doesn't check whether the variable path is qualified.  In cases where variable namespace notation is used, this code produces variable names like `$__using_env:foo`, preventing the remote computer from parsing the variables correctly.  The changes in this PR add handling for qualified variable paths, producing variable names like `$__using_env_foo`

This PR does not fix all issues with the handling of `$using:` expressions.  Variable names that include special characters still aren't parsed correctly, for instance.  Since a user technically _could_ name a variable `$__using_env_foo`, this might be considered an ["unlikely grey area" breaking change](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md). Long-term, it might be worth reconsidering how `Invoke-Command` handles the `-ComputerName` parameter; always falling back to v2.0 seems unnecessarily restrictive.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
> When the `-ComputerName` parameter is used, `Invoke-Command` is unable to check which version of PowerShell is available on the remote computer and assumes v2.0.

I wonder why we need the workaround if we can prepare full fix.

If I understand correctly, with  ComputerName we create new runspace but do not open it in `CreateHelpersForSpecifiedComputerNames()`, as result we can not detect remote PowerShell version. So I guess we need to open the new runspace in `CreateHelpersForSpecifiedComputerNames()`.

**Comment by dwtaber** [comment]
> > When the `-ComputerName` parameter is used, `Invoke-Command` is unable to check which version of PowerShell is available on the remote computer and assumes v2.0.
> 
> I wonder why we need the workaround if we can prepare full fix.
> 
> If I understand correctly, with ComputerName we create new runspace but do not open it in `CreateHelpersForSpecifiedComputerNames()`, as result we can not detect remote PowerShell version. So I guess we need to open the new runspace in `CreateHelpersForSpecifiedComputerNames()`.

Implementing proper version detection for the `-ComputerName` parameter seems preferable to me as well.  Since the current behavior (falling back to v2) is documented at various points in the code comments, it seemed to be an intentional design choice, maybe based on factors I wasn't aware of.  Honestly, this is the first pull request I've submitted, and I didn't want to overstep with a potentially significant change to how `Invoke-Command` connections work, so I went with a more conservative fix, but I'm not married to it.

**Comment by dwtaber** [comment]
Can I get some guidance on the two tests that have failed?  It looks like `Invoke-WebRequest` failed to reach a URI, but I can't see how my changes would have affected that cmdlet.  Is it possible the resource was just unavailable when the test was run?

I'd also appreciate any suggestions on writing a Pester test for this issue.  I don't think any of the current remoting tests target a remote computer, so they don't offer much guidance.  So far I've been testing against computers available to me, but obviously that's too context-dependent to be of use to anyone else.  Are there any designated endpoints for this sort of testing?

**Comment by iSazonov** [comment]
I restarted CI-static.

**Comment by rjmholt** [comment]
Tagging @PaulHigin for review as well

**Comment by dwtaber** [comment]
Git/GitHub novice question: when updating from the master branch, I should have used a fast-forward merge to avoid creating a separate merge commit, right? How much of a problem is it that I, uh, didn't do that?

**Review by PaulHigin — APPROVED** [review]
Changes look good to me.

**Review by rjmholt — APPROVED** [review]

**Comment by ImportTaste** [comment]
I really wish this had made it into 7.2, waiting for 7.3 for an essential fix like this really sucks.

**Comment by TravisEz13** [comment]
@PowerShell/powershell-maintainers 
We only take security fixes and regression to LTS.  This is appropriate for 7.3.  Rejecting back-port.

**Pull request merged**
