### PR TITLE
Upgrade .Net Core Runtime from 2.1.5 to 2.2.0-preview3-27014-02

### PR DESCRIPTION
**Pull request by bergmeister**
## PR Summary

Upgrading to the latest official preview of .Net Core 2.2.
The update to 2.2 was applied everywhere except for the alpine docker image scripts as they need validation from the MSFT side beforehand.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
Perhaps worth the wait. It seems 2.2 branch inspired only by ASP.NET and EntityFramework changes.
Release 2.2.0 is expected in December and PowerShell release 6.2.0 in March. By this moment we will have a 2.2.1 service release. Also most of ordinary changes will be in 3.0 not in servicing releases and 2.2.

**Comment by SteveL-MSFT** [comment]
I'm ok with taking .NET Core 2.2 early in our 6.2-preview releases to make sure nothing obvious gets broken and any major issues gives .NET Core time to fix in 2.2.x

**Comment by iSazonov** [comment]
Preview3 is expected in weeks https://github.com/aspnet/Announcements/issues/307.

**Review by TravisEz13 — DISMISSED** [review]

**Comment by TravisEz13** [comment]
The changes look good.  We are verifying with DotNet that 2.2 will be an LTS.

**Comment by TravisEz13** [comment]
2.2 will not be an LTS.  We should probably stay on 2.1 for now.  At least until we discuss the impact of this.  I like your changes to the xunit tests though.  Would you mind submitting a separate PR for those?  I can if you want me to.

**Comment by bergmeister** [comment]
Ok, thanks for the info, I will open a PR for the xunit test runner tomorrow.

**Comment by SteveL-MSFT** [comment]
We're having conversations with .NET Core team in terms of support alignment between PSCore6 and .NET Core.  Until that gets resolved, we should only move to LTS versions of .NET Core.

**Comment by iSazonov** [comment]
I see .Net Core 3.0 will come with tons changes, enhancement and additions. We may have to put a lot of effort into upgrading to this version. I think we can close the PR.

**Comment by bergmeister** [comment]
Ok, agreed, I will close the PR but leave the branch in case anyone in the community is interested.

**Pull request closed without merging**
