### PR TITLE
Revive 'download.sh' and make it redirect to 'install-powershell.sh'

### PR DESCRIPTION
**Pull request by daxian-dbw**
Per the discussion at https://github.com/PowerShell/PowerShell/pull/5309#issuecomment-342575567, I add the `download.sh` back and make it redirect to `install-powershell.sh`.

/cc @DarwinJS

### CODE REVIEW

**Review by adityapatwardhan — APPROVED** [review]
LGTM

**Comment by adityapatwardhan** [comment]
@daxian-dbw Restarted the macOS build.

**Comment by DarwinJS** [comment]
Great!

**Comment by daxian-dbw** [comment]
macCI was cancelled several times. This change doesn't affect anything in PowerShell, so I will merge it.

**Pull request merged**
