### PR TITLE
Change New-FileCatalog -CatalogVersion default to 2

### LINKED ISSUE #19131: Update New-FileCatalog -CatalogVersion default to 2
### Summary of the new feature / enhancement

Now that Windows 7 is no longer supported please update `New-FileCatalog -CatalogVersion` to `2`. Here is the section from the help documenation.

> However, `1.0` is the only supported algorithm on Windows 7 and Server 2008R2.

### Proposed technical implementation details (optional)

Change this line to 2.

https://github.com/PowerShell/PowerShell/blob/2f43013df380e6ea1f04ddcf32d9efdefa9ae6a3/src/Microsoft.PowerShell.Security/security/CatalogCommands.cs#L163

### PR DESCRIPTION
**Pull request by ThomasNieto**
# PR Summary

Updates the default parameter value from 1 to 2.

## PR Context

Resolves #19131

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10487
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by ThomasNieto** [comment]
@daxian-dbw think I could get the CI to run again? The test failure isn't related to this change.

**Review by iSazonov — COMMENTED** [review]
Have we a test for default value?

**Comment by ThomasNieto** [comment]
@iSazonov the existing test using the default value was updated to check the algorithm is now using SHA256 instead SHA1.

**Review by iSazonov — APPROVED** [review]

**Comment by ThomasNieto** [comment]
@iSazonov do you have access to kick off CI again?

**Comment by iSazonov** [comment]
Macos Test-Connection test was restarted.

**Review by daxian-dbw — APPROVED** [review]

**Comment by daxian-dbw** [comment]
The breaking change was reviewed and approved by the Security WG (see the corresponding issue).

**Pull request merged**
