### PR TITLE
WIP: Devcontainer updates and support codespaces

### PR DESCRIPTION
**Pull request by JustinGrote**
# PR Summary

This provides several updates with the goal of enabling a PowerShell contributor to begin contributing as fast as possible to PowerShell utilizing a devcontainer or CodeSpaces and Visual Studio Code.

* Update devcontainer base OS to official vscode Ubuntu 18.04 devcontainer image
* Add devcontainer tooling and initial setup scripts to match the docs/building/linux.md document as closely as possible
* Add setup steps mirrored from the codespaces devcontainer repo to ensure proper codespaces support
* Remove legacy Fedora references that are no longer reference in the codebase or Azure Pipelines AFAIK

## Known Issues
* Codespaces doesnt support `WaitFor` on the creation commands yet, so occasionally a race condition occurs where omnisharp loads before dotnet has been bootstrapped by `Start-PSBootstrap`, leading to a dotnet not found message. This can be resolved by just reloading the window. I can also suppress the message but I chose not to as it seems to be fairly rare. Once `waitfor` is supported then this won't be an issue

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by JustinGrote** [comment]
@msftbot still active, just life stuff in between :)

**Comment by fflaten** [comment]
Maybe include `<EnableWindowsTargeting>true</EnableWindowsTargeting>` per project or in a `Directory.Build.props` in the root so we can compile for Windows. Had to use that to catch all errors in #17769.

**Comment by JustinGrote** [comment]
@fflaten I don't think windows containers are supported for either devcontainers or codespaces?

**Comment by fflaten** [comment]
> @fflaten I don't think windows containers are supported for either devcontainers or codespaces?

Not Windows containers, but being able to run `Start-PSBuild -Runtime win7-x64` in Ubuntu container. Without that property it won't download the required Windows targeting packs. See https://docs.microsoft.com/en-us/dotnet/core/tools/sdk-errors/netsdk1100

**Comment by JustinGrote** [comment]
Thanks @msftbot, still active :)

**Comment by JustinGrote** [comment]
@SteveL-MSFT have some time to investigate this again. Question: Prebuilds now use Github Actions, and are stored in Github storage. These have a free allocation now for public repos, as such will this be possible to do now?

**Pull request closed without merging**
