### PR TITLE
Fix "Pull Request Process" dead link in GOVERNANCE.md

### PR DESCRIPTION
**Pull request by IISResetMe**
## PR Summary

In the project governance document, the current "Pull Request Process" anchor links to a non-existing document. 

The closest I could find was the Pull Request section in the CONTRIBUTING.md guide, so I've added that in the link section.

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [X] Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [ ] Issue filed - Issue link:
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

### CODE REVIEW

**Comment by markekraus** [comment]
@IISResetMe I have re-added the Pull request template to your PR description. Can you please update the template accordingly? Thanks!

**Comment by IISResetMe** [comment]
@markekraus Done!

**Review by markekraus — APPROVED** [review]
LGTM

**Comment by IISResetMe** [comment]
@iSazonov @SteveL-MSFT Going forward, we should probably describe the PR flow explicitly in /docs, like the remaining governance documentation

**Comment by SteveL-MSFT** [comment]
@IISResetMe please open a new issue for that

**Review by SteveL-MSFT — APPROVED** [review]

**Pull request merged**
