### PR TITLE
Fix the indicator for redirecting standard input

### LINKED ISSUE #2745: NativeCommandProcessor not TTY compatible
NativeCommandProcessor no longer presents a TTY device to native commands, at least on .NET Core 1.1.

This prevents the use of repls, screen and tmux on UNIX based systems.

The problem appears to have been introduced in https://github.com/PowerShell/PowerShell/commit/b93042670f15aeb1b473ab420f4421ddc3be5b78

Steps to reproduce
------------------
1. On Linux, run `Start-DevPowerShell`
1. Execute `stty`
Expected behavior
-----------------
```
speed 38400 baud; line = 0;
-brkint -imaxbel iutf8
```

Actual behavior
---------------
```
/usr/bin/stty: 'standard input': Inappropriate ioctl for device
````

Environment data
----------------

```
Name                           Value                                                                                                                                                                                                         
----                           -----                                                                                                                                                                                                         
PSVersion                      6.0.0-alpha                                                                                                                                                                                                   
PSEdition                      Core                                                                                                                                                                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                                                                                                       
BuildVersion                   3.0.0.0                                                                                                                                                                                                       
GitCommitId                    v6.0.0-alpha.12-102-g594759b36fc11272b5842c8ef823c224a5f67836                                                                                                                                                 
CLRVersion                                                                                                                                                                                                                                   
WSManStackVersion              3.0                                                                                                                                                                                                           
PSRemotingProtocolVersion      2.3                                                                                                                                                                                                           
SerializationVersion           1.1.0.1   
```

### PR DESCRIPTION
**Pull request by daxian-dbw**
Fix #2745 
`PipelinePosition` starts from 1, ~~so the indicator for redirecting standard input should be `PipelinePosition > 1`.~~

When there is input to a native command like `1,2,3 | <native>`, the native command is still marked as position 1 in the pipeline because the input doesn't take up pipeline position. So we cannot simply using `PipelinePosition` to decide whether standard input needs to be redirected.

The new fix swaps the running order of the following code in `PipelineProcessor.Start`, so as to make sure `ExpectingInput` is set before calling `DoPrepare`. Then in `NativeCommandProcessor.Prepare` we can use `MyInvocation.ExpectingInput` to check whether to redirect standard input.
```
commandProcessor.DoPrepare(psDefaultParameterValues);
myInfo.ExpectingInput = commandProcessor.IsPipelineInputExpected();
```

### CODE REVIEW

**Comment by daxian-dbw** [comment]
Will add a test in a few mins.

**Comment by daxian-dbw** [comment]
@vors @lzybkr From reading the code, I feel it's fine to swap the order of calling `DoPrepare` and assigning `myInfo.ExpectingInput`, but I would need to run all tests to verify. If you know something that will obviously be broken by this change, please let me know.

**Comment by daxian-dbw** [comment]
`stty` may not be on the Travis CI build. I will come up with a more robust test.

**Review by vors — APPROVED** [review]

**Comment by daxian-dbw** [comment]
I have ran all tests on Linux, there were 2 failures, and they are related to `Get-PackageProvider` and `Register-PackageSource`. This was because I didn't specify `-PSModuleRestore` when building and thus I don't have PackageManagement and PowerShellGet modules installed.

So Linux test run was good.

image

**Comment by daxian-dbw** [comment]
OK, finally finished running all tests on windows and analyzing the failures. There are 8 test failures:
1. `SSH Remoting API Tests.SSHConnectionInfo should throw file not found exception for invalid key file path` -- ssh.exe is not available on my test machine
2. 4 failures in `Get-ComputerInfo` tests for properties: `DeviceGuardAvailableSecurityProperties`, `DeviceGuardRequiredSecurityProperties`, `DeviceGuardSecurityServicesConfigured`, `DeviceGuardSecurityServicesRunning` -- somehow there is no value for them on my test VM, which is WS2016.
3. "Set-Date should be able to set the date in an elevated context" -- `Set-Date` fails even in elevated session because `NativeMethods.SetLocalTime(ref systemTime)` fails in `SetDateCommand.ProcessRecord`. It may be due to the test machine is a VM. `Set-Date` doesn't work well with VMs.
4. `Register-PackageSource` and `Get-PackageProvider` cannot be found -- PackageManagement related.

image

None of the failures is related to swapping the order of `DoPrepare` and assigning `myInfo.ExpectingInput`. So Windows test run was good.

**Pull request merged**
