### PR TITLE
Fix Update-Help failing silently with implicit non-US culture.

### LINKED ISSUE #17696: Update-Help fails silently for UICulture en-GB
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Help pages for `about_topics` are missing and cannot be downloaded on en-GB locale. Verbose output shows only redirects and zero downloads. Issue can be fixed by passing `-UICulture en-US` to `Update-Help`. I understand that the help pages are set to specific locale, but if it causes them to be completely missing in a different locale of same language, it's a bad user experience. Either show a warning "Help pages for UICulture en-GB not found, but available in en-US, try calling with `-UICulture en-US`", or just download them automatically. `Get-Help` already works with partial locale matches, just `Update-Help` needs fixing. 

```powershell
> Get-UICulture
LCID             Name             DisplayName
----             ----             -----------
2057             en-GB            English (United Kingdom)
> Update-Help -Force -Verbose
```

### Expected behavior

```console
> Get-Help about_operators
ABOUT_OPERATORS
Short description
Describes the operators that are supported by PowerShell.
```

### Actual behavior

```console
> Get-Help about_operators
Get-Help: Get-Help could not find about_operators in a help file in this session. To download updated help topics type: "Update-Help". To get help online, search for the help topic in the TechNet library at https://go.microsoft.com/fwlink/?LinkID=107116.
```

### Error details

```console
> get-error
Exception             :
    Type        : Microsoft.PowerShell.Commands.HelpNotFoundException
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : Get-Help could not find about_operators in a help file in this session.
To download updated help topics type: "Update-Help". To get help online, search for the help
topic in the TechNet library at https://go.microsoft.com/fwlink/?LinkID=107116.
            HResult : -2146233087
        CategoryInfo          : ResourceUnavailable: (:) [],
ParentContainsErrorRecordException
        FullyQualifiedErrorId : HelpNotFound
        ErrorDetails          :
    HelpTopic   : about_operators
    Message     : Get-Help could not find about_operators in a help file in this session. To
download updated help topics type: "Update-Help". To get help online, search for the help
topic in the TechNet library at https://go.microsoft.com/fwlink/?LinkID=107116.
    HResult     : -2146233087
CategoryInfo          : ResourceUnavailable: (:) [Get-Help], HelpNotFoundException
FullyQualifiedErrorId : HelpNotFound,Microsoft.PowerShell.Commands.GetHelpCommand
InvocationInfo        :
    MyCommand        : Get-Help
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 8
    Line             : get-help about_operators
    PositionMessage  : At line:1 char:1
                       + get-help about_operators
                       + ~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : get-help
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment data

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.5
PSEdition                      Core
GitCommitId                    7.3.0-preview.5
OS                             Linux 5.15.0-1011-raspi #13-Ubuntu SMP PREEMPT Thu Jun 2 11:44…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by dkaszews**
# PR Summary

`HelpCultureNotSupported` is caught and ignored with implicit culture (`-UICulture` not given explicitly, defaults to system) to allow trying again with culture's parents. It does not however check if there are any more fallbacks, so all errors of this type are completely silenced. I store first error of this type, then show it if none of the fallbacks succeed,

Fixes #17696 

## PR Context

`Update-Help` with implcit culture fails silently on non-US systems (`en-GB` in my case), with no feedback on what is wrong even when using `-Verbose`. With this fix, the user is shown the same error as with explicit `-UICulture (Get-UICulture)`, which clearly describes what they should do:

```powershell
Update-Help: Failed to update Help for the module(s) '...' with UI culture(s) {en-GB} : No UI culture was found that matches the following pattern: en-GB. Verify the pattern and then try the command again..
English-US help content is available and can be installed using: Update-Help -UICulture en-US.
```

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed: [Docs issue #9072](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9072)
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@dkaszews Thanks for submitting the PR!
@adityapatwardhan, can you please review when you have time? Thanks!

**Comment by adityapatwardhan** [comment]
@dkaszews I like the change. Thanks for the PR. For testing, I would add some test hooks to make sure we fall in to the expected code paths. 

Look at the files here to see how test hooks can be added:

https://github.com/PowerShell/PowerShell/search?q=testhook&type=code

Also, the test hook is used in product code like this:

https://github.com/PowerShell/PowerShell/blob/17791759356ffa6e2ae657d2ec19a147ce062957/src/Microsoft.PowerShell.Commands.Management/commands/management/Computer.cs#L450-L456

**Comment by dkaszews** [comment]
@adityapatwardhan Thanks for the tip! Please take a look if something like this is good.

**Comment by dkaszews** [comment]
If found additional issues all related to matching culture:

1. We use globbing to try and match current culture with the one in help, but because valid `CultureInfo` values never contain wildcards, this does nothing. E.g.: `en-GB` has fallback `en`, but it still won't glob match with `en-US`. A simple fix would be to suffix (or surround) culture with `'*'`:
    ```csharp
    // UpdateableHelpSystem:594:
    IEnumerable<WildcardPattern> patternList = SessionStateUtilities.CreateWildcardsFromStrings(
    // - globPatterns: new[] { currentCulture },
	globPatterns: new[] { currentCulture + '*' },
	options: WildcardOptions.IgnoreCase | WildcardOptions.CultureInvariant);
    ```
1. Second issue is that in `UpdateableHelpSystemBase:EndProcessing`, when we collapse all `HelpCultureNotSupported` exceptions for different modules into a single error, the supported culture is actually ignored, always displaying `"en-US is supported"` without checking that it actually is. That may be true for PowerShell-core modules, but if some module provides help in let's say `en-GB` or even `fr-FR`, it will be misleading, as I believe may be the case in #17534 . Fix for that is slightly more involved, as it would require storing the supported cultures in the exception and probably reworking the exception hierarchy, as right now they are only in string. 

Which of those should I fix here and which should be a separate issue? I would say the first one can be here, as it's just a single line, but the other I would prefer merging separately.

**Comment by dkaszews** [comment]
CodeRefactor reports new issues in `UpdateHelpCommand.cs` on lines 471 and 476, but I only modified 217 and see similar errors at other places in the file. How can I get it resolved as false positive?

**Comment by adityapatwardhan** [comment]
Thanks for the updates. If the CodeFactor issues are not in the code block you touched, you can ignore them.

I would prefer both the changes 1 and 2 in a separate PR as it changes the behavior and is an improvement in fallback lookup. 
This PR is focused on fixing the error message on fallback.

**Review by adityapatwardhan — APPROVED** [review]

**Comment by dkaszews** [comment]
@adityapatwardhan Sure, I'll create new issues and separate PRs for those two later

**Comment by dkaszews** [comment]
@adityapatwardhan Anything else I should do before this can be merged?

**Comment by adityapatwardhan** [comment]
@dkaszews thank you for your contribution!

**Pull request merged**
