### PR TITLE
6.0.0: Fix x86 installer bug: it gets installed as an x64 component and has the same UpgradeCode as the x64 installer leading to an uninstallation of an x64 installation (and vice versa)

### PR DESCRIPTION
**Pull request by bergmeister**
## PR Summary

This is the PR for 6.0.0, which is based on the 6.0.0 branch with the cherry-picked commit fix. 
It fixes bug #5597: x86/x64 installer are uninstalling each other when installing either of them:

-Make x86 installer to be installed as a x86 component (-arch argument to candle.exe, which sets the `sys.BUILDARCH` variable)
-Make the UpgradeCode unique per platform

Replace `var.ProductTargetArchitecture` variable with sys.BUILDARCH use to have only 1 variable for the architecture
Additionally, the architecture was appended to the package name to be able to distinguish the installations.

Windows installer PRs usually got reviewed by @SteveL-MSFT in the past.

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [x] Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission) : Not sure? Package name now includes architecture...
    - [x] Issue filed - Issue link: https://github.com/PowerShell/PowerShell/issues/5597
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] NA [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [] NA [Add `[feature]` if the change is significant or affectes feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

### CODE REVIEW

**Comment by TravisEz13** [comment]
Closing this PR.  Maintainers will submit a PR merging the commits for master to `6.0.0`

**Comment by bergmeister** [comment]
OK. What I have seen locally, is that it merges fine with 6.0.0 except for a whitespace conflict that tortoise-git auto-merged for me.

**Comment by bergmeister** [comment]
I did some analysis and it showed that the bug about the upgrade code being constant and the `-arch` parameter being hardcoded to `x64` was already present in the first commit [here](https://github.com/PowerShell/PowerShell/commit/8f1a5194c563a3a74e7b92181c87b9e33803c4b4) that added the WiX file and the MSI build script...

**Comment by TravisEz13** [comment]
PR #5828 is open to merge the equivalent to `6.0.0`

**Pull request closed without merging**
