### PR TITLE
Update installpsh-<distrofamily>.sh Installers to Handle "preview" in version number

### PR DESCRIPTION
**Pull request by DarwinJS**
## PR Summary

Remove sed global option from version tag parsing for letter v removal, which currently hacks the word "preview" to "preiew"

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [X] Issue filed - Issue link: https://github.com/PowerShell/PowerShell/issues/6572
- **Testing - New and feature**
    - [X] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by TravisEz13** [comment]
We should consider using https://github.com/PowerShell/PowerShell/blob/master/tools/metadata.json instead of the tag.  You could add a new name-value pair for the latest preview release.

**Comment by DarwinJS** [comment]
But wouldn't you need to install tools to parse json or end up parsing json using regex?  Wanna keep this as broad as possible with zero prerequisites if possible.

**Comment by TravisEz13** [comment]
the couple of distros I've tried come with `jq`, but the docker containers don't.  It's a good point.  I'm happy with this change as is if you don't feel it's worth the time and investigation.

**Review by TravisEz13 — APPROVED** [review]

**Comment by DarwinJS** [comment]
Thanks @TravisEz13 !  Since this is like PowerShell's "bootstrapper" for non-windows, I'm interested in hyper-minimalism over modern methods or data formats.

**Pull request merged**
