### PR TITLE
Move Start-TypeGen logic from Build.psm1 to SDK csproj file

### PR DESCRIPTION
**Pull request by iSazonov**
Related #3400
(Also it is one step to unblock #3690)

Now Microsoft.PowerShell.SDK.csproj:
1. Generate Reference Assembly List ("RefAssemblyList.inc" file) in project local sub directory "gen" (Target Name="TypeCatalogGen"):
 - Check if Reference Assembly List is updated and only then overwrite RefAssemblyList.inc
 - If RefAssemblyList.inc is updated then generate new CorePsTypeCatalog.cs 
2. Support Clean target to remove RefAssemblyList.inc (for rebuild)

### CODE REVIEW

**Comment by iSazonov** [comment]
@daxian-dbw I think I'm a little late with the PR, but it could still be useful for a while.

**Comment by daxian-dbw** [comment]
@iSazonov We still need to have `TypeCatalogGen` in our build. With the type catalog, you can use a .NET type without caring whether the assembly that contains it is already loaded because powershell is able to look it up in the type catalog and load the assembly automatically. So it would be a breaking change if we remove the type catalog. And `TypeCatalogGen` will be useful for new features too, for example, the extension methods support @powercode is working on -- we will need to do some analysis of all reference assemblies at build time to build a cache of all .NET extension methods, which will improve the runtime performance. So this PR is not late 😄
BTW, I'm busy on other tasks recently and thus is slow on code review, sorry for that.

**Comment by iSazonov** [comment]
@TravisEz13 @daxian-dbw Could you please continue the code review?

**Comment by TravisEz13** [comment]
@daxian-dbw Are you ok with this change now?

**Comment by daxian-dbw** [comment]
@TravisEz13 I haven't got the time to carefully review this yet. Will do it soon.

**Comment by iSazonov** [comment]
@daxian-dbw Could you please review?

**Comment by daxian-dbw** [comment]
Will the `TypeCatalogGen` target execute when we running `dotnet restore` or `dotnet build` on `Microsoft.PowerShell.SDK.csproj`?

**Comment by iSazonov** [comment]
We call `dotnet msbuild .\Microsoft.PowerShell.SDK.csproj /t:"Clean;TypeCatalogGen" "/property:DesignTimeBuild=true" ` in Build.psm1 in the same point as before - so the behavior must be the same.

Ah, sorry - your question of a direct call - it needs to be checked explicitly because dependencies is deeply.

**Comment by daxian-dbw** [comment]
Great. My concern was that the type catalog (both `.inc` and `.cs`) would be generated when just running `Start-PSBuild` for a build. I will continue the review.
(BTW, I took Monday off, so please don't be concerned if I didn't reply promptly.)

**Comment by TravisEz13** [comment]
@daxian-dbw Do you want to review?

**Comment by iSazonov** [comment]
Should I fix or close the PR?

/cc @daxian-dbw

**Comment by daxian-dbw** [comment]
Sorry that I completely lost the context here. I won't have much time for code review recently. I'm fine we close this PR for now and we can revive it when needed.

**Pull request closed without merging**
