### PR TITLE
Remove WriteVerbose statement from ConvertTo-Json

### LINKED ISSUE #7486: Remove unnecessary verbose message from ConvertTo-Json
In #6392 this line below was added to the `ConvertTo-Json` cmdlet.

`WriteVerbose(StringUtil.Format(UtilityCommonStrings.ConvertToJsonProcessValueVerboseMessae, t.Name, depth));`

This produces unnecessarily verbose output when converting complex objects to json.

In my opinion, this verbosity doesn't add any value and clutters up script output.

```
VERBOSE: Processing object of type [OrderedDictionary] at depth 0
VERBOSE: Processing object of type [PSCustomObject] at depth 1
VERBOSE: Processing object of type [OrderedDictionary] at depth 0
VERBOSE: Processing object of type [PSCustomObject] at depth 1
```

I propose either removing this entry entirely or changing it to `WriteDebug` to keep the noise down.

### PR DESCRIPTION
**Pull request by devblackops**
## PR Summary

Fix #7486.

In PR #6392, a `WriteVerbose` statement was added to `ConvertTo-Json` which I feel is unnecessary. On large or complex objects being serialized to json, this produces a ton of verbose messages which isn't adding any value to the end user. This PR removes that statement.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [X] Issue filed - Issue link: #7486 
- **Testing - New and feature**
    - [X] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
@devblackops I wonder do you see the verbose messages without `-Verbose` ?

**Review by markekraus — CHANGES_REQUESTED** [review]
@devblackops Please also remove the message string which would no longer be used after this pr:

https://github.com/PowerShell/PowerShell/blob/791159d615adf6cdeb67940413d2e96ea0c61274/src/Microsoft.PowerShell.Commands.Utility/resources/UtilityCommonStrings.resx#L177-L179

**Comment by devblackops** [comment]
@iSazonov The messages aren't shown without `-Verbose` but often will be inherited from cmdlets/functions that invoke `ConvertFrom-Json` that **do** have `-Verbose` specified.

It's easy enough to suppress the verbose output with `-Verbose:False` or set it via `$PSDefaultParameterValues` but in this case, these messages aren't really adding any value, hence the PR to remove them.

**Comment by devblackops** [comment]
@markekraus I pushed a commit to remove the resource string.

**Review by dantraMSFT — APPROVED** [review]
I agree the verbose statement doesn't add much value.

It was added when StopProcessing was added so I expect it was done for debugging purposes.

**Review by markekraus — APPROVED** [review]
LGTM

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@devblackops Thanks for your contribution!

**Pull request merged**
