### PR TITLE
Replace Archive module source code by download from the gallery

### PR DESCRIPTION
**Pull request by vors**
I pointed it to www.powershellgallery.com and not the myget at the moment.
I think it's reasonable at the moment.
If we decide to consume dev build of Archive module in the future, we can change the `SourceLocation` easily.

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
Fixing helpuri failure https://github.com/PowerShell/Microsoft.PowerShell.Archive/pull/25

@vors you should compare the test code between the copy we have in PS/PS and what is in the Archive repo and merge them

**Comment by vors** [comment]
The old failures seems to relate to the older (non-compatible with Core edition) version of Acrhive module in the gallery.
If they persist, we would need to initiate a new release for the archive before the switch.

**Comment by vors** [comment]
@SteveL-MSFT tests yes, we should remove them before merging.
Meanwhile, they revile that we have old, Unix-incompatible release in the gallery.

This is blocked on https://github.com/PowerShell/Microsoft.PowerShell.Archive/issues/26

**Comment by SteveL-MSFT** [comment]
@vors I'll have someone look into getting those issues fixed

**Comment by chunqingchen** [comment]
Can you please resolve the conflicts?

**Comment by SteveL-MSFT** [comment]
CC @anmenaga

**Comment by mirichmo** [comment]
@SteveL-MSFT @anmenaga - What is the current status of this? Is it still blocked?

**Comment by anmenaga** [comment]
The dependent work item (PowerShell/Microsoft.PowerShell.Archive#26) is almost done. I expect that it will be checked in next week.

**Comment by mvadu** [comment]
@anmenaga ANy progress with the checkin?

**Comment by vors** [comment]
Ready for a review!
@mirichmo @anmenaga

**Review by anmenaga — APPROVED** [review]
Looks good.

**Pull request merged**
