### PR TITLE
Fix: Update AppxManifest.xml to show application name on DefaultTile for Windows 10 21H2/22H2 Start Menu

### PR DESCRIPTION
**Pull request by Zhoneym**
# PR Summary

Fix: Update AppxManifest.xml to show application name on DefaultTile for Windows 10 21H2/22H2 Start Menu

## PR Context

- Modified: AppxManifest.xml
- Attempt to fix the issue of Powershell's magnet icon being too large on the Windows 10 start menu and not displaying the application name.

Original issue: https://github.com/PowerShell/PowerShell/issues/20055

powershell 

Expected fix: Fixed tile displaying application name 'PowerShell' on Windows 10 22h2 Start menu

## PR Checklist

- [x] PR title clearly indicates the modification of AppxManifest.xml
- [x] PR description summarizes the changes in AppxManifest.xml  
- [x] No breaking change observed in AppxManifest.xml
- [x] Updated manifest version in AppxManifest.xml
- [x] Impacts user interface, documentation needs to be updated
- [ ] Start menu screenshot provided to demonstrate the fix
- [ ] Test cases added to cover manifest file changes
- [x] Manifest tool used to validate schema compliance  
- [x] No permission changes observed in AppxManifest.xml
- [x] App upgrade impact considered for manifest changes

### CODE REVIEW

**Comment by Zhoneym** [comment]
https://answers.microsoft.com/zh-hans/windows/forum/all/%E6%9C%89%E4%BA%9Bmicrosoft/ee1b391c-5ce6-4304-903e-94be1fa29bb7

**Comment by dkaszews** [comment]
Please use the [pull request template](https://github.com/PowerShell/PowerShell/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and give the PR a descriptive name

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Review by daxian-dbw — APPROVED** [review]

**Comment by Zhoneym** [comment]
> 请使用[拉取请求模板](https://github.com/PowerShell/PowerShell/blob/master/.github/PULL_REQUEST_TEMPLATE.md)并为 PR 指定一个描述性名称

finnished

**Review by SteveL-MSFT — APPROVED** [review]

**Review by TravisEz13 — APPROVED** [review]

**Pull request merged**
