### PR TITLE
Update width of datetime formatting to accommodate change in Japan datetime era

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

With the new Emperor, Japan is entering a new era which affects the format of their datetime.  It needs one more character to the width.  Since I don't anticipate this change happening again (the last time I believe was hundreds of years ago), I'm simply updating the width from 25 to 26 rather than defining a const.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/building/windows-core.md.https://www.microsoft.com/net/core#windowscmd should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 113
113:                                 throw "retry of URL failed with error: $($_.Message)"

```

**Comment by SteveL-MSFT** [comment]
@PoshChan please retry static

**Comment by PoshChan** [comment]
@SteveL-MSFT, successfully started retry of `PowerShell-CI-static-analysis`

**Review by adityapatwardhan — APPROVED** [review]

**Comment by stknohg** [comment]
This pull request probably corrects the display of "元年"(the first year), but I think it seems to have no effect.
I tried to display "元年" with the latest master build(2be3db8ab8757fe9ecccd2cc545ae9044ed76574).

## Language Setting

fig01

* Using Japanese Era

## Result of `dir` command

fig02

```
C:\> $PSVersionTable.GitCommitId
6.2.0-rc.1-219-g2be3db8ab8757fe9ecccd2cc545ae9044ed76574
C:\> dir


    Directory: C:\

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----          平成31年4月26日    14:58                Go
d----          平成31年4月18日    17:36                Intel
d----          平成30年9月15日    16:33                PerfLogs
d-r--            令和元年5月7日    18:28                Program Files
d-r--            令和元年5月7日    15:34                Program Files (x86)
d----            令和元年5月8日     9:38                Program Files2
d----          平成31年4月26日    16:08                project
d----            令和元年5月7日    15:56                temp
d-r--          平成31年4月26日    13:36                Users
d----            令和元年5月7日    10:42                Windows
d----            令和元年5月7日     9:19                Windows.old
```

* LastWriteTime width is 26.
* `元年` is 2 Full width charactors. "令和元年5月7日"(=2019.05.07) has 8 charactors, so the date of  LastWriteTime starts with 2 whitespaces.

**Comment by stknohg** [comment]
To solve this problem fundamentally, it is necessary to handle the east asian full width character's width correctly.
(related issue ; https://github.com/PowerShell/PowerShell/issues/6290)

This full width charactor problem is very difficult, I think it is better to simply ignore the display collapse.

**Pull request merged**
