### PR TITLE
Mark private members as static part 10

### PR DESCRIPTION
**Pull request by xtqqczze**
`src\System.Management.Automation\`
-`src\System.Management.Automation\engine\`

Contributes to #13897.

https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1822

### CODE REVIEW

**Comment by xtqqczze** [comment]
CodeFactor "Complex Method" issues are preexisting.

**Comment by iSazonov** [comment]
@xtqqczze Please resolve merge conflicts.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
CI static fails on https://www.codefactor.io/

**Comment by xtqqczze** [comment]
> CI static fails on https://www.codefactor.io/
> 
> > **[HTTP Error 500.31 - Failed to load ASP.NET Core runtime](https://www.codefactor.io/)**

Tracking issue opened: #14269.

**Comment by iSazonov** [comment]
> > CI static fails on https://www.codefactor.io/
> > > **[HTTP Error 500.31 - Failed to load ASP.NET Core runtime](https://www.codefactor.io/)**
> 
> Tracking issue opened: #14269.

It works already :-)

**Pull request merged**
