### PR TITLE
Add global AnalyzerConfig with default configuration

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

* Copy `microsoft.codeanalysis.netanalyzers/5.0.0-rtm.20502.2/editorconfig/AllRulesDefault/.editorconfig` to `.globalconfig`
* Add Add IDE diagnostics to `.globalconfig` with most rules hidden
  * copied from [dotnet/runtime](https://github.com/stephentoub/runtime/blob/3b6600cbefe6b96706c5315ce184accbb4501f3b/eng/CodeAnalysis.ruleset) and converted using `RulesetToEditorconfigConverter.exe`
* Disable diagnostics for `Microsoft.Management.UI.Internal`

## PR Context

Alternative to #12892

If Visual Studio 2019 is installed, it should be updated to 16.8 Preview5+ because OmniSharp appears to prefer the Visual Studio  MSBuild instance to the StandAlone instance. Otherwise, the global AnalyzerConfig may be ignored.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [NA] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [NA] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [NA] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [NA] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [NA] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [NA] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by iSazonov** [comment]
Why not follow https://github.com/dotnet/runtime/blob/master/eng/Analyzers.props?

**Comment by xtqqczze** [comment]
> Why not follow https://github.com/dotnet/runtime/blob/master/eng/Analyzers.props?
> (Also I'd think about xUnit tests folder too.)
Previously, you had wanted to use EditorConfig instead of ruleset configuration.

**Comment by iSazonov** [comment]
> Previously, you had wanted to use EditorConfig instead of ruleset configuration.

My thought was and is that we shouldn't have two configs - in EditorConfig and in ruleset. If VS Code supports(?) ruleset it is better to use ruleset and follow .Net team's pattern.

**Comment by xtqqczze** [comment]
Closed in favour of #12892

**Comment by xtqqczze** [comment]
@iSazonov This PR uses `.globalconfig` file. It is the easiest solution and it just works, including `TreatWarningsAsErrors`.

**Comment by iSazonov** [comment]
I will merge because:
- we should benefit from Roslyn analyzers that is best practice.
- it is more convenient than alternative analyzers.
- we will be able to force rules in PRs without requests from maintainers.
- After we moved to .Net 5.0 RC1 Roslyn analyzers are already enabled by default.
- VS Code OmniSharp works with EditorConfig and GlobalConfig (need latest VS 2019 16.8 Preview5+).

As a side notice, we could disable Analyzers in all CIs to speed up compiling and separate check (compile only) with enabled analyzers.

**Review by iSazonov — APPROVED** [review]

**Pull request merged**
