### PR TITLE
Enable CA1000: Do not declare static members on generic types

### PR DESCRIPTION
**Pull request by xtqqczze**
https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/CA1000

### CODE REVIEW

**Comment by xtqqczze** [comment]
CI failures attributed to #14101.

**Comment by xtqqczze** [comment]
restarting tests

**Comment by iSazonov** [comment]
The rule is enable for public members only. Since we have no complains we could force the rule to avoid breaking changes in public API in future.

@xtqqczze  Could you please check the rule for internal and private?

**Comment by xtqqczze** [comment]
4e28528 enables rule for internal and private too.

**Review by iSazonov — APPROVED** [review]

**Pull request merged**
