### PR TITLE
Remove empty branch and add Dbg.Assert in ExportCsvHelper.

### LINKED ISSUE #6809: Do we need empty branch in Microsoft.PowerShell.Commands.ExportCsvHelper?
Do we need this check in Microsoft.PowerShell.Commands.ExportCsvHelper?

```powershell
        ExportCsvHelper(PSCmdlet cmdlet, char delimiter)
        {
            if (cmdlet == null)
            {
            }
            _cmdlet = cmdlet;
            _delimiter = delimiter;
        }
```
https://github.com/PowerShell/PowerShell/blob/84344cbb32ec5e2479e00394951832794bf37244/src/Microsoft.PowerShell.Commands.Utility/commands/utility/CSVCommands.cs#L880

### PR DESCRIPTION
**Pull request by sethvs**
## PR Summary

Remove empty branch and add Dbg.Assert in ExportCsvHelper.
Fix #6809 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by dantraMSFT — CHANGES_REQUESTED** [review]
Relying on Dbg.Assert for parameter checking is not a good practice because we don't run tests against Debug builds. I've encountered numerous bugs that relied on Assert for validation but had none in release/production builds.

In this case, the previous code was clearly incorrect but replacing it with a Dbg.Assert doesn't solve it.

I suggest, you make the assignment  a condition of non-null or throw an ArgumentNullException when null.

**Comment by sethvs** [comment]
Fixed.

**Comment by dantraMSFT** [comment]
@iSazonov: I would say yes.  Assert is perfectly fine if it is used as a debugging aid as long as it has runtime code to back it up.  At a minimum, it should be part of any PR review.

**Review by dantraMSFT — APPROVED** [review]

**Comment by iSazonov** [comment]
@daxian-dbw @TravisEz13 Should we add @dantraMSFT's suggestion in our PR check list?

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
@iSazonov I think this comes to the level of something that should be documented guidance, but not something that should be in the checklist for every PR.  If it should be verified for every PR, we should probably write a test to verify that this code is not in any changed code blocks.

**Pull request merged**
