### PR TITLE
use global nuget package cache

### PR DESCRIPTION
**Pull request by lzybkr**
It's not clear why we were using a local cache for nuget packages, but the implementation used an environment variable which would affect other builds.

If there is a good reason to have a local cache, the environment variable should only be set while restoring packages for this project, basically save and restore the previous value around our restore.

### CODE REVIEW

**Comment by vors** [comment]
@andschwa was it added to make caching on AppVeyor easier?
@lzybkr Notice that cross-gen call need to be updated in this case.

**Comment by andschwa** [comment]
@vors, @dantraMSFT added the custom NuGet package path in 2ae8f5c3a029f8407a5b8c7998a5e4f5b372e9bd.

**Comment by lzybkr** [comment]
We're not caching in AppVeyor - we should add that (but these changes don't prevent I think).

It looks like the actual commit was 585eefc -  @dantraMSFT - the commit message and comment say what but not why - can you explain?

**Comment by lzybkr** [comment]
I spoke with @dantraMSFT - he says the change was introduced to avoid build errors and help ensure reproducible builds.

We don't see issues on non-Windows systems, so maybe the problems have gone away. I think it's fine to merge, and if the problems come back, we can fix this the other way I proposed, by save/set/restore the environment variable.

**Comment by iSazonov** [comment]
@lzybkr After merge the commit to my local repo I can not build on Windows because of multiple errors
> PowerShell\src\powershell-win-core\project.json(87,47): error NU1001: The dependency System.Xml.XPath.XmlDocument >= 4.3.0 could not be resolved.

`Start-PSBuild -Clean`  don't help.

**Comment by iSazonov** [comment]
@lzybkr After merge the commit to my local repo I can not build on Windows because of multiple errors
> PowerShell\src\powershell-win-core\project.json(87,47): error NU1001: The dependency System.Xml.XPath.XmlDocument >= 4.3.0 could not be resolved.

`Start-PSBuild -Clean`  don't help. 

The problem is only with VS Code.

**Comment by lzybkr** [comment]
Did you try -Restore?

**Comment by andschwa** [comment]
Yeah this change is going to require people to `dotnet restore` again.

**Comment by iSazonov** [comment]
Thanks! `Start-PSBuild -Restore` resolve the problem.

**Pull request merged**
