### PR TITLE
Fix Move-Item -Path with wildcard char

### PR DESCRIPTION
**Pull request by kwkam**
## PR Summary

Set the context.SuppressWildcardExpansion in MoveItem instead of
escaping the path every time. Also solve the issue where Move-Item
complains -Path wildcard pattern is not valid when -Path contains
special characters that forms an invalid pattern.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [x] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]
I wonder that we have so many `try-catch` blocks. Perhaps we could remove half of them ( in new PR).

**Comment by iSazonov** [comment]
@mklement0 Could you please (fast) review last (~10) @kwkam 's PRs related to literal paths, wildcards and escapes?

@SteveL-MSFT Should we speed up the review of the PRs or postpone it after 6.1?

**Comment by SteveL-MSFT** [comment]
@iSazonov other than a handful of issues marked for 6.1, if other PRs make it in that's great, if they don't we'll start shipping 6.2 Previews after 6.1 RC is out in a few weeks.  Since we have stable and preview channels now, it should be ok for people to depend on stable builds and try out preview builds.  Right now most of my team is focused on some other things not directly PSCore6.1 related.

**Comment by mklement0** [comment]
@iSazonov: Sorry, that's more than I can take on right now; I've glanced at this one, and it looks fine.

**Review by SteveL-MSFT — APPROVED** [review]

**Pull request merged**
