### PR TITLE
Add StringUtil.Format overload to avoid unnecessary allocations

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

* Rename method parameters so that their names correspond to `string.Format`
* Add `StringUtil.Format` overload to avoid unnecessary boxing allocations

## PR Context

See also: https://github.com/dotnet/runtime/issues/14484

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [NA] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [NA] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [NA] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [NA] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [NA] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [NA] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]

**Comment by xtqqczze** [comment]
@iSazonov Can we merge yet?

**Comment by iSazonov** [comment]
@xtqqczze Could you please add `using System.Globalization;` and re-format the class to one style (I mean ещ get rid of
multistring `internal static string Format`)?

**Comment by xtqqczze** [comment]
@iSazonov There is also a `StringUtil` class in `System.Management.Automation.SecurityAccountsManager` and `Microsoft.PowerShell.ScheduledJob`. Maybe we can remove duplicated code if we make the class `public`?

Also, the `Format` method in `Microsoft.PowerShell.ScheduledJob` uses `Threading.Thread.CurrentThread.CurrentCulture` as the `IFormatProvider` which I'm not sure is correct (see https://docs.microsoft.com/dotnet/api/system.threading.thread.currentculture?view=net-5.0#remarks)

**Comment by iSazonov** [comment]
> Microsoft.PowerShell.ScheduledJob

The code is excluded from compilation. We shouldn't change it.

**Comment by xtqqczze** [comment]
@iSazonov It would be helpful if files containing frozen/excluded code had an explanation at the beginning of the file.

**Comment by iSazonov** [comment]
@xtqqczze I think it makes no sense to explicitly add comments in files. It is only graphical and WinRM code - you already know this. But we could add a comment in our Contribution guide.

**Comment by xtqqczze** [comment]
@iSazonov I know this now, but an explanation would be helpful for new contributors.

**Pull request merged**
