### PR TITLE
Cleanup COM interfaces in jump list code - fix PreserveSig attributes

### PR DESCRIPTION
**Pull request by weltkante**
# PR Summary

Correction of wrong/unnecessary COM interop attributes

## PR Context

While reviewing the JumpList COM interop code for #9295 I noticed that several `[PreserveSig]` attributes were wrong. The methods which got the attribute wrong were never called, so this is not a direct fix for the issue, its just to prevent future problems should they ever be called.

Also there were some unnecessary `[MethodImpl]` attributes which are not supposed to be there, these are cleaned up.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by daxian-dbw** [comment]
Close and reopen the PR to force Windows CI build working properly.

**Review by daxian-dbw — APPROVED** [review]

**Comment by daxian-dbw** [comment]
@bergmeister Can you please review this PR?

**Review by bergmeister — COMMENTED** [review]
I cannot comment much on the code change itself as I am not a COM expert (maybe you guys could ask someone from the .Net team?), so I cannot say if it makes it better or worse, we could trust the author but the PS team has to decide on the risk of changing something when there hasn't been reported issues (since we fixed the original problem by using an STA thread, I haven't heard about problems with the JumpLIst since then). I appreciate the author's good intentions but there is a chance that this is a change that could cause a regression in edge cases or less common scenarios like old OSs, especially since we do not have test automation for this feature.
I have tested manually though that the functionality still works on Win 10 (1809) (one needs to make sure to build PowerShell from  a folder where the JumpList has never been created before due to persistence).
I therefore leave the decision up to the PowerShell team and want to stay neutral on this.

**Comment by anmenaga** [comment]
@SteveL-MSFT what is your opinion on this?

**Comment by SteveL-MSFT** [comment]
@anmenaga based on the docs, it would seem this is correct.  Can we get the CodeFactor issue fixed?

**Comment by weltkante** [comment]
@SteveL-MSFT do I insert newlines for the whole file or only the line it complains about? there are plenty more of methods without newlines in this file.

**Comment by SteveL-MSFT** [comment]
@weltkante only the line it is complaining about.  Thanks!

(General style issues in the file should be a seperate PR, but I'm not asking for you to do that unless you want to :)

**Comment by weltkante** [comment]
Very sorry for the noise, got my repo settings wrong and had to amend. Build failure seems independent?

**Comment by weltkante** [comment]
Very sorry for the noise, got my repo settings wrong and had to amend. Build failure seems independent?

**Comment by SteveL-MSFT** [comment]
@PoshChan please retry windows

**Comment by PoshChan** [comment]
@SteveL-MSFT, successfully started retry of `PowerShell-CI-Windows`

**Comment by SteveL-MSFT** [comment]
@weltkante the static analysis failures are understood and should not block this PR

**Comment by anmenaga** [comment]
Looks like the general consensus is to merge this PR.
Test failure in `PowerShell-CI-windows` is unrelated `TestAppDomainProcessExitEvenHandlerNotLeaking` failure that @daxian-dbw is fixing separately.

**Pull request merged**
