### PR TITLE
Fix global tool issues around exit code, command line parameters and path with spaces

### LINKED ISSUE #10301: PowerShell's dotnet global tool doesn't accept -WorkingDirectory option
# Steps to reproduce
1) Install powershell core via the dotnet global tool utility:
```powershell
dotnet tool install --global PowerShell  
```
2) run the new powershell command with the "Working Directory" option/flag:
```powershell
pwsh -WorkingDirectory ~
```
# Expected behavior
It is expected that this option works and the shell starts in the provided directory.

# Actual behavior
The following error is thrown
```none
-WorkingDirectory : The term '-WorkingDirectory' is not recognized as the name of a cmdlet, function, script file, or operable program.                                                                           
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.At line:1 char:1                                                                                         
+ -WorkingDirectory ~                                                                                    
+ ~~~~~~~~~~~~~~~~~                                                                                      
+ CategoryInfo          : ObjectNotFound: (-WorkingDirectory:String) [], CommandNotFoundException        + FullyQualifiedErrorId : CommandNotFoundException               
```

# Environment data

Running install and pwsh command in:
```none
Name                           Value                                                                     
----                           -----                                                                     
PSVersion                      5.1.18362.145                                                             
PSEdition                      Desktop                                                                   
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                   
BuildVersion                   10.0.18362.145                                                            
CLRVersion                     4.0.30319.42000                                                           
WSManStackVersion              3.0                                                                       PSRemotingProtocolVersion      2.3                                                                       SerializationVersion           1.1.0.1   
```

Installed pwsh (installed as global tool):
```none
Name                           Value
----                           -----
PSVersion                      6.2.2
PSEdition                      Core
GitCommitId                    6.2.2
OS                             Microsoft Windows 10.0.18362
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by adityapatwardhan**
# PR Summary

Fixes #10301 #10362 #10184 

1. Fix issue where `pwsh` command line options were not passed.
1. Fix issue where the location where the global tool was installed could not have spaces in them
1. Fix issue where the return code was not returned.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by TravisEz13 — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
@PoshChan please remind me after 24 hours

**Comment by PoshChan** [comment]
@adityapatwardhan, I do not understand: please remind me after 24 hours

Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline, `restart` can be used in place of `retry`
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for \<target\> which can be a comma separated list are: `static`,`windows`,`macos`,`linux`,`all`
  - `get failures` this will attempt to get the latest failures for all of the target pipelines
  - `remind me in <value> <units>` this will create a reminder that will be posted after the specified duration
    \<value\> is a number, and \<units\> can be `minutes`, `hours`, or `days` (singular or plural)

**Comment by adityapatwardhan** [comment]
@PoshChan please remind me in 24 hours

**Comment by PoshChan** [comment]
@adityapatwardhan, this is the reminder you requested 24 hours ago

**Pull request merged**
