### PR TITLE
Add Fluent Design Icon asset for PowerShell 7 usage

### PR DESCRIPTION
**Pull request by sar**
# PR Summary

Add a modern PowerShell icon with [Fluent Design](https://www.microsoft.com/design/fluent/) guidelines and inspired by the [community](https://twitter.com/Steve_MSFT/status/1279220914412851200). Retains the same design ethos and color palette, with a subtle new fluent approach. PR contains static svg asset.

#### Asset Details

``assets/ps_fluent_design_384.svg``

##### Aspect Ratios

Example Bounding Box Usage: ``512x512 or larger HiDPI 1:1``
Icon Proportions: ``384x240 8:5``
Fun Fact: Icon is proportionally skewed at a 7-degree angle

##### Color Palletes

Grayscale: ``#FFFFFF, #000000``
Gradient: ``[#2E466A 0%, #1C2C40 ~50%, #00040A 100%]`` 45 degrees top-left
Layout and color placement tested for Pinned Start Menu Tile, List Tile, Taskbar, rpm/deb Installer, MacOS Launchpad and Dock

#### Next Steps

Compile static assets in different sizes for dev/test in preview builds.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None: Static Assets only
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Review by SteveL-MSFT — APPROVED** [review]
Awesome, thanks!

**Comment by TylerLeonhardt** [comment]
Looks very clean :)

Personally, I think it's a bit too oblong along the X axis.

**Comment by TylerLeonhardt** [comment]
I'm concerned people will confuse it with Windows Terminal because folks already do confuse terminal with shell

**Comment by SteveL-MSFT** [comment]
My approval doesn't mean we'll switch to using this new logo.  I do think it's good enough that we can build upon it.

**Pull request merged**
