### PR TITLE
Enable nullable: System.Management.Automation.ICommandRuntime

### PR DESCRIPTION
**Pull request by powercode**
Tracking issue: #12631.

Should we allow null for the parameters to 

WriteDebug, WriteWarning, WriteVerbose, etc?

### CODE REVIEW

**Comment by rjmholt** [comment]
> Should we allow null for the parameters to
>
> WriteDebug, WriteWarning, WriteVerbose, etc?

I suspect that we ideally would not, but I'm not sure if making such a change would break anything

**Comment by iSazonov** [comment]
IParameterMetadataProvider has 5 dependencies. This complicates understanding design intentions and we will review this later on phase 5.

**Comment by iSazonov** [comment]
> > Should we allow null for the parameters to
> > WriteDebug, WriteWarning, WriteVerbose, etc?
> 
> I suspect that we ideally would not, but I'm not sure if making such a change would break anything

Nullable annotations can not break anything. They only explicitly expose design intentions.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
> Should we allow null for the parameters to
> 
> WriteDebug, WriteWarning, WriteVerbose, etc?

It seems it makes no sense.

**Comment by iSazonov** [comment]
Hmm, we never check for null in the WriteDebug() API until low level host implementations where we ignore null messages.
For WriteError() we throw if null.
For WriteObject() we accept null.
For  WriteProgress() we throw if null.
For WriteVerbose we accept null (we do the same as for WriteDebug()).
For WriteWarning we accept null (we do the same as for WriteDebug()).
For WriteCommandDetail() we accept null.

**Comment by rjmholt** [comment]
WriteObject makes sense. The throws make sense. The skips trouble me, since changing them is breaking, but it would be nice to change the type signature. But I'm not sure I see the value there. I guess the best course of action is to label the APIs as you've researched them @iSazonov

**Comment by iSazonov** [comment]
>  The skips trouble me, since changing them is breaking

Nullable annotations are only about _design intentions_. So we can annotate all the "skips" as non-nullable without adding real null checks and de-facto without breaking changes.
I can the commit if you want.

**Comment by rjmholt** [comment]
> So we can annotate all the "skips" as non-nullable without adding real null checks and de-facto without breaking changes.

Yeah that's perfect

**Comment by iSazonov** [comment]
The PR branch was removed so I opened new PR #15566.

**Pull request closed without merging**
