### PR TITLE
vscode: Enable EditorConfig support in OmniSharp

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

Enable support for EditorConfig in OmniSharp.

## PR Context

OmniSharp has this support since omnisharp-roslyn v1.33.0:

* https://github.com/OmniSharp/omnisharp-roslyn/blob/master/CHANGELOG.md#1330---2019-07-01
* #7357
* https://github.com/OmniSharp/omnisharp-roslyn/pull/1526

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]
LGTM.

I tried enableRoslynAnalyzers. It takes many time for analyzing and we need to adjust before enable.

**Comment by vexx32** [comment]
@iSazonov I've used the `enableRoslynAnalyzers` setting as a good tool to work with when doing a cleanup / refactor of an individual file. It will probably be quite a while before we get all those analyzer recommendations into the codebase, but the majority of them do look like great suggestions to take on board.

**Comment by iSazonov** [comment]
My concern is that it takes a lot of computer resources. Perhaps we could enable subset of the analyzer to highlight our code conventions.

**Comment by xtqqczze** [comment]
@vexx32 I too am using `enableRoslynAnalyzers`, with additional PackageReference `Roslynator.Analyzers` added to a csproj of interest. I have submitted PR #11640 based on one of the analyzer recommendations, but it seems like a huge amount of work to fix all issues.

@iSazonov Currently Omnisharp queues all documents in the solution for code analysis, rather than running on demand, so this uses a lot of resources when developing in vscode.

**Comment by iSazonov** [comment]
@xtqqczze  Can we configure the code analysis?

**Pull request merged**
