### PR TITLE
Move artifacts to artifact staging directory before uploading

### PR DESCRIPTION
**Pull request by adityapatwardhan**
# PR Summary

Artifact upload is asynchronous task and hence the file path needs to be valid for much longer. During build we occasionally clean the build directory and then the built artifacts are deleted. This change moves the artifacts to artifact staging directory and then issues an upload request from that path.

## PR Context

Fixing daily build failure.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Review by TravisEz13 — APPROVED** [review]

**Comment by PoshChan** [comment]
@adityapatwardhan, your last commit had 1 failures in `PowerShell-CI-windows`
Task-based PowerShell async APIs.PowerShell::StopAsync.can stop a script that is running asynchronously
```powershell
Expected $true, but got $false.
at <ScriptBlock>, D:\a\1\s\test\powershell\engine\Api\TaskBasedAsyncPowerShellAPI.Tests.ps1: line 213
213:                 $ir.IsFaulted | Should -Be $true
```

**Comment by adityapatwardhan** [comment]
@PoshChan Please retry windows

**Comment by PoshChan** [comment]
@adityapatwardhan, successfully started retry of `PowerShell-CI-Windows`

**Comment by adityapatwardhan** [comment]
Merged this without waiting for 24 hours as this fixes the daily build break.

**Pull request merged**
