### PR TITLE
Remove UTF-8 BOM from text files

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

Strip UTF-8 BOM from text files

## PR Context

* 137 source files currently start with UTF-8 BOM
* Follow-up #417

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
- **User-facing changes**
    - [x] Not Applicable
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]
It would be nice to have a test to exclude regression.

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Comment by SteveL-MSFT** [comment]
@iSazonov a test should be easy to write, but can be separate from this PR

**Review by TravisEz13 — APPROVED** [review]

**Comment by iSazonov** [comment]
@xtqqczze Thanks for your contribution!

**Pull request merged**
