### PR TITLE
Update use of `Windows PowerShell` to just `PowerShell` in our logging

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

Some cases where we log on non-Windows and it mentions Windows PowerShell when it's not specific about Windows PowerShell.  Searched for occurrences of `Windows PowerShell` in our code base and changed the ones that can be generic `PowerShell`.  VSCode fixed some whitespace issues and saw some typos in a comment I fixed at the same time.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by iSazonov** [comment]
@SteveL-MSFT Previously we already fixed this by replacing Windows PowerShell with PowerShell Core in all code base. All changes in the PR is related to Windows code. I think it makes no sense to change something in the Windows only code.

**Comment by SteveL-MSFT** [comment]
Specifically, the PowerShell.Core.Instrumentation.man manifest for ETW events uses Windows PowerShell when it should have used just PowerShell.  This is Windows specific, but not Windows PowerShell specific.

**Comment by iSazonov** [comment]
If we previously replaced Windows PowerShell with PowerShell Core should we now replace PowerShell Core with PowerShell?

**Comment by SteveL-MSFT** [comment]
@iSazonov We should probably replace them where it's not important to differentiate that it's Core.  I'll review the instances and add it to this PR.

**Comment by SteveL-MSFT** [comment]
Turns out there's a lot more instances of PowerShell Core, so doing that as a separate PR

**Review by iSazonov — APPROVED** [review]

**Pull request merged**
