### PR TITLE
Update docs and scripts for PowerShell 6.0.0 GA release

### PR DESCRIPTION
**Pull request by daxian-dbw**
## PR Summary

Update docs and scripts for PowerShell 6.0.0 GA release

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [x] Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [ ] Issue filed - Issue link:
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

### CODE REVIEW

**Review by anmenaga — APPROVED** [review]
LGTM

**Review by adityapatwardhan — APPROVED** [review]

**Comment by TravisEz13** [comment]
please update https://github.com/PowerShell/PowerShell/blob/6.0.0/tools/metadata.json

**Review by TravisEz13 — CHANGES_REQUESTED** [review]
please update https://github.com/PowerShell/PowerShell/blob/6.0.0/tools/metadata.json

**Comment by daxian-dbw** [comment]
@TravisEz13 Your comment has been addressed. Thanks!

**Review by TravisEz13 — APPROVED** [review]

**Pull request merged**
