### PR TITLE
Move Windows pinvokes

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Please review commit by commit.

Contributes to #18553.

1. Move Windows pinvokes (migrated to LibraryImport in #18496 and #18520) to new location.
2. Exclude from compile in csproj instead of using #if-#endif

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by jborean93** [comment]
I really don't mind the format that is ultimately used but it would be nice if there was a common standard set out by the pwsh team for PInvoke calls and how to structure them. I moved some of the WinTrust stuff in the PR https://github.com/PowerShell/PowerShell/pull/17545 and went with the format of

+ Single file per dll
+ Simple wrapper method that wraps the extern call with a more managed interface
  + Makes it simpler for multiple locations to call the same function but without having to add things like error checking in each reference

Here you've moved it to a single file per function and it's just the extern def.

I'm totally not opposed to any route we ultimately go for but it would be nice to choose one rather than fragmenting it even more.

**Comment by daxian-dbw** [comment]
I didn't realize it's organized as one file per function.
I personally prefer to single file per dll.

**Comment by iSazonov** [comment]
The only inconvenience that many files might cause is if you tried to open them all at once in the editor. But why would you want to do that?
You will never be able to keep order in one big file. People will prefer IntelliSense to nested region directives.

**Comment by daxian-dbw** [comment]
An inconvenience off the top of my head is that it would be harder to search for something related to a p/invoke call, be it the use of a marshal attribute, a parameter type, or a function when you only remember partial of its name.

I personally prefer to have only a few files dedicated to all p/invokes. In case that a lot of functions get used from a dll, then use a single file for that dll. For the rest, use a single file per platform if possible. This doesn't prevent you from using partial classes for all p/invokes of a specific platform.

**Comment by iSazonov** [comment]
> An inconvenience off the top of my head is that it would be harder to search for something related to a p/invoke call, be it the use of a marshal attribute, a parameter type, or a function when you only remember partial of its name.

How is a partial search related to number of files? VS Code has great and very fast multi file search (Ctrl-Shift-F). Given how unpredictable the location of code in PowerShell is sometimes, I seem to use it more often than the single-file search.

>I personally prefer to have only a few files dedicated to all p/invokes. In case that a lot of functions get used from a dll, like the WinTrust stuff, then use a single file for that dll. For the rest, use a single file per platform if possible. This doesn't prevent you from using partial classes for all p/invokes of a specific platform.

It's impossible to maintain any order in these files, especially since you're already talking about exceptions. These files are already unnecessarily huge. In fact, the code does not fit on one screen and you will anyway be forced to use search and possibly use additional editor windows even for the same file.
Moreover, this code is leaf and stable, ie rarely defeated change - for this reason alone it should have been removed from these big files.

**Comment by iSazonov** [comment]
@daxian-dbw 
I expect that the .Net team will actively improve LibraryImport in .Net 8. This is another argument for removing pinvokes and related code from the main code and sticking to their style.
Once they finish this work this code will be so stable that it can be placed in just one file, or even in a separate repository.

By the way, they sometimes put related pinvokes in the same file. _The main convenience for the current work._

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Comment by iSazonov** [comment]
@daxian-dbw Could you merge?

**Comment by daxian-dbw** [comment]
@iSazonov Thanks for doing this refactoring!

**Pull request merged**
