### PR TITLE
Cleanup: sort usings

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Sort using-s with the script. Please review commit by commit.
```powershell
function UsingSort {
    param($file, $out_file)

    $all = Get-Content -Path $file -Encoding Utf8NoBom

    Set-Content -Path $out_file -Value $all[0..2] -Encoding Utf8NoBom

    $i = 3 # Skip license header
    $usingSystem = @()
    $usingAlias = @()
    $using = @()

    # Process usings
    while ($all[$i] -like "using *") {
        if ($all[$i] -like "using System*") {
            $usingSystem += $all[$i]
        } elseif ($all[$i] -like "using *=*") {
            $usingAlias += $all[$i]
        } else {
            $using += $all[$i]
        }

        if ($i++ -ge $all.Length) {
            break
        }
    }

    # Sort and output
    if ($usingSystem) {
        # Length-2 - remove last dot or semi to move `using System;` on top.
        $usingSystem | Sort-Object -Property @{e={$_[0..($_.Length-2)]}} | Add-Content -Path $out_file -Encoding Utf8NoBom
    }

    if ($using) {
        Add-Content -Path $out_file -Value "" -Encoding Utf8NoBom
        $using | Sort-Object -Property @{e={$_[0..($_.Length-2)]}} | Add-Content -Path $out_file -Encoding Utf8NoBom
    }

    if ($usingAlias) {
        Add-Content -Path $out_file -Value "" -Encoding Utf8NoBom
        $usingAlias | Sort-Object -Property @{e={$_[0..($_.Length-2)]}} | Add-Content -Path $out_file -Encoding Utf8NoBom
    }

    Add-Content -Path $out_file -Value $all[$i..($all.length-1)] -Encoding Utf8NoBom

}
$list = Get-ChildItem -Recurse src\*.cs
$list | ForEach-Object { Write-Host -NoNewline ">$_ :"; UsingSort $_ $_; "<" }
```

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by PoshChan** [comment]
@iSazonov, your last commit had 1 failures in `PowerShell-CI-linux`
Validate 'Save-Help -DestinationPath for all PowerShell Core modules..Validate Save-Help for the 'Microsoft.PowerShell.Management' module
```powershell
Expected 'Microsoft.PowerShell.Management_eefcb906-b326-4e99-9f54-8b4bb6ef3c6d_en-US_helpcontent.zip', because Save-Help for  should download 'Microsoft.PowerShell.Management_eefcb906-b326-4e99-9f54-8b4bb6ef3c6d_en-US_helpcontent.zip', but got $null.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1: line 333
333:     $compressedFile | Should -Be $expectedCompressedFile -Because "Save-Help for $module should download '$expectedCompressedFile'"
```

**Comment by iSazonov** [comment]
@PoshChan Please retry linux.

**Comment by PoshChan** [comment]
@iSazonov, I do not understand the build target(s) `linux.`; I only allow `static`, `windows`, `macos`, `linux`, `all`

**Comment by iSazonov** [comment]
@PoshChan Please retry linux

**Comment by PoshChan** [comment]
@iSazonov, successfully started retry of `PowerShell-CI-Linux`

**Comment by iSazonov** [comment]
@TravisEz13 Could you please look why we lost CodeFactor in CI list?

**Comment by adityapatwardhan** [comment]
I was wondering if we can do something about unused using statements.

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by iSazonov** [comment]
> I was wondering if we can do something about unused using statements. Not sure if there are any.

Waiting https://github.com/OmniSharp/omnisharp-vscode/pull/2873

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you please clarify why we lost CodeFactor in CI list?

**Pull request merged**
