### PR TITLE
Fix for files/folders created at pwd by New-Item when given path is drive root (#5228)

### LINKED ISSUE #5228: New-Item ignore's Path param if Name param is specified
Steps to reproduce
------------------

```powershell
Set-Location ~
New-Item -Path C:\ -Name Test -ItemType Directory -Verbose
```

Expected behavior
-----------------

```none
Test folder created in Root C:\
```

Actual behavior
---------------

```none
Folder created in current path
PS C:\Users\Aftab> New-Item -Path C:\ -Name Test -ItemType Directory -Verbose
VERBOSE: Performing the operation "Create Directory" on target "Destination: C:\Users\Aftab\Test".


    Directory: C:\Users\Aftab


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       25/10/2017     13:51                Test


PS C:\Users\Aftab> Get-Item C:\Test
Get-Item : Cannot find path 'C:\Test' because it does not exist.
At line:1 char:1
+ Get-Item C:\Test
+ ~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Test:String) [Get-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetItemCommand

PS C:\Users\Aftab> Get-Item ~\Test


    Directory: C:\Users\Aftab


Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       25/10/2017     13:51                Test
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by ghost**
## PR Summary

If the `Path` argument to `New-Item` is the root of a drive such as `C:\`, the LocationGlobber attempts to generate a drive root relative path from the path `C:`. `GetDriveRootRelativePathFromPSPath` determines that this is an absolute path, and strips the drive name and colon from the path; originally, this would result in `GenerateRelativePath` determining that the current working directory should be given as the relative path. Now, a check is made on whether stripping the drive name and colon results in an empty string; if it does, the root of the current PSDrive `context.Drive.Root` is returned as the relative path.

This fixes #5228.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [X] Issue filed - Issue link: https://github.com/PowerShell/PowerShell/issues/5228#
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by mcbobke** [comment]
For now, I will leave this as ready to merge and non-breaking until review.

**Comment by mcbobke** [comment]
Confirmed that this broke Get-ChildItem when `Path` is not specified (by default, then attempts to use $pwd).

**Comment by iSazonov** [comment]
@mcbobke Feel free to ask if you need help.

**Comment by mcbobke** [comment]
I've been working on a different solution and am currently testing it before I commit. Thanks for the encouragement, I will definitely be asking some questions once it's up!

**Comment by mcbobke** [comment]
Alright, I think I'm on the right track this time. Because the argument for `Path` may not be given if that parameter is not specified when using the cmdlet, returning an empty string in the spot that I was doing so before would break the expected functionality of creating an item in the current working directory.

Testing for an empty path after `GetDriveRootRelativePathFromPSPath` strips the drive name and colon ensures that the case in which a drive root is specified as the path is handled. Rather than attempt to generate a drive relative path from an empty path (which would generate the relative path to the current working directory), the current context's PSDrive's root is returned.

Looking forward to review.

**Comment by iSazonov** [comment]
@mcbobke The PR contains alien commits. I suggest you to rebase and squash before we start review.

**Comment by mcbobke** [comment]
@iSazonov I did my best to clean up the commit history; is there anything I can do to clean it up further?

**Comment by iSazonov** [comment]
@mcbobke I still see an alien commit https://github.com/PowerShell/PowerShell/pull/6584/commits

**Comment by mcbobke** [comment]
Whoops! Apologies. Looks like it's fixed now.

**Comment by iSazonov** [comment]
@mcbobke No, your commit contains unrelated code.

I see you make the PR from forked master branch. You should create new branch for every new work.
1. fork the repo
2. create new branch 
3. add commits to the new branch "work"
4. make PR based on branch "work"
5. after merge the PR remove the branch "work"
6. rebase your local master branch from the original repo
7. goto 2

**Comment by mcbobke** [comment]
Understood @iSazonov . How should I branch this work off now that it's in master?

**Comment by iSazonov** [comment]
If you haven't experience with git you could simply backup your code (copy files) and re-create your fork.

**Comment by mcbobke** [comment]
I have some experience with Git, but I have learned some things while working on this change. :P Does that mean I need to recreate the PR as well? I can revert the commit and branch it off, if I can also edit the PR. Otherwise, I'd create a new one.

**Comment by iSazonov** [comment]
You are free to choose a way.
When I started with the project I was doing a full reset a couple of times.

**Comment by mcbobke** [comment]
Okay, what I'll do then is branch off and create a new PR and reference this one. Thanks for all of your help, this has been a learning experience!

**Comment by iSazonov** [comment]
@mcbobke  If our docs is not clear for the repo newbies please feel free to commit additions with you experience.

**Comment by mcbobke** [comment]
That's a really good idea. I will look through and see where I can add some clarification.

**Pull request closed without merging**
