### PR TITLE
Cleanup Export-Command from assemblyinfo

### LINKED ISSUE #9361: What is the Export-Command assembly
There's an assembly granted `InternalsVisibleTo` called `Export-Command` but I can't find any information on it.

https://github.com/PowerShell/PowerShell/blob/13fd3af8106dbfd5d65e697036af5999255badc7/src/System.Management.Automation/AssemblyInfo.cs#L22-L27

Maybe worth a comment above the attribute if it's an internal only tool or something along those lines.

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Fix #9361. 

Remove unused code.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@PoshChan please retry linux

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by PoshChan** [comment]
@SteveL-MSFT, could not find build at: , error: Invoke-RestMethod : 




    Access Denied: The Personal Access Token used has expired.
    
        body {
            font-family: "-apple-system",BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Helvetica,Ubuntu,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
            font-size: 14px;
            height: 100%;
            margin: 0;
            background-color: #fff;
        }

        A {
            color: #007ACC;
            text-decoration: none;
        }
        A:hover {
            text-decoration: underline;
        }

        .header {
            background-color: #0078d4;
            color: #fff;
            height: 40px;
            font-size: 14px;
        }

        .header .logo {
            height: 20px;
            margin: 9px 5px 0 9px;
        }

        .header .product-name {
            vertical-align: top;
            padding-top: 10px;
            display: inline-block;
        }

        .content {
            margin-left: 15%;
            margin-right: 5%;
        }

        .error-summary {
            margin-bottom: 40px;
        }

        .error-code {
            display: inline-block;
            vertical-align: top;
            color: #777;
            font-size: 200px;
            line-height: 130px;
            margin-top: 60px;
            margin-right: 40px;
        }

        .error-details {
            display: inline-block;
            vertical-align: top;
            margin-top: 60px;
            max-width: 500px;
        }

        .error-details > h1 {
            font-size: 28px;
            margin: 0;
            text-transform:uppercase;
            font-weight:normal;
        }
        .error-details > h3 {
            text-transform: uppercase;
            font-size: 16px;
        }

        .error-details .action {
            font-size: 16px;
        }

        .error-details .action-text {
            vertical-align: middle;
        }

        .error-details > .helpful-links > a {
            margin-right: 10px;
        }

        .more-info {
            min-width:600px;
        }

        .more-info > pre {
            margin: 20px 0;
            white-space: pre-wrap;
        }

        .tips, .additionalDetails {
            min-width:500px;
            margin: 40px 0;
        }

        .tips > ul {
            list-style-type: square;
        }

        .tips > ul > li {
            margin-bottom: 10px;
        }

        .additionalDetails > h3 {
            font-size: 16px;
            font-weight: normal;
        }

        .additionalDetails .title {
            font-weight: bold;
            color: #444;
        }

        .additionalDetails .info {
            color: #777;
        }

        .additionalDetails > div {
            margin-top: 5px;
            margin-left: 20px;
        }
    


    
        
        Azure DevOps Services
    
    
        
            401
            
                Not Authorized
                
                The request requires authentication
                
                    
                        Sign in
                    
                
                
                    Service Status and Support
                    @AzureDevOps
                
            
        

        
        
            More information about this error
            Access Denied: The Personal Access Token used has expired.

            
        
        
        
            Additional technical details:
            
                Activity ID:
                93906262-9036-42d8-b3a6-c5a94d1fa97d
            
            
                Date and Time:
                4/24/2019 4:43:18 PM (UTC)
            
        
        
    
    
    
        function getError() {
            return "eyJVcmkiOiJodHRwczovL2Rldi5henVyZS5jb206NDQzL1Bvd2VyU2hlbGwvX2FwaXMvYnVpbGQvYnVpbGRzLzIxNDczP2FwaS12ZXJzaW9uPTUuMCIsIlN0YXR1c0NvZGUiOjQwMSwiTWVzc2FnZSI6IkFjY2VzcyBEZW5pZWQ6IFRoZSBQZXJzb25hbCBBY2Nlc3MgVG9rZW4gdXNlZCBoYXMgZXhwaXJlZC4iLCJEZXRhaWxzIjoiIiwiQ29udGVudCI6bnVsbCwiSWRlbnRpdHkiOiIifQ==";
        }

        try {
            if (typeof window.external !== "undefined" && typeof window.external.notifyError !== "undefined") {
                window.external.notifyError(getError());
            }
            else if (typeof window.notifyError !== "undefined") {
                window.notifyError(getError());
            }
        }
        catch (x) {
            document.write("" + x + "");
        }
    





At D:\home\site\wwwroot\Modules\AzDevOps\AzDevOps.psm1:7 char:9
+         Invoke-RestMethod -Uri $url -Authentication Basic -Credential ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Reques\u2026PowerShell/6.2.0
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by iSazonov** [comment]
@PoshChan please retry linux

**Comment by PoshChan** [comment]
@iSazonov, could not find build at: , error: Invoke-RestMethod : 




    Access Denied: The Personal Access Token used has expired.
    
        body {
            font-family: "-apple-system",BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Helvetica,Ubuntu,Arial,sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol";
            font-size: 14px;
            height: 100%;
            margin: 0;
            background-color: #fff;
        }

        A {
            color: #007ACC;
            text-decoration: none;
        }
        A:hover {
            text-decoration: underline;
        }

        .header {
            background-color: #0078d4;
            color: #fff;
            height: 40px;
            font-size: 14px;
        }

        .header .logo {
            height: 20px;
            margin: 9px 5px 0 9px;
        }

        .header .product-name {
            vertical-align: top;
            padding-top: 10px;
            display: inline-block;
        }

        .content {
            margin-left: 15%;
            margin-right: 5%;
        }

        .error-summary {
            margin-bottom: 40px;
        }

        .error-code {
            display: inline-block;
            vertical-align: top;
            color: #777;
            font-size: 200px;
            line-height: 130px;
            margin-top: 60px;
            margin-right: 40px;
        }

        .error-details {
            display: inline-block;
            vertical-align: top;
            margin-top: 60px;
            max-width: 500px;
        }

        .error-details > h1 {
            font-size: 28px;
            margin: 0;
            text-transform:uppercase;
            font-weight:normal;
        }
        .error-details > h3 {
            text-transform: uppercase;
            font-size: 16px;
        }

        .error-details .action {
            font-size: 16px;
        }

        .error-details .action-text {
            vertical-align: middle;
        }

        .error-details > .helpful-links > a {
            margin-right: 10px;
        }

        .more-info {
            min-width:600px;
        }

        .more-info > pre {
            margin: 20px 0;
            white-space: pre-wrap;
        }

        .tips, .additionalDetails {
            min-width:500px;
            margin: 40px 0;
        }

        .tips > ul {
            list-style-type: square;
        }

        .tips > ul > li {
            margin-bottom: 10px;
        }

        .additionalDetails > h3 {
            font-size: 16px;
            font-weight: normal;
        }

        .additionalDetails .title {
            font-weight: bold;
            color: #444;
        }

        .additionalDetails .info {
            color: #777;
        }

        .additionalDetails > div {
            margin-top: 5px;
            margin-left: 20px;
        }
    


    
        
        Azure DevOps Services
    
    
        
            401
            
                Not Authorized
                
                The request requires authentication
                
                    
                        Sign in
                    
                
                
                    Service Status and Support
                    @AzureDevOps
                
            
        

        
        
            More information about this error
            Access Denied: The Personal Access Token used has expired.

            
        
        
        
            Additional technical details:
            
                Activity ID:
                936f8aa0-9036-42d8-b3a6-c5a94d1fa97d
            
            
                Date and Time:
                4/25/2019 3:32:12 AM (UTC)
            
        
        
    
    
    
        function getError() {
            return "eyJVcmkiOiJodHRwczovL2Rldi5henVyZS5jb206NDQzL1Bvd2VyU2hlbGwvX2FwaXMvYnVpbGQvYnVpbGRzLzIxNDczP2FwaS12ZXJzaW9uPTUuMCIsIlN0YXR1c0NvZGUiOjQwMSwiTWVzc2FnZSI6IkFjY2VzcyBEZW5pZWQ6IFRoZSBQZXJzb25hbCBBY2Nlc3MgVG9rZW4gdXNlZCBoYXMgZXhwaXJlZC4iLCJEZXRhaWxzIjoiIiwiQ29udGVudCI6bnVsbCwiSWRlbnRpdHkiOiIifQ==";
        }

        try {
            if (typeof window.external !== "undefined" && typeof window.external.notifyError !== "undefined") {
                window.external.notifyError(getError());
            }
            else if (typeof window.notifyError !== "undefined") {
                window.notifyError(getError());
            }
        }
        catch (x) {
            document.write("" + x + "");
        }
    





At D:\home\site\wwwroot\Modules\AzDevOps\AzDevOps.psm1:7 char:9
+         Invoke-RestMethod -Uri $url -Authentication Basic -Credential ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidOperation: (Method: GET, Reques\u2026PowerShell/6.2.0
}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException
+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand

**Comment by iSazonov** [comment]
@TravisEz13 Could you please look the issue with CI-linux?

**Comment by iSazonov** [comment]
@PoshChan Please retry linux.

**Comment by PoshChan** [comment]
@iSazonov, I do not understand the build target(s) `linux.`; I only allow `static`, `windows`, `macos`, `linux`, `all`

**Comment by iSazonov** [comment]
@PoshChan Please retry linux.

**Comment by PoshChan** [comment]
@iSazonov, I do not understand the build target(s) `linux.`; I only allow `static`, `windows`, `macos`, `linux`, `all`

**Comment by iSazonov** [comment]
@PoshChan Please retry linux

**Comment by PoshChan** [comment]
@iSazonov, successfully started retry of `PowerShell-CI-Linux`

**Pull request merged**
