### PR TITLE
Add `-Force` parameter to `Resolve-Path` and `Convert-Path` cmdlets to support wildcard hidden files

### LINKED ISSUE #20929: Add a `-Force` switch to `Convert-Path` and `Resolve-Path` so as to also support hidden files.
### Summary of the new feature / enhancement

Currently, both `Convert-Path` and `Resolve-Path` only ever report non-hidden files as matching a given _wildcard pattern_.

In order to also support hidden files, a `-Force` switch should be added, analogous to `Get-Item` and `Get-ChildItem`.

E.g., on Unix-like platforms:

```powershell
# Ditto for Resolve-Path
Convert-Path ~/.bash*
```

This currently produces NO output, because `.`-prefixed files and directories are considered hidden on Unix-like platforms.
Desired output (for example):

```
/Users/jdoe/.bash_sessions
/Users/jdoe/.bash_history
/Users/jdoe/.bash_profile
/Users/jdoe/.bashrc
```

Note: The problem arises only with _wildcard patterns_ - literal paths _are_ found.

### Proposed technical implementation details (optional)

_No response_

### PR DESCRIPTION
**Pull request by ArmaanMcleod**
# PR Summary

Fixes #20929

Added `-Force` parameter to `Resolve-Path` and `Convert-Path` cmdlets to support wildcard hidden files.

## PR Context

Currently it is not possible to use `Resolve-Path` and `Convert-Path` with wildcard hidden paths.

This PR resolves this by adding the missing `-Force` parameter so hidden files can be supported with above cmdlets.

The tests are the same between both cmdlets and differentiate differently between Windows(setting `Hidden` attribute) and Unix(prefixing file with `.`) for hidden files.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10755
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [x] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by ArmaanMcleod** [comment]
Need to add tests for unix hidden files starting with `.`

**Comment by ArmaanMcleod** [comment]
@mklement0 Let me know what you think of these changes and if it works for you now 🙂.

**Comment by mklement0** [comment]
Thank you, @ArmaanMcleod - looks great.

The only thing missing is a documentation issue.

**Comment by ArmaanMcleod** [comment]
> Thank you, @ArmaanMcleod - looks great.
> 
> The only thing missing is a documentation issue.

Thanks @mklement0. Issue raised, thanks for reminding me 😄.

**Comment by SteveL-MSFT** [comment]
The @PowerShell/wg-powershell-cmdlets reviewed this.  We prefer more specific parameters to the general `Force`, however, as the base class already supports `Force` as the way to include hidden files and the change is just propagating this we are ok with this behavior change.

**Review by iSazonov — APPROVED** [review]

**Review by SteveL-MSFT — APPROVED** [review]

**Review by andyleejordan — APPROVED** [review]
Hi, I really like this PR. Very simple code change to enable missing functionality just by exposing what's already implemented and should've been available, and you wrote thorough tests and documentation. What's outside of your control is that the CI ran last _December_, so I've opted to update your branch with a rebase and trigger a new run of our CI. As long as that still passes and I can verify the added tests ran and passed, I'll get this in! Thanks so much for your work and patience.

**Pull request merged**
