### PR TITLE
doc updates for v6.0.0-beta.3 release

### PR DESCRIPTION
**Pull request by daxian-dbw**
doc updates for v6.0.0-beta.3 release

### CODE REVIEW

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Comment by daxian-dbw** [comment]
The failed AppVeyor build is somehow a daily build (not sure why). The failed tests there are already fixed by #4058 in master. But the release branch doesn't have the fix and hence those tests failed.

**Comment by daxian-dbw** [comment]
The packaging failure in OSX is because it tried to create the package beta.3 with beta.3 powershell. It's not a real problem.

**Comment by daxian-dbw** [comment]
Given that, I will merge this branch.

**Pull request merged**
