### PR TITLE
Fix update help tests for PSReadline

### LINKED ISSUE #5973: Nightly Builds failing after #5759
#5759 changes were merged without any `[feature]` tags for full testing. Now nightly and PR builds are failing.

Again, I'm asking that we start running feature tests by default in PRs. Trying to determine what is and is not a feature affecting change is proving to be pointless. If you are concerned about quick README updates, add a README tag to bypass feature tests. Otherwise, they should be on by default, IMO.

https://ci.appveyor.com/project/PowerShell/powershell-f975h

```none
TEST FAILURES
Description: Validate Update-Help for module 'PSReadLine'
Name:        Validate Update-Help from the Web for all PowerShell Core modules...Validate Update-Help for module 'PSReadLine'
message:
Expected: {1}
But was:  {0}
stack-trace:
at line: 157 in C:\projects\powershell-f975h\test\powershell\engine\Help\UpdatableHelpSystem.Tests.ps1
157:     $helpFilesInstalled.Count | Should Be $expectedHelpFiles.Count
Description: Validate Update-Help for module 'PSReadLine'
Name:        Validate Update-Help -SourcePath for all PowerShell Core modules...Validate Update-Help for module 'PSReadLine'
message:
Expected: {1}
But was:  {0}
stack-trace:
at line: 157 in C:\projects\powershell-f975h\test\powershell\engine\Help\UpdatableHelpSystem.Tests.ps1
157:     $helpFilesInstalled.Count | Should Be $expectedHelpFiles.Count
```

https://travis-ci.org/PowerShell/PowerShell/jobs/331386328

```none
TEST FAILURES
Description: Validate Update-Help from the Web for all PowerShell Core modules./
Name:        Validate Update-Help for module 'PSReadLine'
message:
Expected: {1}
But was:  {0}
stack-trace:
at line: 157 in /home/travis/build/PowerShell/PowerShell/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
157:     $helpFilesInstalled.Count | Should Be $expectedHelpFiles.Count
Description: Validate Update-Help -SourcePath for all PowerShell Core modules./
Name:        Validate Update-Help for module 'PSReadLine'
message:
Expected: {1}
But was:  {0}
stack-trace:
at line: 157 in /home/travis/build/PowerShell/PowerShell/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
157:     $helpFilesInstalled.Count | Should Be $expectedHelpFiles.Count
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input: 
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 352 in /home/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
352:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input:  -IntERactive
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 352 in /home/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
352:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input:  -i
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 352 in /home/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
352:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input w/ initial command
message:
Expected string length 7 but was 4. Strings differ at index 4.
Expected: {PS> 1+1}
But was:  {PS> }
---------------^
stack-trace:
at line: 372 in /home/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
372:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Redirected input explicit prompting (-File -)
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 388 in /home/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
388:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Redirected input no prompting (-Command -)
message:
Expected string length 1 but was 0. Strings differ at index 0.
Expected: {2}
But was:  {}
-----------^
stack-trace:
at line: 399 in /home/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
399:             $process.StandardOutput.ReadLine() | Should Be "2"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Redirected input w/ nested prompt
message:
Expected string length 29 but was 4. Strings differ at index 4.
Expected: {PS> $host.EnterNestedPrompt()}
But was:  {PS> }
---------------^
stack-trace:
at line: 432 in /home/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
432:             $process.StandardOutput.ReadLine() | Should Be "PS> `$host.EnterNestedPrompt()"
```

https://travis-ci.org/PowerShell/PowerShell/jobs/331386331

```none
TEST FAILURES
Description: Validate Update-Help from the Web for all PowerShell Core modules./
Name:        Validate Update-Help for module 'PSReadLine'
message:
Expected: {1}
But was:  {0}
stack-trace:
at line: 157 in /Users/travis/build/PowerShell/PowerShell/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
157:     $helpFilesInstalled.Count | Should Be $expectedHelpFiles.Count
Description: Validate Update-Help -SourcePath for all PowerShell Core modules./
Name:        Validate Update-Help for module 'PSReadLine'
message:
Expected: {1}
But was:  {0}
stack-trace:
at line: 157 in /Users/travis/build/PowerShell/PowerShell/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1
157:     $helpFilesInstalled.Count | Should Be $expectedHelpFiles.Count
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input: 
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 352 in /Users/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
352:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input:  -IntERactive
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 352 in /Users/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
352:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input:  -i
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 352 in /Users/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
352:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Interactive redirected input w/ initial command
message:
Expected string length 7 but was 4. Strings differ at index 4.
Expected: {PS> 1+1}
But was:  {PS> }
---------------^
stack-trace:
at line: 372 in /Users/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
372:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Redirected input explicit prompting (-File -)
message:
Expected string length 7 but was 125. Strings differ at index 0.
Expected: {PS> 1+1}
But was:  {An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.}
-----------^
stack-trace:
at line: 388 in /Users/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
388:             $process.StandardOutput.ReadLine() | Should Be "PS> 1+1"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Redirected input no prompting (-Command -)
message:
Expected string length 1 but was 0. Strings differ at index 0.
Expected: {2}
But was:  {}
-----------^
stack-trace:
at line: 399 in /Users/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
399:             $process.StandardOutput.ReadLine() | Should Be "2"
Description: ConsoleHost unit tests/Redirected standard input for 'interactive' use
Name:        Redirected input w/ nested prompt
message:
Expected string length 29 but was 4. Strings differ at index 4.
Expected: {PS> $host.EnterNestedPrompt()}
But was:  {PS> }
---------------^
stack-trace:
at line: 432 in /Users/travis/build/PowerShell/PowerShell/test/powershell/Host/ConsoleHost.Tests.ps1
```

PR build failures: 
* https://travis-ci.org/PowerShell/PowerShell/jobs/331469515#L4276
* https://travis-ci.org/PowerShell/PowerShell/jobs/331469516#L3427

### PR DESCRIPTION
**Pull request by adityapatwardhan**
## PR Summary

closes #5973
The path for PSReadline after updating has a module version. The tests needed to be updated.

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [X] Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [NA] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [NA ] Issue filed - Issue link:
- [NA] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [NA] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [X] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]

**Comment by daxian-dbw** [comment]
@adityapatwardhan There are failures in Travis CI runs. Please take a look.

**Comment by adityapatwardhan** [comment]
I suspect they are due to newer version on PSReadline. Having a look.

**Comment by adityapatwardhan** [comment]
cc @TravisEz13 

The failures in Console tests are due upgrading the PSReadline version to v2.0.0.-beta1. We need to revert the change https://github.com/PowerShell/PowerShell/pull/5759

**Comment by daxian-dbw** [comment]
Close this PR as we are reverting #5759, which introduced the failures.

**Pull request closed without merging**
