### PR TITLE
Remove AppVeyor specific cmdlet from 'Start-NativeExecution'

### PR DESCRIPTION
**Pull request by daxian-dbw**
## PR Summary

Remove the use of `Add-AppveyorCompilationMessage` from `Start-NativeExecution`.
`Add-AppveyorCompilationMessage` is an AppVeyor specific cmdlet which won't work when running `Start-NativeExecution` in Travis CI.

#6111 seems to cause CI to fail in master (Travis CI, macOS only) when running `dotnet restore`: https://travis-ci.org/PowerShell/PowerShell/jobs/346997722
However, the CI builds for the PR were successful: https://travis-ci.org/PowerShell/PowerShell/builds/346459731?utm_source=github_status&utm_medium=notification

I also tried on Macbook locally and the restore is successful. I'm not sure what might cause the failure in the master CI, and will wait till tomorrow morning to see if the subsequent daily builds will also fail for the same error. When looking at the `dotnet restore` failure, I found errors about `Add-AppveyorCompilationMessage` in Travis CI, so fixing it in this PR.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by adityapatwardhan** [comment]
If `Add-AppveyorCompilationMessage` is useful in AppVeyor CI, then maybe we can use `$env:APPVEYOR`.

It so happened that `$env:CI` is defined by both Travis-CI and AppVeyor.

https://www.appveyor.com/docs/environment-variables/
https://docs.travis-ci.com/user/environment-variables/

**Comment by daxian-dbw** [comment]
According to @TravisEz13, `Add-AppveyorCompilationMessage` is to make sure the AppVeyor build fails. But the `throw` statement already makes the build fails, no matter in AppVeyor or Travis CI, so I don't think this is really needed here.

**Comment by daxian-dbw** [comment]
It seems the failure in `dotnet restore` was because of the outdated cache content. After running `dotnet nuget locals all --clear` before `dotnet restore`, the macOS CI build worked fine (see [build result](https://travis-ci.org/PowerShell/PowerShell/builds/347362201?utm_source=github_status&utm_medium=notification)).

However, the cache was not updated in the last build because `cache.push` timeout was reached. So I temporarily increase the timeout to make the cache update succeed.

**Review by adityapatwardhan — APPROVED** [review]

**Review by adityapatwardhan — APPROVED** [review]

**Comment by daxian-dbw** [comment]
CI builds passed. It looks to me refreshing the cache fixed the build break. I will merge this PR and see how it goes.

**Pull request merged**
