### PR TITLE
Replace `Requires.NotNullOrEmpty(string)` with `ArgumentException.ThrowIfNullOrEmpty`

### PR DESCRIPTION
**Pull request by xtqqczze**
Breaking change: _Bucket 3: Unlikely Grey Area_

This PR makes changes to public APIs so that an `ArgumentException` is thrown instead of `ArgumentNullException` when a string is empty rather than null.

* [System.Management.Automation.Subsystem.Prediction.PredictionContext.Create(String)](https://learn.microsoft.com/dotnet/api/system.management.automation.subsystem.prediction.predictioncontext.create#system-management-automation-subsystem-prediction-predictioncontext-create(system-string))
* [System.Management.Automation.Subsystem.Prediction.PredictiveSuggestion..ctor(String)](https://learn.microsoft.com/dotnet/api/system.management.automation.subsystem.prediction.predictivesuggestion.-ctor#system-management-automation-subsystem-prediction-predictivesuggestion-ctor(system-string))
* [System.Management.Automation.Subsystem.Prediction.PredictiveSuggestion..ctor(String, String)](https://learn.microsoft.com/dotnet/api/system.management.automation.subsystem.prediction.predictivesuggestion.-ctor#system-management-automation-subsystem-prediction-predictivesuggestion-ctor(system-string-system-string))
* [System.Management.Automation.Subsystem.Prediction.CommandPrediction.OnSuggestionAccepted(PredictionClient, Guid, UInt32, String)](https://learn.microsoft.com/dotnet/api/system.management.automation.subsystem.prediction.commandprediction.onsuggestionaccepted#system-management-automation-subsystem-prediction-commandprediction-onsuggestionaccepted(system-management-automation-subsystem-prediction-predictionclient-system-guid-system-uint32-system-string))

If a consumer caught the `ArgumentNullException` and not the base class `ArgumentException` this is a change in behavior.

However, it seems unlikely to depend on a specific exception being thrown, because if specific behavior was required, the caller could have implemented the necessary business logic.

### CODE REVIEW

**Comment by xtqqczze** [comment]
@daxian-dbw Please mark `Review - Maintainer`.

**Comment by xtqqczze** [comment]
_PowerShell-CI-macos (Test for macOS mac Test - UnelevatedPesterTests - Others_ test failure:
```log
Invoke-WebRequest tests.Error occurred in Describe block
```

**Comment by daxian-dbw** [comment]
I think this change is fine. But you need to rebase with the master, because #19133 introduces another use of the `Requires.NotNullOrEmpty(string value, string paramName)`. So, you need to update that one as well. Thanks!

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Review by iSazonov — APPROVED** [review]

**Pull request merged**
