### PR TITLE
Fix build/package/installation scripts for SLES

### PR DESCRIPTION
**Pull request by tomconte**
## PR Summary

Small changes to the SUSE installation script so that it allows installing on SLES 12+ in addition to openSUSE 42+

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [X] Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [X] Issue filed - Issue link: #3427
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [NA] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [NA] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

### CODE REVIEW

**Comment by TravisEz13** [comment]
does line 587 in build.psm1 need to be updated as well?

**Comment by tomconte** [comment]
I am working on additional changes to `build.psm1` and `packaging.psm1` to allow packaging on SUSE family (openSUSE + SLES) and also creating a specific RPM that has the proper dependencies (to avoid the error message that we currently get when installing the RedHat RPM on SUSE). I will push additional commits to this PR if it works for you!

**Comment by tomconte** [comment]
@TravisEz13 SUSE doesn't need these symlinks AFAICT... It's able to resolve the dynamic libraries properly:

```
> ldd /opt/microsoft/powershell/6.0.0-124-g75c452c7/libmi.so
        libssl.so.1.0.0 => /lib64/libssl.so.1.0.0 (0x00007fc6b15a8000)
        libcrypto.so.1.0.0 => /lib64/libcrypto.so.1.0.0 (0x00007fc6b114d000)
```

**Comment by adityapatwardhan** [comment]
@tomconte Thanks for your contribution!
If you are expecting more changes to this PR, please add a `WIP:` in the title until it is ready for review.  More information here: https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress

**Comment by tomconte** [comment]
Thanks @adityapatwardhan, would appreciate your review now.

**Review by TravisEz13 — APPROVED** [review]

**Review by adityapatwardhan — APPROVED** [review]

**Pull request merged**
