### PR TITLE
Removed automatically adding year to copyright message

### PR DESCRIPTION
**Pull request by adityapatwardhan**
Removed automatically adding year to copyright message for file generated by New-ModuleManifest and New-PSRoleCapabilityFile.

### CODE REVIEW

**Comment by iSazonov** [comment]
It seems new tests not needed - why validate an entity what is absent? Or alternatively we would check a exact format of the copyright string.

**Comment by adityapatwardhan** [comment]
@iSazonov fixed.

**Comment by lzybkr** [comment]
I agree with @iSazonov - we don't really need a test for this.

If the code were to change, maintainers will want to understand the reasoning behind the change before merging - regardless of the existence of a test.

And you also added a file in your last commit that shouldn't be there.

**Comment by adityapatwardhan** [comment]
@iSazonov  @lzybkr Removed tests and files added inadvertently. 
We were recommended by CELA (legal) to remove year from copyright strings.

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Review by iSazonov — APPROVED** [review]
LGTM

**Pull request merged**
