### PR TITLE
Rename Copy.Item.Tests.ps1 to match naming convention

### PR DESCRIPTION
**Pull request by romero126**
# PR Summary

Rename Copy.Item.Tests.ps1 -> Copy-Item.Tests.ps1 
in order to match naming convention inside \test\powershell\Modules\Microsoft.PowerShell.Management

## PR Context

All filenames in \test\powershell\Modules\Microsoft.PowerShell.Management use Verb-Command.Tests when naming their files. This one however does not match that standard.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by iSazonov** [comment]
We have many files not matching naming convention. 
If we want have consistency we must fix everything or fix nothing.

**Comment by romero126** [comment]
I agree completely. However we cant just fix everything all at once.. That's why we need the approach fix it when you see it. :)

**Comment by vexx32** [comment]
Mm true. I could see fixing the naming on each file in a given folder, doing it one folder at a time, perhaps?

**Comment by iSazonov** [comment]
I don't see a value from the change because we use modern IDEs with power and fast search, c# plugins allows us to follow by references, also sometimes we have many classes in one file - as result file name lost value but in the same time renaming complicates commit history.

**Comment by daxian-dbw** [comment]
> ... in the same time renaming complicates commit history.

I kinda agree with @iSazonov on that. Renaming a file will cause the file history to be "lost" (or to be more accurate, harder to retrieve). So if it's not necessary, maybe we should avoid renaming files.

**Comment by vexx32** [comment]
Is it so frequent that we need to dig up file history?

The additional time needed to dig up file history is usually not immense, and not needed very often. I would be surprised if that's necessary anywhere near as much as folx need to go looking for the file. Time lost finding the file as it is now v.s. time lost finding the file as it was before the rename weighted depending on frequency of need.

I would argue that having a consistent naming convention will make maintenance easier both for the PS team and folx in the community, especially folx just starting to look at contributing. In my opinion the consistency is valuable here, but y'all may have different ideas. 🙂

**Comment by iSazonov** [comment]
> Is it so frequent that we need to dig up file history?

If you want to get better understanding how a code works you will look history frequently.

**Review by daxian-dbw — APPROVED** [review]
Conflicts resolved.
@romero126 Sorry that this PR has been overlooked for so long ...
The general guideline is to avoid renaming files to keep the history handy. But in this particular case, the history is not very interesting. So I decide to take this change.

**Comment by daxian-dbw** [comment]
The change in this PR has nothing to do with the CI failure, so I will force merge it.

**Pull request merged**
