### PR TITLE
Graphicalhost

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
Bring in the graphicalhost code needed for out-gridview and show-command.  show-command is working, but out-gridview isn't able to find the `InputValueTemplate` resource in generic.xaml at `filterrulepanel.cs:356` which ends up with an unhandled exception so the cmdlet hangs waiting for the wpf window to show.

Anyone know WPF to figure out what's going on?

### CODE REVIEW

**Comment by Jaykul** [comment]
I do know WPF, but ...
Doesn't it seem silly to put all this windows only code into the core? 
How about a nice external Windows-only module?

**Comment by SteveL-MSFT** [comment]
This code would only ship with the Windows build of PS7.  We could split out the cmdlets to a separate module although it's technically a breaking change for anyone using the fully qualified module path.

**Comment by iSazonov** [comment]
Is it another code than we removed from the repo previously? That code was compiled for PowerShell Native.

**Comment by SteveL-MSFT** [comment]
@iSazonov this shouldn't have anything to do with the PowerShell-Native code as this is all C# (and XAML).  The graphicalhost code was never in this repo as it is entirely WPF based and wasn't supported on .NET Core previously.

**Comment by SteveL-MSFT** [comment]
Thinking about this further, I'm in support of having this code and the associated cmdlet code moved to another repo as a separate module altogether.  The primary reason is I'd prefer not to have so much Windows specific code in this repo.  Although a breaking change, it's unlikely to be impactful as these cmdlets are mostly used interactively.

**Comment by iSazonov** [comment]
In the case it should be done in Windows PowerShell - now we can load Windows PowerShell modules. Also a benefit in the way is one code base. But Windows PowerShell was frozen. But we have Windows Compatibility module and could do proxying for the cmdlets too.

And finally - we could use a cross platform project like https://github.com/AvaloniaUI/Avalonia if we really want to be portable.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agree that we should have this code in a separate module containing these two cmdlets and the WPF code.  This is a `breaking change` for anyone using module qualified path, but it seems highly unlikely for these two specific cmdlets.

**Comment by vexx32** [comment]
This would be awesome if we could write it in Avalonia or something of that nature! But yeah, separate module seems to be a good first step.

**Comment by iSazonov** [comment]
Only separate module or new repo too?

**Comment by SteveL-MSFT** [comment]
@iSazonov sorry, separate repo was implied.  i'll get to this after finishing up the 3.0 port work

**Pull request closed without merging**
