### PR TITLE
Get-ComputerInfo - fix typo in property name

### LINKED ISSUE #3166: Get-ComputerInfo Typo - BiosSeralNumber
Steps to reproduce
------------------
`Get-ComputerInfo | ft BiosSer*`

Expected behavior
-----------------
Returned heading should be BiosSerialNumber

Actual behavior
---------------
Returned is listed as BiosSeralNumber

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
biosserialnumber

### PR DESCRIPTION
**Pull request by iSazonov**
Close #3166

### CODE REVIEW

**Comment by joeyaiello** [comment]
You're so fast, @iSazonov! I'm just waking up, you're already fixing 4 hour old issues. 😄

**Review by daxian-dbw — APPROVED** [review]

**Comment by iSazonov** [comment]
@joeyaiello I still thought for a long time-to be or not to be :-)

**Comment by lzybkr** [comment]
I added the breaking change label because this is a public api - scripts may be using that property name.

If we're concerned about the break - then would could add an alias.

**Comment by iSazonov** [comment]
@lzybkr I dont see the typo in PS 5.1 (Win 10 build 15031)

**Comment by lzybkr** [comment]
I do:

```
#13 PS> [Microsoft.PowerShell.Commands.ComputerInfo].GetProperty('BiosSeralNumber')

MemberType       : Property
Name             : BiosSeralNumber
DeclaringType    : Microsoft.PowerShell.Commands.ComputerInfo
ReflectedType    : Microsoft.PowerShell.Commands.ComputerInfo
MetadataToken    : 385876785
Module           : Microsoft.PowerShell.Commands.Management.dll
PropertyType     : System.String
Attributes       : None
CanRead          : True
CanWrite         : True
GetMethod        : System.String get_BiosSeralNumber()
SetMethod        : Void set_BiosSeralNumber(System.String)
IsSpecialName    : False
CustomAttributes : {}

#14 PS> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.14393.693
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14393.693
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Comment by iSazonov** [comment]
Sorry. I confirm.

**Comment by ncook-hxgn** [comment]
This seems to still be a problem on 5.1 (which I have across a group of computers. I don't see it in PS 7.0.3 which I run locally / develop in) .. which version was this fixed in?
I think what I mean to ask is, is a fix for this available via Windows Update for WMF 5.1?

**Comment by iSazonov** [comment]
@ncook-hxgn Windows PowerShell is frozen - no functional updates, only security ones. All new features are in only in PowerShell 7+.

**Pull request merged**
