### PR TITLE
Remove the 'Code Coverage Status' badge from the build status table

### PR DESCRIPTION
**Pull request by daxian-dbw**
## PR Summary

Remove the 'Code Coverage Status' badge from the build status table because https://codecov.io/gh/PowerShell/PowerShell had become deactivated.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.

### CODE REVIEW

**Review by TravisEz13 — APPROVED** [review]

**Review by JamesWTruher — APPROVED** [review]

**Comment by iSazonov** [comment]
Could you please clarify what is our policy about code coverage? Aren't we interested in that?

**Comment by daxian-dbw** [comment]
We are interested to have coverage data of the code base, but its priority is low because we have lots of more important tasks.

**Comment by iSazonov** [comment]
Eh, maybe someone in the community could customize CodeCov if you posted the requirements in an issue.

**Comment by daxian-dbw** [comment]
Maybe @JamesWTruher or @adityapatwardhan can do that. But even if a community member picks up the work, it may still be a low priority for the team to help or review the work, so it's better to set the right expectations.

**Pull request merged**
