### PR TITLE
Removing trailing whitespace 

### PR DESCRIPTION
**Pull request by powercode**
Trailing whitespace removed from cs,json,xml,xaml,ps1,psm1,ps1xml, psd1 files.

The followning command was used:
```
using namespace System.Text.RegularExpressions

function Remove-TrailingWhitespace {
    param(
        [Parameter(Mandatory, ValueFromPipelineByPropertyName, ValueFromPipeline)]
        [Alias('PSPath')]
        [string] $LiteralPath
    )
    begin {
        $trailingWhiteSpace  = [Regex]::new('(?m)[ \t]+\r?$', [RegexOptions]::Compiled)
    }

    process {
        try {
            $LiteralPath = (Resolve-Path $LiteralPath).ProviderPath
            if (Test-path -PathType Leaf $LiteralPath) {
                $content = Get-Content -Raw -LiteralPath $LiteralPath
                if ($null -ne $content) {
                    $trimmedContent = $trailingWhiteSpace.Replace($content, "`r")
                    if ($trimmedContent -ne $content) {
                        # Set-Content fails for some reason with 'Set-Content : Stream was not readable.'
                        [io.file]::WriteAllText($LiteralPath, $trimmedContent, [Text.Encoding]::ASCII)
                        Get-Item $LiteralPath
                    }
                }
            }
        }
        catch {
            Write-Error -Message $_.Exception.Message -TargetObject $LiteralPath
        }
    }
}
```

### CODE REVIEW

**Comment by vors** [comment]
Can you, please, resolve the conflicts?

**Comment by vors** [comment]
@powercode sorry there are conflicts again :(
I know it's pretty annoying.

**Comment by powercode** [comment]
Just pushed a resolved version

**Comment by powercode** [comment]
```
Unhandled Exception: System.IO.IOException: Broken pipe
   at System.IO.UnixFileStream.CheckFileCall(Int64 result, Boolean ignoreNotSupported)
   at System.IO.UnixFileStream.WriteNative(Byte[] array, Int32 offset, Int32 count)
   at System.IO.UnixFileStream.FlushWriteBuffer()
   at System.IO.UnixFileStream.Dispose(Boolean disposing)
   at System.IO.UnixFileStream.Finalize()
Test result file 'pester-tests.xml' not found for test/powershell.
At /home/travis/build/PowerShell/PowerShell/build.psm1:814 char:9
+         throw "Test result file '$testResultsFile' not found for $Tes ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Test result fil...est/powersh 
   ell.:String) [], RuntimeException
    + FullyQualifiedErrorId : Test result file 'pester-tests.xml' not found fo 
   r test/powershell.
```

Don't think I'm responsible for that.

**Comment by lzybkr** [comment]
There are way too many changes to review and I'm concerned about the potential for problems due to changing the file encoding.

For example, if we test data that used a specific encoding, we would lose the coverage due to a PR like this.

**Comment by lzybkr** [comment]
Closing this in favor of #3001.

**Pull request closed without merging**
