### PR TITLE
Check `pwsh.exe` and `pwsh` in daily version on Windows

### PR DESCRIPTION
**Pull request by centreboard**
# PR Summary
Check for `pwsh.exe` on Windows to get the daily version currently installed

## PR Context
Improves on #10489
On Windows `pwsh` doesn't exist so the same daily version was reinstalled when calling
`iex "& {$(irm aka.ms/install-powershell.ps1)} -Daily"`

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
There is a failure unrelated to your change, which is blocking this PR.
https://powershell.visualstudio.com/PowerShell/_build/results?buildId=34391&view=logs&jobId=68b94060-b87a-5de8-40f0-78718e402518&taskId=50e847f0-73a2-533f-c084-25a3970df96e&lineStart=36&lineEnd=37&colStart=1&colEnd=1
Do you want to fix or do you want me to?

**Comment by centreboard** [comment]
@TravisEz13 Could you please look at it? I don't have a mac and naively replacing caskroom/cask with homebrew/cask-cask didn't work for me in Azure Pipelines.

**Comment by TravisEz13** [comment]
I've opened https://github.com/PowerShell/PowerShell/pull/10752 to fix the issue. I'll help update this PR once we have fixed that issue.

**Comment by TravisEz13** [comment]
The other PR was merged.  I retried your test.

**Comment by TravisEz13** [comment]
@PoshChan  Please remind me in 1 hour

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 1 hour ago

**Comment by TravisEz13** [comment]
Thanks for your contribution

**Comment by bergmeister** [comment]
Awesome, thanks :-)

**Pull request merged**
