### PR TITLE
Adding VBS feature names to Get-ComputerInfo

### PR DESCRIPTION
**Pull request by mattifestation**
Adding new Virtualization-Based Security (VBS) feature names to the Get-ComputerInfo cmdlet. This commit addresses issue #16357

# PR Summary

This PR adds supported Virtualization-Based Security (VBS) feature names to the Get-ComputerInfo cmdlet. This PR addresses issue #16357.

Thank you for your consideration.

## PR Context

Upon merging this PR, users of Windows Defender Application Control (WDAC) will benefit more greatly from Get-ComputerInfo in that it will present all available VBS features in a human-readable fashion, as Get-ComputerInfo intended. The feature names added in this PR will also offer parity with the feature names presented in the `msinfo32.exe` UI.

Note: this change would also ideally need to be backported to Windows PowerShell.

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
It would be great to update tests. `Get-StringValuesFromValueMap` does one way check and don't catch the absence before.

**Comment by iSazonov** [comment]
I think the test is broken because it doesn't catch the issue. The test checks seem only valid return values but it doesn't check absence of values.

**Review by SteveL-MSFT — APPROVED** [review]
The test is marked as `Pending` and I'm not sure what values will show up in CI/CD instances

**Comment by iSazonov** [comment]
Manually checked - new values present in output:
image

**Comment by iSazonov** [comment]
@mattifestation Thanks for your contribution!

**Pull request merged**
