### PR TITLE
Use new Environment.IsPrivilegedProcess API

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Use new .Net 8.0 System.Environment.IsPrivilegedProcess API in code updating windows title  - no allocations, 2 pinvokes instead of many.

Notice, if local administrator is used and pwsh is started with `runas /trustlevel:0x20000` (IsPrivilegedProcess is still return true in the scenario) the window title contains "with restricted privileges" so it looks good:
image

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
@daxian-dbw @TravisEz13 Could you please help to find a root why the tests fail? I added debug output in 
[System.Environment]::IsPrivilegedProcess return True in "UnElevated" CI while original version of `Test-IsElevated` returns False. It's amazing. I cannot reproduce locally the behavior (tried `runas /trustlevel:0x20000` as in Build.psm1). 
Is this `IsPrivilegedProcess` bug or something specific in our CIs that we should fix here?

**Comment by jborean93** [comment]
@iSazonov essentially dotnet calls [GetTokenInformation](https://learn.microsoft.com/en-us/windows/win32/api/securitybaseapi/nf-securitybaseapi-gettokeninformation) to get the [TOKEN_ELEVATION](https://learn.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-token_elevation) bool value. The reason why this doesn't work in CI is either because UAC is disabled or token filtering is not applied to user account in question (builtin Administrator by default doesn't get filtered by UAC). In this scenario the `TOKEN_ELEVATION` value is still 1 as there is no linked token for that logon session.

The `runas /trustlevel:0x20000` method will create a restricted token without all the privileged groups and privileges even on an account that wouldn't normally get affected by UAC which is why the `IsInRole` check works but the `TOKEN_ELEVATION` check will always return 1 for an account that wouldn't be affected by UAC.

**Comment by jborean93** [comment]
> So I guess there is no easy way to recognize this scenario?

I think this particular scenario is pretty rare, I've only really seen it here and on some random blog posts. If pwsh wanted to use this API instead of checking the admin group then I would say changing how it runs the unelevated tests is probably the better bet and it will more accurately test them in a context that most non-admins would have. It's a minor difference though so it's not the end of the world if they want to continue using the existing method, just means you need to continue to use the identity/role checks that are there today.

**Comment by iSazonov** [comment]
@jborean93 Thanks for help!

@daxian-dbw PR is ready for review.

**Comment by daxian-dbw** [comment]
@iSazonov Can you please summarize why you reverted some changes to `principal.IsInRole` in other files but left this one in [ConsoleHostRawUserInterface.cs](https://github.com/PowerShell/PowerShell/pull/19406/files#diff-83f6244fd3f88c5d706cc087bddc2ed5f1f8ad14de2c83880b579946a9877747)?

**Comment by iSazonov** [comment]
> @iSazonov Can you please summarize why you reverted some changes to `principal.IsInRole` in other files but left this one in [ConsoleHostRawUserInterface.cs](https://github.com/PowerShell/PowerShell/pull/19406/files#diff-83f6244fd3f88c5d706cc087bddc2ed5f1f8ad14de2c83880b579946a9877747)?

`Environment.IsPrivilegedProcess`  is based on process TOKEN_ELEVATION. The token is always true for local administrator specially in scenario if process is involved with `runas /trustlevel:0x20000`, as result `Environment.IsPrivilegedProcess` always returns true as false positive.
So we have options:
1. Continue to use `principal.IsInRole`
2. Ignore `runas /trustlevel:0x20000` scenario and use `Environment.IsPrivilegedProcess` everywhere.
3. Fix `Environment.IsPrivilegedProcess` in .Net.

As for the PR, I use `Environment.IsPrivilegedProcess` in point where we safe using it. 
As for the rest of the places, that's for discussion.

**Review by daxian-dbw — DISMISSED** [review]
Thanks! LGTM.
Can you please open an issue about this in .NET repo?

**Comment by iSazonov** [comment]
@daxian-dbw Done https://github.com/dotnet/runtime/issues/84137

**Comment by daxian-dbw** [comment]
Sorry, I was confused. By looking at your latest PR description, before your change, the console title will not show as `Administrator`, but after your change, it shows up as `Administrator`, right? If so, that's a behavior change that I'm not sure about.
Loop in @TravisEz13 to comment on it.

**Comment by iSazonov** [comment]
> Sorry, I was confused. By looking at your latest PR description, before your change, the console title will not show as `Administrator`, but after your change, it shows up as `Administrator`, right? If so, that's a behavior change that I'm not sure about. Loop in @TravisEz13 to comment on it.

Yes, PowerShell windows title was changed in the PR but now it looks exacly how cmd.exe
image

**Comment by iSazonov** [comment]
There is "with restricted privileges" in the title that user see too.

**Comment by daxian-dbw** [comment]
@iSazonov I prefer to hold on this change until the corresponding .NET issue gets fixed.

**Comment by daxian-dbw** [comment]
I'm closing this PR. We can revisit the changes using `Environment.IsPrivilegedProcess` once the .NET issue gets resolved.

**Pull request closed without merging**
