### PR TITLE
Fix check for vcvarsall.bat absence

### PR DESCRIPTION
**Pull request by PetSerAl**
## PR Summary

If this line:
https://github.com/PowerShell/PowerShell/blob/d04fef469b774ffa63536ad460aff3708642999a/build.psm1#L225
does not find any candidates for `vcvarsall.bat`, then it ends assign `$null` to `$vcvarsallbatPath`. Passing `$null` for `-Path` parameter will cause check to fail due to parameter validation. This PR adds explicit check for `$null` to fix this.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]

**Review by iSazonov — APPROVED** [review]
Leave a comment

**Comment by TravisEz13** [comment]
@adityapatwardhan  another change to port to the native repo.

**Comment by iSazonov** [comment]
I suggest cut off and do changes only in https://github.com/PowerShell/PowerShell-Native

**Comment by adityapatwardhan** [comment]
I agree, I will update the README file under libpsl-native and powershell-native folder accordingly.

**Comment by adityapatwardhan** [comment]
Opened a PR for the README updates. https://github.com/PowerShell/PowerShell/pull/7248

**Pull request merged**
