### PR TITLE
Compare-Object Apply -IncludeEqual when -ExcludeDifferent is specified

### LINKED ISSUE #11847: Compare-Object: -ExcludeDifferent should imply -IncludeEqual
`Compare-Object` only reports _differences_ by default, requiring explicit opt-in for inclusion of _equal_ objects via `-IncludeEqual`.

Therefore, the only meaningful behavior when you use `-ExcludeDifferent` is to _default_ to `-IncludeEqual`.

Without that, as is currently the case, _nothing_ is ever output, so it is currently effectively pointless to pass `-ExcludeDifferent` _without also passing `-IncludeEqual`_.

# Steps to reproduce

```powershell
Compare-Object 1,2 3, 1 -ExcludeDifferent -PassThru -IncludeEqual  | Should -Be 1
# Currently produces NO output, because -IncludeEqual isn't implied.
Compare-Object 1,2 3, 1 -ExcludeDifferent -PassThru | Should -Be 1
```

# Expected behavior

Both tests should pass.

# Actual behavior

The 2nd test fails, because `-IncludeEqual` is not implied.

# Environment data

```none
PowerShell Core 7.0.0-rc.2
```

### PR DESCRIPTION
**Pull request by davidseibel**
# PR Summary

Fixes #11847

## PR Context

This pull request corrects the following behavior specified in issue #11847: when Compare-Object is used with the -ExcludeDifferent switch, the -IncludeEqual switch is not inferred.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [X] Issue filed: [PowerShell-Docs issue #5789](https://github.com/MicrosoftDocs/PowerShell-Docs/issues/5789)
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by davidseibel** [comment]
I would like input from the maintainers on whether they think an experimental feature is required in this case.  I can't think of a use case where anyone would use -ExcludeDifferent without wanting to see the objects that are equal, but I can see where it could still technically be a breaking change.

I am also still working on documentation, once I have that submitted, this PR should be ready for submission as well.

**Comment by TravisEz13** [comment]
@PowerShell/powershell-committee Can your review and see if we want to take this change, if it should be experimental, and if we should call it breaking?

I think it should be experimental.  I think this is [breaking change, bucket 2](https://github.com/PowerShell/PowerShell/blob/master/docs/dev-process/breaking-change-contract.md#bucket-2-reasonable-grey-area).  I think someone could have reasonably taken a decency on this, but I think the new behavior is predictable and obvious.

**Review by iSazonov — APPROVED** [review]

**Comment by TravisEz13** [comment]
One of the macos failures doesn't look random.  You may need to rebase.  Tell me if you need me to do that for you.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this.  We agree that the original intent is that `-IncludeEqual` is implicit with `-ExcludeDifferent` otherwise `-ExcludeDifferent` by itself is not useful.

**Comment by TravisEz13** [comment]
@davidseibel I rebased your branch to see if it resolved the failure.  Be sure to pull the changes, before making any additional changes.

**Comment by TravisEz13** [comment]
@PoshChan  Please remind me in 1 hour

**Comment by davidseibel** [comment]
@TravisEz13 - thanks, sorry for the slow response on my part.

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 1 hour ago

**Comment by vexx32** [comment]
@davidseibel probably safest to do a `git reset origin/master` since Travis needed to force-push to do the rebase.

**Comment by iSazonov** [comment]
@davidseibel Thanks for your contribution!

**Pull request merged**
