### PR TITLE
re-factor ArgumentToPSVersionTransformationAttribute

### PR DESCRIPTION
**Pull request by JamesWTruher**
# PR Summary

This attribute is multiply defined in multiple places, this PR re-factor is the code to have only one definition.

## PR Context

This should fix the build break when creating nuget packages.
One side effect of this PR is that the cmdlet `set-strictmode` will support `set-strictmode -version off`.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by adityapatwardhan — APPROVED** [review]

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by daxian-dbw** [comment]
I have a concern on supporting `-Version off` for `Set-StrictMode` (see https://github.com/PowerShell/PowerShell/issues/16736). Quoted here:

>IMHO, I think `off` may not be a suitable value for `Set-StrictMode -Version`. `-Version latest` means the latest version, but `-Version off` doesn't seem to make sense that naturally. The parameter `-StrictMode` in `Invoke-Command` is different from `-Version`, and thus `-StrictMode off` reads much more naturally than `-Version off`.

**Comment by daxian-dbw** [comment]
As for the build break, here is PR to fix that: https://github.com/PowerShell/PowerShell/pull/16800. (the `ValidateVersionAttribute` still needs to be added to that list)

**Comment by JamesWTruher** [comment]
> I have a concern on supporting `-Version off` for `Set-StrictMode` (see #16736). Quoted here:
> 
> > IMHO, I think `off` may not be a suitable value for `Set-StrictMode -Version`. `-Version latest` means the latest version, but `-Version off` doesn't seem to make sense that naturally. The parameter `-StrictMode` in `Invoke-Command` is different from `-Version`, and thus `-StrictMode off` reads much more naturally than `-Version off`.

I agree that it is a little unnatural, however I think that is overweighed by not having duplicated code, which I think is more important than a slight unnaturalness in usage. `-Strictmode off` will still continue to work, it just now has a slightly extended behavior.

**Review by PaulHigin — CHANGES_REQUESTED** [review]
Regarding packaging.psm1 changes, these can be removed because there is already a PR to address it (and which can be backported).  #16800.

Otherwise changes LGTM.

**Comment by JamesWTruher** [comment]
> Regarding packaging.psm1 changes, these can be removed because there is already a PR to address it (and which can be backported). #16800.
> 
> Otherwise changes LGTM.

If there is a PR to address the build break, then this PR can be rejected. We don't need to do the re-factor

**Comment by JamesWTruher** [comment]
closing in favor of https://github.com/PowerShell/PowerShell/pull/16800

**Pull request closed without merging**
