### PR TITLE
Added missing changelog for v7.1.0-preview.2

### PR DESCRIPTION
**Pull request by anmenaga**
# PR Summary
For some reason the changelog for `v7.1.0-preview.2` is missing from `master` branch.
Adding it by copy-paste from `tags/v7.1.0-preview.2`.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
there should have been spelling changes too

**Review by adityapatwardhan — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
Spelling errors - please fix

```
 CHANGELOG/preview.md
       30 | ands syntax (#10784) (Thanks @ChrisLGardner!) 
       33 | - Added Support For Big Endian `UTF-32` (#11947) (Thanks @No 
       35 |  time input (#12179) (Thanks @jackdcasey!) 
       54 | ix erroneous comment in <code>tokenizer.cs</code> (#12206) (Thanks @Shay 
       69 | caused by upcoming release of v5 (#12262) (Thanks @bergmeister 
       78 | <p>@rkitover, @bergmeister</p> 
       83 | <li>Add the <code>nuget.config</code> from root to the tempo 
       84 | <li>Bump System.IO.Packaging (#12365)</li> 
       88 | tallations. (#11429) (Thanks @rkitover!)</li> 
       90 | <li>Fix the <code>Sync PSGalleryModules to Artifacts</code> build (#1 
      100 |  properties (#11876) (Thanks @kevinoid!) 
      101 | dopters.md` (#12266) (Thanks @parameshbabu!) 

>> 12 spelling errors found in 70 files
```

**Comment by xtqqczze** [comment]
Fixes #12660

**Comment by xtqqczze** [comment]
@anmenaga the changelog was missing because we failed to merge `v7.1.0-preview.2` into `master` after release

**Pull request merged**
