### PR TITLE
Use SHA256 as digest for RPM packages (FIPS compliance)

### LINKED ISSUE #15866: PowerShell package in yum repository needs to have a payload digest.
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing a problem when attempting to install PowerShell from the Microsoft yum repo when using FIPS mode on RedHat 8.4.  An additional SHA256 digest needs to be added to the package so that FIPS enabled systems running Redhat 8+ can validate the payload of the package.

https://access.redhat.com/solutions/4460971

### Expected behavior

```console
yum install powershell

Powershell would then be installed
```

### Actual behavior

```console
yum install powershell

Powershell is not installed, failing validation.
```

### Error details

```console
Error: Transaction test error:
  package powershell-7.1.3-1.centos.8.x86_64 does not verify: no digest

[root@test75-rhel8 ~]# rpm --checksig -v /var/cache/dnf/packages-microsoft-com-prod-37360e73ce94b4be/packages/powershell-7.1.3-1.centos.8.x86_64.rpm
/var/cache/dnf/packages-microsoft-com-prod-37360e73ce94b4be/packages/powershell-7.1.3-1.centos.8.x86_64.rpm:
    Header V4 RSA/SHA256 Signature, key ID be1229cf: OK
    Header SHA1 digest: OK
    Payload SHA256 digest: NOTFOUND
    V4 RSA/SHA256 Signature, key ID be1229cf: OK
    MD5 digest: NOTFOUND
```

### Environment data

```powershell
Redhat Enterprise Linux v8+ or CentOS v8+ when running in FIPS mode
```

### Visuals

Capture

### PR DESCRIPTION
**Pull request by ngharo**
Set the RPM digest algorithm to SHA256 when distribution target is Red Hat.

## PR Context

fpm is used to build the rpm package. By default, the rpm digest will use md5. md5 is _not_ FIPS compliant. If I specify sha256 as an option during the build I am able to install correctly.

Fixes #15866

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None that I'm aware of
- **User-facing changes**
    - [x] Not Applicable
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]

**Comment by vanlinnj** [comment]
Subscribing to this PR for updates.

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
@ngharo Thank you for fixing this.

**Comment by TravisEz13** [comment]
windows packaging failures are unrelated

**Pull request merged**
