### PR TITLE
Enable SA1001: Commas should be spaced correctly

### PR DESCRIPTION
**Pull request by xtqqczze**
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1001.md

### CODE REVIEW

**Comment by xtqqczze** [comment]
@iSazonov Could you please reopen?

**Comment by iSazonov** [comment]
> @iSazonov Could you please reopen?

Done. Please resolve merge conflicts.

**Review by iSazonov — APPROVED** [review]

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
Please rebase from master and resolve conflicts

**Comment by xtqqczze** [comment]
rebased

**Comment by xtqqczze** [comment]
Test failures on **PowerShell-CI-linux**:

```log
Check failure on line 1 in Test-Connection.Ping.Force IPv4 with implicit PingOptions
Check failure on line 1 in Test-Connection.MTUSizeDetect.MTUSizeDetect works
```

**Comment by TravisEz13** [comment]
Please seperate the changes to the remoting code base, so we can get a clear CI run.

**Comment by TravisEz13** [comment]
@PoshChan  Please remind me in 1 day

**Comment by xtqqczze** [comment]
> Please seperate the changes to the remoting code base, so we can get a clear CI run.

I tried to do this in afc5cb15cffc02a32ea0130f15d02860e7345138, but it was easier to rebase :)

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 1 day ago

**Review by TravisEz13 — APPROVED** [review]

**Comment by hacker8-eng** [comment]
Oi

**Pull request merged**
