### PR TITLE
Add script to create icns files.

### LINKED ISSUE #7455: Create automated way to create macOS icon.
Currently the macOS icon is create manually. This should be scripted out and use the SVG icon files.

### PR DESCRIPTION
**Pull request by thezim**
## PR Summary

Add script to generate macOS icon file. It does not attempt to integrate with the current build process as the macOS icon file is mostly static.

`libsvg` was chosen because of its low dependency count over other solutions that use backends like Chromium, PhontomJS, etc. ImageMagick's `convert` was tested but resulting PNGs where not satisfactory and would have required an overcomplicated script having to calculate the `density` argument.

* Has a dependency on librsvg (can be installed via Brew)
* Uses SVG file as input
* Can be integrated in later to build process if desired

Closes #7455

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by TravisEz13** [comment]
Does this need to be in our repo?  This will take a significant about of time to review due to the use of `librsvg`

**Comment by thezim** [comment]
@TravisEz13 The intent was to have the knowledge in this repo in case someone else needed to generate the `icns` files for the project due to an icon asset change.

**Comment by TravisEz13** [comment]
It's probably the right thing to do.  The tool uses a GPL license and will take some time to get approval to use the tool.

**Comment by TravisEz13** [comment]
Sorry, still waiting on the review here.

**Comment by anmenaga** [comment]
@TravisEz13 how do we currently generate macOS icon file?

**Comment by thezim** [comment]
@anmenaga I generated both of the current ones. This was a manual process. Export PNGs from the SVG to proper names and resolutions, then use `iconutil` assemble the asset.

**Comment by TravisEz13** [comment]
Yup, I just checked the internal review and it is still ongoing.

**Comment by TravisEz13** [comment]
Sorry, still in review

**Comment by TravisEz13** [comment]
Sorry, still in review

**Comment by thezim** [comment]
@TravisEz13  done.

**Review by TravisEz13 — APPROVED** [review]

**Pull request merged**
