### PR TITLE
Change `PSManageBreakpointsInRunspace` to be non-Experimental

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

Remove code that made this an Experimental Feature and updated tests.

## PR Context

@PowerShell/powershell-committee agreed to take this feature out of Experimental: https://github.com/PowerShell/PowerShell/issues/13406

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/6560
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]

**Comment by daxian-dbw** [comment]
@SteveL-MSFT please rebase your branch.

**Comment by TylerLeonhardt** [comment]
I'm not sure I feel comfortable with moving this out of experimental in light of some of the odd behavior Justin was seeing in his codespaces demo which happened with PowerShell 7 console debugging.

**Comment by anmenaga** [comment]
@SteveL-MSFT Is `PowerShell-CI-windows` failing expected?

**Comment by daxian-dbw** [comment]
@TylerLeonhardt Can you please open an issue to track the odd behavior you and Justin observed?

**Comment by TylerLeonhardt** [comment]
@daxian-dbw I've opened this issue: https://github.com/PowerShell/PowerShell/issues/13567 the gist is, we (probably I) broke the behavior way back for PS7. We probably shouldn't have a `-BreakAll` on `Debug-Runspace` but rather a `NoBreakAll` or similar to maintain backcompat.

**Review by PaulHigin — APPROVED** [review]
I think we can address any issues as they arise.

**Comment by SteveL-MSFT** [comment]
Reassinging as Andrew is out right now

**Comment by adityapatwardhan** [comment]
Re-running CI tests

**Comment by SteveL-MSFT** [comment]
Fixed via https://github.com/PowerShell/PowerShell/pull/15864

**Pull request closed without merging**
