### PR TITLE
WIP: Don't merge this is just a test

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-macos

**Comment by SteveL-MSFT** [comment]
I see in the logs a number of people trying to interact with @PoshChan, it's hardcoded currently to only respond to my commands :)

**Comment by vexx32** [comment]
@SteveL-MSFT you can't keep _all_ the fun to yourself forever 😉

**Comment by SteveL-MSFT** [comment]
@vexx32 Don't worry, PoshChan is OSS, just not ready for public consumption yet.  It's built on PowerShell and Azure Functions.  What I'm trying to fix right now is getting it to successfully call the AzDevOps API to trigger a rebuild.

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-macos

**Comment by SteveL-MSFT** [comment]
@PoshChan Please build PowerShell-CI-windows

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-windows

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-macos

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-macos

**Comment by SteveL-MSFT** [comment]
@PoshChan write something

**Comment by SteveL-MSFT** [comment]
@PoshChan say somthing

**Comment by SteveL-MSFT** [comment]
@PoshChan are you there?

**Comment by SteveL-MSFT** [comment]
@PoshChan testing 1.2.3

**Comment by PoshChan** [comment]
I do not understand: testing 1.2.3

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-macos

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-windows

**Comment by PoshChan** [comment]
Started rebuild of `PowerShell-CI-windows`

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-linux

**Comment by PoshChan** [comment]
SteveL-MSFT, started rebuild of `PowerShell-CI-linux`

**Comment by vexx32** [comment]
@SteveL-MSFT is it too late for `PwshChan`? 😂

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-macos

**Comment by PoshChan** [comment]
@SteveL-MSFT, started rebuild of `PowerShell-CI-macos`

**Comment by romero126** [comment]
I thought pwsh was what the powershell team was moving forward with. Wouldn't posh Chan be inconsistent with the desire to push PWSH moving forward? @SteveL-MSFT

**Comment by SteveL-MSFT** [comment]
`PoshChan` is the name the community has already given to the avatar character, so the name is just a play on that.  I believe we've said that `pwsh` is pronounced `posh`, so `PwshChan` would work as well.

**Comment by vexx32** [comment]
🤔 I wasn't there for the pronunciation pronouncement, so I've been pronouncing it `push` 😂

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-macos

**Comment by PoshChan** [comment]
@SteveL-MSFT, started rebuild of `PowerShell-CI-macos`

**Comment by romero126** [comment]
Honestly I thought it was pronounced  p-wish so your not the only one 🤣🤣🤣

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-linux

**Comment by PoshChan** [comment]
@SteveL-MSFT, started rebuild of `PowerShell-CI-linux`

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild PowerShell-CI-macos

**Comment by PoshChan** [comment]
@SteveL-MSFT, started rebuild of `PowerShell-CI-macos`

**Comment by SteveL-MSFT** [comment]
@PoshChan say something

**Comment by PoshChan** [comment]
@SteveL-MSFT, I do not understand: say something

**Comment by SteveL-MSFT** [comment]
Closing this for now as I don't have time to continue working on this right now.  Plan is to get ability for maintainers to initiate a feature or package run without requesting the author to push a new commit.

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild macos,linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild macos,linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild macos, linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild macos, linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild windows,linux

**Comment by SteveL-MSFT** [comment]
@PoshChan Please rebuild macos,linux

**Comment by PoshChan** [comment]
@SteveL-MSFT, started rebuild of `PowerShell-CI-macos`

**Comment by PoshChan** [comment]
@SteveL-MSFT, started rebuild of `PowerShell-CI-linux`

**Comment by SteveL-MSFT** [comment]
@PoshChan Please remind me in 5 minutes

**Comment by SteveL-MSFT** [comment]
@PoshChan Please remind me in 1 minute

**Comment by PoshChan** [comment]
@SteveL-MSFT, will remind you in 60 minute

**Comment by PoshChan** [comment]
@SteveL-MSFT, this is the reminder you requested

**Comment by SteveL-MSFT** [comment]
@PoshChan Please remind me in 5 minutes

**Comment by PoshChan** [comment]
@SteveL-MSFT, will remind you in 5 minutes

**Comment by PoshChan** [comment]
@SteveL-MSFT, this is the reminder you requested 5 minutes ago

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, linux, all

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild linux,all

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild linux,all

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild linux,all

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild linux,all

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild linux,all

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild linux,all

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild linux,all

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild linux,all

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild linux,all

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild linux,all

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
Did not find matching build context: ` all`\r\nAllowed contexts:\r\n

**Comment by PoshChan-Staging** [comment]
Did not find matching build context: `macos`\r\nAllowed contexts:\r\n

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
Did not find matching build context: `macos`\r\nAllowed contexts:\r\n

**Comment by PoshChan-Staging** [comment]
Did not find matching build context: ` all`\r\nAllowed contexts:\r\n

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, could not find `buildId` in \u0027\u0027

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, could not find build at \u0027https://dev.azure.com//PowerShell/_apis/build/builds/?api-version=5.0\u0027

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, did not find matching build context: `Project_CI_macOS`\\r\\nAllowed contexts:\\r\\n

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, did not find matching build context: `Project_CI_macOS`\u003cbr/\u003eAllowed contexts:\u003cbr/\u003e

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, did not find matching build context: `Project_CI_macOS`; Allowed contexts:

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, did not find matching build context: `Project_CI_macOS`; Allowed contexts:

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, did not find matching build context: `Project_CI_macOS`; Allowed contexts:

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, I do not understand the build target(s) \u0027 all\u0027; I only allow `linux`,`all`,`staging`,`macos`,`windows`

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, I do not understand the build target(s) `macos, all`; I only allow `IsReadOnly`,`IsFixedSize`,`IsSynchronized`,`Keys`,`Values`,`SyncRoot`,`Count`

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, did not find matching build context: `Project_CI_macOS PowerShell-CI-static-analysis Project_CI_windows Project_CI_Linux`; allowed contexts:

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, did not find matching build context: `Project_CI_macOS`; allowed contexts:

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, did not find any matching pull request statuses

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, did not find matching build context: `Project_CI_macOS`; allowed contexts: @{context=PowerShell-CI-windows},@{context=PowerShell-CI-linux},@{context=PowerShell-CI-macos},@{context=PowerShell-CI-static-analysis},@{context=PowerShell-CI-install-ps}

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, did not find matching build context: `Project_CI_macOS`; allowed contexts: PowerShell-CI-windows,PowerShell-CI-linux,PowerShell-CI-macos,PowerShell-CI-static-analysis,PowerShell-CI-install-ps

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, linux

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, did not find matching build context: `PowerShell_CI_macOS`; allowed contexts: PowerShell-CI-windows,PowerShell-CI-linux,PowerShell-CI-macos,PowerShell-CI-static-analysis,PowerShell-CI-install-ps

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, linux

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, failed to start rebuild of `PowerShell-CI-macOS`

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, linux

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, failed to start rebuild of `PowerShell-CI-macOS`, error: Invoke-RestMethod : Cannot validate argument on parameter \u0027Uri\u0027. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.\r\nAt D:\\home\\site\\wwwroot\\AzDevOps-Rebuild\\run.ps1:85 char:35\r\n+         $null = Invoke-RestMethod @params\r\n+                                   ~~~~~~~\r\n+ CategoryInfo          : InvalidData: (:) [Invoke-RestMethod], ParameterBindingValidationException\r\n+ FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeRestMethodCommand\r\n \r\n

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, linux

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, failed to start rebuild of `PowerShell-CI-macOS`, error: Invoke-RestMethod : Cannot validate argument on parameter \u0027Uri\u0027. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.\r\nAt D:\\home\\site\\wwwroot\\AzDevOps-Rebuild\\run.ps1:87 char:35\r\n+         $null = Invoke-RestMethod @params\r\n+                                   ~~~~~~~\r\n+ CategoryInfo          : InvalidData: (:) [Invoke-RestMethod], ParameterBindingValidationException\r\n+ FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.InvokeRestMethodCommand\r\n \r\n

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, linux

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, failed to start rebuild of `PowerShell-CI-macOS`, error: Invoke-RestMethod : {\"$id\":\"1\",\"innerException\":null,\"message\":\"Value cannot be null.\\r\\nParameter name: build.Definition\",\"typeName\":\"System.ArgumentNullException, mscorlib\",\"typeKey\":\"ArgumentNullException\",\"errorCode\":0,\"eventId\":0}\r\nAt D:\\home\\site\\wwwroot\\AzDevOps-Rebuild\\run.ps1:85 char:17\r\n+         $null = Invoke-RestMethod @params\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~\r\n+ CategoryInfo          : InvalidOperation: (Method: POST, Reque\\u2026application/json\r\n}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException\r\n+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand\r\n

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, linux

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, failed to start rebuild of `PowerShell-CI-macOS`, error: Invoke-RestMethod : {\"$id\":\"1\",\"innerException\":null,\"message\":\"Value cannot be null.\\r\\nParameter name: build.Definition\",\"typeName\":\"System.ArgumentNullException, mscorlib\",\"typeKey\":\"ArgumentNullException\",\"errorCode\":0,\"eventId\":0}\r\nAt D:\\home\\site\\wwwroot\\AzDevOps-Rebuild\\run.ps1:86 char:17\r\n+         $null = Invoke-RestMethod @params\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~\r\n+ CategoryInfo          : InvalidOperation: (Method: POST, Reque\\u2026application/json\r\n}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException\r\n+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand\r\n

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, linux

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, failed to start rebuild of `PowerShell-CI-macOS`, error: Invoke-RestMethod : {\"$id\":\"1\",\"innerException\":null,\"message\":\"Value cannot be null.\\r\\nParameter name: build.Definition\",\"typeName\":\"System.ArgumentNullException, mscorlib\",\"typeKey\":\"ArgumentNullException\",\"errorCode\":0,\"eventId\":0}\r\nAt D:\\home\\site\\wwwroot\\AzDevOps-Rebuild\\run.ps1:88 char:17\r\n+         $null = Invoke-RestMethod @params\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~\r\n+ CategoryInfo          : InvalidOperation: (Method: POST, Reque\\u2026application/json\r\n}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException\r\n+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand\r\n

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, linux

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, failed to start rebuild of `PowerShell-CI-macOS`, error: Invoke-RestMethod : {\"$id\":\"1\",\"innerException\":null,\"message\":\"Value cannot be null.\\r\\nParameter name: build.Definition\",\"typeName\":\"System.ArgumentNullException, mscorlib\",\"typeKey\":\"ArgumentNullException\",\"errorCode\":0,\"eventId\":0}\r\nAt D:\\home\\site\\wwwroot\\AzDevOps-Rebuild\\run.ps1:89 char:17\r\n+         $null = Invoke-RestMethod @params\r\n+                 ~~~~~~~~~~~~~~~~~~~~~~~~~\r\n+ CategoryInfo          : InvalidOperation: (Method: POST, Reque\\u2026application/json\r\n}:HttpRequestMessage) [Invoke-RestMethod], HttpResponseException\r\n+ FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeRestMethodCommand\r\n

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild macos, linux

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please remind me in 10 minutes

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, will remind you in 10 minutes

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, this is the reminder you requested 10 minutes ago

**Comment by SteveL-MSFT** [comment]
@PoshChan-Staging Please rebuild all

**Comment by PoshChan-Staging** [comment]
@SteveL-MSFT, successfully started rebuild of `PowerShell-CI-static-analysis, PowerShell-CI-windows, PowerShell-CI-macOS, PowerShell-CI-Linux`

**Pull request closed without merging**
