### PR TITLE
Update build and packaging modules for Alpine

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

Enable building and packaging for Alpine from within PowerShell.
Added `linux-musl-x64` runtime and `tar-musl` packaging type.
Sorted the runtimes alphabetically

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
Needs to be run with PowerShell built from https://github.com/PowerShell/PowerShell/pull/7139.  Validated resulting tar.gz pkg:

> Tests Passed: 6382, Failed: 24, Skipped: 1228, Pending: 335, Inconclusive: 0

DSC compilation tests failed, need libmi.so built for musl.  Other seemingly unrelated failures that may be due to running in a Docker container or differences with Alpine.

**Comment by adityapatwardhan** [comment]
@SteveL-MSFT  Is there a issue filed for building `libmi.so` for `musl`?

**Comment by adityapatwardhan** [comment]
Opened issue for `musl` support for `libmi.so`. https://github.com/Microsoft/omi/issues/533

**Comment by adityapatwardhan** [comment]
Filed issue to figure out Alpine Linux release #7167

**Review by adityapatwardhan — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
This will be merged after #7139

**Comment by TravisEz13** [comment]
This wouldn't allow packaging with the alpine-x64 runtime-id you used in the build PR

**Comment by adityapatwardhan** [comment]
@SteveL-MSFT  once #7139 is merged please push an empty commit with `[Package]` to test the changes to packaging.

https://github.com/PowerShell/PowerShell/blob/6ef94c1dfe912ce18f93c05ce5362bbce2284291/docs/testing-guidelines/testing-guidelines.md#validating-packaging-changes-for-a-pr

**Comment by SteveL-MSFT** [comment]
@adityapatwardhan #7139 is only used to build the initial bootstrap pwsh to be used with build.psm1.  Since a version of pwsh doesn't currently exist for linux-musl-x64, the first pkg we build will have to be done semi-manually.  Therefore #7139 doesn't directly affect this PR.

**Pull request merged**
