### PR TITLE
Update PSReadLine version to `2.1.0-rc1`

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Update PSReadLine version to `2.1.0-rc1`

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by rjmholt — APPROVED** [review]

**Comment by ThomasNieto** [comment]
Will this be in PS 7.1 RC/GA? If so, will PSReadline 2.1 be stable at that time? I don't want to have another scenario where a stable release of PowerShell has a prerelease version of PSReadline. Reason being, that it will be difficult to upgrade PSReadline to stable once it does become available. Remember all the issues with PSReadline 2.0.0-betaX in 7.0 and being unable to upgrade to 2.0.0 stable due to PSGet issues with upgrading prerelease to stable binary modules? If you do decide to go through with it, the first version of PSReadline should be 2.1.1. 😄

**Review by iSazonov — APPROVED** [review]

**Comment by doctordns** [comment]
I would assume that any final RC of PowerShell 7.1 would include only fully released versions of all modules, including PSReadline. Is that assumption valid??

**Comment by ThomasNieto** [comment]
One other question, PS 7.1 RC1 has PSReadline 2.0.4. Why are changing the PSReadline version to 2.1 during the RC instead of shipping the betas along side the previews?

```powershell
C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.0-rc.1
PSEdition                      Core
GitCommitId                    7.1.0-rc.1
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

C:\> Get-Module PSReadLine -ListAvailable

    Directory: C:\program files\powershell\7-preview\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     2.0.4                 PSReadLine                          Desk      {Get-PSReadLineKeyHandler, Set-PSReadLineKeyHandler, Remove-PSReadLineKeyHandler, Get-PSReadLineOption…}
```

**Comment by iSazonov** [comment]
> One other question, PS 7.1 RC1 has PSReadline 2.0.4. Why are we changing the PSReadline version to 2.1 during the RC instead of shipping the 2.1 betas along side the 7.1 previews?
> 

Not all users want the latest PSReadline build and prefer the familiar latest release.

**Comment by adityapatwardhan** [comment]
Please correct me if I am wrong @daxian-dbw. The plan is to ship PSReadLine 2.1.0 with 7.1 GA.

**Comment by doctordns** [comment]
w

> Please correct me if I am wrong @daxian-dbw. The plan is to ship PSReadLine 2.1.0 with 7.1 GA.

Thanks. My question was whether there would be a PowerShell 7.l RC with the GA version of PSReadline 2.l.0? Or will you just bump the module version for GA of 7.1?

**Comment by daxian-dbw** [comment]
> Please correct me if I am wrong @daxian-dbw. The plan is to ship PSReadLine 2.1.0 with 7.1 GA.

Yes, we are going to ship PS 7.1.0 GA along with PSReadLine 2.1.0.

**Comment by daxian-dbw** [comment]
> Thanks. My question was whether there would be a PowerShell 7.l RC with the GA version of PSReadline 2.l.0? Or will you just bump the module version for GA of 7.1?

There is no plan to make any changes to PSReadLine 2.1-rc1 unless there is functionality or stability regression. Shipping the PSReadLine 2.1-rc1 with PS 7.1 RC2 is a way to find those potential functionality or stability regressions. If no such issue is reported, then we will just bump the module version to 2.1 before PS 7.1 GA.

**Comment by daxian-dbw** [comment]
> Will this be in PS 7.1 RC/GA? If so, will PSReadline 2.1 be stable at that time? I don't want to have another scenario where a stable release of PowerShell has a prerelease version of PSReadline.

@ThomasNieto PS 7.1 GA will ship with the PSReadLine 2.1 GA version.

**Pull request merged**
