### PR TITLE
Replace illegal in notices container name

### PR DESCRIPTION
**Pull request by TravisEz13**
# PR Summary

Replace illegal in notices container name

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by anmenaga — APPROVED** [review]

**Review by JamesWTruher — APPROVED** [review]
lgtm

**Comment by chuckrock0095** [comment]
Sent from my LG MobileOn Apr. 14, 2022 4:45 p.m., Travis Plunk ***@***.***> wrote:PR Summary
Replace illegal in notices container name
PR Context

PR Checklist
 PR has a meaningful title
Use the present tense and imperative mood when describing your changes
 Summarized changes Make sure all .h, .cpp, .cs, .ps1 and .psm1 files have the correct copyright header This PR is ready to merge and is not Work in Progress.
If the PR is work in progress, please add the prefix WIP: or [ WIP ] to the beginning of the title (the WIP bot will keep its status check at Pending while the prefix is present) and remove the prefix when the PR is ready.
Breaking changes
 NoneOR Experimental feature(s) needed
 Experimental feature name(s): 

User-facing changes
 Not ApplicableOR Documentation needed
 Issue filed: 

Testing - New and feature
 N/A or can only be tested interactivelyOR Make sure you've added a new test if existing tests do not effectively test the code changed
Tooling
 I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.OR I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
 Impact on PowerShell Editor Services which is used in the PowerShell extension for VSCode
(which runs in a different PS Host).
 Issue filed: 
 Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
 Issue filed: 
 Impact on PSScriptAnalyzer (which provides linting & formatting in the editor extensions).
 Issue filed: 
 Impact on EditorSyntax (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
 Issue filed: 






You can view, comment on, or merge this pull request online at:
  https://github.com/PowerShell/PowerShell/pull/17154

Commit Summary
bb9b54a  Replace `.` in notices container name

File Changes  (1 file)

    M
    tools/releaseBuild/azureDevOps/templates/compliance/generateNotice.yml
    (2)
  

Patch Links:
https://github.com/PowerShell/PowerShell/pull/17154.patchhttps://github.com/PowerShell/PowerShell/pull/17154.diff

**Comment by TravisEz13** [comment]
This is in the 7.2 release which is in progress.

**Pull request merged**
