### PR TITLE
Style: Add period in summary doc tags

### PR DESCRIPTION
**Pull request by iSazonov**
## PR Summary

Style fix: Add period in summary doc tags.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by RDIL — APPROVED** [review]
Looks good to me!

**Review by daxian-dbw — APPROVED** [review]
I ran a script to validate the changes in this PR, and all look good :D Thanks @iSazonov!

---

**CheckAddingPeriod.ps1**

```
param(
    [Parameter(Mandatory=$true)]
    [string]
    $PRUrl,

    [switch]
    $PassThru
)

enum DiffState {
    None
    FileInfo
    DiffContent
}

[DiffState]$state = [DiffState]::None
$Log = @{}

$diffFile = Join-Path -Path $PSScriptRoot -ChildPath "diff.txt"
if (Test-Path -Path $diffFile) { Remove-Item -Path $diffFile -Force -ErrorAction Stop }

##
## .diff and .patch can be append in the end to get some raw content
##
$PRUrl += ".diff"
Invoke-WebRequest -Uri $PRUrl -OutFile $diffFile

$Script:ScanResult = $null
switch -Wildcard -File $diffFile
{    
    "diff --git *"
        {
            $state = [DiffState]::FileInfo
            $fileName = ($_ -split " ")[-1].Substring(2)

            if ($Script:ScanResult -ne $null -and 
                $Script:ScanResult["OriginalStrs"].Count -ne $Script:ScanResult["NewStrs"].Count)
            {
                throw "$($Script:ScanResult['FileName']) contains mismatched + and -"
            }
            
            if ($Log.ContainsKey($fileName)) 
            {
                throw "$fileName appeared twice in diff file. Something is wrong"
            }

            $Script:ScanResult = @{ FileName = $fileName; OriginalStrs = @(); NewStrs = @() }
            $Log[$fileName] = $Script:ScanResult
        }

    "@@ * @@ *"
        {
            $state = [DiffState]::DiffContent
        }

    "-*"
        {
            if ($state -eq [DiffState]::DiffContent)
            {
                $old = $_.Substring(1)
                $Script:ScanResult["OriginalStrs"] += $old
            }
        }

    "+*"
        {
            if ($state -eq [DiffState]::DiffContent)
            {
                $new = $_.Substring(1)
                $Script:ScanResult["NewStrs"] += $new
            }
        }
}


Write-Host -Object "$($Log.Count) files involved in this PR`n"

foreach ($result in $Log.Values)
{
    $newStrs = $result["NewStrs"]
    $originalStrs = $result["OriginalStrs"]

    for ($i = 0; $i -lt $originalStrs.Length; $i++)
    {
        $oldString = $originalStrs[$i]
        $newString = $newStrs[$i]

        $afterReplace = $oldString.Trim() + "."
        $afterProcess = $newString.TrimStart()

        if (!$afterProcess.StartsWith("///") -or $afterReplace -cne $afterProcess)
        {
            Write-Error -Message @"
$($result['FileName']) - mismatch
Old: $oldString
New: $newString
"@
        }
    }
}

if ($PassThru) { return $Log }
```

**Comment by iSazonov** [comment]
@daxian-dbw You could publish the script in gist. 
Or do you hope never see so large PRs? :-)

**Comment by daxian-dbw** [comment]
The very first version of this script was published in gist years ago, at https://gist.github.com/daxian-dbw/3df8f9236a73a1d9b8c5cc913476d618
The scripts I used to validate this PR and the other one were slightly updated on top of the original one.

**Pull request merged**
