### PR TITLE
Use Unix line endings for shell scripts

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

* Specify line ending behaviour in EditorConfig like in dotnet/runtime
* Update line endings in *.sh

## PR Context

These changes fix [SC1017](https://github.com/koalaman/shellcheck/wiki/SC1017)

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [NA] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [NA] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [NA] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [NA] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [NA] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [NA] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [NA] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [NA] Issue filed: 
        - [NA] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [NA] Issue filed: 
        - [NA] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [NA] Issue filed: 
        - [NA] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [NA] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
We use `core.autocrlf=true` in git config.
https://stackoverflow.com/questions/1967370/git-replacing-lf-with-crlf

**Review by rjmholt — APPROVED** [review]

**Comment by iSazonov** [comment]
See the history https://github.com/PowerShell/PowerShell/search?q=autocrlf&type=issues
Conclusion was to delegate this to Git autocrlf

**Review by andyleejordan — APPROVED** [review]
I agree with @iSazonov that auto-crlf in Git ought to be ensuring this already happens, but I've had issues with that working 100% (you can forcibly add files, etc., it's just not perfect), so I see no harm setting this explicitly for shell scripts.

**Comment by xtqqczze** [comment]
The issue is that shell scripts should never contain `\r\n` line terminators.

https://github.com/dotnet/runtime/blob/main/.gitattributes has:
`*.sh text eol=lf`

Apparently if this was not the case there could issues if a shell script was accessed in Unix via a file share from Windows.

**Pull request merged**
