### PR TITLE
Migrating docs from source to docs repo

### PR DESCRIPTION
**Pull request by sdwheeler**
## PR Summary

The docs folder in this repo contains a lot of documentation about the PowerShell source code and build environment.
It also has contained documentation about about installing and using Powershell.
That documentation really belongs in the [PowerShell/PowerShell-Docs](https://github.com/PowerShell/PowerShell-Docs) repo.

We are in the process of migrating the user-focused article to the docs repo.
This file records which files have been migrated.

## 2018-05-18

The following files have been moved to the PowerShell/PowerShell-Docs repo.

| Original file location      | New location in PowerShell/PowerShell-Docs                               |
|-----------------------------|--------------------------------------------------------------------------|
|docs/installation/linux.md   | reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Linux.md   |
|docs/installation/macos.md   | reference/docs-conceptual/setup/Installing-PowerShell-Core-on-macOS.md   |
|docs/installation/windows.md | reference/docs-conceptual/setup/Installing-PowerShell-Core-on-Windows.md |
|docs/BREAKINGCHANGES.md      | reference/docs-conceptual/whats-new/breaking-changes-ps6.md              |
|docs/KNOWNISSUES.md          | reference/docs-conceptual/whats-new/known-issues-ps6.md                  |

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed - Issue link: https://github.com/PowerShell/PowerShell-Docs/issues/2441
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by iSazonov** [comment]
With removing the files we'll have many broken links internally and externally. Can we replace each removed file with a placeholder file with a description and link to new file?

**Comment by sdwheeler** [comment]
@iSazonov We should not be linking to docs on GitHub. We should only be linking to published docs on docs.microsoft.com. Can you provide some examples to help me understand the impact?

Also, I added a DOCSMIGRATION.md file with that information, it that not sufficient?

**Comment by sdwheeler** [comment]
@iSazonov That is another reason to not have docs like that in the source repo. In docs.microsoft.com we have a way to redirect those external links when they change. We cannot do that when the link points to GitHub.

**Comment by iSazonov** [comment]
@sdwheeler Please see the comment https://github.com/PowerShell/PowerShell/issues/6002#issuecomment-359987432
If somebody press link there he get "GitHub page not found". I'd prefer to get a page with text and link on new document place "The document was moved. See new link".

**Comment by iSazonov** [comment]
@SteveL-MSFT I assume that most of these references to documentation do not use commits. People will do this in the future too and GitHub does not block it. Actually the problem is not this. People will get the Page not found, and we can show them a page with a link to the new document location. I suppose it will be more user friendly. I don't insist if you don't see the problem.

**Comment by SteveL-MSFT** [comment]
@iSazonov seems like maybe we can use this to redirect https://help.github.com/articles/redirects-on-github-pages/ ?

**Comment by sdwheeler** [comment]
@SteveL-MSFT @iSazonov that redirection only applies to GitHub Pages published using Jekyll.

**Comment by SteveL-MSFT** [comment]
@sdwheeler too bad.  For now, I would suggest moving ahead as-is.  @iSazonov you have a valid concern and we should be more aware of that going forward if we add new docs to this repo.  If there is sufficient community feedback, we can consider putting replacement .md files that tell the user where the new documentation is.

**Comment by iSazonov** [comment]
LGTM.

**Review by adityapatwardhan — APPROVED** [review]

**Comment by bergmeister** [comment]
Not even the links of the main readme were updated...

**Comment by SteveL-MSFT** [comment]
@sdwheeler can you submit a PR to update the links on the README.md?

**Comment by sdwheeler** [comment]
@SteveL-MSFT Will do. I had a previous PR for this but it got closed. Will work on a new one.

**Comment by bergmeister** [comment]
@sdwheeler see pr https://github.com/PowerShell/PowerShell/pull/6981

**Comment by rkeithhill** [comment]
Folks, people rely on these installation instructions.  I have internal documentation that points to these links so folks know how to install PS Core.  It is **way** not cool to have these install links broken for multiple days.  :-(

**Pull request merged**
