### PR TITLE
Fix `SuspiciousContentChecker.Match` to detect a pre-defined string when the text starts with it

### PR DESCRIPTION
**Pull request by daxian-dbw**
## PR Summary

Fix `SuspiciousContentChecker.Match` to detect a pre-defined string when the text starts with it.

## PR Context

The method `SuspiciousContentChecker.Match` has a flaw: when the text starts with a string that is defined in `LookupHash(uint h)`, it cannot detect the string.

```
PS:1> $t = [psobject].Assembly.GetType('System.Management.Automation.ScriptBlock+SuspiciousContentChecker')
PS:2> $t::Match("Add-Type") -eq $null
True
PS:3> $t::Match(" Add-Type")      ## it can detect the string when text doesn't start with it.
Add-Type
```
**NOTE:** The `SuspiciousContentChecker.Match` check is a defense-and-depth thing, so this bug is **NOT** a security vulnerability.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Review by iSazonov — COMMENTED** [review]
Since we take into account only ASCII chars and `-` I suggest adding more tests with using specific chars - ASCII non-letters, Unicode, surrogates in different positions in prefix, in word, in suffix. 
Also now we check start position and I'd expect we check the transition for the 19th position too.

And maybe xUnit test would be more fast for the internal API (also exclude reflection - it is not good for public test) .

**Comment by daxian-dbw** [comment]
After chatting with @TravisEz13, my understanding is that this defense-and-depth feature is sort of broken (high chance of collision) and it was decided to not fix it. So, adding more tests for it doesn't seem worth the effort in my opinion.

But I'm totally open to add more tests. What do you mean by "we check start position and I'd expect we check the transition for the 19th position too"? Can you provide an example string that you want to be added to the tests?

About xUnit test, I don't think it's necessary unless it turns out to be hard to test some specific characters. PowerShell has the `` `u{xxx}`` syntax for representing Unicode characters, so we should be fine using Pester with a tiny bit of reflection.

**Review by TravisEz13 — APPROVED** [review]

**Comment by iSazonov** [comment]
> But I'm totally open to add some more tests. What do you mean by `"we check start position and I'd expect we check the transition for the 19th position too"`? Can you provide an example string that you want to be added to the tests?

Sorry, typo, 29th - max word size. So a test could check starting with 30th position.
I ask about tests with non-ASCII chars based on your comment in my PR.

> After chatting with @TravisEz13, my understanding is that this defense-and-depth feature is sort of broken (high chance of collision) and it was decided to not fix it. So, adding more tests for it doesn't seem worth the effort in my opinion.

We could reduce collisions with simple trick - take into account word length.

**Comment by daxian-dbw** [comment]
I have added the requested tests. But be noted that, those are just smoke tests, and are by no means intended for covering the `Match` implementation.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
LGTM.

**Pull request merged**
