### PR TITLE
Make sure GA revision increases from RC/Preview releases

### PR DESCRIPTION
**Pull request by TravisEz13**
# PR Summary

Make sure GA revision increases from RC/Preview releases
- Fix revision to 500 for all GA releases
- Add tests to verify expected revisions

## PR Context

Make sure GA revision increases from RC/Preview releases. 
This allows SDK builds using preview to work against GA builds.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by adityapatwardhan** [comment]
@TravisEz13 The nuget packages use the release tag to set the version for the package. Also, it is used to set the version of the ref assembly. That needs to be fixed too. Is that change happening in a different PR?

**Comment by TravisEz13** [comment]
@adityapatwardhan The NuGet package needs to start using the runtime DLL, per yesterday's conversation.  If we don't go down that path, I think the right thing to do is to read the `fileversion` from the runtime and use that.

**Review by daxian-dbw — APPROVED** [review]

**Review by anmenaga — APPROVED** [review]
For PR that only scoped to versioning numbers update - LGTM.

**Comment by adityapatwardhan** [comment]
@TravisEz13 are you adding the change we discussed about the nuget ref assembly using the file version?

**Comment by adityapatwardhan** [comment]
@TravisEz13  and me also discussed about using the runtime assembly for the ref, but there are some complications regarding it.

1. Which runtime assembly do we use, windows or linux?
2. Should the assemblies just be under `lib` folder? But, I believe `lib` does not support having RID under it. 
3. Can we just have `runtime` folder? Will the appropriate assembly be picked for compilation?

**Comment by daxian-dbw** [comment]
Here are my opinions:
> Which runtime assembly do we use, windows or linux?

Be consistent with the existing NuGet package, we should use the Unix version of the runtime DLL.
It's not the ideal solution for sure, but should be fine as a temp workaround.

> Should the assemblies just be under lib folder? But, I believe lib does not support having RID under it.

I guess for now we can just replace the ref assembly with the runtime assembly and keep the folder structure unchanged.

> Can we just have runtime folder? Will the appropriate assembly be picked for compilation?

I don't think the runtime folder alone would work.

**Comment by TravisEz13** [comment]
I think this PR is ready to merge.  Is there anything we are waiting on?

**Pull request merged**
