### PR TITLE
Update Arch Linux installation instructions

### PR DESCRIPTION
**Pull request by kylesferrazza**
Update arch linux installation instructions to reflect the new powershell-bin package, and the differences in the various ways of installing/building through the AUR.

### CODE REVIEW

**Comment by TravisEz13** [comment]
@kylesferrazza   I added a docker file to build based on the `powershell-bin` package and referenced it as an example in the instructions.  I suspect we need to add more packages to the image for things like SSL support, but this should be a good start.  Please review

**Comment by kylesferrazza** [comment]
The dockerfile looks great! Just built the image and it worked perfectly.

**Comment by TravisEz13** [comment]
I just merged the fix for the macOS image.

**Comment by TravisEz13** [comment]
I restarted Travis-ci which **should** pick up the macOS change.

**Comment by kylesferrazza** [comment]
Looks good, all the tests passed.

**Review by TravisEz13 — APPROVED** [review]

**Pull request merged**
