### PR TITLE
Fix erroneous assert

### PR DESCRIPTION
**Pull request by tamasvajk**

### CODE REVIEW

**Review by PaulHigin — CHANGES_REQUESTED** [review]
I prefer the original fix.  It is more readable than the with null coalescing.

**Comment by tamasvajk** [comment]
@PaulHigin I don't mind reverting the second commit, but I'm unsure who makes the final decision in this, and I'd like to avoid going back and forth between the two variants. Is it @iSazonov who decides in the end?

**Comment by iSazonov** [comment]
@tamasvajk I like first commit more too as more readable in the assert context.

**Comment by tamasvajk** [comment]
@iSazonov thank you for the confirmation. I reverted the second commit.

**Review by iSazonov — APPROVED** [review]

**Review by PaulHigin — APPROVED** [review]

**Comment by iSazonov** [comment]
@tamasvajk Thanks for your contribution!

**Pull request merged**
