### PR TITLE
Fix Markdown lint issues

### PR DESCRIPTION
**Pull request by TravisEz13**
- Make heading styles consistent
- Make heading names unique (make anchors usable)
- Make sure there are line breaks around element which require them
- remove trailing spaces
- Don't use emphasis as a heading
- make sure code blocks declare what language is used

cc @PowerShell/area-documentation

### CODE REVIEW

**Comment by TravisEz13** [comment]
Fixing syntax issues revealed more spelling issue.  I have fixed those.

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Comment by andschwa** [comment]
Why are we changing the headings? IMHO `===` and `---` look _so much more_ readable when editing source.

**Comment by TravisEz13** [comment]
The `====` and `---` styles only allow two levels of heading past that you must use the other style.  So using this style promotes inconsistency.  It leads to other issues such as people using emphasis instead of headings if people are not aware of the other style.  Not following proper markdown syntax can lead to some parsers not being able to parse the document.  This is shown as I made syntax fixes the Travis-CI spelling checking found more spelling fixes.

**Comment by TravisEz13** [comment]
restarting Linux due to a MyGet failure

**Comment by TravisEz13** [comment]
Also, this is a small preparation for #838 to work out these type of issues.

**Comment by TravisEz13** [comment]
Another example, in `windows.md` we use the same level of the headers, but of different styles, that appear to be nested under each other.  see https://github.com/PowerShell/PowerShell/blame/master/docs/installation/windows.md#L4

**Pull request merged**
