### PR TITLE
Enhance -split operator with RightToLeft splitting (#2)

### PR DESCRIPTION
**Pull request by IISResetMe**
This pull request adds RightToLeft support to the binary -split operator, as requested in #4765

I've added tests for negative integer input for the Max-substrings operand to work with both regex patterns and scriptblocks.

(Originally submitted as https://github.com/PowerShell/PowerShell/pull/5125, submitted anew due to completely botched rebase of the original branch)

### CODE REVIEW

**Comment by iSazonov** [comment]
@IISResetMe I see we could make some optimizations in the code. But your code works well and we can merge. What are your plans? If you want stop and merge I'll ask only some style comments.

**Comment by IISResetMe** [comment]
@iSazonov depends on the extent of your suggested optimizations :-) 

I've already included the list allocation changes from the previous PR

**Comment by iSazonov** [comment]
We can exclude `buf` StringBuilder using Append(String, In32, Int32) overload.
We can exclude  many `if (rightToLeft)`.
We can explude many Reverse().

**Comment by IISResetMe** [comment]
@iSazonov I've already removed the `StringBuilder` instance in favor of `List<char>`, but I think I've found a way to simplify the code and avoid most of the `if(rightToLeft)` branches. I'll fiddle with it and push changes tonight

**Comment by IISResetMe** [comment]
CLosing this for now to avoid too many merge conflicts, will resubmit a new PR when I find the time

**Pull request closed without merging**
