### PR TITLE
Add more users to PoshChan failures detection and fix alias for static analysis

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

Adding more users (MVPs and regular contributors) to allow use of the automatic CI failures response from PoshChan (and allow requesting failures) since it seems to be working ok to get more feedback.  Also fix the alias for static runs to `static`.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Review by adityapatwardhan — APPROVED** [review]

**Comment by vexx32** [comment]
@SteveL-MSFT you may want to add either a MD help doc or a template response for PoshChan for folks to use who are forgetful with the list of accepted commands and/or aliases so someone could e.g, `<@>PoshChan please help` or something

**Comment by SteveL-MSFT** [comment]
@vexx32 great suggestion, can you create an issue in https://github.com/SteveL-MSFT/PoshChan-Bot?

**Comment by SteveL-MSFT** [comment]
@PoshChan help @vexx32

**Comment by PoshChan** [comment]
@SteveL-MSFT, all requests start with the magic word: `Please`
Commands available in this repo for you:
  - `retry <target>` this will attempt to retry only the failed jobs for the target pipeline
  - `rebuild <target>` this will perform a complete rebuild of the target pipeline, `rerun` can be used in place of `rebuild`
    Supported values for \<target\> which can be a comma separated list are: `staging`,`windows`,`macos`,`linux`,`all`
  - `get failures` this will attempt to get the latest failures for all of the target pipelines
  - `remind me in <value> <units>` this will create a reminder that will be posted after the specified duration
    \<value\> is a number, and \<units\> can be `minutes`, `hours`, or `days` (singular or plural)

**Review by adityapatwardhan — APPROVED** [review]

**Pull request merged**
