### PR TITLE
[Windows] Rework start menu folder name

### LINKED ISSUE #5884: start menu folder includes version number
I installed the 6.0 release and the start menu folder that is created is called `PowerShell-6.0.0` will the folder name change with future versions? Is this because side-by-side installs are possible? Wouldn't it be better to just have it called `PowerShell 6`? The dash makes it look a bit weird as well.

### PR DESCRIPTION
**Pull request by Stanzilla**
## PR Summary

Changes the Windows start menu folder name from `ProductSemanticVersionWithName` to `ProductSemanticVersionWithNameAndOptionalArchitecture` as discussed in https://github.com/PowerShell/PowerShell/issues/5884.

Fix #5884 

Before:
explorer_2018-01-13_00-55-39

After: 
explorer_2018-01-13_00-58-43

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [x] Issue filed - Issue link: https://github.com/PowerShell/PowerShell/issues/5884
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

### CODE REVIEW

**Comment by bergmeister** [comment]
Thanks and welcome to the PowerShell Open Source community .You can tick the `Issue filed` checkbox. Also, if you add e.g. the word 'fix' before the issue number in the summary, your issue will get closed automatically upon completion of this PR (I learnt this myself only recently from others, see [here](https://help.github.com/articles/closing-issues-using-keywords/))

**Comment by bergmeister** [comment]
OK. I have downloaded and installed it and it looks now like that as expected (i.e. to hypen in the folder name):
image
You can do this also yourself if you want to: Just click on 'Details' besides the appveyor check, then click on 'Artifacts' and here you can download the msi from your PR.

**Comment by Stanzilla** [comment]
Hrm, wouldn't it be better if the folder itself was just called `PowerShell` and all side by side installs just add a shortcut that has their version number to that folder?

**Review by bergmeister — APPROVED** [review]

**Comment by bergmeister** [comment]
Given that 6.0 has already shipped, maintainers might disagree with the 'common root folder approach' but your suggestion is certainly worth (another) discussion. Therefore I approve this change but let's discuss the other option in a separate issue.

**Comment by bergmeister** [comment]
OK. We are ready to go. All we have to do is wait for maintainers to respond and review.

**Review by bergmeister — CHANGES_REQUESTED** [review]
@Stanzilla I had another think and I think we have chosen the wrong property to replace it with because in the case of the x86 installer, the folder name would then also end in in " x86" (therefore we would not have a common folder for x64 and x86 any more). Sorry. Please change the line to:
`<Directory Id="ApplicationProgramsFolder" Name="$(var.ProductName) $(env.ProductSemanticVersion)">`

**Comment by iSazonov** [comment]
I am fine to rename the start folder name to `PowerShell` without version. I think we don't confuse users and don't break anything.
@SteveL-MSFT Thoughts?

**Comment by Stanzilla** [comment]
@bergmeister are you ok with this after my changes?

**Comment by bergmeister** [comment]
@Stanzilla I as a community contributor cannot merge a PR or make the final decision on it. I myself only happen to be a very active community member and I happen to have made a lot of installer features, improvements and fixes recently. Therefore I can only say it is OK from a code perspective but it needs product management approval from the MS side.  Personally, I think it is a change for the better moving forward but there is this downside that when 6.0 and 6.1 are installed that it will look a bit odd...
The guys at MS were quite busy releasing the 6.0.1 patch this week therefore if you don't get an answer by the end of next week, then let's ping Steve and he usually gets stuff sorted quite quickly. In the meantime enjoy using your custom version of PowerShell :-)

**Comment by iSazonov** [comment]
@bergmeister If you are ok with the PR please change status to approve.

**Review by bergmeister — APPROVED** [review]

**Comment by iSazonov** [comment]
@SteveL-MSFT Could you please review?

**Comment by SteveL-MSFT** [comment]
I'm ok with the proposed changes.  However, I would like @joeyaiello as the PM to make the call here.

**Comment by iSazonov** [comment]
@SteveL-MSFT @joeyaiello What is your conclusion?

**Comment by joeyaiello** [comment]
I love the shared folder approach, looks great. 👍 

Thanks for the contribution, @Stanzilla!

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by iSazonov** [comment]
Please clarify - I see 
ps-menu

Is that what we want?

**Comment by Stanzilla** [comment]
@iSazonov I was actually already thinking about mentioning that but I could not come up with a better solution yet. Are side-by-side installations actually possible? So far the installer always overwrote my current installation. One solution here would be to do:

PowerShell >
	Open here (6.1.0-preview.7604)
	Open here as Administrator (6.1.0-preview.7604)
	Open here (6.1.0)
	Open here as Administrator (6.1.0)


But that gets really long...

**Comment by bergmeister** [comment]
@stanzilla: that is because you need to also change the minor version to have side by side. I can do some mockups but at the moment I am concerned that there might not be enough space in the submenu for preview versions.
The bigger concern is that it could make the root registry not unique any more in case someone has already defined a context menu named "PowerShell" (e.g. for Windows PowerShell)

**Comment by bergmeister** [comment]
I was also thinking about rather using 'PowerShell Core' for the top sub menu (in the start menu and explorer context menu) to avoid ambiguity but that might bite us in later version when PowerShell Core will replace Windows PowerShell (in the far future)

**Comment by iSazonov** [comment]
>But that gets really long...

We should consider only release versions - they have short names.

>The bigger concern is that it could make the root registry not unique any more in case someone has already defined a context menu named "PowerShell" (e.g. for Windows PowerShell)

The same is true for Start menu but we don't concern about it (this already was approved).

I see other products (7zip, WinRar) use unified name in folder menu.

**Comment by bergmeister** [comment]
@iSazonov Fair points, but:
> The same is true for Start menu but we don't concern about it (this already was approved).

The difference is that the start menu because it is represented by a directory where we would just create a shortcut in an already existing directory if there was already a start menu entry called 'PowerShell'. The explorer context menu is however represented by a registry entry where we could clash and override the existing entry.

**Comment by iSazonov** [comment]
@bergmeister Do you know the examples for "PowerShell"?

**Comment by iSazonov** [comment]
It is HowTo. I meant popular projects with which there might be a conflict.

**Pull request merged**
