### PR TITLE
One step closer to build a fully-functional FullCLR PS

### PR DESCRIPTION
**Pull request by vors**
-  Add majority of missed files
-  Add guards
-  Add a local nuget feed for Microsoft.WSMan.Management and Microsoft.mshtml references

### CODE REVIEW

**Comment by masaeedu** [comment]
I'm struggling to get started with the Powershell SDK in a project targeting NET461 and found this issue due to the "add a local nuget feed for Microsoft.WSMan.Management and Microsoft.mshtml references" note you added. I found the `Microsoft.mshtml` package in [your feed](https://powershell.myget.org/gallery/powershell-core), but I don't know where to look for `Microsoft.WSMan.Management`. My project.json currently looks like this:

```
{
  "version": "1.0.0-*",

  "dependencies": {
    "Microsoft.PowerShell.SDK": "1.0.0-alpha9"
  },

  "frameworks": {
    "net461": {
      "imports": "dnxcore50",
      "frameworkAssemblies": {
      }
    }
  }
}
```

Are there any official docs on using the Powershell SDK in full framework projects?

**Comment by andschwa** [comment]
@masaeedu Just because I have to say: we're not supporting FullCLR builds whatsoever. The open-source PowerShell project is for PowerShell on CoreCLR.

Anyway, let's see what we can do. While I know we had a Microsoft.WSMan.Management package in our previous (private) feed, I'm not seeing it in our new (public) [powershell-core MyGet feed](https://powershell.myget.org/gallery/powershell-core/). @daxian-dbw do you konw what happened to Microsoft.WSMan.Management?

@masaeedu I'm also not seeing a direct dependency on Microsoft.WSMan.Management from Microsoft.PowerShell.SDK. Can you post your `project.lock.json` file?

**Comment by masaeedu** [comment]
> Just because I have to say: we're not supporting FullCLR builds whatsoever. The open-source PowerShell project is for PowerShell on CoreCLR.

I appreciate you going above and beyond :). Unfortunately we haven't managed to port everything to `netstandard` just yet, so some mixed projects have to use `net461`.

> I'm also not seeing a direct dependency on Microsoft.WSMan.Management from Microsoft.PowerShell.SDK. Can you post your project.lock.json file?

It isn't a direct dependency, the dependency is Microsoft.PowerShell.SDK -> Microsoft.PowerShell.Commands.Management -> Microsoft.WSMan.Management. Here's my lock json:

**Comment by andschwa** [comment]
Ah, I think I know what happened. We quit depending on Microsoft.WSMan.Management as a package and instead build it from source as a project in `src/Microsoft.WSMan.Management`.

@daxian-dbw we'll probably need to build and publish Microsoft.WSMan.Management as a package.

@masaeedu what you can do in the meantime is build the package yourself; a `dotnet pack --version-suffix alpha9` in that directory *ought* to create the package (with the correct version). Then there's the matter of getting `dotnet restore` to find it, which should just amount to adding a new feed in your `nuget.config` that points to a local folder and sticking the package there.

**Comment by daxian-dbw** [comment]
Indeed. Microsoft.PowerShell.Commands.Management for net451 depends on Microsoft.WSMan.Management, but the latter is not published. Issue #2065 was opened to track the fix.

**Pull request merged**
