### PR TITLE
Remove 'out' in ReadConsole pinvoke

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Revert change based on the comment https://github.com/PowerShell/PowerShell/pull/8847#discussion_r262645497

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by daxian-dbw** [comment]
Look goo to me.
Can you please update this signature as well: https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/namespaces/FileSystemProvider.cs#L7082

Should be changed from `[return: MarshalAs(UnmanagedType.I1)]` to `[return: MarshalAs(UnmanagedType.Bool)]`.

**Comment by jazzdelightsme** [comment]
@daxian-dbw : No! `CreateSymbolicLinkW` really does return a 1-byte boolean value. (`BOOLEAN` versus `BOOL`).

**Comment by daxian-dbw** [comment]
@jazzdelightsme Thanks for catching that! Can you please explain a bit more about the difference between `BOOLEAN` and `BOOL` in C++?

**Comment by daxian-dbw** [comment]
Ha, I might find it -- https://stackoverflow.com/a/6420546/7129704

> BOOL is a Microsoft specific type that is defined as an int. You can find it in windef.h

**Review by daxian-dbw — APPROVED** [review]

**Comment by iSazonov** [comment]
@daxian-dbw I see in https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/interop-pinvokes.md#strings that StringBuilder marshalling always  re-allocate/re-copy buffers. Make sense review our code to reduce such allocations? Although at first glance I did not see how we could do it.

And the PR fix could be in 6.2.

**Comment by daxian-dbw** [comment]
Thanks @iSazonov. By reading that guideline, it seems `StringBuilder` should never be used for P/Invoke as it incurs 4 allocations. I think it make sense to review our uses of it and replace with `ArrayPool<char>` when appropriate, because we will copy the existing pattern when writing new code. I will take a look at this `ReadConsole` case in particular.

**Comment by iSazonov** [comment]
Tracking issue #9139

> I will take a look at this ReadConsole case in particular.

Please review my old PR first - it is related :-)

**Comment by daxian-dbw** [comment]
@iSazonov We are using `StringBuilder` for the `[out] string` parameter in P/Invoke almost everywhere.

**Pull request merged**
