### PR TITLE
support for linuxmint in installpsh-debian.sh

### PR DESCRIPTION
**Pull request by DarwinJS**
## PR Summary

Add #8437 - add linuxmint support

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
- **Testing - New and feature**
    - [X] Not Applicable or can only be tested interactively

### CODE REVIEW

**Comment by DarwinJS** [comment]
There is an official docker image (https://hub.docker.com/r/linuxmintd/mint19-amd64/), but do you bother with doing tests only for install scripts?

**Comment by TravisEz13** [comment]
I ran the install-ps CI here and set it to automatically run in the future:  https://powershell.visualstudio.com/PowerShell/_build/results?buildId=7894

**Review by TravisEz13 — APPROVED** [review]

**Comment by DarwinJS** [comment]
Wow that was fast - thanks!

**Comment by DarwinJS** [comment]
LinuxMint is worth it - finally a distro that does not annoy the daylights out of all my windows keyboard shortcut reflexes :)

**Comment by TravisEz13** [comment]
I like LinuxMint too, but I found macOS has the apps I need to run it full time.

**Comment by DarwinJS** [comment]
Yes - I don't use it as a primary - but for testing bash and powershell core since the rest of my team runs macs.  Although I am doing more of that with Docker as well.

**Comment by TravisEz13** [comment]
I started using https://github.com/CanonicalLtd/multipass for a lot of my testing of Linux from macOS.  This is partly because I'm testing snap packages which don't really work in docker.

**Pull request merged**
