### PR TITLE
Retrieve more info with Get-AuthenticodeSignature

### PR DESCRIPTION
**Pull request by jborean93**
# PR Summary

Adds the Signatures property to the Signature output object of
Get-AuthenticodeSignature and Set-AuthenticodeSignature. This new object
is an array of signature detail objects that contains the signing and
digest algorithm as well as the timestamp information of the signature.
It does this for all the entries in the authenticode block and not just
the first entry

## PR Context

I was trying to get this information to test out the changes in https://github.com/PowerShell/PowerShell/pull/17560 and found the `Get-AuthenticodeSignature` was lacking some of the data needed. This hopefully expands the functionality of the cmdlet and expose more data that might be useful for others.

Still need to finalise the tests and fix up a few things before I can mark this as ready.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by daxian-dbw** [comment]
Reopen PR to re-trigger the CI runs.

**Comment by iSazonov** [comment]
I'd prefer to have https://github.com/dotnet/runtime/issues/34042 :-)

**Comment by jborean93** [comment]
An issue from nearly 3 years ago with no progress + a somewhat vague request. Is that asking for cross platform support, more implementations in dotnet or something else? If this isn't wanted in PowerShell it would be great if I could put it in https://www.nuget.org/packages/Microsoft.Security.Extensions but it doesn't appear to be open source or available for contributors. Ultimately I'm hoping to add more information for `Get-AuthenticodeSignature` which includes the various signature details rather than just a general overview of the trust.

**Comment by iSazonov** [comment]
@jborean93 A lot of code exists in PowerShell only because these features are missing from the .Net Runtime and Libraries. We have already removed a lot of code as .Net went from version 1 to 7. This is the preferred path. There is not much point in repackaging the code - only the risk of regression. It is more valuable to spend this effort to extend .Net.

**Comment by jborean93** [comment]
The bulk of the code is very PowerShell specific. It's adding extra info the the return object of `Get-AuthenticodeSignature` or `Set-AuthenticodeSignature`. The only real code that is generic enough to potentially go in dotnet are the PInvoke defs that retrieve the signature byte array which yes it might be nice in dotnet but I honestly am not prepared to learn the whole development process there.

If the changes here aren't wanted in PowerShell that's fair enough, I won't add any more efforts in moving it to a ready state.

**Review by PaulHigin — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
