### PR TITLE
Fix Start-Process with -UseNewEnvironment switch

### LINKED ISSUE #3545: Start-Process fails to launch new powershell.exe instance with -UseNewEnvironment switch
Steps to reproduce
------------------
I dont know why would anyone do this, but here it goes: you cannot launch another `powershell.exe` using `Start-Process` cmdlet with `-UseNewEnvironment` switch.

Windows PowerShell:
```
Start-Process -FilePath C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoNewWindow -UseNewEnvironment
```

PowerShell Core (Debug build):
```
Start-Process -FilePath .\powershell.exe -NoNewWindow -UseNewEnvironment
```

Expected behavior
-----------------
A new instance of powershell.exe console should start.

Actual behavior
---------------
Windows PowerShell outputs error and dies:
```
Internal Windows PowerShell error.  Loading managed Windows PowerShell failed with error 8009001d.
```

PowerShell Core (Debug build) outputs more errors + assert message and dies:
```
Error resolving full path []
Error resolving full path []
PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

The shell cannot be started. A failure occurred during initialization:
ASSERT: caller makes sure it's not null or empty
```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.0.0-alpha
GitCommitId                    v6.0.0-alpha.18-9-g8d4db01a5d4b5dcd981ef216d3d7f24b484c7c60-dirty
WSManStackVersion              3.0
CLRVersion
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
PSEdition                      Core
SerializationVersion           1.1.0.1
```

### PR DESCRIPTION
**Pull request by iSazonov**
Fixed #3545.

I fixed by restore "ProgramFiles" and "ProgramFiles(X86)"environment variables for subprocess.
I don't understand how PowerShell use it in start time and perhaps my fix is not in right place.

### CODE REVIEW

**Comment by JamesWTruher** [comment]
this needs at least 1 test for validation unless a test already exists.

**Comment by daxian-dbw** [comment]
This probably is not the right fix, what if I'm starting an application which is not powershell and I really would like no environment variable at all?

I feel the right approach probably should be avoiding using environment variables in powershell as much as possible. After we move to `netcoreapp2.0`, we can use `[System.Environment]::GetFolderPath` to get most special folder paths on windows. For example, `ClrFacade.GetFileSecurityZone` uses `Environment.GetEnvironmentVariable("SystemRoot")` which can be replaced now. It seems `PSReadline` also depends on environment variables and thus I got the error `The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine`.

However, it's impossible to avoid environment variables in powershell on Unix, as `[System.Environment]::GetFolderPath` doesn't work in most cases. So I believe powershell started by `Start-Process powershell -UseNewEnvironment` on Unix platforms won't work well by design.

**Comment by iSazonov** [comment]
@daxian-dbw Thanks that confirmed my doubts!

As the latest option of this partial solution can I put a check that exactly `powershell` runs?

**Comment by daxian-dbw** [comment]
@iSazonov That feels a hack to me. I prefer to fix the issue for win-core powershell by directly removing the dependencies on environment variables -- I believe they are workarounds for `Environment.GetFolderPath` which were missing in .NET Core 1.1 and prior.

**Comment by iSazonov** [comment]
I created new Issue #3662 about avoiding using environment variables and close the PR.

**Pull request closed without merging**
