### PR TITLE
Update NetAnalyzers

### PR DESCRIPTION
**Pull request by xtqqczze**

### CODE REVIEW

**Comment by xtqqczze** [comment]
```log
Verify Markdown Links.Verify links in /home/vsts/work/1/PowerShell/docs/learning-powershell/README.md.https://www.manning.com/books/learn-powershell-in-a-month-of-lunches → Status: 503 should work
Failed to complete request to "https://www.manning.com/books/learn-powershell-in-a-month-of-lunches → Status: 503". NotFound Response status code does not indicate success: 404 ().
```

**Comment by xtqqczze** [comment]
PowerShell-CI-static-analysis failures are unrelated.

**Comment by iSazonov** [comment]
Already updated by dependabot.

**Comment by xtqqczze** [comment]
@iSazonov Thanks, I didn't know dependbot was monitoring this.

**Pull request closed without merging**
