### PR TITLE
Use CIM cmdlets instead of WMI cmdlets in tests

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

* Replace WMI cmdlets with CIM cmdlets
* Refactor OrderedAttributeForHashTables test
* Use [New-CimInstance ClientOnly parameter](https://docs.microsoft.com/en-us/powershell/module/cimcmdlets/new-ciminstance?view=powershell-6#parameters) where possible.

## PR Context

* WMI cmdlets were removed in PSVersion 6
* Fixes PSScriptAnalyzer rule violation [AvoidUsingWMICmdlet](https://github.com/PowerShell/PSScriptAnalyzer/blob/master/RuleDocumentation/AvoidUsingWMICmdlet.md)

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
- **User-facing changes**
    - [x] Not Applicable
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by xtqqczze** [comment]
> 2019-12-23T04:44:38.1811873Z New-CimInstance: D:\a\1\s\test\powershell\Language\Scripting\OrderedAttributeForHashTables.Tests.ps1:52
> 2019-12-23T04:44:38.1815776Z Line |
> 2019-12-23T04:44:38.1822496Z   52 |  … $script:a = New-CimInstance -ClassName Win32_Environment -Property ([ …
> 2019-12-23T04:44:38.1823774Z 
> 2019-12-23T04:44:38.1827509Z      |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 2019-12-23T04:44:38.1832703Z      | Access denied

**Comment by xtqqczze** [comment]
2019-12-27T00:53:00.2202932Z       [-] https://gitter.im/PowerShell/PowerShell?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge should work 269.56s
2019-12-27T00:53:00.2787888Z         RuntimeException: retry of URL failed with error: Response status code does not indicate success: 504 (GATEWAY_TIMEOUT).
2019-12-27T00:53:00.2790901Z         at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 117

**Comment by xtqqczze** [comment]
PowerShell-CI-static-analysis was broken by a [Gitter outage](https://gitlab.com/gitlab-com/gl-infra/infrastructure/issues/8821).

**Review by adityapatwardhan — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
@xtqqczze Thank you for your contribution!

**Pull request merged**
