### PR TITLE
move to preview4

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

Cherrypicked change to enable CI on this branch.
Update build to 3.0-Preview.4
Update versioning to 7.0.0

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by adityapatwardhan** [comment]
closing an opening the PR to trigger CI

**Comment by adityapatwardhan** [comment]
cherry-picked the change which enables CI from master and pushed to this branch.

**Comment by SteveL-MSFT** [comment]
Seems like the big blocking issue is that `Add-Type` is broken

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-static-analysis`
Verify Markdown Links.Verify links in /home/vsts/work/1/s/docs/testing-guidelines/CodeCoverageAnalysis.md.https://codecov.io/gh/PowerShell/PowerShell should work
```powershell
retry of URL failed with error: 
at <ScriptBlock>, /home/vsts/work/1/s/test/common/markdown/markdown-link.tests.ps1: line 113
113:                                 throw "retry of URL failed with error: $($_.Message)"

```

**Comment by SteveL-MSFT** [comment]
@PoshChan please retry static

**Comment by PoshChan** [comment]
@SteveL-MSFT, successfully started retry of `PowerShell-CI-static-analysis`

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 9 failures in `PowerShell-CI-macos`
(These are 5 of the failures)

Validate Update-Help from the Web for one PowerShell Core module..Validate Update-Help for module 'Microsoft.PowerShell.Core' with scope as 'False'
```powershell
Expected 1, but got 0.
at <ScriptBlock>, /Users/vsts/agent/2.150.0/work/1/s/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1: line 181
181:     $helpFilesInstalled.Count | Should -Be $expectedHelpFiles.Count
```
Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1:11 char:30
```
Validate 'Save-Help -DestinationPath for one PowerShell Core modules..Validate Save-Help for the 'Microsoft.PowerShell.Core' module
```powershell
Expected 'Microsoft.PowerShell.Core_00000000-0000-0000-0000-000000000000_en-US_HelpContent.zip', because Save-Help for  should download 'Microsoft.PowerShell.Core_00000000-0000-0000-0000-000000000000_en-US_HelpContent.zip', but got $null.
at <ScriptBlock>, /Users/vsts/agent/2.150.0/work/1/s/test/powershell/engine/Help/UpdatableHelpSystem.Tests.ps1: line 333
333:     $compressedFile | Should -Be $expectedCompressedFile -Because "Save-Help for $module should download '$expectedCompressedFile'"
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create symbolic link to file
```powershell
Expected exactly '/tmp/4dd728f4-93b7-46e4-9299-f7c773ce4676/file.txt', but got /.
at <ScriptBlock>, /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1: line 455
455:             $link.Target[0] | Should -BeExactly $real.ToString()
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create a symbolic link to nothing
```powershell
Expected '/tmp/4dd728f4-93b7-46e4-9299-f7c773ce4676/not-a-file', but got /.
at <ScriptBlock>, /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1: line 464
464:             $link.Target[0] | Should -Be $nonFile.ToString()
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 7 failures in `PowerShell-CI-linux`
(These are 5 of the failures)

Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1:11 char:30
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create symbolic link to file
```powershell
Expected exactly '/tmp/f4322734-1a63-45ca-b8f2-1b6f9b40eab3/file.txt', but got /.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1: line 455
455:             $link.Target[0] | Should -BeExactly $real.ToString()
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create a symbolic link to nothing
```powershell
Expected '/tmp/f4322734-1a63-45ca-b8f2-1b6f9b40eab3/not-a-file', but got /.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1: line 464
464:             $link.Target[0] | Should -Be $nonFile.ToString()
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create a symbolic link to a directory
```powershell
Expected exactly '/tmp/f4322734-1a63-45ca-b8f2-1b6f9b40eab3/subdir', but got /.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1: line 476
476:             $link.Target[0] | Should -BeExactly $real.ToString()
```
Measure-Object.Numeric tests.Should be able to return all the statitics for given values
```powershell
Expected strings to be the same, but they were different.
Expected length: 16
Actual length:   18
Strings differ at index 16.
Expected: '3.02765035409749'
But was:  '3.0276503540974917'
---------------------------^
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Measure-Object.Tests.ps1: line 185
185:             ($result.StandardDeviation).ToString()  | Should -Be '3.02765035409749'
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 324 failures in `PowerShell-CI-windows`
(These are 5 of the failures)

Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create symbolic link to file
```powershell
Expected exactly 'C:\Users\VSSADM~1\AppData\Local\Temp\63f2a62c-fd2a-4ea7-8e63-e734f5030708\file.txt', but got C.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\FileSystem.Tests.ps1: line 455
455:             $link.Target[0] | Should -BeExactly $real.ToString()
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create a symbolic link to nothing
```powershell
Expected 'C:\Users\VSSADM~1\AppData\Local\Temp\63f2a62c-fd2a-4ea7-8e63-e734f5030708\not-a-file', but got C.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\FileSystem.Tests.ps1: line 464
464:             $link.Target[0] | Should -Be $nonFile.ToString()
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create a directory symbolic link to a directory
```powershell
Expected exactly 'C:\Users\VSSADM~1\AppData\Local\Temp\63f2a62c-fd2a-4ea7-8e63-e734f5030708\subdir', but got C.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\FileSystem.Tests.ps1: line 486
486:             $link.Target[0] | Should -BeExactly $real.ToString()
```
Dot-source operator is not allowed in modules on locked down systems that export functions with wildcards.Verifies that a classes only module with dot-source and with using directive loads successfully
```powershell
The term 'PublicUsingFn' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Security\ConstrainedLanguageModules.Tests.ps1: line 426
426:                 $result = PublicUsingFn

```
Import trusted manifest files in system lockdown mode.Verifies that trusted manifest with nested modules and no extension module exports explicit function
```powershell
Cannot load the module 'C:\Users\VSSADM~1\AppData\Local\Temp\a232a9cf-e1dd-4967-93c0-c4b460e52cde\ImportTrustedManifestWithNestedModsAndNoExtNoFnExport_System32' because the module nesting limit has been exceeded. Modules can only be nested to 10 levels. Evaluate and change the order in which you are loading modules to prevent exceeding the nesting limit, and then try running your script again.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Security\ConstrainedLanguageModules.Tests.ps1: line 1214
1214:                 $module = Import-Module -Name $manifestFileName -Force -PassThru

```

**Comment by SteveL-MSFT** [comment]
@PoshChan please retry windows

**Comment by PoshChan** [comment]
@SteveL-MSFT, successfully started retry of `PowerShell-CI-Windows`

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-macos`
Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1:11 char:30
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 389 failures in `PowerShell-CI-windows`
(These are 5 of the failures)

Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create symbolic link to file
```powershell
Expected exactly 'C:\Users\VSSADM~1\AppData\Local\Temp\fa7b8f20-a1bb-43eb-8ba6-4be3919a51a8\file.txt', but got C.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\FileSystem.Tests.ps1: line 455
455:             $link.Target[0] | Should -BeExactly $real.ToString()
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create a symbolic link to nothing
```powershell
Expected 'C:\Users\VSSADM~1\AppData\Local\Temp\fa7b8f20-a1bb-43eb-8ba6-4be3919a51a8\not-a-file', but got C.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\FileSystem.Tests.ps1: line 464
464:             $link.Target[0] | Should -Be $nonFile.ToString()
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create a directory symbolic link to a directory
```powershell
Expected exactly 'C:\Users\VSSADM~1\AppData\Local\Temp\fa7b8f20-a1bb-43eb-8ba6-4be3919a51a8\subdir', but got C.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\FileSystem.Tests.ps1: line 486
486:             $link.Target[0] | Should -BeExactly $real.ToString()
```
Connection.Test connection to local host port 80
```powershell
Expected $true, but got $false.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\Test-Connection.Tests.ps1: line 271
271:         Test-Connection '127.0.0.1' -TCPPort $WebListener.HttpPort | Should -BeTrue
```
Web cmdlets tests using the cmdlet's aliases.Execute Invoke-WebRequest
```powershell
No connection could be made because the target machine actively refused it.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\WebCmdlets.Tests.ps1: line 3246
3246:         $result = Invoke-WebRequest $uri

```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-linux`
Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1:11 char:30
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 7 failures in `PowerShell-CI-macos`
(These are 5 of the failures)

Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1:11 char:30
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create symbolic link to file
```powershell
Expected exactly '/tmp/7d27d065-4c2c-445a-902f-779e46f06266/file.txt', but got /.
at <ScriptBlock>, /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1: line 455
455:             $link.Target[0] | Should -BeExactly $real.ToString()
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create a symbolic link to nothing
```powershell
Expected '/tmp/7d27d065-4c2c-445a-902f-779e46f06266/not-a-file', but got /.
at <ScriptBlock>, /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1: line 464
464:             $link.Target[0] | Should -Be $nonFile.ToString()
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create a symbolic link to a directory
```powershell
Expected exactly '/tmp/7d27d065-4c2c-445a-902f-779e46f06266/subdir', but got /.
at <ScriptBlock>, /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1: line 476
476:             $link.Target[0] | Should -BeExactly $real.ToString()
```
Measure-Object.Numeric tests.Should be able to return all the statitics for given values
```powershell
Expected strings to be the same, but they were different.
Expected length: 16
Actual length:   18
Strings differ at index 16.
Expected: '3.02765035409749'
But was:  '3.0276503540974917'
---------------------------^
at <ScriptBlock>, /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Measure-Object.Tests.ps1: line 185
185:             ($result.StandardDeviation).ToString()  | Should -Be '3.02765035409749'
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 389 failures in `PowerShell-CI-windows`
(These are 5 of the failures)

Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create symbolic link to file
```powershell
Expected exactly 'C:\Users\VSSADM~1\AppData\Local\Temp\3715e842-db9c-4d4c-95fe-059a78787a5d\file.txt', but got C.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\FileSystem.Tests.ps1: line 455
455:             $link.Target[0] | Should -BeExactly $real.ToString()
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create a symbolic link to nothing
```powershell
Expected 'C:\Users\VSSADM~1\AppData\Local\Temp\3715e842-db9c-4d4c-95fe-059a78787a5d\not-a-file', but got C.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\FileSystem.Tests.ps1: line 464
464:             $link.Target[0] | Should -Be $nonFile.ToString()
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create a directory symbolic link to a directory
```powershell
Expected exactly 'C:\Users\VSSADM~1\AppData\Local\Temp\3715e842-db9c-4d4c-95fe-059a78787a5d\subdir', but got C.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\FileSystem.Tests.ps1: line 486
486:             $link.Target[0] | Should -BeExactly $real.ToString()
```
Connection.Test connection to local host port 80
```powershell
Expected $true, but got $false.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\Test-Connection.Tests.ps1: line 271
271:         Test-Connection '127.0.0.1' -TCPPort $WebListener.HttpPort | Should -BeTrue
```
Web cmdlets tests using the cmdlet's aliases.Execute Invoke-WebRequest
```powershell
No connection could be made because the target machine actively refused it.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\WebCmdlets.Tests.ps1: line 3246
3246:         $result = Invoke-WebRequest $uri

```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 7 failures in `PowerShell-CI-linux`
(These are 5 of the failures)

Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1:11 char:30
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create symbolic link to file
```powershell
Expected exactly '/tmp/b0a9da78-40a0-4834-b787-b81cc84e259e/file.txt', but got /.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1: line 455
455:             $link.Target[0] | Should -BeExactly $real.ToString()
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create a symbolic link to nothing
```powershell
Expected '/tmp/b0a9da78-40a0-4834-b787-b81cc84e259e/not-a-file', but got /.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1: line 464
464:             $link.Target[0] | Should -Be $nonFile.ToString()
```
Hard link and symbolic link tests.New-Item and hard/symbolic links.New-Item can create a symbolic link to a directory
```powershell
Expected exactly '/tmp/b0a9da78-40a0-4834-b787-b81cc84e259e/subdir', but got /.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/FileSystem.Tests.ps1: line 476
476:             $link.Target[0] | Should -BeExactly $real.ToString()
```
Measure-Object.Numeric tests.Should be able to return all the statitics for given values
```powershell
Expected strings to be the same, but they were different.
Expected length: 16
Actual length:   18
Strings differ at index 16.
Expected: '3.02765035409749'
But was:  '3.0276503540974917'
---------------------------^
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Measure-Object.Tests.ps1: line 185
185:             ($result.StandardDeviation).ToString()  | Should -Be '3.02765035409749'
```

**Pull request merged**
