### PR TITLE
Enable IDE0031: Null check can be simplified

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

Use C# 6.0 null propagation:

* `(result == null) ? null : result.Instance` -> `result?.Instance`
* `(result != null) ? result.Instance : null` -> `result?.Instance`

https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0031

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [NA] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [NA] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [NA] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [NA] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [NA] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [NA] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by iSazonov** [comment]
My personal feeling is that it doesn't add to readability. I would prefer that we move the CodeFactor index to the green area.

**Comment by daxian-dbw** [comment]
@PowerShell/powershell-maintainers reviewed this PR and agreed to accept it. But please delay merging the PR until after the 7.1.0-RC.1 release branch is created.

**Comment by iSazonov** [comment]
Convert o draft until 7.1 RC1.

**Comment by xtqqczze** [comment]
needs triage

**Review by iSazonov — APPROVED** [review]

**Comment by xtqqczze** [comment]
updated PR description

**Comment by xtqqczze** [comment]
@daxian-dbw Can you review?

**Comment by xtqqczze** [comment]
rebased

**Review by TravisEz13 — COMMENTED** [review]
reviewed 13/42

**Comment by TravisEz13** [comment]
@PoshChan Please remind me in 7 days

**Comment by iSazonov** [comment]
@xtqqczze Please resolve merge conflicts.

**Comment by xtqqczze** [comment]
Resolved merge conflicts.

**Comment by iSazonov** [comment]
@TravisEz13 Do you want to continue the code review?

**Pull request merged**
