### PR TITLE
Get-Content -Head and -Tail disallow negative values and cleanup

### PR DESCRIPTION
**Pull request by CarloToso**
# PR Summary

- Disallow negative values for -Head and -Tail
- Add fast return if -Tail == 0
- Cleanup code

TODO:
- ~~Add tests~~

## PR Context
https://github.com/PowerShell/PowerShell/issues/19710 @jhoneill @mklement0 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by TravisEz13 — COMMENTED** [review]
Are there tests for the modified scenarios?

Update:
https://github.com/PowerShell/PowerShell/blob/master/test/powershell/Modules/Microsoft.PowerShell.Management/Get-Content.Tests.ps1

Add tests for:
* tail = 0
* verify error when tail is negative
* verify error when totalcount is negative.

**Comment by CarloToso** [comment]
@TravisEz13 Added tests

**Comment by jhoneill** [comment]
To me this looks like **a** valid solution ,  I have added the wg-cmdlets tag because I think the WG should be saying "There are other ways this could be addressed, we like (or don't like) this one."

**Review by daxian-dbw — APPROVED** [review]
It looks good to me overall. However, this is a breaking change, as today a user can specify negative value like `Get-Content -Tail -50` or `Get-Content -TotalCount -100`, and they just mean get all content.
It seems to be a bucket 3 breaking change, but I'd like the Cmdlet WG to make a conclusion.

**Comment by SteveL-MSFT** [comment]
Added to WG agenda

**Comment by SteveL-MSFT** [comment]
@PowerShell/wg-powershell-cmdlets reviewed this, we agreed that although a breaking change, we think it is a bucket 3 unlikely to impact users change.  The main concern is that `-1` is documented as default and implied to be supported.  Docs would need to be changed to remove mention of this internal detail and users are likely to not specify the parameter rather than explicitly `-1` to get all content so we don't expect users to be using `-1` directly.

**Comment by SteveL-MSFT** [comment]
@JamesWTruher has some individual PR comments he'll add

**Comment by daxian-dbw** [comment]
@SteveL-MSFT @JamesWTruher I didn't see the new comment above until after I merged the PR ...
Please still leave your comment. If it's something you think that needs code changes, please open an issue to track it.

**Comment by daxian-dbw** [comment]
Doc issue https://github.com/MicrosoftDocs/PowerShell-Docs/issues/10183 was opened to track removing mention of the default value.

**Pull request merged**
