### PR TITLE
Use new -WorkingDirectory parameter on pwsh.exe to be able to use context menu when path contains single quotes.

### LINKED ISSUE #6598: File Explorer context-menu integration fails with directory names with embedded apostrophes (single quotes)
Just as the current _Windows PowerShell_ File Explorer context-menu integration (with Shift-right-click) is broken with paths with embedded `'` chars. , as described [here](https://superuser.com/q/1310258/139307), so is PowerShell Core's.

The following two lines must be revised in accordance with the linked instructions:

https://github.com/PowerShell/PowerShell/blob/77f36498e613037babcc99029ca386e36f3b7b59/assets/Product.wxs#L204

https://github.com/PowerShell/PowerShell/blob/77f36498e613037babcc99029ca386e36f3b7b59/assets/Product.wxs#L212

Environment data
----------------

```powershell
PowerShell Core v6.1.0-preview.1
```

### PR DESCRIPTION
**Pull request by bergmeister**
## PR Summary

Fixes #6598 by using PR #6612 that adds a `-WorkingDirectory` parameter on `pwsh.exe` that this PR uses in order to make the explorer context menu also work when the path contains a single quote.
Technical note: `&quot;` is an escape character for a double quote in WiX.
Note that this bug also occurs for the Windows PowerShell Explorer integration in Windows 10.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Comment by SteveL-MSFT** [comment]
@TravisEz13 the WIP check is wrong?

**Comment by SteveL-MSFT** [comment]
Put `WIP:` in title until pending PR is merged

**Comment by bergmeister** [comment]
@SteveL-MSFT @daxian-dbw I pulled in the required changes from master and tested locally that it works using a folder that ends with a single quote.

**Comment by daxian-dbw** [comment]
#6707 is opened to track the test failure in AppVeyor. I have restarted the build.

**Comment by bergmeister** [comment]
Thanks

**Comment by munrobasher** [comment]
Can cross-reference this with [https://superuser.com/questions/1323501/bug-in-powershell-classes-when-script-is-in-a-folder-containing-a-single-quote](url) - is this the same issue here? My problem is with the class statement inside a script that resides in a folder containing a single quote character.

**Comment by bergmeister** [comment]
@munrobasher No, this issue/PR was about a different problem although it looks similar.
I repro-ed your linked issue in PowerShell 5.1 and can also confirm that the issue does not happen when using PowerShell 6.2.1
Windows PowerShell receives only critical and security fixes, I suggest to upgrade to PowerShell 6.2 or not use classes in this case then

**Pull request merged**
