### PR TITLE
Added installation instructions for Kali Linux

### PR DESCRIPTION
**Pull request by sdcampbell**
Close https://github.com/PowerShell/PowerShell/issues/2641

### CODE REVIEW

**Comment by iSazonov** [comment]
I added link on the Issue https://github.com/PowerShell/PowerShell/issues/2641 in description.

**Comment by iSazonov** [comment]
@sdcampbell Please correct errors in markdown files.

**Comment by DarwinJS** [comment]
Does anyone know if installing on any debian based distro will work fine with the existing Ubuntu repository configuration?

**Comment by TravisEz13** [comment]
@sdcampbell  Please fix the markdown issues which are described here:
https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-alpha.18-2944#L464

**Comment by joeyaiello** [comment]
@TravisEz13 @sdcampbell hope it was okay, I just went and ahead and fixed the lint errors for you. Should be good to go now 👍

**Review by TravisEz13 — APPROVED** [review]

**Pull request merged**
