### PR TITLE
Use HTTPS links for go.microsoft.com

### PR DESCRIPTION
**Pull request by xiaoyinl**
For better security and privacy, I think it is better to use HTTPS links wherever possible. So I replace all occurrences of `http://go.microsoft.com` with `https://go.microsoft.com` in all non-binary files in this repository. Note that some go.microsoft.com links redirect to http and then to https, such as https://go.microsoft.com/fwlink/?LinkID=135255. They should redirect to https directly. Could you fix them on the server side?

### CODE REVIEW

**Comment by vors** [comment]
I re-triggered Travis CI build, which was timed-out and may be unrelated to the change.

**Comment by daxian-dbw** [comment]
LGTM. I think this shouldn't cause any issues to Update-Help or Get-Help -Online, but @Francisco-Gamino can you please confirm?

**Comment by Francisco-Gamino** [comment]
We have get-help <cmdletName> -online tests on Window which will break. However, I am not sure if these tests have been ported.

@adityapatwardhan, have we ported the get-help -online tests to GitHub? If we have not, then we need a work item to update fwlinks when porting these tests. Thanks.

**Comment by daxian-dbw** [comment]
@Francisco-Gamino why `get-help -online` tests will break?

**Comment by adityapatwardhan** [comment]
LGTM @JamesWTruher Are the help tests ported?

**Comment by Francisco-Gamino** [comment]
LGTM. I opened an issue to port the updatable help tests to Open PowerShell. See https://github.com/PowerShell/PowerShell/issues/2164

**Pull request merged**
