### PR TITLE
Write-Object -NoEnumerate should not wrap sigular object

### LINKED ISSUE #5122: Write-Output -NoEnumerate wrap singular items into PSObject[]
As far as I understand, issue caused by #2038.

Steps to reproduce
------------------

```powershell
(Write-Output -NoEnumerate 1).GetType().FullName
(1 | Write-Output -NoEnumerate).GetType().FullName
```

Expected behavior
-----------------

```none
System.Int32
System.Int32
```

Actual behavior
---------------

```none
System.Management.Automation.PSObject[]
System.Management.Automation.PSObject[]
```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-beta.8
PSEdition                      Core
GitCommitId                    v6.0.0-beta.8-46-ge3397b63e756bf432bbe80f5e9c4407d52d6b5b9
OS                             Microsoft Windows 10.0.15063
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by PetSerAl**
Fix #5122
I decide to make `ValueFromRemainingArguments` to always unwrap single argument, even if it is not collection. Otherwise it would be impossible to distinguish two cases:
```powershell
Write-Object -NoEnumerate 1
Write-Object -NoEnumerate ( [System.Collections.Generic.List[object]]::new((,1)) )
```

### CODE REVIEW

**Comment by iSazonov** [comment]
@PetSerAl What is the last commit? Need rebase?

**Comment by PetSerAl** [comment]
@iSazonov I am cherry pick first commit from #5109, to make sure that tests pass too, since my change is more strong then proposed here. I think it would be more consistent to unwrap any single parameter passed as `ValueFromRemainingArguments`, while #5109 propose to unwrap only collections.

**Comment by iSazonov** [comment]
@PetSerAl @mklement0 Please see latest comments in #5109 about the PR.

**Comment by iSazonov** [comment]
@PetSerAl Plase add comment why the Issue was closed.

**Comment by PetSerAl** [comment]
@iSazonov Given [this comment](https://github.com/PowerShell/PowerShell/pull/5109#issuecomment-337770066) and that #5109 is now merged, I do not see how my changes in binder can be accepted. And I do not see other way to fix #5122, thus I see no value in keeping this PR open. I do not closing #5122 though. If someone know how to fix it, then them can submit their own PR instead of this one.

**Pull request closed without merging**
