### PR TITLE
Add support <Suppress> in Get-WinEvent -FilterHashtable

### LINKED ISSUE #2402: Add support <Suppress> in Get-WinEvent -FilterHashtable
Now Get-WinEvent -FilterHashtable support only _**Select**_ for query.
Although Windows Event Log supports a subset of XPath 1.0 including _**Suppress**_.
An example of such a query:
query

I see three ways to add new functionality:
1. Add new parameter FilterHashtableSuppress or SuppressFilterHashtable. 
2. Use prefix for standard keys: SUPId, SUPLevel, SUPUserID, SUPStartTime, SUPEndTime, SUPData, SUPNamedKey. Ex.:  
`Get-WinEvent -FilterHashtable @{Logname="Application";SUPId=1001}`

3.Use special 'SuppressHashFilter' property in hash table.
Ex.:  
`Get-WinEvent -FilterHashtable @{Logname="Application";Id=1001;SuppressHashFilter=@{Id=1002}}`

### PR DESCRIPTION
**Pull request by iSazonov**
1. Add support Suppress
2. Refacrtoring BuildStructuredQueryFromHashTable() to use StringBuilder
3. Add tests

Close #2402

### CODE REVIEW

**Comment by iSazonov** [comment]
"Changelog Needed" Is it for me? 
And what about changes in help documentation?

**Comment by lzybkr** [comment]
Regarding `Changelog Needed`, see https://github.com/PowerShell/PowerShell/blob/master/docs/maintainers/issue-management.md

**Comment by iSazonov** [comment]
My question was: who makes adding into changelog - I or maintainers? It is not clear from the documentation.

**Comment by iSazonov** [comment]
Add record to the changelog.

**Comment by lzybkr** [comment]
It doesn't matter who updates the change log, just that it happens. It is of course appreciated if you do.

**Comment by iSazonov** [comment]
Thanks @lzybkr. I did.

**Comment by mirichmo** [comment]
@PaulHigin Please take a look

**Comment by JamesWTruher** [comment]
:shipit:

**Comment by iSazonov** [comment]
@JamesWTruher @lzybkr Thanks for review and support!

**Pull request merged**
