### PR TITLE
Remove extraneous SSH and install docs from PowerShell/PowerShell

### PR DESCRIPTION
**Pull request by joeyaiello**
## PR Summary

This PR removes the `SSHRemoting` and `install` folders within `demos`. I also removed `SSHRemoting` from an existing test, as well as the `.spelling` region for it. 

These docs are now hosted on docs.microsoft.com:
* [PowerShell Remoting Over SSH](https://docs.microsoft.com/en-us/powershell/scripting/core-powershell/ssh-remoting-in-powershell-core?view=powershell-6)
* [Installing PowerShell Core on Windows](https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-windows?view=powershell-6)
* [Installing PowerShell Core on macOS and Linux](https://docs.microsoft.com/en-us/powershell/scripting/setup/installing-powershell-core-on-macos-and-linux?view=powershell-6)

We may also want to delete `docs/installation` from PS/PS, but it's unclear to me yet if folks know to update the doc in PowerShell-Docs from here on out (and it may contain some installation info about installing a preview build that hasn't yet been merged into PowerShell-Docs). /cc @TravisEz13 

If I should delete that, I'll do it in a follow-up PR. Or if someone wants to push into my fork, that's cool too, I just didn't want to do it without a Maintainer giving input first. 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by SteveL-MSFT** [comment]
@joeyaiello you need to add some words back to .spelling

**Comment by iSazonov** [comment]
Maybe add this doc links to main README?

**Comment by bergmeister** [comment]
This is a breaking change in the sense that existing links in code comments or blogs get broken. Is it possible/worthwhile to have at least a redirect to the new place instead of removing the doc completely? Maybe not forever but for half a year as a transition period?

**Comment by joeyaiello** [comment]
@bergmeister I'd really not rather keep stubs around when these docs are particularly easy to Google....If you want to point at a specific tree commit, you can do that. (I get why that's not desirable when you want up-to-date docs, but it does work...)

**Pull request closed without merging**
