### PR TITLE
Add AllowInsecureRedirect switch to Web cmdlets

### LINKED ISSUE #2896: Invoke-WebRequest / Invoke-RestMethod fails to follow HTTP redirects from HTTPS
Steps to reproduce
------------------
1. Install Windows Server Nano (10.0.14393)
2. Connect to the server using PS Remoting, then use PowerShell Core (the built-in version) to download a file, e.g. try to download .NET Core 1.1 ZIP package:

Invoke-Webrequest -Uri 'https://go.microsoft.com/fwlink/?LinkID=835028' -OutFile C:\netcore11.zip -MaximumRedirection 10

Expected behavior
-----------------
File is downloaded, HTTP 302 Redirect returned by go.microsoft.com is handled properly.

Actual behavior
---------------
The following error occurs:
`invoke-webrequest : Response status code does not indicate success: 302 (Moved Temporarily).` 
And there is no workaround, because the thrown exception is a HttpRequestException thrown by EnsureSuccessStatusCode(), which loses all header information (so, unable even to access the Location header).

Issue is still present in the master branch:
https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/CoreCLR/WebRequestPSCmdlet.CoreClr.cs#L352
**EnsureSuccessStatusCode()** should not be used, as it doesn't support redirects, and it also obfuscates the exception, making it impossible to access the returned headers/body even if the exception is caught.

Environment data
----------------
```
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
BuildVersion                   10.0.14393.1000
SerializationVersion           1.1.0.1
PSVersion                      5.1.14393.1000
PSEdition                      Core
WSManStackVersion              3.0
CLRVersion

```

### PR DESCRIPTION
**Pull request by CarloToso**
# PR Summary

WebCmdlets add -AllowInsecureRedirect switch to enable HTTPS to HTTP redirect.
System.Net.Http.HttpClient disables insecure redirects, this PR bypasses the problem, unfortunately at the moment I can't find a way to make it honor the -MaximumRedirects flag, so I have disabled using both of them toghether.
I'm eager to receive your feedback on this feature and some input on how to fix and re-enable the -MaximumRedirect flag.
I'm going to add some tests to show what works and what doesn't work yet.

## PR Context

Fixes #2896 and #18541

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/9689
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
> unfortunately at the moment I can't find a way to make it honor the -MaximumRedirects flag

https://github.com/PowerShell/PowerShell/blob/f5eede60b914a3c124fccf87a201f35e3fc6cdff/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L1045-L1049

This says it is in GetResponse().

**Comment by CarloToso** [comment]
-AllowInsecureRedirect should now work with -MaximumRedirect.
I tested it with this code:
```ps1
0..5 | ForEach-Object {Invoke-WebRequest https://mockbin.org/redirect/300?to=http://mockbin.org/redirect/301?to=https://mockbin.org/redirect/302?to=http://mockbin.org/redirect/303?to=http://mockbin.org/redirect/307?to=https://mockbin.org/status/200 -SkipHttpErrorCheck -AllowInsecureRedirect -MaximumRedirection $_}
0..5 | ForEach-Object {Invoke-RestMethod https://mockbin.org/redirect/300?to=http://mockbin.org/redirect/301?to=https://mockbin.org/redirect/302?to=http://mockbin.org/redirect/303?to=http://mockbin.org/redirect/307?to=https://mockbin.org/status/200 -SkipHttpErrorCheck -AllowInsecureRedirect -MaximumRedirection $_}
Invoke-WebRequest https://mockbin.org/redirect/300?to=http://mockbin.org/redirect/301?to=https://mockbin.org/redirect/302?to=http://mockbin.org/redirect/303?to=http://mockbin.org/redirect/307?to=https://mockbin.org/status/200 -SkipHttpErrorCheck -AllowInsecureRedirect 
Invoke-WebRequest https://mockbin.org/redirect/300?to=http://mockbin.org/redirect/301?to=https://mockbin.org/redirect/302?to=http://mockbin.org/redirect/303?to=http://mockbin.org/redirect/307?to=https://mockbin.org/status/200 -SkipHttpErrorCheck
```
I still have to remove some commented code.

**Comment by CarloToso** [comment]
```ps1
Invoke-WebRequest https://mockbin.org/redirect/300?to=http://mockbin.org/redirect/301?to=https://mockbin.org/redirect/302?to=http://mockbin.org/redirect/303?to=http://mockbin.org/redirect/307?to=https://mockbin.org/status/200 -SkipHttpErrorCheck
```


```ps1
Invoke-WebRequest https://mockbin.org/redirect/300?to=http://mockbin.org/redirect/301?to=https://mockbin.org/redirect/302?to=http://mockbin.org/redirect/303?to=http://mockbin.org/redirect/307?to=https://mockbin.org/status/200 -SkipHttpErrorCheck -AllowInsecureRedirect
```


```ps1
0..5 | ForEach-Object {(Invoke-WebRequest https://mockbin.org/redirect/300?to=http://mockbin.org/redirect/301?to=https://mockbin.org/redirect/302?to=http://mockbin.org/redirect/303?to=http://mockbin.org/redirect/307?to=https://mockbin.org/status/200 -SkipHttpErrorCheck -AllowInsecureRedirect -MaximumRedirection $_).StatusCode}
```


Some inconsistent behaviours (increase redirects errors, status code 308) are fixed by PR #18536.

**Comment by iSazonov** [comment]
LGTM.

**Review by iSazonov — APPROVED** [review]

**Comment by CarloToso** [comment]
@PaulHigin, please review, thanks!

**Comment by CarloToso** [comment]
Is something blocking this PR?

**Comment by iSazonov** [comment]
> Is something blocking this PR?

Yes, holydays :-) 
I hope MSFT team will start active work after Jan 1.
Until that I can consider minor style changes and discuss/review code for already triaged issues.

**Comment by CarloToso** [comment]
I think that after this PR is merged I can work on fixing #14531, it should be similar.

**Comment by iSazonov** [comment]
@Please open new issue in Docs repository and add reference in the PR description.

**Comment by CarloToso** [comment]
> @please open new issue in Docs repository and add reference in the PR description.

Done

**Pull request merged**
