### PR TITLE
Retrieve PowerShell version in PSVersionInfo using assembly informational version instead of FileVersionInfo

### PR DESCRIPTION
**Pull request by Fs00**
# PR Summary

This PR changes `PSVersionInfo` static constructor to retrieve PowerShell version data from `AssemblyInformationalVersionAttribute`, instead of using FileVersionInfo class.

## PR Context

This change is a first step towards making System.Management.Automation single-file-application-friendly ‒ without this PR, PSVersionInfo static constructor throws an exception when used in a single-file application due to `Assembly.Location` returning `""` ‒ and provides a small performance boost at startup (which contributes a tiny bit to #14268) since it does not parse System.Management.Automation DLL to retrieve the version anymore.
Here is the performance of the two changed lines:
- before PR: ~0,23ms
- after PR: **~0,03ms** (~7 times faster)

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by iSazonov** [comment]
@Fs00 Thanks for your contribution!
I hope that we will soon be able to use .Net 6.0 Source Generators. So I'm going to refactor PSVersionInfo class and move all version constants to new GitInfo class. Later we will be able to generate it with a simple source generator and thereby remove all reflection overhead.
I will use your idea in follow PR.

**Comment by Fs00** [comment]
@iSazonov Good to know.
Since it isn't sure when the refactoring with source generators will be done, could this PR be merged in the meantime? It would still be an improvement on the current situation and would allow me to test System.Management.Automation on single-file applications to see if there are any other issues.

**Comment by iSazonov** [comment]
> Since it isn't sure when the refactoring with source generators will be done, could this PR be merged in the meantime?

I see with the PR PowerShell loads less assembles at startup - it is great perf improvement! I think we will merge the PR.

**Comment by iSazonov** [comment]
I see `System.Diagnostics.FileVersionInfo.dll` is still loaded on Windows in AmsiUtils.Init()
https://github.com/PowerShell/PowerShell/blob/ea3036dc6d5bcbd58ee2b3b1960a3647467d0801/src/System.Management.Automation/security/SecuritySupport.cs#L1355-L1357

@PaulHigin @TravisEz13 Do really need the `FileVersionInfo.ProductVersion`? Can we use the same approach as @Fs00 in the PR?

**Review by daxian-dbw — APPROVED** [review]

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@Fs00 Thanks for your contribution!

**Comment by ALIENQuake** [comment]
@Fs00 Late to the party but please accept my gratitude for your efforts to bring PowerShell closer to single-file-application-friendly!

**Pull request merged**
