### PR TITLE
Add Git commit Id to ETW events

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Address #5385 

Add Git commit Id to ETW events to indicate pwsh version in SxS scenario.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by adityapatwardhan** [comment]
I am not sure if we need this change. The PSVersion information is already available in the context. Have a look at snippet below. It also has the path to the pwsh executable.

```
Context:
        Severity = Warning
        Host Name = Default Host
        Host Version = 6.2.3
        Host ID = 0a5b0b2f-bc91-4277-855e-8e515428266a
        Host Application = C:\Program Files\PowerShell\6\pwsh.dll -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command & 'c:\Users\adityap\.vscode\extensions\ms-vscode.powershell-2019.11.0\modules\PowerShellEditorServices\Start-EditorServices.ps1' -HostName 'Visual Studio Code Host' -HostProfileId 'Microsoft.VSCode' -HostVersion '2019.11.0' -AdditionalModules @('PowerShellEditorServices.VSCode') -BundledModulesPath 'c:\Users\adityap\.vscode\extensions\ms-vscode.powershell-2019.11.0\modules' -EnableConsoleRepl -LogLevel 'Normal' -LogPath 'c:\Users\adityap\.vscode\extensions\ms-vscode.powershell-2019.11.0\logs\1576801082-b176810b-eb30-4a56-bf5c-a2e937a83b7b1576178394502\EditorServices.log' -SessionDetailsPath 'c:\Users\adityap\.vscode\extensions\ms-vscode.powershell-2019.11.0\sessions\PSES-VSCode-14272-664832' -FeatureFlags @()
        Engine Version = 6.2.3
        Runspace ID = b39bde2f-2465-40e0-a480-fb31f624fa8b
        Pipeline ID = 578
        Command Name = Invoke-ScriptAnalyzer
        Command Type = Cmdlet
        Script Name = 
        Command Path = 
        Sequence Number = 638
        User = REDMOND\adityap
        Connected User = 
        Shell ID = Microsoft.PowerShell

```

**Comment by iSazonov** [comment]
@adityapatwardhan pwsh path makes no sense for SxS scenario.

 If I understand right "Host Version" and "Engine Version" expose PSVersion, not GitCommitId.
Do we need the GitCommitId?

**Review by SteveL-MSFT — DISMISSED** [review]

**Comment by SteveL-MSFT** [comment]
The original issue is being able to filter events where you have multiple versions of pwsh installed.  Seems like GitCommitId may be overkill and not needed.

**Comment by iSazonov** [comment]
@SteveL-MSFT Close the PR and issue?

**Comment by SteveL-MSFT** [comment]
@iSazonov yeah, I think so

**Pull request closed without merging**
