### PR TITLE
Move psxml type definitions from SMA to Security module

### LINKED ISSUE #14095: Circular dependency at runtime between System.Management.Automation and Microsoft.PowerShell.Security
While using only System.Management.Automation as a dependency for an application of mine (**without the entire SDK** because I didn't need it), I was getting sometimes a `NullReferenceException` that was thrown in this line of code:

https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/TypeTable_Types_Ps1Xml.cs#L51

because `type` was null.

Digging in the stack trace, I found out that the null reference was originated by the following instruction:

https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/TypeTable_Types_Ps1Xml.cs#L4072

The `securityDescriptorCommandsBaseType` variable gets passed to the method `GetMethodInfo`, which contains the return statement with the variable `type` shown above.

Once you know that the referenced type (`Microsoft.PowerShell.Commands.SecurityDescriptorCommandsBase`) belongs to the Microsoft.PowerShell.Security package, and that the latter depends on System.Management.Automation, it becomes apparent that [TypeResolver.ResolveType](https://github.com/PowerShell/PowerShell/blob/76cef3b299911ba264fef7a2f510dd633f36497d/src/System.Management.Automation/engine/parser/TypeResolver.cs#L489) was being used in place of `typeof` to avoid a circular dependency at compile time between the two assemblies.
The problem is that the circular dependency still exists and causes the NRE mentioned above when System.Management.Automation is used alone.

Therefore, since I think that probably that dependency can't be broken, I would propose to "loosen" it by adding a null-check that prevents all the code related to the `securityDescriptorCommandsBaseType` from being executed when Microsoft.PowerShell.Security assembly is not available (which should be lines [4074-4128](https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/TypeTable_Types_Ps1Xml.cs#L4074L4128) or even 4074-4210, I'm not sure).

I'm willing to open a PR to mitigate this problem after receiving your feedback on it, since - unlike me - you know the context and the motivation of the code I mentioned throughout this issue.

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Replace #16349
Fix #14095 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by Fs00** [comment]
I want to point out that this PR would also fix #14095 😃

**Review by rkeithhill — APPROVED** [review]
LGTM

**Review by JamesWTruher — APPROVED** [review]

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by daxian-dbw** [comment]
@SteveL-MSFT and @JamesWTruher This is a breaking change:
- Before this change, a user doesn't need to explicitly import the `Microsoft.PowerShell.Security` module to use the code properties defined for an instance of `System.Security.AccessControl.ObjectSecurity`.
- After this change, a user needs to explicitly import `Microsoft.PowerShell.Security` module to use those code properties and code methods.

Are you fine to accept this breaking change?

**Comment by SteveL-MSFT** [comment]
@daxian-dbw I did a search on GitHub for use of `AccessToString` and all the cases I looked at use `Get-Acl` which comes from the Security module.  Although it's possible using .NET APIs to get an ObjectSecurity instance, it would seem that most, if not all, usage is coming from this module.  Seems unlikely that someone would be impacted.

**Comment by JamesWTruher** [comment]
> @SteveL-MSFT and @JamesWTruher This is a breaking change:
> 
> * Before this change, a user doesn't need to explicitly import the `Microsoft.PowerShell.Security` module to use the code properties defined for an instance of `System.Security.AccessControl.ObjectSecurity`.
> * After this change, a user needs to explicitly import `Microsoft.PowerShell.Security` module in order to use those code properties and code methods.
> 
> Are you fine to accept this breaking change?

I think the _general_ use case is going to because someone invoked `Get-Acl` or some other command from the module which will result in autoloading and those folks will never be affected by this change. However, there are _some_ scenarios where this won't be the case, and those folks will need to load the module. I'm having trouble handicapping the probabilities of those scenarios, though. I don't think it's going to happen very often, and enabling the behavior is pretty easy. It will definitely need documenting, but I think it's ok.

**Comment by daxian-dbw** [comment]
Just checked on Linux, Access Control List APIs are only supported on Windows, so the changes to `src/Modules/Windows/Microsoft.PowerShell.Security/Microsoft.PowerShell.Security.psd1` is sufficient, not need to change the Unix version of `Microsoft.PowerShell.Security.psd1`.

**Pull request merged**
