### PR TITLE
Revert "install-powershell.sh: Adding autodetection of curl / wget" due to regression

### PR DESCRIPTION
**Pull request by TravisEz13**
Reverts PowerShell/PowerShell#7893

@DarwinJS  This regressed the script.  https://travis-ci.org/PowerShell/PowerShellGet/builds/435897616

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]

**Comment by DarwinJS** [comment]
Ok I fixed the indenting which shows a couple badly closed if statements.  What is next - can you cancel this revert?

**Comment by TravisEz13** [comment]
@DarwinJS  Can you open a new PR?

**Comment by TravisEz13** [comment]
@SteveL-MSFT  Perhaps we should move these to a separate repo?  `PowerShell-Tools` and then we could add a CI system to verify these scripts work at least on a couple of OSs.

**Comment by SteveL-MSFT** [comment]
@TravisEz13 I don't think it's worth the effort of a new repo just for a few tools.  It would be better to have some tests for these tools since people are depending on them.

**Pull request merged**
