### PR TITLE
Add nanoserver insider dockerfile

### PR DESCRIPTION
**Pull request by TravisEz13**
update all docker files for POSIX syntax changes

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]

**Comment by alexandair** [comment]
@TravisEz13 microsoft/nanoserver-insider image isn't on DockerHub yet, right?

**Comment by TravisEz13** [comment]
@alexandair The images are public now on Docker Hub: [nanoserver-insider-powershell](https://hub.docker.com/r/microsoft/nanoserver-insider-powershell/)

**Comment by TravisEz13** [comment]
Docs are still coming up, I'm waiting on the docs.microsoft.com link, but if you want to use these please read the docs:  [Using Insider Container Images](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/Using-Insider-Container-Images.md) and [Build and Run an Application](https://github.com/Microsoft/Virtualization-Documentation/blob/live/virtualization/windowscontainers/quick-start/Nano-RS3-.NET-Core-and-PS.md)

**Comment by TravisEz13** [comment]
Our Docs are up, https://github.com/PowerShell/PowerShell/pull/4228

**Comment by alexandair** [comment]
Thank you for docs.

**Pull request merged**
