### PR TITLE
WIP: Fix IDE0005: Remove unnecessary usings

### PR DESCRIPTION
**Pull request by xtqqczze**
https://docs.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0005

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]

**Comment by anmenaga** [comment]
Maintainers think this is a low risk change, considering that a build break will detect any error in this change;
however conflict must be fixed and CI have to be passing; please put back "Review - Maintainer" label once this is updated.

**Comment by iSazonov** [comment]
@xtqqczze Please split the PR by project/folder.

**Comment by iSazonov** [comment]
@xtqqczze Can we close?

**Comment by xtqqczze** [comment]
@iSazonov We still have `System.Management.Automation` 🙁

**Pull request closed without merging**
