### PR TITLE
Remove unneeded catch/throw from 'mkdir' and 'oss' functions

### PR DESCRIPTION
**Pull request by daxian-dbw**
## PR Summary

Remove unneeded catch/throw from 'mkdir' and 'oss' functions.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]

**Comment by lzybkr** [comment]
@daxian-dbw - sorry to have just noticed this - the seemingly unnecessary `try/catch` statements did serve a useful purpose at one point. I recall hating adding them, but IIRC, it improved error reporting in some useful way. Sorry, but I don't remember more than that though.

**Comment by iSazonov** [comment]
Does it update ScriptStackTrace in errorrecord?

**Comment by daxian-dbw** [comment]
@lzybkr Thanks for bringing up that context. Looks like those try/catch were added only for functions that uses `SteppablePipeline`. Might it be related to errors thrown from within the steppable pipeline? I will play with it a bit to see if I can find out why.

**Comment by daxian-dbw** [comment]
The "better error reporting" might be related to `PowerShell.AddScript(...).Invoke()` doesn't throw on terminating error or exception, but instead keep the errors in the error stream.
Here is one example of that:
```
$ps = [powershell]::create()
$ps.AddScript(@'
 try {
     Get-Process -Invalid 42
 } catch {
     throw
 }
'@)
## try/catch/throw is needed for the exception to be thrown from $ps.invoke()
$ps.Invoke()
```

But it doesn't seem to be the exact reason for the try/catch/throw in the original `mkdir` and `oss`.
The following throws the exception even without the try/catch/throw in `mkdir`:
```
$ps = [powershell]::create()
$ps.AddScript("mkdir -Path blahhfe:\jkfjkjakfklajlkf -ea stop") > $null
$ps.Invoke()
```

**Pull request merged**
