### PR TITLE
Use params in ImportPSModule() definition

### LINKED ISSUE #6005: `ImportPSModule` on `InitialSessionState` should be `params`.
Functions in the automation API which take arrays should take them as `params`.

For example [this](https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/InitialSessionState.cs#L1883) should be:

```csharp
        public void ImportPSModule(params string[] name)
        {
            if (name == null)
                throw new ArgumentNullException("name");
            foreach (string n in name)
            {
                ModuleSpecificationsToImport.Add(new ModuleSpecification(n));
            }
        }
```

A developer should not _have_ to call this by newing up an array of strings.

### PR DESCRIPTION
**Pull request by iSazonov**
## PR Summary

Close #6005.

Change method definition 
from ` public void ImportPSModule(string[] name)`
to ` public void ImportPSModule(params string[] name)`

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
Should we add the change to SDK?
Should we document this in PowerShell-Docs repo?

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]
Can we add a test?

**Review by SteveL-MSFT — APPROVED** [review]
Since we don't have existing tests, I won't block this PR.  Based on the discussion of concerns of app compat (even though it was agreed it wouldn't be an issue), it would be nice to have some tests to validate.

**Comment by iSazonov** [comment]
@SteveL-MSFT I think we need __SDK__ test set.

**Comment by iSazonov** [comment]
@twitchax  Could you please check that the change works as expected and we haven't regression?

**Comment by iSazonov** [comment]
@twitchax Can you confirm that you can compile your code after the change?

**Comment by twitchax** [comment]
Yeah: totally fine.

**Pull request merged**
