### PR TITLE
Fix file blocking issue with webcmdlets

### LINKED ISSUE #7669: Webcmdlets using -InFile parameter locks file
Currently when you upload a file via Invoke-Restmethod or Invoke-Webrequest and use the -InFile parameter, it puts a lock on the file, so no other process can read it.  It does not set seem to set the `FileShare.Read` flag

(https://github.com/PowerShell/PowerShell/blob/f5a7d79175248e1efae1232732d361f0ef7322a4/src/Microsoft.PowerShell.Commands.Utility/commands/utility/WebCmdlet/Common/WebRequestPSCmdlet.Common.cs#L1221)

I am trying to parallelize to upload of single files to multiple locations.

Steps to reproduce
------------------
Run below command twice at the same time, either in multiple PS hosts, via jobs or runspaces.

```powershell
Invoke-RestMethod -uri "https://artifactory/artifactory/my-tools/testfile.iso" -Method Put -InFile "C:\temp\testfile.iso" -Credential $creds -ContentType "multipart/form-data"
```

Expected behavior
-----------------
I would not expect this to error since it is a read operation, I would suggest that the file is opened with `FileShare.Read` Flag, so you can have multiple processes access the file at the same time.
```none

```

Actual behavior
---------------
When you run the commands simultaneously, you will get an `The process cannot access the file 'C:\temp\testfile.iso' because it is being used by another process.` error

```none

```

Environment data
----------------

```powershell
> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Microsoft Windows 10.0.17738
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


```

### PR DESCRIPTION
**Pull request by Claustn**
## PR Summary

Resolve #7669.

Allows multiple uploads of the same file in parallel

This PR changes how -InFile parameter on the Web cmdlets open file handles. Previously the file was opened with ShareAccess None, meaning that the file was locked, resulting in that you, for instance, was not able to upload the same file to multiple destinations in parallel.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
@Claustn Thanks! I slightly corrected the PR title and description.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@Claustn Please rename your commit - start title with `[Feature]` or add new empty commit with title `[Feature]` - this will run full test set.

**Review by powercode — COMMENTED** [review]
LGTM!

**Comment by iSazonov** [comment]
CI Appveyor temporary failed.

**Review by PaulHigin — APPROVED** [review]
LGTM

**Review by markekraus — COMMENTED** [review]
LGTM. My approval is pending successful completion of all `[feature]` tests.

**Comment by iSazonov** [comment]
@Claustn Thanks for discovering the issue and fixing it!

**Pull request merged**
