### PR TITLE
WIP: Change WMF4 pre-req check in MSI installer to a warning

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

Currently, the MSI installer does a check to see if version of pwrshplugin.dll is compatible with PSCore6.  This requires WMF4 or newer.  If the check fails, the installer fails.  However, there are valid use cases where the user may not care about WinRM based remoting.  Fix is to change this to a warning message and also disable the checkbox to enable PSRemoting.

Screenshot

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
cc @bergmeister to help review

**Comment by alexandair** [comment]
Warning message:
"...required to enable PowerShell remoting over..."

**Comment by iSazonov** [comment]
Could we make the link clickable?

**Review by bergmeister — APPROVED** [review]
Looks OK from a WiX perspective but I am wondering if it would be better to move the checkbox to the bottom to allow for alignment of the text with the checkbox because to an end user it is not obvious that the checkbox is disabled due to that text. Also, if you consider people who are not interested in remoting: They will get alerted due to the red text and waste time reading and thinking about the text. From a UX perspective, popping a dialog box when attempting to check the EnableRemoting checkbox would be an alternative.

**Comment by bergmeister** [comment]
@iSazonov I remember getting hyperlinks to work in the past, which was not possible, but [this](https://stackoverflow.com/a/45813037/1810304) Thread indicates that WiX 1.11 added this capability.

**Comment by iSazonov** [comment]
If the PR is targeted on 6.1.0 GA I believe we should merge "as is". Any other enhancement carries a risk to break something.

**Comment by SteveL-MSFT** [comment]
@iSazonov this is not required for GA.  We can take it for 6.2.  Anyone who wants to install PSCore6 and not WMF4 on downlevel can use the .zip pkg today.

**Comment by iSazonov** [comment]
Then I suggest to insert pre-request check step on first place and accumulate all pre-request checks there like WMF4, libssl and so on. Results can be in text log. With a button to show. With blocking Next if the checks failed.

**Comment by anmenaga** [comment]
I restarted 'PowerShell-CI-linux' test run.

**Comment by SteveL-MSFT** [comment]
@iSazonov that's a good suggestion, we can use a warning icon for warnings and a red X for any blocking pre-reqs.  Let me think more about this after 6.1 GA.

**Comment by iSazonov** [comment]
@SteveL-MSFT I know Exchenge Server team use that in their installer.

**Comment by iSazonov** [comment]
We could look WiX Bootstrapper.

**Comment by SteveL-MSFT** [comment]
WiX Bootstrapper appears to help install dependencies.  However, it seems there's a set of users who want to use PSCore6 w/o installing WMF4 so I don't think the Bootstrapper will help here.  It would help with other dependencies that are required for .Net Core.

**Comment by iSazonov** [comment]
> there's a set of users who want to use PSCore6 w/o installing WMF4

Is this supported? I think such users should install from zip, yes?

**Comment by SteveL-MSFT** [comment]
@iSazonov actually, that is an excellent point!  I agree that non-standard use should use the zip.  So in that case, we should look at Bootstrapper to help with pre-reqs.  I'm closing this PR and opened issue https://github.com/PowerShell/PowerShell/issues/8176

**Comment by SteveL-MSFT** [comment]
@bergmeister that is a good point about offline installs.  The Bootstrapper has capability to check for files before doing an install of a pre-req.  This means that if the customer has pre-installed the pre-reqs, then the Bootstrapper becomes a no-op.  It seems like the zip is sufficient for edge cases like where the user doesn't care about remoting.  If this is really a mainstream case and not an edge case, we can certainly revisit this.

**Pull request closed without merging**
