### PR TITLE
Add gitkracken files to gitignore

### PR DESCRIPTION
**Pull request by RDIL**
## PR Summary

GitKracken is a pretty popular git client so let’s ignore useless files it makes

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [X] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- **Testing - New and feature**
    - [X] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by RDIL** [comment]
Sorry don’t know why the rest isn’t rendering, meant to say it’s a popular git client and those files shouldn’t be committed.

**Review by TravisEz13 — APPROVED** [review]

**Comment by PSVortex** [comment]
@RDIL Not `gkconfg.yml` but `gkconfig.yml`

**Comment by RDIL** [comment]
Sorry!

**Comment by TravisEz13** [comment]
Thank you @PSVortex 	 for you contribution and @RDIL 	 for your review.

**Comment by RDIL** [comment]
other way round xD

**Comment by TravisEz13** [comment]
Sorry...

**Comment by RDIL** [comment]
Haha it’s fine

**Pull request merged**
