### PR TITLE
Add CommandLine property to Process

### LINKED ISSUE #3322: Extend Process with CommandLine property
Add a CodeMethod to extend System.Diagnostics.Process with CommandLine to be able to see how a process was started.

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Fix #3322 on Windows and Linux. For MacOs we will open new tracking issue to implement later.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by adityapatwardhan** [comment]
@iSazonov can you give a before and after for a perf comparison? Call `Get-CimInstance` or `Get-Content` for every `System.Diagnostics.Process` object sounds expensive.

The test can be as simple as:

```PowerShell
Measure-command { 1..100 | % { get-process } }
```

**Comment by iSazonov** [comment]
@adityapatwardhan It is "on demand" property - you evaluate it only if you explicitly call the property. But if you call you get a slowdown. It is not in default output so users don't see slowdown in common scenarios.
Notice, I found WMI is very fast on latest Windows versions (Windows 10 and Windows Server 2019). If someone provides feedback that it's still slow we could consider a P/Invoke. 
On Linux `/proc` works fast. 
For MacOs I do not know API. I am going to open new tracking issue for this after the PR will be merged.

**Comment by iSazonov** [comment]
Using `/proc` is simple and reliable on Linux so no need to create a workaround.
I haven't Mac and can not create even a workaround. Nonetheless I hope there is a good API for that.

**Comment by adityapatwardhan** [comment]
@TravisEz13 @JamesWTruher Do you know of a macOS workaround for this?

**Comment by adityapatwardhan** [comment]
@iSazonov I am not sure if we should take this PR without having a solution for all platforms. This introduces gotchas and makes cross platform scripting difficult.

@iSazonov @SteveL-MSFT - thoughts?

**Comment by iSazonov** [comment]
My plan is to open a tracking issue for MacOs. We have a lot of time before release and can investigate how enhance the feature on MacOs.

**Comment by powercode** [comment]
The APIs will probably require some native coding on the mac.

**Review by adityapatwardhan — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
@iSazonov Please open a tracking bug for macOS and also open a issue for documentation as per the PR template.

**Comment by iSazonov** [comment]
@adityapatwardhan Tracking issue #12832

As for doc issue - do we really need to document this? It seems we haven't docs for extended properties at all.
/cc @sdwheeler

**Comment by sdwheeler** [comment]
@iSazonov No, we don't document the extended properties. But this is worth adding to the release notes.

**Comment by adityapatwardhan** [comment]
@iSazonov Thank you for your contribution!

**Pull request merged**
