### PR TITLE
WIP: Enable CA1822 for types with internal visibility

### PR DESCRIPTION
**Pull request by xtqqczze**
Non-breaking change as fixes are only for types with an effective visibility of internal.

https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1822

_Follow-up to: #13897._

### CODE REVIEW

**Comment by xtqqczze** [comment]
```log
D:\a\1\s\src\Microsoft.PowerShell.Commands.Diagnostics\PdhHelper.cs(1019,21): error CA1822: Member 'LookupPerfNameByIndex' does not access instance data and can be marked as static [D:\a\1\s\src\Microsoft.PowerShell.Commands.Diagnostics\Microsoft.PowerShell.Commands.Diagnostics.csproj]
D:\a\1\s\src\Microsoft.PowerShell.Commands.Diagnostics\PdhHelper.cs(1136,23): error CA1822: Member 'GetCounterSetHelp' does not access instance data and can be marked as static [D:\a\1\s\src\Microsoft.PowerShell.Commands.Diagnostics\Microsoft.PowerShell.Commands.Diagnostics.csproj]
```

I thought `src\Microsoft.PowerShell.Commands.Diagnostics\PdhHelper.cs` was not compiled (https://github.com/PowerShell/PowerShell/pull/14491#issuecomment-827944838), yet we have a code quality diagnostic being reported?

**Comment by iSazonov** [comment]
> I thought `src\Microsoft.PowerShell.Commands.Diagnostics\PdhHelper.cs` was not compiled ([#14491 (comment)](https://github.com/PowerShell/PowerShell/pull/14491#issuecomment-827944838)), yet we have a code quality diagnostic being reported?

No, please exclude non-compliling code and frozen code too.

**Comment by xtqqczze** [comment]
> > I thought `src\Microsoft.PowerShell.Commands.Diagnostics\PdhHelper.cs` was not compiled ([#14491 (comment)](https://github.com/PowerShell/PowerShell/pull/14491#issuecomment-827944838)), yet we have a code quality diagnostic being reported?
> 
> No, please exclude non-compliling code and frozen code too.
> 
> Also 68 files are too many for review. Please split the PR on some parts.

`PdhHelper.cs` is compiled, but only on Windows:

https://github.com/PowerShell/PowerShell/blob/0f2f23f67a2c3ec53cf82c8d1a67b479f62934e4/src/Microsoft.PowerShell.Commands.Diagnostics/Microsoft.PowerShell.Commands.Diagnostics.csproj#L24-L28

**Comment by kmccl922** [comment]
Stop sending me these messages i will report you'll 

Sent from Yahoo Mail on Android 
 
  On Wed, Nov 24, 2021 at 5:53 AM, ***@***.***> wrote:   


Reopened #15838.

**Pull request closed without merging**
