### PR TITLE
Fix stylecop hungarian 

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Add very popular "is" and "_is" prefixes.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
Should we just enable [allowCommonHungarianPrefixes](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md#hungarian-notation)?  It seems that you don't need to explicitly specify the leading underscore version?

**Comment by iSazonov** [comment]
CodeFactor still reports "is" and "_is" https://www.codefactor.io/repository/github/powershell/powershell/issues?category=Style&groupId=15

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
some tools read from master and don't use the configuration files from the PR.  I'm just guessing.

**Comment by SteveL-MSFT** [comment]
It's actually difficult to read the updated config from a PR as the json you get back is just the diff of the file and not the complete file.  This is why for @PoshChan I always look in master rather than trying to generate the resulting config file from master + diff.

**Comment by iSazonov** [comment]
@TravisEz13 There is really a problem. As @SteveL-MSFT mentioned above  allowCommonHungarianPrefixes enabled "is" by default - I found [this](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/57821a1c4d014e8d80b3e236ff444e0e30d8a112/StyleCop.Analyzers/StyleCop.Analyzers/NamingRules/SA1305FieldNamesMustNotUseHungarianNotation.cs#L65) in source code too. But CodeFactor continues to report "is". We can see this in previous @daxian-dbw PR #8500 - it seems CodeFactor read config from commit - and then in master too.

**Comment by iSazonov** [comment]
@SteveL-MSFT @TravisEz13 @daxian-dbw 

I received a response from the CodeFactor support:

>Thank you for reaching out.  
CodeFactor supports Settings.StyleCop file as config, but not stylecop.json (it will be supported once https://github.com/DotNetAnalyzers/StyleCopAnalyzers/releases is out of RC). 
So, you can still configure StyleCop to do what allowCommonHungarianPrefixes proposes by modifying Settings.StyleCop file (e.g. https://stackoverflow.com/a/45606734) 
Please let me know if I was able to address your inquiry or if you need anything else.  
Thank you, 


So I reverted previous commit and change Settings.StyleCop as recommended. You can see that now CodeFactor reports "2253 issues fixed."

**Review by SteveL-MSFT — APPROVED** [review]

**Review by TravisEz13 — APPROVED** [review]

**Pull request merged**
