### PR TITLE
Fix for Stop-Service failure with less privileged user when not setting SDDL.

### LINKED ISSUE #16649: PWSH 7.2.1: Set-Service: Service * cannot be configured due to the following error: Access is denied.
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Open PWSH as Adminstrator via Start > PowerShell > PowerShell 7 (x64) > Run as Administrator and run the below command. In Windows PowerShell 5.1.x it works fine. Hence, seems a regression.
I haven't tried the command in any prior PWSH version.
Also, SCPolicySvc is not the only service set-service fails to set with the same error message. However, it doesn't fail to set all services, just certain ones.

### Expected behavior

```console
PS C:\WINDOWS\system32> set-service -name SCPolicySvc -startuptype disabled ; stop-service -name SCPolicySvc -force
PS C:\WINDOWS\system32>
```

### Actual behavior

```console
PS C:\Windows\System32> set-service -name SCPolicySvc -startuptype disabled ; stop-service -name SCPolicySvc -force
Set-Service: Service 'Smart Card Removal Policy (SCPolicySvc)' cannot be configured due to the following error: Access is denied.
PS C:\Windows\System32>
```

### Error details

```console
get-error

Exception             :
    Type           :
Microsoft.PowerShell.Commands.ServiceCommandException
    ServiceName    : SCPolicySvc
    Message        : Service 'Smart Card Removal Policy
(SCPolicySvc)' cannot be configured due to the following error:
Access is denied.
    InnerException :
        Type            : System.ComponentModel.Win32Exception
        NativeErrorCode : 5
        ErrorCode       : -2147467259
        Message         : Access is denied.
        HResult         : -2147467259
    HResult        : -2146233087
TargetObject          : System.ServiceProcess.ServiceController
CategoryInfo          : PermissionDenied:
(System.ServiceProcess.ServiceController:ServiceController)
[Set-Service], ServiceCommandException
FullyQualifiedErrorId : CouldNotSetService,Microsoft.PowerSh
ell.Commands.SetServiceCommand
InvocationInfo        :
    MyCommand        : Set-Service
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 359
    Line             : set-service -name SCPolicySvc
-startuptype disabled ; stop-service -name SCPolicySvc -force
    PositionMessage  : At line:1 char:1
                       + set-service -name SCPolicySvc
-startuptype disabled ; stop-service -n …
                       +
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    InvocationName   : set-service
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :




PS C:\Windows\System32>
```

### Environment data

```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.1
PSEdition                      Core
GitCommitId                    7.2.1
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Windows\System32>
```

### Visuals

image

### PR DESCRIPTION
**Pull request by kvprasoon**
# PR Summary

This PR is to fix bug in `Stop-Service`, it fails when a less privileged  user tries to Set service properties using `Set-Service` cmdlet without using `-SecurityDescriptorSddl` parameter.

Fixes: #16649 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed: #16649
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by iSazonov — COMMENTED** [review]
@kvprasoon Please open new issue in Docs repository to update SecurityDescriptorSddl parameter description for the scenario (what permissions users need to exclude access denied error).

**Comment by kvprasoon** [comment]
@iSazonov https://github.com/MicrosoftDocs/PowerShell-Docs/issues/8443

**Comment by kvprasoon** [comment]
@iSazonov @TravisEz13 @daxian-dbw  anything else ?

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@TravisEz13 Friendly ping.

**Review by SteveL-MSFT — APPROVED** [review]

**Review by TravisEz13 — APPROVED** [review]

**Pull request merged**
