### PR TITLE
Fix Tests from #4479

### PR DESCRIPTION
**Pull request by markekraus**
My Bad... the tests I had in #4479 were failing in the nightly. This fixes them and now they now pass and fail for the right reasons.

### CODE REVIEW

**Comment by adityapatwardhan** [comment]
@markekraus Thanks for fixing the tests. Can you run 'Feature' tests to validate that all the required tests are executed. 

The documentation for executing additional tests is at: https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md

Look for the section titled 'Requesting additional tests for a PR'

**Comment by adityapatwardhan** [comment]
@markekraus I have pushed an empty commit to execute the feature tests.

**Comment by markekraus** [comment]
@adityapatwardhan Thank you. I will make sure to do this in the future.

**Comment by markekraus** [comment]
@adityapatwardhan The tests pass pass now.

* [AppVeyor L7736](https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-beta.5-4549#L7736)
* [AppVeyor L7737](https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-beta.5-4549#L7737)
* [AppVeyor L7739](https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-beta.5-4549#L7739)
* [AppVeyor L7926](https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-beta.5-4549#L7926)
* [AppVeyor L7927](https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-beta.5-4549#L7927)
* [AppVeyor L7929](https://ci.appveyor.com/project/PowerShell/powershell/build/6.0.0-beta.5-4549#L7929)

The [Travis CI failure](https://travis-ci.org/PowerShell/PowerShell/jobs/261953384#L693) appears to be unrelated.

**Comment by adityapatwardhan** [comment]
@markekraus Restarted the tests on Travis CI.

**Comment by markekraus** [comment]
@adityapatwardhan All Travis CI Tests passing now as well

* [Travis CI L8863](https://travis-ci.org/PowerShell/PowerShell/jobs/261953384#L8863)
* [Travis CI L8864](https://travis-ci.org/PowerShell/PowerShell/jobs/261953384#L8864)
* [Travis CI L8865](https://travis-ci.org/PowerShell/PowerShell/jobs/261953384#L8865)
* [Travis CI L9029](https://travis-ci.org/PowerShell/PowerShell/jobs/261953384#L9029)
* [Travis CI L9030](https://travis-ci.org/PowerShell/PowerShell/jobs/261953384#L9030)
* [Travis CI L9031](https://travis-ci.org/PowerShell/PowerShell/jobs/261953384#L9031)

**Comment by adityapatwardhan** [comment]
@daxian-dbw Can you have a quick look? This fixes the daily build failure.

**Review by daxian-dbw — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
@markekraus  Thanks for fixing the tests.

**Pull request merged**
