### PR TITLE
Rid of ResolveLinkTarget from IsWindowsApplication

### LINKED ISSUE #16293: OperationStopped: Incorrect function when running an exe from a mounted ISO
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

My repro steps:
- Download the Enterprise WDK: https://docs.microsoft.com/en-us/windows-hardware/drivers/other-wdk-downloads
- Mount the ISO (Mount-DiskImage -ImagePath S:\iso\dev\EWDK_fe_release_20348_210507-1500.iso).
- From a "cmd.exe" prompt, run LaunchBuildEnv.cmd amd64
- Start Powershell 7.2 RC1: "c:\Program Files\PowerShell\7-preview\pwsh.exe"
- Run MSBuild.exe

But I do _not_ think this is linked to the EWDK but the fact I'm running a exe from a mounted iso.
(was running just fine with 7.1.5 or the previous 7.2 preview)

### Expected behavior

```console
Successfully run msbuild.exe
```

### Actual behavior

```console
OperationStopped: Incorrect function. : 'E:\Program Files\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin\MSBuild.exe'
```

### Error details

```console
Exception             :
    Type       : System.IO.IOException
    TargetSite :
        Name          : GetImmediateLinkTarget
        DeclaringType : System.IO.FileSystem, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral,
PublicKeyToken=7cec85d7bea7798e
        MemberType    : Method
        Module        : System.Private.CoreLib.dll
    Message    : Incorrect function. : 'E:\Program Files\Microsoft Visual
Studio\2019\BuildTools\\MSBuild\Current\Bin\MSBuild.exe'
    Data       : System.Collections.ListDictionaryInternal
    Source     : System.Private.CoreLib
    HResult    : -2147024895
    StackTrace :
   at System.IO.FileSystem.GetImmediateLinkTarget(String linkPath, Boolean isDirectory, Boolean throwOnError, Boolean
returnFullPath)
   at System.IO.FileSystem.ResolveLinkTarget(String linkPath, Boolean returnFinalTarget, Boolean isDirectory)
   at System.IO.File.ResolveLinkTarget(String linkPath, Boolean returnFinalTarget)
   at System.Management.Automation.NativeCommandProcessor.IsWindowsApplication(String fileName)
   at System.Management.Automation.NativeCommandProcessor.InitNativeProcess()
   at System.Management.Automation.NativeCommandProcessor.Prepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.CommandProcessorBase.DoPrepare(IDictionary psDefaultParameterValues)
   at System.Management.Automation.Internal.PipelineProcessor.Start(Boolean incomingStream)
   at System.Management.Automation.Internal.PipelineProcessor.SynchronousExecuteEnumerate(Object input)
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput,
CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections,
FunctionContext funcContext)
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
CategoryInfo          : OperationStopped: (:) [], IOException
FullyQualifiedErrorId : System.IO.IOException
InvocationInfo        :
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : -1
    Line             : msbuild.exe
    PositionMessage  : At line:1 char:1
                       + msbuild.exe
                       + ~~~~~~~~~~~
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.2.0-rc.1
PSEdition                      Core
GitCommitId                    7.2.0-rc.1
OS                             Microsoft Windows 10.0.22000
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

image

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

~~Fix #16293 I tested manually and confirm the fix works for mounted ISOs.~~

~~New test is based on ISO with FAT file system (no reparse point support).~~

I prepared the PR as performance improvement a week before #16293 :-)

``` ini

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19041.1288 (2004/?/20H1)
Intel Core i5-2410M CPU 2.30GHz (Sandy Bridge), 1 CPU, 4 logical and 2 physical cores
.NET Core SDK=6.0.100-rc.2.21505.57
  [Host]     : .NET Core 6.0.0 (CoreCLR 6.0.21.48005, CoreFX 6.0.21.48005), X64 RyuJIT
  DefaultJob : .NET Core 6.0.0 (CoreCLR 6.0.21.48005, CoreFX 6.0.21.48005), X64 RyuJIT


```
|      Method |           TestString |      Mean |    Error |   StdDev | Ratio |
|------------ |--------------------- |----------:|---------:|---------:|------:|
|    IsWindowsApplication | C:\Us(...)e.exe [60] | 145.86 us | 1.450 us | 1.286 us |  1.00 |
| IsWindowsApplicationNew | C:\Us(...)e.exe [60] |  82.41 us | 1.437 us | 1.345 us |  0.57 |

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by daxian-dbw — DISMISSED** [review]

**Comment by daxian-dbw** [comment]
I run benchmarks for both the current `SHGetFileInfo` and the `PEHeader` approaches, and the result shows that the `PEHeader` approach is not as performant as the existing `SHGetFileInfo` approach.

As is shown in the results, the `RunOld` is always faster than `RunNew`. `RunOld` uses `SHGetFileInfo` while `RunNew` uses `PEHeader`. Especially for `wt.exe` (store app) and `result.txt` (file with shell-associated app), it's way slower using the `PEHeader` approach. This is because
- for store app, an exception is thrown to get the result when using `PEHeader`;
- for files, the whole file will be read into memory when using `PEHeader`.

Given this, I don't think we should make changes to the existing code.

```
BenchmarkDotNet=v0.13.0, OS=Windows 10.0.19043.1288 (21H1/May2021Update)
Intel Core i7-1065G7 CPU 1.30GHz, 1 CPU, 8 logical and 4 physical cores
.NET SDK=6.0.100-rc.2.21505.57
  [Host]   : .NET 6.0.0 (6.0.21.48005), X64 RyuJIT
  .NET 6.0 : .NET 6.0.0 (6.0.21.48005), X64 RyuJIT

Job=.NET 6.0  Runtime=.NET 6.0

| Method |              ExePath |           Mean |        Error |       StdDev |         Median |
|------- |--------------------- |---------------:|-------------:|-------------:|---------------:|
| RunOld | C:\Pr(...)h.exe [38] |    51,141.1 ns |    609.53 ns |    570.16 ns |    51,159.3 ns |
| RunNew | C:\Pr(...)h.exe [38] |    54,983.0 ns |    968.27 ns |    905.72 ns |    55,131.4 ns |
| RunOld | C:\Us(...)t.exe [57] |    18,302.6 ns |    386.74 ns |  1,128.13 ns |    18,002.8 ns |
| RunNew | C:\Us(...)t.exe [57] |    35,779.6 ns |    520.25 ns |    486.64 ns |    35,571.9 ns |
| RunOld | C:\WI(...)d.exe [31] |    60,472.8 ns |    954.44 ns |    846.08 ns |    60,254.5 ns |
| RunNew | C:\WI(...)d.exe [31] |    64,938.8 ns |  1,176.96 ns |  1,043.34 ns |    64,702.2 ns |
| RunOld | C:\ar(...)t.txt [23] |       179.8 ns |      2.97 ns |      2.48 ns |       179.5 ns |
| RunNew | C:\ar(...)t.txt [23] | 1,388,967.6 ns | 25,999.91 ns | 43,440.01 ns | 1,388,259.2 ns |

** C:\Pr(...)h.exe -- C:\Program Files\PowerShell\7\pwsh.exe  (console app)
** C:\Us(...)t.exe -- C:\Users\rocky\AppData\Local\Microsoft\WindowsApps\wt.exe (store app)
** C:\WI(...)d.exe -- C:\WINDOWS\system32\notepad.exe (gui app)
** C:\ar(...)t.txt -- C:\arena\tmp\result.txt (file that has shell-associated app)
```

<details><summary>Benchmark source code</summary>
<p>

#### See the Benchmark source code below

```c#
using System;
using System.IO;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Reflection.PortableExecutable;

using BenchmarkDotNet.Attributes;
using BenchmarkDotNet.Running;
using BenchmarkDotNet.Jobs;

namespace benchmark
{
    class Program
    {
        static void Main(string[] args)
        {
            var summary = BenchmarkRunner.Run<Benchmark_IsWindowsApplication>();
        }
    }

    [SimpleJob(RuntimeMoniker.Net60)]
    public class Benchmark_IsWindowsApplication
    {
        [ParamsSource(nameof(ValuesForPath))]
        public string ExePath { get; set; }

        public IEnumerable<string> ValuesForPath()
        {
            yield return @"C:\Program Files\PowerShell\7\pwsh.exe";
            yield return @"C:\WINDOWS\system32\notepad.exe";
            yield return @"C:\arena\tmp\result.txt";
            yield return @"C:\Users\rocky\AppData\Local\Microsoft\WindowsApps\wt.exe";
        }

        [Benchmark]
        public bool RunOld()
        {
            return IsWindowsApplication_OLD(ExePath);
        }

        [Benchmark]
        public bool RunNew()
        {
            return IsWindowsApplication_NEW(ExePath);
        }

        internal static bool IsWindowsApplication_NEW(string fileName)
        {
            try
            {
                using var stream = new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.Read);
                PEHeader peheader = (new PEHeaders(stream)).PEHeader;
                return peheader is not null && peheader.Subsystem == Subsystem.WindowsGui;
            }
            catch
            {
                return false;
            }
        }

        internal static bool IsWindowsApplication_OLD(string fileName)
        {
            SHFILEINFO shinfo = new SHFILEINFO();
            IntPtr type = SHGetFileInfo(fileName, 0, ref shinfo, (uint)Marshal.SizeOf(shinfo), SHGFI_EXETYPE);

            switch ((int)type)
            {
                case 0x0:
                    // 0x0 = not an exe
                    return false;
                case 0x5a4d:
                    // 0x5a4d - DOS .exe or .com file
                    return false;
                case 0x4550:
                    // 0x4550 - windows console app or bat file
                    return false;
                default:
                    // anything else - is a windows program...
                    return true;
            }
        }

        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
        private struct SHFILEINFO
        {
            public IntPtr hIcon;
            public int iIcon;
            public uint dwAttributes;

            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 260)]
            public string szDisplayName;

            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 80)]
            public string szTypeName;
        }

        private const uint SHGFI_EXETYPE = 0x000002000; // flag used to ask to return exe type

        [DllImport("shell32.dll", CharSet = CharSet.Unicode)]
        private static extern IntPtr SHGetFileInfo(string pszPath, uint dwFileAttributes,
            ref SHFILEINFO psfi, uint cbSizeFileInfo, uint uFlags);
    }
}
```

</p>
</details>

**Comment by iSazonov** [comment]
What is the reason you are measuring the opposite scenario? This optimization is just for exe files, which is the most common use. Or do you think users prefer to run wt.exe in a loop 100 times per second? :-)

**Comment by iSazonov** [comment]
> for files, the whole file will be read into memory when using PEHeader.

I don't see this in PEHeader sources - it seek a offset only.

**Comment by iSazonov** [comment]
Why do you exclude File.ResolveLinkTarget from IsWindowsApplication_OLD? Sly! :-)

**Comment by daxian-dbw** [comment]
> Why do you exclude File.ResolveLinkTarget from IsWindowsApplication_OLD? Sly! :-)

Yeah, I missed that line of code :) But it also occurred to me that we don't need that line of code today given that it doesn't work for Windows Store apps (`AppExeCLinks`).

The whole reason that `InternalSymbolicLinkLinkCodeMethods.WinInternalGetTarget(fileName)` was originally [added here](https://github.com/PowerShell/PowerShell/pull/13481/files#diff-f4036ed1a5c3c9f35845bfd272e345992a55ee26e27bdf38446ab9c66e971aafR978-R986) was to fix for the Windows Store apps. You submitted the PR #13481, remember? :)

`WinInternalGetTarget` was replaced by `File.ResolveLinkTarget` when deprecating `WinInternalGetTarget`, but since there is no documented API to retrieve the actual target of a Windows Store app, there is no point to keep `File.ResolveLinkTarget` anymore. **We can totally remove that for now, until the regarding API gets documented.**

> What is the reason you are measuring the opposite scenario? This optimization is just for exe files, which is the most common use. Or do you think users prefer to run wt.exe in a loop 100 times per second? :-)

The `PEHeader` approach is generally slower than `SHGetFileInfo`, not just `wt.exe`. Directly execute a document is also quite common, like an excel, an .txt file, or a word file.

> Also Windows team doesn't publish APIs for appx. So we can not detect whether it is a console or GUI and so on. Before we could do something useful for appx MSFT must introduce public API for this.

Yeah, both approaches return `false` for Windows Store app, but the `PEHeader` one requires exception handling for that, so it's way slower. Yeah, this is not a common scenario, but like I said, the `PEHeader` is slower in general, for all 4 scenarios tested.

> I don't see this in PEHeader sources - it seek a offset only.

I didn't look into the `PEHeader` source, maybe that's caused by creating a `FileStream`.

**Comment by iSazonov** [comment]
So I understand from your comment that negotiations with Windows team were fruitless and we will not get public appx API. In the case, yes, we should simply remove `File.ResolveLinkTarget` and obviously one p/invoke `SHGetFileInfo` will be faster than `PEHeader`.

**Comment by daxian-dbw** [comment]
From the last conversation with the Windows Store team about this, they said it was by-design to not document that API, because they might change how the mapping goes behind the scene.

I don't think anyone from our team has started the conversation again after we learnt about this regression in `NativeCommandProcessor`, and I don't know if that will change any of their decision. But if they documented the API, .NET team will update `ResolveLinkTarget` to support `AppExeLink`, so we can just add back `File.ResolveLinkTarget` when that day comes.

Can you maybe update your PR to remove `File.ResolveLinkTarget` in this code path?

**Comment by iSazonov** [comment]
> Can you maybe update your PR to remove File.ResolveLinkTarget in this code path?

Too long path :-) Will do new PR.

**Comment by daxian-dbw** [comment]
Yeah, a new PR is better, making the purpose clearer too.
Please make sure the new PR description captures the gist of https://github.com/PowerShell/PowerShell/pull/16295#issuecomment-959748719. Thanks!

I will close this PR then.

**Review by t10-13rocket — APPROVED** [review]
LGTM

**Pull request closed without merging**
