### PR TITLE
Update to Pester 4.8.0, revert workaround for long paths

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 2 failures in `PowerShell-CI-macos`
Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1:11 char:30
```
Convert-Path tests.Convert-Path supports pipelined input by property name
```powershell
Expected exactly /private/tmp/1eb7c052-e3dc-4190-87fc-517831f76f7d, but got '/private/tmp/1eb7c052-e3dc-4190-87fc-517831f76f7d'.
at <ScriptBlock>, /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Convert-Path.Tests.ps1: line 17
17:         Get-Item -Path $TestDrive | Convert-Path | Should -BeExactly $TestDrive
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 4 failures in `PowerShell-CI-windows`
PowerShellGet - Module tests (Admin).Error occurred in Describe block
```powershell
Exception calling "ShouldContinue" with "2" argument(s): "Object reference not set to an instance of an object."
At D:\a\1\s\src\powershell-win-core\bin\release\netcoreapp3.0\win7-x64\publish\Modules\PowerShellGet\PSModule.psm1:11044 char:9
```
PowerShellGet - Script tests (Admin).Error occurred in Describe block
```powershell
Exception calling "ShouldContinue" with "2" argument(s): "Object reference not set to an instance of an object."
At D:\a\1\s\src\powershell-win-core\bin\release\netcoreapp3.0\win7-x64\publish\Modules\PowerShellGet\PSModule.psm1:11044 char:9
```
Convert-Path tests.Convert-Path supports pipelined input by property name
```powershell
Expected exactly C:\Users\VssAdministrator\AppData\Local\Temp\5c5ea23b-c5eb-4961-80ab-215d46ac7de3, but got 'C:\Users\VssAdministrator\AppData\Local\Temp\5c5ea23b-c5eb-4961-80ab-215d46ac7de3'.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\Convert-Path.Tests.ps1: line 17
17:         Get-Item -Path $TestDrive | Convert-Path | Should -BeExactly $TestDrive
```
Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\Send-MailMessage.Tests.ps1:11 char:30
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 2 failures in `PowerShell-CI-linux`
Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1:11 char:30
```
Convert-Path tests.Convert-Path supports pipelined input by property name
```powershell
Expected exactly /tmp/8ca21578-b180-40db-9d10-89dbb6d09b1d, but got '/tmp/8ca21578-b180-40db-9d10-89dbb6d09b1d'.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Convert-Path.Tests.ps1: line 17
17:         Get-Item -Path $TestDrive | Convert-Path | Should -BeExactly $TestDrive
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-macos`
Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1:11 char:30
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 3 failures in `PowerShell-CI-windows`
PowerShellGet - Module tests (Admin).Error occurred in Describe block
```powershell
Exception calling "ShouldContinue" with "2" argument(s): "Object reference not set to an instance of an object."
At D:\a\1\s\src\powershell-win-core\bin\release\netcoreapp3.0\win7-x64\publish\Modules\PowerShellGet\PSModule.psm1:11044 char:9
```
PowerShellGet - Script tests (Admin).Error occurred in Describe block
```powershell
Exception calling "ShouldContinue" with "2" argument(s): "Object reference not set to an instance of an object."
At D:\a\1\s\src\powershell-win-core\bin\release\netcoreapp3.0\win7-x64\publish\Modules\PowerShellGet\PSModule.psm1:11044 char:9
```
Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Utility\Send-MailMessage.Tests.ps1:11 char:30
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 1 failures in `PowerShell-CI-linux`
Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1:11 char:30
```

**Comment by SteveL-MSFT** [comment]
The current failures are due to PackageManagement issue that's been fixed, but waiting on a new version to be published to PSGallery

**Comment by iSazonov** [comment]
It seems PackageManagement is last issue, yes?
Make sense to have in future a branch to run tests everyday for latest .Net Core builds? In the case we will see breaking change earlier.

**Comment by SteveL-MSFT** [comment]
@iSazonov PkgMgmt is last known issue.  However, due to issue in PkgMgmt, it's causing the tests in CI to timeout so any tests that exist after it aren't getting run.  So after PkgMgmt fix, we may have additional failures.

I don't know if we can really automate picking up latest .NET Core builds.  Part of the issue is that we need a coherent build which aligns the SDK, runtime, and ASPNETCORE which doesn't come out that frequently.  Also, there's usually changes in MSBuild that can break us.  This may have to stay as a manual process.

One we have a good build, we do have improvements in our Release Automation so we should (soon) be seeing daily runs across our entire supported platforms instead of just a specific version of Linux, macOS, and Windows.  (macOS may be limited to what AzDevOps supports...)

**Comment by SteveL-MSFT** [comment]
@PoshChan please remind me in 1 minute

**Comment by PoshChan** [comment]
@SteveL-MSFT, this is the reminder you requested 1 minute ago

**Pull request merged**
