### PR TITLE
Align name schemes for test files

### PR DESCRIPTION
**Pull request by ThreeFive-O**
# PR Summary

Renames three test files to be in line with the rest of naming scheme of the other test files and the respective cmdlet name.
- FormatHex.Tests.ps1 -> Format-Hex.Tests.ps1
- NewTemporaryFile.Tests.ps1 -> New-TemporaryFile.Tests.ps1
- NewGuid.Tests.ps1 -> New-Guid.Tests.ps1

## PR Context

Test files mostly follow the name scheme of the respective cmdlet name in PowerShell.
No code changes are made. It's more of a cosmetic change.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
There is still NewGuid.

**Comment by ThreeFive-O** [comment]
Thank you very much @iSazonov. I've renamed it and modified the PR description accordingly.

**Comment by RDIL** [comment]
I feel like this should have the Changelog Automation tag `CL-Test` since this modifies test files.

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Pull request merged**
