### PR TITLE
Adding ValidateNotNullOrEmpty attribute to parameters listed in #2672

### PR DESCRIPTION
**Pull request by dlwyatt**
Do changes to parameter metadata require tests?  If so, should they be located with the tests for each individual command, or would it be sufficient to write a single `It` block with `-TestCases` to hit all of the affected commands in this issue / PR?

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
I imagine we'd eventually have tests per cmdlet to keep it organized so I would prefer having individual tests scripts we would eventually build up for complete test coverage

CC @JamesWTruher

**Comment by HemantMahawar** [comment]
@dlwyatt Agree with @SteveL-MSFT and that's the approach we have used with #2542 and #2545 as well.

**Comment by iSazonov** [comment]
Perhaps we should add the relevant comments in the Provider cmdlets why we don't fix them to block accidental changes in future.

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]
Get-Service -Name is missing

**Comment by dlwyatt** [comment]
Get-Service was already fixed in https://github.com/PowerShell/PowerShell/commit/67638548fc9992f2a242ed33b48eea19ea06099c .

**Comment by JamesWTruher** [comment]
i believe we do need tests against metadata changes. Strictly speaking we should really have tests which ensure that we have the proper parameters and that their configuration (type/attributes/etc) is correct.

**Comment by lzybkr** [comment]
@JamesWTruher - are you fine with accepting the PR without tests?

If we do add tests, I'd rather see that we test behaviors, e.g. that `Get-Service -Name $null` throws, and not test that the metadata is what is "expected".

When I've seen test failures that validated implementation details, the fix was always to change the expectations in the test, which to me means the test wasn't catching anything, it was just duplicating the code in a test.

**Review by lzybkr — APPROVED** [review]

**Pull request merged**
