### PR TITLE
Add in Url Alias for IRM/IWR Cmdlets

### LINKED ISSUE #16658: Add URL alias to URI parameters on Invoke-WebRequest & Invoke-RestMethod
### Summary of the new feature / enhancement

Add Alias to the `URI` parameter on Invoke-WebRequest & Invoke-RestMethod

### Proposed technical implementation details (optional)

_No response_

### PR DESCRIPTION
**Pull request by kilasuit**
# PR Summary

Fixes #16658 

## PR Context
Users may get URI/URL mixed up and by adding an alias to this shared parameter will reduce errors in interactive scripting 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
Make draft until we get a conclusion from WG in related issue.

**Comment by kilasuit** [comment]
@PaulHigin can you please review this along with the conversation in #16658 & comment on whether or not this is something that could be merged or not

**Comment by PaulHigin** [comment]
This seems like a reasonable change to me, and I don't see how this would be a breaking change.  However, the cmdlet working group should weigh in on it.  So adding that tag.

**Comment by iSazonov** [comment]
For WG. I can't agree with that _cosmetic_ addition.
1. URI is not wrong term in the context
2. Aliases are always bad thing until they do useful work. Ex., we added PSPath alias to LiteralPath parameter of many cmdlets. As result we get perf win because of skipping unneeded globbing.
3. For interactive scenario - the source of this request - we have tab-completion, suggestions and now predictions - all this makes cosmetic aliases unnecessary.

**Comment by kilasuit** [comment]
> For interactive scenario - the source of this request - we have tab-completion, suggestions and now predictions - all this makes cosmetic aliases unnecessary.

Sorry @iSazonov I have to disagree with you on especialy on that last part because you are forgetting about the non-advanced users who are coming to this language for the first time, who may not know about `tab-completion, suggestions and now predictions ` as well as those using the language for years and still don't use those to their full potential. Plus this request was as pointed out in the issue based on a long standing Microsoft FTE who correctly pointed out that muscle memory in this particular instance causes unneccessary failures, which this PR would address and is exactly why we have aliases on parameters, for improving the **user experience** not for engine perfomance gains like you mention in your 2nd point & your first isn't an issue of being technically correct, but an issue that many users **do not understand** the differnce between them and use them interchangably.

This is defiinitley more for the Interactive UX WG than the Cmdlets one I think @PaulHigin so I'm tagging @JamesWTruher & @daxian-dbw as these are their key areas from that WG

**Comment by iSazonov** [comment]
@kilasuit I could agree if we made a breaking change and _replaced_ the parameter name, but otherwise it only worsens the UX - aliases have never been a public contract and are not mentioned anywhere - neither in documentation, nor in tab completion.
And there are all kinds of newbies - those who learn and those who are lazy. You don't have to worry about the latter, and the former, if they were able to find this teamlet, no doubt they are already familiar with the list of parameters.

**Comment by kilasuit** [comment]
@iSazonov - sorry, whilst I respect your POV on just about everything else when it comes to PowerShell i have to point out that your view here is currently not correct

1) They are a part of the public contract
2) They are documented (albeit poorly) [in this doc](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced?view=powershell-7.2#long-description) but [called out fully in this section of this other doc](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_functions_advanced_parameters?view=powershell-7.2#alias-attribute)  
3) Implict parameter completion allows use of named aliases or lazy aliases
4) As @PaulHigin mentioned this isn't a breaking change and is why aliases exist to not end up being a breaking change in the first place

**Comment by daxian-dbw** [comment]
Labelled both this PR and the issue with `WG-Interactive-Console`, as the main disagreement in the discussions in #16658 is about a subtle change in tab completion for this parameter when the `Emacs` edit mode is in use, see https://github.com/PowerShell/PowerShell/issues/16658#issuecomment-1001809209.

**Comment by kilasuit** [comment]
This is currently waiting agreement based on the above mentioned comment in the issue as this has identified a potential additional change to PSReadline (raised in https://github.com/PowerShell/PSReadLine/issues/3198) to equate for adapting this particular user experience.

**Comment by kilasuit** [comment]
Reopening this PR & asking for others in the Interactive UX WG to comment on this.

**Pull request closed without merging**
