### PR TITLE
Switch to MIT license for files copied from Roslyn

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

Since https://github.com/dotnet/roslyn/issues/37797 Roslyn has used MIT license. Presumably we can now update the copyright header of these files.

Also add a comment explaining this code is from Roslyn.

There may be additional code copied from Roslyn, I found the details on these files from https://github.com/PowerShell/PowerShell/pull/6134 which I cross-checked with https://github.com/dotnet/roslyn

## PR Context

Follow-up: https://github.com/PowerShell/PowerShell/pull/6134

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@xtqqczze Please rebase to pass CIs.

**Comment by xtqqczze** [comment]
@iSazonov @daxian-dbw These files are wrapped with `#if !CORECLR`, we should review the code to see whether they are is still needed for .NET 5.0.

**Review by daxian-dbw — APPROVED** [review]

**Comment by daxian-dbw** [comment]
They are for searching assemblies in GAC in the Parser, but I cannot remember exactly for what now.

**Comment by xtqqczze** [comment]
> 
> 
> They are for searching assemblies in GAC in the Parser, but I cannot remember exactly for what now.

They are used in these files:

https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/parser/Compiler.cs#L2791
https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/parser/Parser.cs#L5079

**Comment by iSazonov** [comment]
Our ALC Resolver uses TryFindInGAC() method to search in GAC. 

The referenced code is for using assembly statement - I'd expect it would search in GAC too.

**Comment by vexx32** [comment]
I was under the impression that the GAC functionality is effectively nonexistent for .NET Core? Has that changed again in .NET 5?

**Comment by xtqqczze** [comment]
`System.Reflection.Assembly.GlobalAssemblyCache` will be obsoleted in .NET 5 (https://github.com/dotnet/designs/blob/master/accepted/2020/better-obsoletion/obsoletions-in-net5.md)

**Comment by iSazonov** [comment]
We have GlobalAssemblyCache in GlobalAssemblyCache.cs file.

I see the .Net document mentions UTF7 - we should review this.

**Comment by xtqqczze** [comment]
> I see the .Net document mentions UTF7 - we should review this.

Issue opened: #13358

**Comment by xtqqczze** [comment]
@iSazonov https://github.com/MicrosoftDocs/PowerShell-Docs/pull/6446 suggests there is no GAC in PowerShell 6 and higher, should we open an issue to review GAC functionality?

**Comment by iSazonov** [comment]
@xtqqczze Feel free to open new issue.

**Comment by xtqqczze** [comment]
I don't know enough about this to open an issue, pinging @rjmholt.

**Comment by rjmholt** [comment]
> I was under the impression that the GAC functionality is effectively nonexistent for .NET Core? Has that changed again in .NET 5?

This is effectively true, but I believe there is still some .NET Framework GAC fallback functionality on Windows to support particular Windows modules... @adityapatwardhan is the right person to ask here

**Pull request merged**
