### PR TITLE
Switch from BMP to PNG for graphical MSI installer assets

### PR DESCRIPTION
**Pull request by joeyaiello**
# PR Summary

Converted the MSI's bitmaps (BMPs) to PNGs that have transparent backgrounds instead of white backgrounds.

This breaks rendering of images for Windows 7 and Server 2008R2, but it's required for accessibility purposes so that the High Contrast Black theme renders text correctly for accessibility. (Unfortunately, BMP does not support transparency.)

## PR Context

In order to be fully accessible, we need to support the High Contrast Black theme in Windows. This makes system-wide text white which is unreadable on the BMP's hardcoded white background. 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
@PoshChan Please remind me in 6 hours

**Review by bergmeister — APPROVED** [review]

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 6 hours ago

**Comment by TravisEz13** [comment]
@joeyaiello Does this need to be back-ported?

**Comment by joeyaiello** [comment]
It would certainly make my life easier in closing the loop with a11y folks if we could slip it into a servicing release, but if it's a huge hassle, don't worry about it.

**Pull request merged**
