### PR TITLE
Do not check commands for wildcard characters.

### LINKED ISSUE #10997: command with wildcard characters on path cannot be executed
# Steps to reproduce

Create an executable file with PowerShell wildcard characters in its name, say `a[hello].ps1`, place it somewhere in the PATH, and then try to execute it from PowerShell.

```
Describe "Execute scripts by file name only via `$env:PATH." {
  BeforeAll {
	$originalPath= $env:PATH
    $dir = Convert-Path TestDrive:
    "'hi1'" | Set-Content -LiteralPath $dir/script.ps1
    "'hi2'" | Set-Content -LiteralPath $dir/script[1].ps1
    $env:PATH += [IO.Path]::PathSeparator + $dir
  }
  AfterAll {
    $env:PATH = $originalPath
  }
  It "Finds and executes a script with a vanilla file name." {
    script.ps1 | Should -Be 'hi1'
  }
  It "Finds and executes a script whose file name looks like a wildcard." {
    script[1].ps1 | Should -Be 'hi2'
  }
}
```

# Expected behavior

The file executes

# Actual behavior

It doesn't, but is suggested as a possible similar command.

There is no escaping of the wildcard characters that works.

# Environment data

All version of PowerShell, on Windows 10, specifically 5.1, 6.2.3, and 7.0.0-preview5 were tested.

# Reason - Determined from Debug

Because the command contains wildcard characters, it is rejected from a PATH search by `CommandSearcher.CanDoPathLookup()` in `CommandSearcher.setupPathSearcher()`.   If the command had been in the immediate path, using `.\a[hello].ps1` would have successfully worked.

@mklement0, I believe you may have touched on this subject before, but I could not immediately find an existing issue for this.

I believe this can be corrected, by only sending an escaped version of the path to `CommandSearcher.CanDoPathLookup()`, as I cannot find any reason that the path should not be treated literal at this point.  Or, maybe the wildcard character check can be removed entirely, it appears this is the only place where the function `CanDoPathLookup()` is used.

### PR DESCRIPTION
**Pull request by msftrncs**
# PR Summary

Remove the check in CanDoPathLookup for wildcard characters in the command, as it prevents a PATH search of the command if it contains wildcard characters.

Fixes #10997

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by msftrncs** [comment]
A test is now failing on Windows,  (Shouldn't it fail on MacOs and Linux too?)

```
Describing Use literal path first when executing scripts
  [-] 'Relative path that where module qualified syntax overlaps' should not execute 28ms
    Expected an exception, with FullyQualifiedErrorId 'CouldNotAutoLoadModule' to be thrown, but no exception was thrown.
    139:             { & $command } | Should -Throw -ErrorId $ExpectedErrorId
```

I actually don't understand why this test would succeed (produce an exception).  I think the wildcard was preventing it from working, and the exception thrown was misleading.

**Comment by TravisEz13** [comment]
@msftrncs If the syntax is not longer treated as a module qualified invocation, then the change is breaking.

**Comment by TravisEz13** [comment]
This probably doesn't fail on non-windows because of differences in handling of the file system.

**Comment by msftrncs** [comment]
Its not that the syntax is no longer treated as module qualified …   if it hadn't been for the wildcard characters, it would have executed …  if the actual path had not been found, PowerShell would have still checked for modules, but an existing file will be executed if it is found.

I do not think this breaks anything.

In the test, the file path is `subFolder\[test1].ps1`. 

The test for this kind of path appears to occur in the same section as `$env:PATH`, so when the code I removed previously flagged this path as `WildcardCharacters`, this prevented this path from testing for `DirectorySeparator`.  Under `DirectorySeparator` the path would be tested as a relative path to a file.  With the fix, this now works as it should.

Had the file been `subFolder\test1.ps1`, this test would also have failed, because the file would have executed, since it would have flagged as `DirectorySeparator`.

**Comment by TravisEz13** [comment]
Please write tests under the old code (separate PR) validating your assumptions and show that your are not breaking these scenarios.

**Comment by msftrncs** [comment]
This potentially fixes #9256.

**Comment by msftrncs** [comment]
@TravisEz13, I have submitted PR #11225, though I do not know if it meets your criteria.  After submitting that PR, I became aware of #9256, which is exactly the issue being raised in this potential breaking change.

**Comment by TravisEz13** [comment]
Can you please write up an summary of the use cases that you are trying to fix and why?  I don't feel like I have enough information to send this to the committee for review.

**Comment by iSazonov** [comment]
@TravisEz13 #10997 contains full and clear description and examples.

**Comment by TravisEz13** [comment]
> #10997 contains full and clear description and examples.

Where?

**Pull request closed without merging**
