### PR TITLE
Invoke-RestMethod -FollowRelLink fix links containing commas

### PR DESCRIPTION
**Pull request by CarloToso**
# PR Summary

## PR Context

Add the fix proposed by @ashscodes in #17528

### CODE REVIEW

**Review by SteveL-MSFT — APPROVED** [review]
Is it possible to add a test?

**Comment by iSazonov** [comment]
> Is it possible to add a test?

I guess we can add new constant in Constants.cs and use it in new branch in LinkController.cs.

**Comment by CarloToso** [comment]
Would this test be ok ?

```cs
    It "Validate Invoke-WebRequest handles commas"
    {
        $uri = Get-WebListenerUrl -Test 'Link' -Query @{maxlinks = 3; linknumber = 1; type = "with,comma"}
        $command = "Invoke-WebRequest -Uri '$uri'"
        $result = ExecuteWebCommand -command $command

        $result.Output.RelationLink.Count | Should -BeExactly 3
        $baseUri = Get-WebListenerUrl -Test 'Link'
        $result.Output.RelationLink["last"] | Should -BeExactly "${baseUri}?maxlinks=3&linknumber=3&type=with,comma"
        $result.Output.RelationLink["first"] | Should -BeExactly "${baseUri}?maxlinks=3&linknumber=1&type=with,comma"
        $result.Output.RelationLink["self"] | Should -BeExactly "${baseUri}?maxlinks=3&linknumber=1&type=with,comma"
    }
```

**Comment by iSazonov** [comment]
If this doesn't work before the PR, I am ok with the test.

**Comment by CarloToso** [comment]
> If this doesn't work before the PR, I am ok with the test.

I checked, the test fails before this PR

**Review by iSazonov — APPROVED** [review]

**Pull request merged**
