### PR TITLE
Update Code of Conduct and Security Policy

### PR DESCRIPTION
**Pull request by andyleejordan**
# PR Summary

Updates the readme, code of conduct and security policy.

## PR Context

It was requested by OSPO.
## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by andyleejordan** [comment]
I might suggest that we just remove the COC section from the bottom of the readme, as GitHub now shows readme/COC/license as tabs on the repo's main page.

**Comment by andyleejordan** [comment]
This has been updated and ready for review. We unfortunately cannot rely on the organization templates.

**Comment by andyleejordan** [comment]
I fixed the spell-checked "spellchecked" typo that was failing the Markdown linter since I caused it to trigger by editing the contributing document. As we need to use the security policy file verbatim(ish) I added an exclusion to the linter for it.

**Comment by andyleejordan** [comment]
Also, I'm unsure why so many links in the readme and other existing documentation could be relative but instead are hard links to the master branch's tree on GitHub...but there are some relative links used so I went with that.

Finally, I specifically didn't move the files from where they already were even though they could both be in `.github` or the root, but with too many other links out there pointing to them it would be a frustrating move for no reason.

**Review by sdwheeler — APPROVED** [review]

**Comment by andyleejordan** [comment]
I added:

> **DO** enforce the Code of Conduct by taking reports of abuse and violations to the committee for resolution

as a requirement for both repository maintainers and PowerShell Committee members. Then I spelled out (copied the existing, and linked to it in contributing guidelines) the enforcement policy followed by the committee.

Finally I added a note to the PowerShell Committee that employees should review the resources available at https://aka.ms/opensource/moderation-support.

While I've added these two requirements, I don't believe they need to be explicitly approved as they were implicit requirements, and now they're spelled out explicitly.

**Comment by andyleejordan** [comment]
(And fixed more Markdown linter issues I triggered by touching the files.)

**Review by SteveL-MSFT — APPROVED** [review]

**Pull request merged**
