### PR TITLE
Ensure the SSHClientSessionTransportManager stream writer and reader fields are cleared after dispose.

### LINKED ISSUE #7740: ObjectDisposedException attempting to Remove-PSSession an SSH-Based PSSession
I have a remoting test from Linux to Windows Server 2016 that connects using PubKeyAuthentication, Copies a File to the target using Copy-Item, the tests for the file's existence using Invoke-Command.

I'm finding this test randomly fails (30-40% of the time) with an ObjectDisposedException when calling Remove-PSSession on the outbound session.

Message: "Cannot access a closed file."

The stack trace is very consistent:

at System.IO.FileStream.Flush(Boolean flushToDisk)
 at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
 at System.IO.StreamWriter.Dispose(Boolean disposing)
 at System.IO.TextWriter.Dispose()
 at System.Management.Automation.Remoting.Client.SSHClientSessionTransportManager.CloseConnection()
 at System.Management.Automation.Remoting.Client.SSHClientSessionTransportManager.Dispose(Boolean isDisposing)
 at System.Management.Automation.Remoting.BaseTransportManager.Dispose()
 at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.Dispose(Boolean disposing)
 at System.Management.Automation.Remoting.ClientRemoteSessionDSHandlerImpl.Dispose()
 at System.Management.Automation.Remoting.ClientRemoteSessionImpl.Dispose(Boolean disposing)
 at System.Management.Automation.Remoting.ClientRemoteSessionImpl.Dispose()
 at System.Management.Automation.Internal.ClientRunspacePoolDataStructureHandler.Dispose(Boolean disposing)
 at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.Dispose(Boolean disposing)
 at System.Management.Automation.Runspaces.RunspacePool.Dispose()
 at System.Management.Automation.RemoteRunspace.Dispose(Boolean disposing)
 at System.Management.Automation.Runspaces.Runspace.Dispose()
 at Microsoft.PowerShell.Commands.RemovePSSessionCommand.ProcessRecord()
 at System.Management.Automation.Cmdlet.DoProcessRecord()
 at System.Management.Automation.CommandProcessor.ProcessRecord()

Looking at both the PowerShell code and the CoreFx code, there are three problems:

1: SSHClientSessionTransportManager.CloseConnection disposes three streams but does not clear the associated fields. The result is multiple unnecessary calls to StreamXXX.Dispose.  A minor perf hit, at worse.

2: System.IO.StreamWriter does not correctly detect it has been disposed.  It calls its Flush method which detects the underlying stream is null and throw the ObjectDisposedException.

3: The System.IO.Stream* instances have already been disposed before the test has called Remove-PSSession.

The cause of this is TBD; investigation in progress.

The attached file provides a repro.  Running it in a loop will average about 3 failures out of 10.  It does not fail when run on Windows but the repro percentage can be seen consistently on Ubuntu 16.04. In all cases, the target system is Windows Server 2016.

Steps to reproduce
------------------

[SshObjectDisposedException.ps1.txt](https://github.com/PowerShell/PowerShell/files/2362754/SshObjectDisposedException.ps1.txt)

```powershell

```

Expected behavior
-----------------
The script runs without errors

Actual behavior
---------------
~30% of the time, the script fails when closing the PSSession (Remove-PSSession)

Environment data
----------------

Client System:  Ubuntu 16.04
```powershell
Name                           Value
----                           -----
PSVersion                      6.1.0-rc.1
PSEdition                      Core
GitCommitId                    6.1.0-rc.1
OS                             Linux 4.15.0-1022-azure #22~16.04.1-Ubuntu SMP Thu Aug 16 10:31:05 UTC 2018
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Target System: Windows Server 2016
```powershell
Name                           Value
----                           -----
GitCommitId                    6.1.0-rc.1-43-g70d601502dc05ef99f4950a67ccadf73b5338ce8
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSEdition                      Core
PSVersion                      6.1.0-rc.1
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
Platform                       Win32NT
OS                             Microsoft Windows 10.0.14393
SerializationVersion           1.1.0.1
```

### PR DESCRIPTION
**Pull request by dantraMSFT**
Fix https://github.com/PowerShell/PowerShell/issues/7740

## PR Summary

Fix the ObjectDisposedException in SSHClientSessionTransportManager.CloseConnection calling StreamWriter.Dispose multiple times.

There are two changes:

* Clear the streamreader and streamwriter fields after disposing.
* Use InterlockedExchange for the above fields and _sshProcessId to avoid possible race conditions for async usage.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [X] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]

**Review by PaulHigin — COMMENTED** [review]
LGTM, but this shouldn't be necessary.  From Microsoft documentation:
"If an object's Dispose method is called more than once, the object must ignore all calls after the first one. The object must not throw an exception if its Dispose method is called multiple times. Instance methods other than Dispose can throw an ObjectDisposedException when resources are already disposed."

**Review by PaulHigin — COMMENTED** [review]
Adding link...
https://docs.microsoft.com/en-us/dotnet/api/system.idisposable.dispose?view=netframework-4.7.2

**Review by PaulHigin — APPROVED** [review]

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Comment by iSazonov** [comment]
@PaulHigin I guess that Dispose() should support a protection
https://blogs.msdn.microsoft.com/blambert/2009/07/24/a-simple-and-totally-thread-safe-implementation-of-idisposable/

**Pull request merged**
