### PR TITLE
Update the map between console color to VT sequences

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Update the map between console color to VT sequences.
The `ConsoleColor` to `VT Escape Sequences` mapping in `VTUtils.cs` is not accurate, and thus is updated according to https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#text-formatting

https://github.com/PowerShell/PowerShell/blob/895d4b3f3ebb51193d68095d2a95549b0b92c5fc/src/System.Management.Automation/utils/VTUtils.cs#L25-L43

The update is needed as "Bright foreground color" (e.g. bright red `\x1b[91m`) is rendered differently from `bold` color (e.g. `\x1b[1;31m`) in some front-end client, such as the Jupyter Notebook client.
See the 3rd and 4th output below as an example:
image

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
Did you check the color rendering on Linux and/or macOS and Windows Terminal?

**Review by SteveL-MSFT — DISMISSED** [review]
Did you check the color rendering on Linux and/or macOS and Windows Terminal?

**Comment by daxian-dbw** [comment]
I did check on console host and win terminal, but not Linux and macOS yet. Will do that and update here.

**Comment by daxian-dbw** [comment]
I tested the changes on console host, windows terminal, Linux terminal and macOS terminal, and all look good:

### Windows console host

image

### Windows terminal

image

### Linux

image

### macOS

screenshot is coming up soon

**Comment by adityapatwardhan** [comment]
@SteveL-MSFT Please update your review

**Comment by TravisEz13** [comment]
LGTM.   Let's merge so we can start the build

**Comment by daxian-dbw** [comment]
Since I have tested it on all platforms, I'm OK to merge this PR.

**Comment by adityapatwardhan** [comment]
I am OK to merge this PR.

**Pull request merged**
