### PR TITLE
Refactor `MUIFileSearcher.AddFiles`

### PR DESCRIPTION
**Pull request by xtqqczze**
* Use custom `EnumerationOptions` for ensure case insensitivity on Linux (available since .NET Core 2.1).
* Use `Directory.EnumerateFiles` instead of `Directory.GetFiles` to avoid allocations (contributes to #14318)

### CODE REVIEW

**Comment by iSazonov** [comment]
I wonder why you are trying to update the edge code. :-)

**Comment by xtqqczze** [comment]
> I wonder why you are trying to update the edge code. :-)

Sorry, could you clarify what you mean?

**Comment by iSazonov** [comment]
What I mean is that you are wasting your time on help subsystem code that should have been upgraded as a whole a long time ago...

**Comment by xtqqczze** [comment]
See also:
* #3852
* #3971
* #4053

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Pull request merged**
