### PR TITLE
Rework Send-MailMessage cmdlet with MailKit

### LINKED ISSUE #7591: Send-MailMessage incorrectly handling ValueFromPipelineByPropertyName parameters
The current implementation is processing parameters in BeginProcessing. While this works for parameters that are explicitly passed to the cmdlet, it fails for parameters that are populated form properties of the pipeline object because parameters are not set until the pipeline object is sent to ProcessRecord.

The logic for parameters bound from the pipleline needs to be moved to ProcessRecord.

Steps to reproduce
------------------

```powershell
$object = [PSCustomObject]@{To = $address; From = $address;  Subject = $subject;  Body = $body; SmtpServer = '127.0.0.1'}
$object | Send-MailMessage
```

Expected behavior
-----------------
The mail is sent.

Actual behavior
---------------
System.ArgumentNullException: Value cannot be null
Parameter name: address

### LINKED ISSUE #10015: HadErrors() returns $true if Send-MailMessage cmdlet is used
# Steps to reproduce

I user PowerShell Class (version 6.2.1) in .NET Core project, If **scripts** include `Send-MailMessage` cmdlet, `shell.HadErrors` get `true`: 

```csharp
using (PowerShell shell = PowerShell.Create())
{
    shell.AddScript(scripts);
    var results = shell.Invoke();

        if (shell.HadErrors)
        {
            _logger.LogTrace($"shell.HadErrors is {shell.HadErrors}");
        }
}
```

I trace `shell.Streams` object, only `Warning` count 1, other `PSDataStreams` properties (`Error` ...) count 0.

`Warning` message is  `new System.Collections.Generic.ICollectionDebugView<System.Management.Automation.WarningRecord>(shell.Streams.Warning._data).Items[0]	{The command 'Send-MailMessage' is obsolete. This cmdlet does not guarantee secure connections to SMTP servers. While there is no immediate replacement available in PowerShell, we recommend you do not use Send-MailMessage at this time. See https://aka.ms/SendMailMessage for more information.}	System.Management.Automation.WarningRecord`

# Expected behavior

`shell.HadErrors` is `false`.

# Actual behavior

`shell.HadErrors` is `true`.

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      5.1.17134.765
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.765
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### PR DESCRIPTION
**Pull request by ThreeFive-O**
# PR Summary

This PR will fix the underlying architecture of the Send-MailMessage cmdlet using the actively maintained `MailKit` SMTP client.
Note: `System.Net.Mail.SmtpClient` receives no further development and only supports STARTTLS secure connections.

**Enhancements**
- Fix #7591: Pipelining into the cmdlet is now supported
- SMTPS is now supported

**Benefits of MailKit**
- Modern actively maintained dependency (would fix #10015)
- Secure connection upgrades from insecure connections using STARTTLS is supported implicitly (no parameter has to be specified)
- Secure connections over SSL/TLS is supported (Gmail, Yahoo, ... see #8987)
- MailKit and MimeKit allow easier implementation of missing functionality (see #9191)

**Backward compatibility and breaking changes**
All parameters are left as they are, BUT
- `Credential` parameter is the only way to provide credentials right now. `System.Net.Mail.SmtpClient` has the ability to get the default credentials from Windows. 
-> Requires change in documentation; X-plat credential provider solution for PowerShell 7 might be the solution to that.

- `DeliverNotificationOption` is implemented, but the functionality should be reviewed as all tested platforms either don't support Delivery Status Notfication (DSN) (e.g. Gmail, GMX, Yahoo) or ignore the setting (Outlook.com - btw the only SMTP server I've came accross which reports DSN capability).
-> Subject to discuss in RFC to deprecate this parameter.

- `Encoding` parameter no longer has any influence on subject/body encoding as this is handled by MimeKit
-> Requires further research, but may be subject to deprecate.

- `UseSsl` is no longer mandatory to allow STARTTLS upgrade from an insecure connection. The parameter is now used to explicitly state the the entire connection should be wrapped in a SSL/TLS connections, also known as SMTPS. -> Using Port 0 (default - automatic port selection will use Port 465 for `UseSsl` but can of course be overridden with any other port number; If `UseSsl` is not specified the default port 25 for SMTP is used, although most STARTTLS endpoints use port 587).
-> Critical breaking change for automated scripts; Subject to discuss
Possible workaround: Use another parameter for SMTPS functionality and keep `UseSsl` parameter for STARTTLS (though it wouldn't have any relevance in the code and would be a non-functional parameter like `Encoding`, though not breaking any scripts)

**Test infrastructure**
The Pester tests use netDumbster which only supports insecure connections.
STARTTLS and SMTPS functionality have been tested interactively against:
- Outlook.com (STARTTLS 587)
- Gmail.com (SMTPS 465)
- Yahoo.com (SMTPS 465 and STARTTLS 587)

## PR Context

As of #9178 is marked as obsolete and an RFC PR PowerShell/PowerShell-RFC#160 was opened to discuess the future of the cmdlet.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by ThreeFive-O** [comment]
@TravisEz13 Tests for `Remoting` are failing for Windows ElevatedPesterTests due to missing dependencies:
`New-PSSession : [localhost] Processing data from remote server localhost failed with the following error message: Could not load file or assembly 'MailKit, Version=2.2.0.0, Culture=neutral, PublicKeyToken=4e064fe7c44a8f1b'. The system cannot find the file specified. For more information, see the about_Remote_Troubleshooting Help topic.`
Could you please point me in the right direction how to resolve this dependency issue? Thank you very much.

**Comment by TravisEz13** [comment]
cc @SteveL-MSFT  about if this is the right place for this

**Comment by TravisEz13** [comment]
We have a list of Assemblies trusted for remoting here https://github.com/PowerShell/PowerShell-Native/blob/534965cb5f5657a019815216a09de419dc6eec91/src/powershell-native/nativemsh/pwrshcommon/pwrshcommon.cpp#L671

Work with @adityapatwardhan  on how you can progress.  My proposal would be that we publish a pre-release of PowerShell-Native with your changes and you can work off of that.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, we appreciate this work, but ask that this be a module published to PSGallery.  A decision whether this ships in PowerShell will be decided later.

- We have concerns about potential for breaking changes (types, functionality)
- Size concerns bringing in another assembly
- In general, our direction is to have more modules/cmdlets validated via PSGallery before deciding it should be shipped with PowerShell

**Comment by FireInWinter** [comment]
I don't agree that existing functionality should be moved to a separate module.  It's too bad SMTPClient was deprecated, but this seems like a punishment to the community to remove a builtin feature and put it elsewhere.

**Pull request closed without merging**
