### PR TITLE
Remove FusionAssemblyIdentity and GlobalAssemblyCache

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

This has never been used in pwsh and is unlikely to be used to handle meta-information in the GAC.

Contribute to #18330

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by xtqqczze** [comment]
Since .NET Core, there is no Global Assembly Cache :p

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Review by xtqqczze — APPROVED** [review]

**Review by xtqqczze — COMMENTED** [review]
@iSazonov search for "// Code in this file was copied from https://github.com/dotnet/roslyn" shows `src\System.Management.Automation\engine\parser\GlobalAssemblyCache.cs`. I think the PR could remove this as well.

**Comment by xtqqczze** [comment]
Contributes to #4357.

**Comment by xtqqczze** [comment]
See #13305 for discussion on `GlobalAssemblyCache`.

> > I was under the impression that the GAC functionality is effectively nonexistent for .NET Core? Has that changed again in .NET 5?
> 
> This is effectively true, but I believe pwsh.exe still keeps some .NET Framework GAC fallback functionality on Windows to support particular Windows modules... @adityapatwardhan is the right person to ask here
> 
> _Originally posted by @rjmholt in https://github.com/PowerShell/PowerShell/issues/13305#issuecomment-671562594_

**Comment by xtqqczze** [comment]
> Good catch @xtqqczze! @iSazonov Can you remove `src\System.Management.Automation\engine\parser\GlobalAssemblyCache.cs` in this PR as well?

Yeah, `GlobalAssemblyCache` references `FusionAssemblyIdentity` so both should be removed at the same time.

Additionally:

https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/parser/Compiler.cs#L2791
https://github.com/PowerShell/PowerShell/blob/4b9b0788ed28ea6d463ce857d1ed81bd4a977a59/src/System.Management.Automation/engine/parser/Parser.cs#L5079

**Comment by xtqqczze** [comment]
We can remove all `GlobalAssemblyCache` code as it is not compiled. (`#if !CORECLR`)

**Comment by daxian-dbw** [comment]
The support in loading GAC assemblies is in `PowerShellAssemblyLoadContext`, not related to these 2 files.

**Comment by iSazonov** [comment]
@xtqqczze Thanks! GlobalAssemblyCache removed.

**Comment by xtqqczze** [comment]
LGTM

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Pull request merged**
