### PR TITLE
Have *-Location modify the Environment.CurrentDirectory which changes the cwd on *nix

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
## PR Summary

I noticed that *-Location doesn't set the environment current directory:
https://msdn.microsoft.com/en-us/library/system.environment.currentdirectory(v=vs.110).aspx

On *nix, this value is mapped to the `cwd` property on the process. In bash, when you change directories, that property changes. To test on *nix:
`lsof -p YOU_PID | grep cwd`

I discovered this when I was trying to add PowerShell support to hypercwd (https://github.com/hharnisc/hypercwd/issues/41) which is a plug-in to [hyper](hyper.is) that, when you open a new tab, preserves the location from the previous tab. In the plug-in, they do this for *nix:
https://github.com/hharnisc/hypercwd/blob/master/setCwd.js#L8

I don't think this is a breaking change.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by rkeithhill** [comment]
I thought the issue with setting the process's `cwd` is that with PowerShell you can have multiple runspaces, each in a different directory.  So this "process global" cwd value could get changed out from underneath you in any particular runspace by another runspace.

**Comment by tylerl0706** [comment]
That makes sense - and this change might not be the way to go about this...

but I think  setting `cwd` should really be best effort rather than no effort. I'm inclined to say that your scenario doesn't happen super often, and `cwd` is easily "resettable" by resetting your location.

That said, you're scenario is totally valid. Don't think there's much to prevent that.

**Comment by iSazonov** [comment]
It is a breaking change because scripts can expect that `Environment.CurrentDirectory` is not changed.

It is bad practice to change a common value in _any_ multi-thread application randomly.

**Comment by BrucePay** [comment]
@tylerl0706  PowerShell uses the `$pwd` variable - a PowerShell variable (runspace affined) not an environment variable, to contain the cwd. Concurrent scenarios are fairly common and something that we will be actively facilitating in the future. Given that, even if we made this change no one could use it because they would have no idea when the variable might change. On the other hand, if the environment variable was set for the child process when `CreateProcess()` is called, that would be reliable and useful. And you wouldn't need to track the location - that's tracked automatically in $pwd.

**Comment by tylerl0706** [comment]
Sounds good. Thanks so for the feedback

**Pull request closed without merging**
