### PR TITLE
Code cleanup: convert usage of String to string

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

A scan of the code indicates I can simply search and replace on:

` String.` <= this one is preceded by a single space
`!String.`
`(String.`

and fix the casing.  Only two lines I had to manually fix in SecureStringCommands which has a `String` parameter so put those back.

Spent a bit of time reviewing each of the changes in this PR so a quick scan from someone else should be sufficient.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by daxian-dbw** [comment]
Be careful that we do want to use the full name in the places that we are explicitly dealing with different primitive types, for example, 
https://github.com/PowerShell/PowerShell/blob/8d27eb44b10bf48d8a47e50dd75d23b06c534270/src/System.Management.Automation/CoreCLR/CorePsStub.cs#L312-L329

Those cases are in the interpreter code, COM related code, serialization related code, type conversion related code, type resolver related code, and possibly other places.
And you need to be careful about the enum members of `TypeCode`, which has the same name as the full names of those primitive types. (and similar cases where the full names of those types are used as strings)

**Review by daxian-dbw — APPROVED** [review]
LGTM. It took me around 40 mins to go through the changes in this PR :)

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
GitHub "Load Diff" is very slow 😕 

For such large PRs I think it is better to make one commit per module/assembly.

**Comment by iSazonov** [comment]
@SteveL-MSFT Please resolve merge conflicts.

**Comment by iSazonov** [comment]
@SteveL-MSFT Merge conflicts :-(

**Comment by iSazonov** [comment]
@SteveL-MSFT Can we close the PR? Seems all fixed.

**Pull request closed without merging**
