### PR TITLE
add absolute url for issue template and pull request template

### PR DESCRIPTION
**Pull request by chucklu**
Correct the url for FAQ and known issues in issue template
Add url for contributing.md in pull request template

Both of them work fine in preview model of github.

### CODE REVIEW

**Comment by markekraus** [comment]
As far as I can tell, these links are never clickable or even visible as hyperlinks. I wonder if it would make more sense to use absolute URLs so the can at least be copy/pasted from the PR/Issue TextBox.

**Comment by daxian-dbw** [comment]
I agree with @markekraus that we probably should use absolute URLs in those places.

**Comment by chucklu** [comment]
@markekraus  When you remove the comment mark in markdown,then preview it,you can click the url.

The template with comment mark is weird,since it was written in markdown. But it‘s invisible in preview model.
I suggest you check the issue template of git for windows.Here is the [link](https://github.com/git-for-windows/git/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by chucklu** [comment]
@markekraus  Hi,I have add absolute url for it,and force push to my fork repository.
Now,this pull request fetches the commit with absolute url.
You can check it,thanks.

**Comment by markekraus** [comment]
Looks good to me! Thanks!

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Pull request merged**
