### PR TITLE
Note that Ubuntu 16.04 package works on Debian Testing too

### PR DESCRIPTION
**Pull request by Daniel15**
This is noted at https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#ubuntu-1604, but not in the readme.

### CODE REVIEW

**Comment by mirichmo** [comment]
@andschwa Please review

**Comment by andschwa** [comment]
If we're not actively supporting it, it shouldn't be in the readme. Debian Testing users already know they're likely able to use recent Ubuntu packages.

**Comment by iSazonov** [comment]
If Debian community really want Powershell so vote here and join the Powershell project.

**Comment by Daniel15** [comment]
¯\_(ツ)_/¯

**Pull request closed without merging**
