### PR TITLE
Only register App Path for release package

### LINKED ISSUE #20374: After installing the preview version of PowerShell 7 (7.4.0-preview.5), it launches by default when I call `pwsh`. How do I get 7.3.7 to remain as the default PowerShell version side by side with the preview?
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Ensure you have PowerShell 7 (7.3.7) installed on your machine.
2. Install the preview version of PowerShell 7 (7.4.0-preview.5) via `winget install --id Microsoft.Powershell.Preview --source winget`
3. Press `WIN-R` to open the run dialog, and type `pwsh`.
4. Observe that `7.4.0` opens now instead of `7.3.7.`

Interestingly enough, if I open a command prompt (windows cmd), and then type `pwsh`, it opens the correct version (`7.3.7`)

### Expected behavior

```console
Running `pwsh` opens the non-preview version of PowerShell 7.
```

### Actual behavior

```console
Running `pwsh` opens the preview version of PowerShell 7.
```

### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.5
PSEdition                      Core
GitCommitId                    7.4.0-preview.5
OS                             Microsoft Windows 10.0.19045
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

Removed

### PR DESCRIPTION
**Pull request by heaths**
Resolves #20374

### CODE REVIEW

**Comment by heaths** [comment]
The change to the component ID won't matter. Only component GUIDs matter, which in WiX are based on any parent context (which didn't change) and the key path (which also didn't change), as you can see here comparing my installed release PowerShell, a "release" MSI I built, and a preview MSI I built (from back to fore):

image

Also of note: @TravisEz13, should `Start-PSPackage -SkipReleaseCheck` skip the BOM check? @SteveL-MSFT had to give me a lot of help to get the MSI built (I forgot some initially; other cases were non-obvious errors to me). Seems checking the BOM is more of a release activity.

**Review by SteveL-MSFT — APPROVED** [review]
Best I can tell, LGTM

**Comment by heaths** [comment]
I'm looking into the test failure now, but you might have a CI script problem as well:

```
Tests completed in 524.18s
Tests Passed: 1449, Failed: 1, Skipped: 13, Pending: 66, Inconclusive: 0 
Result Attachments will be stored in LogStore
Run Attachments will be stored in LogStore
The input object cannot be bound to any parameters for the command either because the command does not take pipeline input or the input and its properties do not match any of the parameters that take pipeline input.1 tests in test/powershell failed
At D:\a\1\s\build.psm1:1813 char:13
+             throw "$($x.'test-results'.failures) tests in $TestArea f …
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : OperationStopped: (1 tests in test/powershell failed:String) [], RuntimeException
+ FullyQualifiedErrorId : 1 tests in test/powershell failed
Publishing test results to test run '2143526'.
```

**Comment by heaths** [comment]
Looks like the test error is probably unrelated, but I'll try rerunning it in case it's ephemeral.

```
Failed: Set/New/Remove-Service cmdlet tests.Remove-Service can remove a service
Error message: Expected $null or empty, but got @(System.ServiceProcess.ServiceControll
Stack trace:
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Management\Set-Service.Tests.ps1: line 279
279:             $service | Should -BeNullOrEmpty
```

**Comment by iSazonov** [comment]
Restart CI-Windows...

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Pull request merged**
