### PR TITLE
Moved PowerShellGet to be a git submodule

### PR DESCRIPTION
**Pull request by kilasuit**
This decouples PowerShellGet from the PowerShell repository allowing development to occur on the PowerShellGet repository

### CODE REVIEW

**Comment by bmanikm** [comment]
@kilasuit, @vors, @raghushantha 
Can we pull the latest version of PowerShellGet module from the PSGallery as a post-build step?

**Comment by lzybkr** [comment]
As we make our modules installable independently, I don't think we want to ship unreleased versions of those modules, which implies we don't want to build the modules as git submodules

Instead, I think we want to fetch packages from a nuget feed - most likely powershell.myget.org but possibly powershellgallery.com.

**Comment by kilasuit** [comment]
@lzybkr totally agree that we need to have that for v6 release but the concern I have currently is that there are 2 places to make changes _until_ the work for #1979 is fully completed (which yes IMO would include pulling the modues in via a nuget feed of sorts like you've suggested once we get there) but I think for the short term pulling in as a git submodule is a realistic middle ground that allows us the time to correctly identify the right route for how we implement it as a bigger part of #1979 and stops the " 2 places to edit the same code" issue we currently have.

On reflection I should really have put the above in the original comment and I'm not actually sure why I didn't.

**Comment by kilasuit** [comment]
Hope that clears up any unnecessary confusion caused

**Comment by lzybkr** [comment]
We are moving forward with pulling a package (specifics to be determined). This work might not be done for the next release, but hopefully the release after that.

Introducing submodules is a pain, removing them is also a pain, so we're rejecting this PR.

As this issue should be resolved in the short term, we won't be making PowerShellGet/PackageManagement fixes in both places, we'll live with the bugs present in PowerShell/PowerShell for the next release.

**Comment by kilasuit** [comment]
No worries @lzybkr - totally agree with the points made re adding/removing submodules and glad to see this be planned to tie in within the next few releases.

I'll keep my eyes on how the package pulling implementation goes in line with #1979 as IMO getting that right really is crucial for the long term.

**Pull request closed without merging**
