### PR TITLE
Add retry logic to prerequisite URL tests

### LINKED ISSUE #5567: WMF link test intermittently fails
1. The test does not give the url which fails to verify the failure
1. I've seen similar failures twice.
https://travis-ci.org/PowerShell/PowerShell/jobs/308584873#L4450

```
TEST FAILURES
Description: Windows Installer/
Name:        Pre-Requisistes link for 'WMF 4.0' is reachable
message:
Error 404 - Not Found/**/Warning: This site requires the use of scripts, which your browser does not currently allow.See how to enable scriptsTry Microsoft EdgeA fast and secure browser that's designed for Windows 10No thanksGet startedSkip to main contentMicrosoftDownload CenterOfficeWindowsSurfaceXboxDealsSupportMoreSoftwareWindows appsOneDriveOutlookSkypeOneNotePCs &amp; Devices  PCs &amp; tabletsAccessoriesVR &amp; mixed realityMicrosoft HoloLensEntertainmentXbox gamesPC gamesWindows digital gamesMovies &amp; TVBooksBusinessMicrosoft AzureMicrosoft Dynamics 365Microsoft 365Cloud platformEnterpriseData platformDeveloper &amp; IT  Microsoft.NETVisual StudioWindows Dev CenterDocsOtherMicrosoft StoreFree downloads &amp; securityEducationStore locationsGift cardsHoliday gift guideView allNo results0Sign inDownload CenterWindowsOfficeWeb browsersDeveloper toolsXboxWindows Phone
```

### PR DESCRIPTION
**Pull request by daxian-dbw**
The package prerequisite URL tests have been failing intermittently recently, because sometimes the WMF download URLs lead to a "we're sorry, this download is no longer available" page, even though the URLs actually work in the web browser. I'm disabling those tests for now.

Close #5567

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
Can we try adding a simple retry before disabling?

**Comment by daxian-dbw** [comment]
@SteveL-MSFT Sure, I will use retries and let's see how it goes.

**Comment by daxian-dbw** [comment]
The failed tests are known. #5605 will make them pending for now.

**Comment by iSazonov** [comment]
We could run the package prerequisite URL tests with another test tag ("Doc").
Also could we run tests by demand from GitHub PR page? We could run the package prerequisite URL tests and feature tests by this way. It seems to me more comfortable.

**Comment by markekraus** [comment]
I'm not sure what is best for this. We need to ensure the links work, but they erroneously fail often. A retry will help sometimes, but many times when this test fails it fails for days at a time.

**Review by adityapatwardhan — APPROVED** [review]
LGTM

**Pull request merged**
