### PR TITLE
Correct incorrect cmdlet name in script

### LINKED ISSUE #11002: Restart-Computer -cn -Force -Wait -Timeout is broken in latest build.
# Steps to reproduce

```
1. Install Powershell 7 Release 5 x64 on a up-to-date Windows 10 Computer
2. Run Powershell 7
3. Run the following script...

$ComputerNames = "Computer1","Computer2", "Computer3"
$ComputerNames | ForEach-Object -Parallel {
     Restart-Computer -ComputerName $_ -Force -Wait -Timeout 1800
}
4. Wait the allotted Timeout period of 30 minutes.

Where Computer1-3 are test computers on the same network.

Paul Higin Tested this and commented in another tread;

"This appears to be an error in the Restart-Computer cmdlet. When I run it alone in the latest
preview build, it restarts the remote computer as expected, but never returns and eventually 
crashes PowerShell. I get the same behavior when running it within a foreach -parallel 
script block.

This appears to have nothing to do with foreach -parallel, except that foreach -parallel doesn't
currently support progress data (by design) and so there is no indicator of how the computer
restart is proceeding.

I feel this Issue should be closed and two new issues open:
a. Restart-Computer -cn -Force -Wait -Timeout is broken in latest build.
b. ForEach -Parallel to support progress data stream (not sure how this would work and it would 
be a new feature request anyway)."
--




 
```

# Expected behavior

```
The remote computer will reboot and the script will continue without error.
```

# Actual behavior

```
The computers reboot, but PowerShell never reconnects to them.

After 30 Minutes, the following errors are received;

Restart-Computer: Failed to restart the computer Computer1 with the following error
 message: The computer did not finish restarting within the specified time-out period..
Restart-Computer: Failed to restart the computer Computer2 with the following error
 message: The computer did not finish restarting within the specified time-out period..
Restart-Computer: Failed to restart the computer Computer3 with the following error
 message: The computer did not finish restarting within the specified time-out period..

```

# Environment data

```
Name                           Value
----                           -----
PSVersion                      7.0.0-preview.5
PSEdition                      Core
GitCommitId                    7.0.0-preview.5
OS                             Microsoft Windows 10.0.17763
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### LINKED ISSUE #12232: Restart-Computer wait for PowerShell never completes
# Steps to reproduce

Restart-Computer -ComputerName myServer -Wait -For PowerShell -Force

# Expected behavior

Restart-Computer should complete waiting for PowerShell when it comes avaible after restart.

# Actual behavior

Restart-Computer never completes. 

# Additional
Restart-Computer -ComputerName myServer -Wait -For WinRM-Force - this works as expected.

# Environment data

PSVersion                                 7.1.0-preview.1
PSEdition                                  Core
GitCommitId                             7.1.0-preview.1
OS                                             Microsoft Windows 10.0.18362
Platform                                    Win32NT
PSCompatibleVersions              {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion     2.3
SerializationVersion                  1.1.0.1
WSManStackVersion                 3.0

### PR DESCRIPTION
**Pull request by urizen-source**
Corrects incorrect cmdlet name in script, which has been causing for instance "Restart-Computer -Computername otherserver -Wait -For Powershell" to never complete.
Also fixes "Restart-Computer -ComputerName $_ -Force -Wait -Timeout 1800" where powershell is implicit.

## PR Context

Resolves #12232
Also resolves  #11002 which is also dependant on this powershell script, and it hangs in the same place.
Issue is that the powershell script invoked has an exception because of the incorrect cmdlet-name, and this exception is silently ignored, so it never determines that any powershell is reachable on restarted servers.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Comment by iSazonov** [comment]
Should we backport this?

**Comment by iSazonov** [comment]
@urizen-source Thanks for your contribution!

**Comment by adityapatwardhan** [comment]
Since 7.2.x is LTS lets have some bake time for this in 7.3.x and consider this for next 7.2 release.

**Comment by TravisEz13** [comment]
Triaging backports:  Waiting for next release before backporting to LTS in order to give some time to discover issue.

**Pull request merged**
