### PR TITLE
Add a precheck for git to build.psm1

### LINKED ISSUE #13222: Start-PSBuild: cryptic error message MSB3073
## Steps to reproduce

```powershell
Start-PSBuild
```

## Expected behavior

```none
git: The term 'git' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

## Actual behavior

```none
`PowerShell\PowerShell.Common.props(17,5): error MSB3073: The command "git describe --abbrev=60 --long" exited with code 9009`
```

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.18363
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by yecril71pl**
# PR Summary

Adds a check for `git` command at build time.  Fixes #13222.

## PR Context

We check that `dotnet` is available as a command.  Similarly, the build process requires `git` to be available.  You can get the sources without having `git` installed, or you may have used `wsl git`, in which case you will be unable to build 😞
## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by iSazonov — DISMISSED** [review]

**Comment by anmenaga** [comment]
Interesting coincidence. Yesterday I was setting up PS build on a clean Ubuntu 16.04 LTS and got the very message about missing `git`; once I installed it through `apt-get`, the build started working. That means the check was already somewhere in the build code even without this change?

**Comment by yecril71pl** [comment]
I would risk a hypothesis that this means that Microsoft Build under Ubuntu can pronounce "Command not found"  instead of "9009".  It may be the case that the general approach under Linux is to address the readers so that they understand what is going on: under Microsoft Windows it is just the opposite.  General protection fault.

**Comment by anmenaga** [comment]
The CI error in Windows Packaging reproed on re-run; it comes from `WindowsPowerShell\Modules\Pester\4.10.1\Pester.psm1`
```
The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The term 'Pester\SafeGetCommand' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\Pester\4.10.1\Functions\PesterState.ps1: line 74
at New-PesterState, C:\Program Files\WindowsPowerShell\Modules\Pester\4.10.1\Functions\PesterState.ps1: line 30
at Invoke-Pester<End>, C:\Program Files\WindowsPowerShell\Modules\Pester\4.10.1\Pester.psm1: line 1094
at Invoke-CIFinish, D:\a\1\s\tools\ci.psm1: line 500
at <ScriptBlock>, D:\a\_temp\f4487122-8ca5-49e5-bbe5-f8c400147c9b.ps1: line 5
at <ScriptBlock>, <No file>: line 1
Pester\SafeGetCommand : The running command stopped because the preference variable "ErrorActionPreference" or common 
parameter is set to Stop: The term 'Pester\SafeGetCommand' is not recognized as the name of a cmdlet, function, script 
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct 
and try again.
At C:\Program Files\WindowsPowerShell\Modules\Pester\4.10.1\Functions\PesterState.ps1:74 char:49
+ ... $script:SafeCommands['New-Object'] = & (Pester\SafeGetCommand) -Name  ...
+                                             ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Pester\SafeGetCommand:String) [], ActionPreferenceStopException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by anmenaga** [comment]
@yecril71pl I was told that a rebase is needed to fix CI error. Please rebase this and I'll merge it. Thank you.

**Comment by yecril71pl** [comment]
I am sorry for this mess, I never intended to add anything here.  I shall revert my changes ASAP.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@yecril71pl Nit: one simple way to rebase:
```
git pull --rebase PowerShell master
```
and resolve conflicts if exist.

**Comment by TravisEz13** [comment]
@iSazonov Perhaps we should add https://github.com/PowerShell/PowerShell-Docker/blob/master/.github/workflows/rebase.yml

**Comment by iSazonov** [comment]
@TravisEz13 It is interesting!
My concerns:
- merge conflicts
- is it only for maintainers? If yes there can be conflicts if author add new commits locally without sync with remote. If no how authors discover the feature? And again local-remote conflicts.

**Comment by TravisEz13** [comment]
It doesn't resolve conflict, more for the case where tests or code is out of date.

Only if the person, who runs the command has permission to push to the branch.   So:

- The author can run it always
- The maintainer can run it, if the author gave permissions for maintainers to update the branch AND there are no workflow updates (workflow updates are not included in the permissions given to maintainers)

**Comment by iSazonov** [comment]
@TravisEz13 I agree - If this already works for PowerShell-Docker this will work for the repo too.

**Comment by TravisEz13** [comment]
@iSazonov It's definitely not perfect, but in docker the tests often don't merge right without rebasing, even though there are no conflicts.  So, I used this.

**Pull request merged**
