### PR TITLE
Add secret scanning to CI

### PR DESCRIPTION
**Pull request by TravisEz13**
# PR Summary

Add secret scanning to CI

## PR Context

This should prevent us from having any secrets in our history

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Review by PaulHigin — APPROVED** [review]
LGTM

**Review by adityapatwardhan — APPROVED** [review]

**Comment by TravisEz13** [comment]
@PoshChan 	please remind me in 24 hours

**Comment by PoshChan** [comment]
@TravisEz13, all requests start with the magic word `Please`.

**Comment by TravisEz13** [comment]
@PoshChan Please remind me in 24 hours

**Comment by PoshChan** [comment]
@TravisEz13, will remind you in 24 hours

**Comment by PoshChan** [comment]
@TravisEz13, this is the reminder you requested 24 hours ago

**Pull request merged**
