### PR TITLE
Enable CA1868: Unnecessary call to 'Contains' for sets

### PR DESCRIPTION
**Pull request by xtqqczze**
https://learn.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1868

Fix applied to concrete types `HashSet<T>` and `List<T>`.

### CODE REVIEW

**Comment by xtqqczze** [comment]
CodeFactor SA1000 issues are pre-existing.

**Comment by xtqqczze** [comment]
`PowerShell-CI-macos` failures appear unrelated.

**Comment by iSazonov** [comment]
@xtqqczze Please rebase to fix CI-macos

**Comment by xtqqczze** [comment]
rebased onto 0919240822e032af91dc2fe4ce481e82002b92c0 to fix CI-macos

**Comment by xtqqczze** [comment]
@iSazonov Can we run `PowerShell-Windows-Packaging-CI`?

**Review by iSazonov — APPROVED** [review]

**Pull request merged**
