### PR TITLE
use PkgMgmt 1.3.2 and PSGet 2.1.3 which has fix for NetCore30

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
# PR Summary

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@PoshChan please get failures

**Comment by SteveL-MSFT** [comment]
Opened issue against pkgmgmt for macOS failures: https://github.com/OneGet/oneget/issues/450

**Review by TravisEz13 — APPROVED** [review]

**Review by adityapatwardhan — APPROVED** [review]

**Comment by SteveL-MSFT** [comment]
Waiting to see result of PkgMgmt failure on macOS

**Comment by SteveL-MSFT** [comment]
@PoshChan please get failures

**Comment by PoshChan** [comment]
@SteveL-MSFT, test results were not published for PowerShell-CI-linux at vstfs:///Build/Build/22549

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 2 failures in `PowerShell-CI-macos`
PowerShellGet - Module tests (Admin).Should install a module correctly to the required location with AllUsers scope
```powershell
Expected a value, but got $null or empty.
at <ScriptBlock>, /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Modules/PowerShellGet/PowerShellGet.Tests.ps1: line 165
165:         $installedModuleInfo | Should -Not -BeNullOrEmpty
```
PowerShellGet - Module tests.Should install a module correctly to the required location with default CurrentUser scope
```powershell
Expected a value, but got $null or empty.
at <ScriptBlock>, /Users/vsts/agent/2.150.3/work/1/s/test/powershell/Modules/PowerShellGet/PowerShellGet.Tests.ps1: line 134
134:         $installedModuleInfo | Should -Not -BeNullOrEmpty
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, test results were not published for PowerShell-CI-static-analysis at vstfs:///Build/Build/22547

**Comment by PoshChan** [comment]
@SteveL-MSFT, test results were not published for PowerShell-CI-windows at vstfs:///Build/Build/22550

**Pull request merged**
