### PR TITLE
Cmdlets: Set -Subject parameter to non-mandatory on Send-MailMessage command

### LINKED ISSUE #4043: Send-MailMessage $Subject Mandatory=$true
Not a bug, but a request for "Send-MailMessage" cmdlet

```powershell
 $From = $email
    $To = $Number
    $Body = "Something"
    $Subject = $null
    $SMTPServer = "smtp.gmail.com"
    $SMTPPort = "587"
    Send-MailMessage -From $From -to $To -Subject $Subject `
        -Body $Body -SmtpServer $SMTPServer -port $SMTPPort -UseSsl `
    -Credential $Cred
```

RESULT:
```
Send-MailMessage : Cannot validate argument on parameter 'Subject'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
At line:8 char:52
+       -Body $Body -SmtpServer $SMTPServer -Subject $Subject -port $SM ...
+                                                    ~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Send-MailMessage], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Microsoft.PowerShell.Commands.SendMailMessage
```

CAUSE:
```
[Parameter(Mandatory=$true, Position=1)]
        [Alias('sub')]
        [ValidateNotNullOrEmpty()]
        [string]
        ${Subject},
```

--------
Emails do not require subjects to be present.  However, in the Send-MailMessage cmdlet, the $subject parameter is set to "Mandatory=$true".  Since an email does not require a subject, this should really be set to "$false". 

I've created my own workaround this, but I feel that this should be changed since a subject is not imperative for an email to be sent.

### PR DESCRIPTION
**Pull request by pcgeek86**
Fixes #4043 

Cheers,
Trevor Sullivan

### CODE REVIEW

**Comment by pcgeek86** [comment]
FYI @joeyaiello @stevel-msft

**Comment by SteveL-MSFT** [comment]
Should it output a warning if no subject?

**Comment by pcgeek86** [comment]
Hmm, good thought but my vote would be no.

**Comment by BitteringAgent** [comment]
Now that I think about it.  It should work like any other email application where there is a warning for no subject.  So there should be a warning, but also there should be a -Force to push past the warning of having no subject.

**Comment by SteveL-MSFT** [comment]
@BitteringAgent `-force` wouldn't be needed as a warning is just informational

**Comment by BitteringAgent** [comment]
Ah, I haven't dealt with too many cmdlets with warnings other than maybe doing a remote session into Exchange Online.  Thanks.

**Comment by iSazonov** [comment]
Missing Subject is a very bad practice. By default, we must ask for it to present. Maybe add `-IgnoreSubject`?

**Comment by SteveL-MSFT** [comment]
Another option is to prompt and allow `-force`

**Comment by TravisEz13** [comment]
restarted mac tests due to random failure.

**Comment by TravisEz13** [comment]
I agree with @iSazonov , but prefer @SteveL-MSFT 's proposal to fix the issue.

**Comment by iSazonov** [comment]
@pcgeek86 Could you please continue?

**Comment by dantraMSFT** [comment]
I think a better user experience would be to leave Subject as mandatory and place it in a 'Subject' parameter set.  Add a -NoSubject switch and place it in a 'NoSubject' parameter set, then set the default parameter set to 'Subject'.
This ensures the best practice is the default, avoids having to use an ambiguous -Force switch while still requiring an explicit choice to send without an subject.

**Comment by TravisEz13** [comment]
@pcgeek86 comments haven't been addressed in a long time.  At some point, if comments are not addressed, I'll close the PR.

**Pull request closed without merging**
