### PR TITLE
Add 'osx.10.12-x64' runtime to project.json files

### LINKED ISSUE #3070: osx.10.12-x64 is not a supported RID for building powershell
Steps to reproduce
------------------

On a clean macOS 10.12 installation do a build.

Expected behavior
-----------------

Build ok

Actual behavior
---------------

```
PS /Users/vors/dev/PowerShell> dotnet --info                                                                          
.NET Command Line Tools (1.0.0-preview2-1-003177)

Product Information:
 Version:            1.0.0-preview2-1-003177
 Commit SHA-1 hash:  a2df9c2576

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.12
 OS Platform: Darwin
 RID:         osx.10.12-x64
PS /Users/vors/dev/PowerShell> Start-PSBuild -Clean                                                                   Cleaning your working directory. You can also do it with 'git clean -fdX'                                             
Skipping repository bin/Modules/archive
Removing dotnet-install.sh
Removing dotnet-uninstall-pkgs.sh
Removing powershell.version
Skipping repository src/powershell-unix/bin/Linux/netcoreapp1.0/osx.10.11-x64/Modules/archive
Skipping repository src/powershell-unix/bin/Linux/netcoreapp1.0/osx.10.11-x64/publish/Modules/archive
Skipping repository src/powershell-unix/bin/Linux/netcoreapp1.1/osx.10.11-x64/Modules/archive
VERBOSE: Using configuration 'Linux'
VERBOSE: Top project directory is /Users/vors/dev/PowerShell/src/powershell-unix
VERBOSE: Using framework 'netcoreapp1.1'
The variable cannot be validated because the value osx.10.12-x64 is not a valid value for the Runtime variable.
At /Users/vors/dev/PowerShell/build.psm1:528 char:9
+         $Runtime = dotnet --info | % {
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], ValidationMetadataException
    + FullyQualifiedErrorId : ValidateSetFailure
 
Could not determine Runtime Identifier, please update dotnet
At /Users/vors/dev/PowerShell/build.psm1:535 char:13
+             Throw "Could not determine Runtime Identifier, please upd ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not deter...e update dotnet:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not determine Runtime Identifier, please update dotnet
```

### PR DESCRIPTION
**Pull request by vors**
Fixes #3070

### CODE REVIEW

**Comment by vors** [comment]
Not sure why PR is marked as `cla-required`. I signed up CLA a long time ago (before joining MS github org).

**Comment by mirichmo** [comment]
Your recent status change probably confused the tool. Signing it again won't hurt (other than costing you a few minutes)

**Comment by mirichmo** [comment]
Are there any additional changes required to get it running on Sierra or is this it?

**Comment by vors** [comment]
The problem is I forgot my password from docusign and it doesn't allow me to restore it, lol

**Comment by vors** [comment]
Not I know about. I actually run the 10.11 build on 10.12 and it works just fine.

**Comment by vors** [comment]
CLA signed

**Review by mirichmo — APPROVED** [review]

**Pull request merged**
