### PR TITLE
Fix test hooks for `CommandLineParameterParser`

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

xUnit tests fail when running with `Debug` configuration after #11482. The failed tests are those related to `WindowsStyle_With_Right_Value` because `ConsoleControl.SetConsoleMode` actually gets called during testing but there is [no console window](https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs#L459), so the assert fails.

This PR moves the call to `ConsoleControl.SetConsoleMode` out of the argument parser.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by iSazonov — COMMENTED** [review]
My intention was to decouple completely the parser from other code - parser should only parse. I think it is better to move the ConsoleControl.SetConsoleMode() out to ConsoleHost and SettingsFile too.
Also I believe it is better to turn on a test hook only for test where it is used.

**Comment by daxian-dbw** [comment]
My idea is to make the parser self-contained as much as possible -- its properties shouldn't be changed from outside the parser except for test hooks.

Specifically, `ConfigurationName` should be properly set within the parser, so after calling `_parser.Parse(args)`, `_parser` should have the correct `ConfigurationName` value without needing to do the following:
```c#
_parser.ConfigurationName = CommandLineParameterParser.GetConfigurationNameFromGroupPolicy();
```

**Comment by iSazonov** [comment]
ConsoleHost is owner of the parser (s_cpp), it defines how use results of command line parsing so I believe all logic should be in ConsoleHost, not in the parser.
It would be surprising if the PowerShell parser started compiling or interpreting or making WMI queries.

**Comment by daxian-dbw** [comment]
I don't think it really matters to make `CommandLineParser` a pure argument parser that doesn't do anything else, and I can imagine that future changes to it for additional flags may likely add simple side effect operations to it. I don't see that's a problem.

**Comment by iSazonov** [comment]
> I don't see that's a problem

Oh, I spent many time to debug new tests because the parser has side effects. If you catch the issue again it confirms that the design is not so good and the worst thing is that this again provokes the addition of workarounds not only in tests but also in the main code. This is what I tried to avoid in my PR. Sorry for long discussion.

**Comment by daxian-dbw** [comment]
> I spent many time to debug new tests because the parser has side effects.

It reveals the fact that the code was not written in a testable way, and hence I added the constructor for testing purpose and the `_isForTesting` field.

Again, I personally don't care that much to make the argument parser a pure parser without side effect, and it's likely we cannot hold that true in future changes, unless you can catch and review all subsequent changes to the argument parser :).

For now, I care more about fixing the test failure in debug build, so I will just go with your approach for this PR.

**Comment by rjmholt** [comment]
> It reveals the fact that the code was not written in a testable way, and hence I added the constructor for testing purpose and the _isForTesting field.
>
> Again, I personally don't care that much to make the argument parser a pure parser without side effect, and it's likely we cannot hold that true in future changes, unless you can catch and review all subsequent changes to the argument parser :).

To express a personal preference, I think:

- Testability and purity are closely related, and both also help code quality and robustness
- Using flags to change side-effects into testable state means testing code paths and production code paths aren't the same
- My ideal would be for the argument parser to process the `string[] args` input and spit out an object that we could either test or send to the consuming ConsoleHost component. Similar to [this .NET library](https://github.com/commandlineparser/commandline#quick-start-examples) or [the prevailing Rust library](https://github.com/clap-rs/clap#quick-example). (System.CommandLine operates at a different level, so doesn't really compare here)

With that said, I know we ultimately want to minimise code churn and maximise performance, so an "ideal" design may not be the right move here

**Comment by iSazonov** [comment]
> I know we ultimately want to minimise code churn and maximise performance

As side value, after decoupling the parser we can easy measure its performances with `dotnet test`. 

As side thought, we do xUnit tests based exclusively on SMA and we could test decoupling (independent from SMA) code in separate xUnit tests to check the algorithms used.

**Comment by iSazonov** [comment]
The Windows test fails
```
[-] Pre-Requisistes link for 'WMF 4.0' is reachable: https://www.microsoft.com/download/details.aspx?id=40855
```
The link does not work https://www.microsoft.com/download/details.aspx?id=40855

I think it is important for Windows Installer.

/cc @TravisEz13 @adityapatwardhan  @SteveL-MSFT

**Comment by rjmholt** [comment]
> The Windows test fails

We're working on this. Unclear why it's failing

**Comment by daxian-dbw** [comment]
That test was disabled by https://github.com/PowerShell/PowerShell/pull/13479. The failure was tracked by #13478

**Review by iSazonov — APPROVED** [review]

**Review by rjmholt — APPROVED** [review]

**Pull request merged**
