### PR TITLE
Remove double spaces between words in resx files (#4740)

### PR DESCRIPTION
**Pull request by korygill**
Fix for issue #4740.

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]
@korygill Thanks for fixing the typos!

**Review by markekraus — APPROVED** [review]
lgtm

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Comment by markekraus** [comment]
@SteveL-MSFT  Thinking about this further, couldn't some of these possibly be Bucket 2 or 3 breaking changes since they modify errors that some may be relying on?

**Comment by SteveL-MSFT** [comment]
@markekraus users should not rely on parsing error messages as they can be localized.  the error messages are meant for humans to read.  automation should rely on things like the FullyQualifiedErrorId and Exception types.

**Comment by markekraus** [comment]
@SteveL-MSFT Thanks! I was pretty sure that would be the answer but wanted to verify.

**Comment by iSazonov** [comment]
We even have examples of where we changed (removed and added)  FullyQualifiedErrorId and Exception types - this was due to error correction or the addition of new features and was therefore not considered an invalid or destructive change.

**Pull request merged**
