### PR TITLE
Fixes of around 350 PSScriptAnalyzer warnings

### PR DESCRIPTION
**Pull request by bergmeister**
This is the clean and rebased version with the split into 4 separate commits as requested by the original PR #4205
Most of them are fixes of PSPossibleIncorrectComparisonWithNull, PSAvoidUsingCmdletAliases (mostly for ForEach-Object, Where-Object, Select-Object) and some PSUseDeclaredVarsMoreThanAssignment warnings.
As part of this, it was also found that a test in ParameterBindingTests needed improvement because since the null comparison is now correct, the test failed initially and needed correcting.

### CODE REVIEW

**Comment by iSazonov** [comment]
@bergmeister Thanks for your conttribution! 
Wait maintainer's reviews.

**Comment by iSazonov** [comment]
@bergmeister Sorry, it seems @lzybkr meant that we should put each change _kind_ in separate commit: %, ?, OutputType, $null and so on. I have no idea how this could be done now without a complete re-work. 

@lzybkr Can we review as is?

**Comment by lzybkr** [comment]
If you do a soft reset, then `git add -p`, git will interactively ask you which diffs (not files, but individual diffs) to add. It's still time consuming, but it makes it much easier to manage big changes, e.g. if we need to use `git bisect` to narrow down a failure.

**Comment by bergmeister** [comment]
OK. I have created #4261, which contains the separation of the commits as requested and will close this one.

**Pull request closed without merging**
