### PR TITLE
Fix the parsing code for method generic arguments

### LINKED ISSUE #16870: Parser error on daily PowerShell 7.3. build
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I have complex in-house module that started to fail to import on recent daily builds of PS 7.3. It is working correctly on PS 5.1 and PS 7.2.1 and on older daily builds of PS 7.3. I was able to narrow the offending code to the following:
```powershell
Get-CimInstance -ClassName 'Win32_NetworkAdapterConfiguration' |
	Where-Object -Property IPEnabled |
	ForEach-Object {
		[IPAddress]::Parse(
			$_.IPSubnet[
				[Array]::IndexOf($_.IPAddress, $_.IPAddress[0])
			]
		)
	}
```

Error:
```powershell
ParserError: D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:6
Line |
   6 |                  [Array]::IndexOf($_.IPAddress, $_.IPAddress[0])
     |                        ~
     | Missing ] at end of type token.

```

The *fix* is to enclose the ` [Array]::IndexOf($_.IPAddress, $_.IPAddress[0])` in extra pair of parentheses. Like so:
```powershell
Get-CimInstance -ClassName 'Win32_NetworkAdapterConfiguration' |
	Where-Object -Property IPEnabled |
	ForEach-Object {
		[IPAddress]::Parse(
			$_.IPSubnet[
				([Array]::IndexOf($_.IPAddress, $_.IPAddress[0]))
			]
		)
	}
```
But as I mentioned before the original code is working on PS 5.1, PS 7.2.1 and older daily builds of PS 7.3 so it has to be a recent change in the PS 7.3 code that is causing this.

### Expected behavior

```console
. .\Test.ps1

AddressFamily      : InterNetwork
ScopeId            :
IsIPv6Multicast    : False
IsIPv6LinkLocal    : False
IsIPv6SiteLocal    : False
IsIPv6Teredo       : False
IsIPv6UniqueLocal  : False
IsIPv4MappedToIPv6 : False
Address            : 16777215
IPAddressToString  : 255.255.255.0
```

### Actual behavior

```console
. .\Test.ps1
ParserError: D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:6
Line |
   6 |                  [Array]::IndexOf($_.IPAddress, $_.IPAddress[0])
     |                        ~
     | Missing ] at end of type token.
```

### Error details

```console
Exception             :
    Type        : System.Management.Automation.ParseException
    Errors      :
        Extent  :
        ErrorId : EndSquareBracketExpectedAtEndOfType
        Message : Missing ] at end of type token.

        Extent  :
        ErrorId : MissingEndParenthesisInMethodCall
        Message : Missing ')' in method call.

        Extent  : ]
        ErrorId : UnexpectedToken
        Message : Unexpected token ']' in expression or statement.

        Extent  : {
        ErrorId : MissingEndCurlyBrace
        Message : Missing closing '}' in statement block or type definition.

        Extent  : )
        ErrorId : UnexpectedToken
        Message : Unexpected token ')' in expression or statement.

        Extent  : }
        ErrorId : UnexpectedToken
        Message : Unexpected token '}' in expression or statement.
    Message     : At D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:6 char:11
                  +                 [Array]::IndexOf($_.IPAddress, $_.IPAddress[0])
                  +                       ~
                  Missing ] at end of type token.

                  At D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:6 char:52
                  +                 [Array]::IndexOf($_.IPAddress, $_.IPAddress[0])
                  +                                                                ~
                  Missing ')' in method call.

                  At D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:7 char:4
                  +             ]
                  +             ~
                  Unexpected token ']' in expression or statement.

                  At D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:3 char:17
                  +     ForEach-Object {
                  +                    ~
                  Missing closing '}' in statement block or type definition.

                  At D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:8 char:3
                  +         )
                  +         ~
                  Unexpected token ')' in expression or statement.

                  At D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:9 char:2
                  +     }
                  +     ~
                  Unexpected token '}' in expression or statement.
    ErrorRecord :
        Exception             :
            Type    : System.Management.Automation.ParentContainsErrorRecordException
            Message : At D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:6 char:11
                      +                 [Array]::IndexOf($_.IPAddress, $_.IPAddress[0])
                      +                       ~
                      Missing ] at end of type token.

                      At D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:6 char:52
                      +                 [Array]::IndexOf($_.IPAddress, $_.IPAddress[0])
                      +                                                                ~
                      Missing ')' in method call.

                      At D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:7 char:4
                      +             ]
                      +             ~
                      Unexpected token ']' in expression or statement.

                      At D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:3 char:17
                      +     ForEach-Object {
                      +                    ~
                      Missing closing '}' in statement block or type definition.

                      At D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:8 char:3
                      +         )
                      +         ~
                      Unexpected token ')' in expression or statement.

                      At D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:9 char:2
                      +     }
                      +     ~
                      Unexpected token '}' in expression or statement.
            HResult : -2146233087
        CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
        FullyQualifiedErrorId : EndSquareBracketExpectedAtEndOfType
        InvocationInfo        :
            ScriptLineNumber : 6
            OffsetInLine     : 11
            HistoryId        : -1
            ScriptName       : D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1
            Line             : [Array]::IndexOf($_.IPAddress, $_.IPAddress[0])

            PositionMessage  : At D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:6 char:11
                               +                 [Array]::IndexOf($_.IPAddress, $_.IPAddress[0])
                               +                       ~
            PSScriptRoot     : D:\Users\Bukem\Documents\PowerShell\SCRIPTS
            PSCommandPath    : D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1
            CommandOrigin    : Internal
        ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
    TargetSite  :
        Name          : Create
        DeclaringType : scriptblock
        MemberType    : Method
        Module        : System.Management.Automation.dll
    Data        : System.Collections.ListDictionaryInternal
    Source      : System.Management.Automation
    HResult     : -2146233087
    StackTrace  :
   at System.Management.Automation.ScriptBlock.Create(Parser parser, String fileName, String fileContents) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\runtime\CompiledScriptBlock.cs:line 660
   at System.Management.Automation.ExternalScriptInfo.ParseScriptContents(Parser parser, String fileName, String fileContents, Nullable`1 definingLanguageMode) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\ExternalScriptInfo.cs:line 263
   at System.Management.Automation.ExternalScriptInfo.get_ScriptBlock() in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\ExternalScriptInfo.cs:line 224
   at System.Management.Automation.CommandDiscovery.CreateCommandProcessorForScript(ExternalScriptInfo scriptInfo, ExecutionContext context, Boolean useNewScope, SessionStateInternal sessionState) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\CommandDiscovery.cs:line 660
   at System.Management.Automation.CommandDiscovery.CreateScriptProcessorForSingleShell(ExternalScriptInfo scriptInfo, ExecutionContext context, Boolean useLocalScope, SessionStateInternal sessionState) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\CommandDiscovery.cs:line 340
   at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(CommandInfo commandInfo, CommandOrigin commandOrigin, Nullable`1 useLocalScope, SessionStateInternal sessionState) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\CommandDiscovery.cs:line 584
   at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\ExecutionContext.cs:line 666
   at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext
context) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\runtime\Operations\MiscOps.cs:line 311
   at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][]
commandRedirections, FunctionContext funcContext) in D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\runtime\Operations\MiscOps.cs:line 510
   at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\CallInstruction.Generated.cs:line 608
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame) in
D:\DEVELOPMENT\PowerShellCore\src\System.Management.Automation\engine\interpreter\ControlFlowInstructions.cs:line 341
CategoryInfo          : ParserError: (:) [], ParseException
FullyQualifiedErrorId : EndSquareBracketExpectedAtEndOfType
InvocationInfo        :
    ScriptLineNumber : 6
    OffsetInLine     : 11
    HistoryId        : -1
    ScriptName       : D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1
    Line             : [Array]::IndexOf($_.IPAddress, $_.IPAddress[0])

    PositionMessage  : At D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1:6 char:11
                       +                 [Array]::IndexOf($_.IPAddress, $_.IPAddress[0])
                       +                       ~
    PSScriptRoot     : D:\Users\Bukem\Documents\PowerShell\SCRIPTS
    PSCommandPath    : D:\Users\Bukem\Documents\PowerShell\SCRIPTS\Test.ps1
    CommandOrigin    : Internal
ScriptStackTrace      : at <ScriptBlock>, <No file>: line 1
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0-preview.1
PSEdition                      Core
GitCommitId                    7.3.0-preview.1-56-g30eac0a11e3479cf4feac76c7fa4b8d621eaabe2
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Enabled experimental features:
```powershell
Get-ExperimentalFeature | Select-Object Name, Enabled

Name                                          Enabled
----                                          -------
PSAMSIMethodInvocationLogging                   False
PSAnsiRenderingFileInfo                         False
PSCleanBlock                                     True
PSCommandNotFoundSuggestion                     False
PSExec                                          False
PSLoadAssemblyFromNativeCode                     True
PSNativeCommandArgumentPassing                   True
PSNativeCommandErrorActionPreference             True
PSNativePSPathResolution                         True
PSRemotingSSHTransportErrorHandling              True
PSStrictModeAssignment                           True
PSSubsystemPluginModel                           True
PSDesiredStateConfiguration.InvokeDscResource    True
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #16870

Update the parsing code to only support the syntax `$var.Method[TypeName1 <, TypeName2 ...>]` for method generic arguments, not the syntax `$var.Method[[TypeName1] <, [TypeName2] ...>]`.

The latter syntax has been supported for type expression since the beginning, but it's ambiguous in this scenario because we could be looking at an indexing operation on a property like: `$var.Property[<expression>]` and the `<expression>` could start with a type expression like `[TypeName]::Method()`, or even just a single type expression acting as a key to a hashtable property. Such cases will cause ambiguities.

Even though it might be possible to write code that sorts out the ambiguity and continue to support the latter syntax for method generic arguments, I choose not to do so, because:
  1. that will definitely increase the complexity of the parsing code and also make it fragile.
  2. the latter syntax hurts readability a lot due to the number of opening/closing brackets.

The downside is that the assembly-qualified type names won't be supported for method generic arguments, but that's likely not a problem in practice, and we can revisit if it turns out otherwise.

-----

Besides, there is no point to allow declaring generic arguments for a property. Even for method group, it makes no sense to allow generic arguments to be declared for it because we don't do anything with the generic arguments for a method group, so no validation will be done -- you will see the following script works in 7.3-preview.1 unexpectedly:
```
PS:1> [string]::Join[nonexisting]

OverloadDefinitions
-------------------
static string Join(char separator, Params string[] value)
static string Join(string separator, Params string[] value)
static string Join(char separator, string[] value, int startIndex, int count)
static string Join(string separator, string[] value, int startIndex, int count)
static string Join(string separator, System.Collections.Generic.IEnumerable[string] values)
static string Join(char separator, Params System.Object[] values)
static string Join(string separator, Params System.Object[] values)
static string Join[T](char separator, System.Collections.Generic.IEnumerable[T] values)
static string Join[T](string separator, System.Collections.Generic.IEnumerable[T] values)
```

So, the related code in AST and parser are removed, and declaring a generic argument on a property will generate the same parsing errors as before:
```
PS:1> [string]::Join[nonexisting]
ParserError:
Line |
   1 |  [string]::Join[nonexisting]
     |                 ~
     | Array index expression is missing or not valid.
```

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Review by SeeminglyScience — APPROVED** [review]
LGTM!

**Comment by vexx32** [comment]
This looks good to me overall!

I would ask that we add a test similar to this actual use case from the linked issue:
```ps1
		[IPAddress]::Parse(
			$_.IPSubnet[
				([Array]::IndexOf($_.IPAddress, $_.IPAddress[0]))
			]
		)
```

It's a bit of an odd case but does look like a pretty solid test case where we should be recognising the index expression instead of a partial generic method syntax.

**Review by PaulHigin — APPROVED** [review]
LGTM

**Comment by kborowinski** [comment]
> This looks good to me overall!
> 
> I would ask that we add a test similar to this actual use case from the linked issue:
> 
> ```powershell
> 		[IPAddress]::Parse(
> 			$_.IPSubnet[
> 				([Array]::IndexOf($_.IPAddress, $_.IPAddress[0]))
> 			]
> 		)
> ```
> 
> It's a bit of an odd case but does look like a pretty solid test case where we should be recognising the index expression instead of a partial generic method syntax.

It indeed looks a bit odd but it's just a simplified version of following code that selects IP subnet from IP subnets array based on IP address index in corresponding IP address array:
```powershell
...
$IPAddress = $_.IPAddress | Where-Object {$_ -like $using:Filter} | Select-Object -First 1
$IPSubnet  = [IPAddress]::Parse(($_.IPSubnet[[Array]::IndexOf($_.IPAddress, $IPAddress)]))
...
```

**Comment by daxian-dbw** [comment]
The `Invoke-WebRequest` failures are known test issues, not related to changes in this PR.

**Pull request merged**
