### PR TITLE
WIP: Add empty line between single-line declarations

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

Automate fix of [RCS0012](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS0012.md)

[RCS0012.log](https://github.com/PowerShell/PowerShell/files/4706617/RCS0012.log)

## PR Context

follow-up #12824

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/powershell/12849)

### CODE REVIEW

**Comment by xtqqczze** [comment]
This PR makes 5548 changes, I think this could be a step too far.

**Comment by xtqqczze** [comment]
@iSazonov I am minded to abandon this PR unless you see a value in the changes?

Maybe I should fix 136 violations of `SA1516: ElementsMustBeSeparatedByBlankLine` in seperate PR?

**Comment by xtqqczze** [comment]
rebased to resolve merge conflicts

**Review by TravisEz13 — COMMENTED** [review]
> Reviewed 67 of 452 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/powershell/12849)* status: 67 of 452 files reviewed (waiting on @adityapatwardhan, @anmenaga, @daxian-dbw, @SteveL-MSFT, and @TravisEz13)

**Review by TravisEz13 — COMMENTED** [review]
> Reviewed 17 of 452 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/powershell/12849)* status: 84 of 452 files reviewed (waiting on @adityapatwardhan, @anmenaga, @daxian-dbw, @SteveL-MSFT, and @TravisEz13)

**Comment by TravisEz13** [comment]
This is way too big.  Can you split into a PR of about 100 files each?
also a reviewable link would be good in a large PR like this, it let's me review one file at a time.

This hung my browser, so getting a PR this size is a horrible experience.

**Comment by xtqqczze** [comment]
@TravisEz13 do you see value in this PR? Before you review any further, perhaps the other maintainers could weigh in on whether the changes are desirable? Compared with #12824 I think these changes are borderline.

**Comment by iSazonov** [comment]
I think the change does not add value and we can ignore this.

**Comment by xtqqczze** [comment]
@TravisEz13 Do you think these changes add value, or not?

**Comment by adityapatwardhan** [comment]
I think this does not provide enough value to accept such are large change.

**Comment by xtqqczze** [comment]
closed as per @iSazonov and @adityapatwardhan

**Pull request closed without merging**
