### PR TITLE
[WIP] Make named pipe IPC opt-in

### PR DESCRIPTION
**Pull request by PaulHigin**
# PR Summary

This PR makes the IPC named pipe listener, which currently always runs, opt-in.  This addresses issue #11599.

## PR Context

Since about PowerShell 5.0, every PowerShell session has a running IPC (inter-process communication) listener that allowed other PowerShell sessions on a local machine (with appropriate privileges) to attach to it and debug running script.  One downside to this is on non-Windows platforms where the created named pipe used for the connection does not always get cleaned up after the session process terminates.  Another drawback is that an extra listener thread always runs in a PowerShell session, that is rarely used.

The fix is to make the IPC listener thread opt-in, through both a new `-StartIPCListener` pwsh.exe parameter and a new `System.Management.Automation.Runspaces.Runspace.StartIPCListener()` API.  This makes debugging running script on other PowerShell sessions less convenient but still doable.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [x] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [x] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by PaulHigin** [comment]
We discussed this some more and agree that opt-out would be less disruptive and still allow users not to have the listener running.  However, the original concern (#11599) was about named pipe files being littered on non-Windows platforms, if PowerShell is abruptly terminated (clicking on the terminal window close button rather than running `exit` command).  I did some investigation and dotNet puts the named pipe file in the users `/tmp` directory.  But it turns out that the CLR also creates three temporary files (two of which are used for debugging), and these files also get leaked.  So disabling PowerShell named pipe listener will not completely solve the problem.  The good news is that these files do get cleaned up on machine reboot, so those temporary files will not remain indefinitely.

**Comment by TravisEz13** [comment]
Based on the current behavior, I agree that Opt-in is a better model as we are getting many reports of this failing very frequently in Ubuntu 22.04

**Comment by jborean93** [comment]
Could pwsh on startup run in a separate thread a method that cleans up older pipes where the PID for that path has already exited? It would be annoying for this to become opt-in as I do fine it quite useful that `Enter-PSHostProcess` just works without having to respawn a new process.

**Comment by PaulHigin** [comment]
@jborean93 I agree that the listener always running is pretty convenient, but it is good to get community input to verify that.  The system already cleans up these temporary files on machine reboot (maybe even user log in/out, but not sure), so I don't think it is necessary to have PowerShell add a redundant cleaning mechanism.  At this point I feel `opt-out` is the right thing to do (sorry if I wasn't clear).  This is similar to what dotNET CLR does now (via environment variable) and gives users the option to opt-out of the listener, and not have littered files causing false alerts, but by default the listener will continue to always run on session start.

**Comment by PaulHigin** [comment]
Closing this PR due to change from opt-in to opt-out preference.

**Comment by olii** [comment]
Is there a PR that implements the opt-out preference?

**Pull request closed without merging**
