### PR TITLE
Add DocumentationAnalyzers to build

### LINKED ISSUE #14321: Enable DocumentationAnalyzers
Enable DocumentationAnalyzers for build and live analysis.

* Add package reference to [DotNetAnalyzers/DocumentationAnalyzers](https://github.com/DotNetAnalyzers/DocumentationAnalyzers).
* Disable all rules

Rule documentation:
https://github.com/DotNetAnalyzers/DocumentationAnalyzers/blob/master/docs/StyleRules.md
https://github.com/DotNetAnalyzers/DocumentationAnalyzers/blob/master/docs/PortabilityRules.md
https://github.com/DotNetAnalyzers/DocumentationAnalyzers/blob/master/docs/Refactorings.md

For example, #14220 fixed [DOC104: UseSeeLangword](https://github.com/DotNetAnalyzers/DocumentationAnalyzers/blob/master/docs/DOC104.md) rule violations.

### PR DESCRIPTION
**Pull request by xtqqczze**
Fix #14321.

* Enable [DOC104: UseSeeLangword](https://github.com/DotNetAnalyzers/DocumentationAnalyzers/blob/master/docs/DOC104.md) as suggestion.

### CODE REVIEW

**Comment by iSazonov** [comment]
My concern is that will delay build. We should think about how to exclude analyzers when they are not needed, for example, when we need to quickly recompile a project locally.

I think the analyzer is not critical for us today and we could add it as optional. Optional GitHub check?

**Comment by xtqqczze** [comment]
PowerShell-CI-windows (Build for Windows Windows Build) #PR-14336-20201206.01 Add DocumentationAnalyzers to build completed in 14m 10s.

**Comment by xtqqczze** [comment]
> My concern is that will delay build. We should think about how to exclude analyzers when they are not needed, for example, when we need to quickly recompile a project locally.
> 
> I think the analyzer is not critical for us today and we could add it as optional. Optional GitHub check?

For a quick local build: `dotnet build -p:RunAnalyzers=false`

**Comment by xtqqczze** [comment]
> > My concern is that will delay build. We should think about how to exclude analyzers when they are not needed, for example, when we need to quickly recompile a project locally.
> > I think the analyzer is not critical for us today and we could add it as optional. Optional GitHub check?
> 
> For a fast local build: `dotnet build -p:RunAnalyzers=false`

@iSazonov Perhaps we could add `-SkipAnalyzers` switch parameter to `Start-PSBuild`?

**Comment by iSazonov** [comment]
> @iSazonov Perhaps we could add `-SkipAnalyzers` switch parameter to `Start-PSBuild`?

Good point.

**Review by iSazonov — APPROVED** [review]

**Pull request merged**
