### PR TITLE
Invoke-RestMethod/WebRequest: Support CTRL-C when reading data and connection hangs

### LINKED ISSUE #16145: Invoke-WebRequest not responding to «Ctrc+c»
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am experiencing a problem with this comandlet.
I started it to downloading and turned off the router.  Comandlet hanged and hangs for more than 10 hours.
I think it should be breaked after I push «Ctrl+c», but it continue hanging.
Sorry my English.

### Expected behavior

```console
«Ctrl+c» – and Oll Korrect.
```

### Actual behavior

```console
Nothing changes.
```

### Error details

```console
I can not start the next command.
```

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19043
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

I prepared the window of PowerShell and reduced the speed of the router to minimal:

I pushed the «Enter»:

I turned off the router:

Now I am trying unsuccessfully to stop it.

### PR DESCRIPTION
**Pull request by stevenebutler**
APIs that should be cancelled are passed the cancellation token so that CTRL-C can cancel even when processing long or timed-out response streams.

Switched use of synchronous stream APIs to asynchronous APIs that use the cancellation token.

# PR Summary

This PR closes #16145

The root cause of these issues was that once the response headers are read, the cancellation token was not always being passed to APIs that deal with reading the response stream. 

In some scenarios, CTRL-C worked (where the cancellation token was being passed down), but this was not occurring in all scenarios and the use of blocking read APIs that do not take cancellation tokens prevented the early cancellation when CTRL-C was used.

## PR Context

This PR helps because it allows all I/O in the web requests cmdlets to be cancelled if the user uses CTRL-C to terminate processing.

A previous iteration of this PR added a timeout, but was incorrect as the desired behaviour is to cancel if the connection is stalled for 5 minutes, not after a fixed timeout.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by stevenebutler** [comment]
@CarloToso and @iSazonov - I renamed the branch to better reflect what this is doing. This closed the PR #19315 I had open so I've opened this one instead for review. Changes are similar to what @CarloToso already reviewed, but updated against latest master changes and with all code factor issues in changed files resolved.

**Comment by adityapatwardhan** [comment]
I think we should add tests for this behavior. I was thinking of executing Invoke-WebRequest and Invoke-RestMethod under the PowerShell API and call a `Stop()` on it. That should be equivalent to sending a cancellation.

Example of using the API:
```powershell
$ps = [PowerShell]::Create()
$ps.AddScript("Invoke-WebRequest .......")
$ps.Stop()
```
and then use `Wait-UntilTrue` to verify that the pipeline was stopped in a resonable time.

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]
We should add a test.

**Comment by stevenebutler** [comment]
> I think we should add tests for this behavior. I was thinking of executing Invoke-WebRequest and Invoke-RestMethod under the PowerShell API and call a `Stop()` on it. That should be equivalent to sending a cancellation.
> 
> Example of using the API:
> 
> ```powershell
> $ps = [PowerShell]::Create()
> $ps.AddScript("Invoke-WebRequest .......")
> $ps.Stop()
> ```
> 
> and then use `Wait-UntilTrue` to verify that the pipeline was stopped in a resonable time.

Ok, I'll look into it when I have some spare time. I assume there's a way to get the web server harness to delay writing, or should I modify it to permit that if it doesn't already?

**Comment by adityapatwardhan** [comment]
There is a Delay in the WebListener - https://github.com/PowerShell/PowerShell/blob/4767c8c6d3d4d409f0835fce390d8713a816f8fb/test/tools/WebListener/Controllers/DelayController.cs#L17-L29

**Comment by adityapatwardhan** [comment]
Sure, please add more functionality to WebListener if needed.

**Comment by iSazonov** [comment]
The PR does not solve the problem completely as I pointed in related issue.

**Comment by stevenebutler** [comment]
> The PR does not solve the problem completely as I pointed in related issue.

I reviewed your comment in the related issue and I don't agree with your conclusion. You claim that cancellation tokens don't always work with the asynchronous API but the issue you link to does not support your argument. In that issue the core team dispute that cancellation tokens can't cancel the async APIs and provided some sample code that would solve the issue. 

It looks like you want to use synchronous APIs with HttpClient and have it honour timeouts set on the HttpClient but were advised that the synchronous APIs are incomplete and won't do what you want. To resolve this issue we should be using the async APIs instead since they are fully cancellable (and if they're not then that's a legitimate bug the core team would fix if we can provide them with a reproducible test case).

If you have a specific test case that this PR doesn't solve for hanging on CTRL-C then it would be an oversight on my part (e.g. missing converting one of the synchronous reads to asynchronous with cancellation token), and I will look into it.

**Comment by stevenebutler** [comment]
> Sure, please add more functionality to WebListener if needed.

I have added a range of tests around the CTRL-C handling as suggested. I have also manually tried some of these cases using the /Stall endpoint in the WebListener and can confirm that once the download has started with existing PowerShell, the response cannot be cancelled if the stream has stalled.

With the changes, a stalled stream cancels immediately when CTRL-C is pressed.

I do have some concerns the tests may be a little timing sensitive since we are racing the CTRL-C with the response headers already having been received and there's no easy way to synchronise that. I've tried to keep the times really short so the tests don't take too long, but they could be increased if the tests are flaky in the CI system.

**Comment by iSazonov** [comment]
> If you have a specific test case that this PR doesn't solve 

You can see in related dotnet issue.

> It looks like you want to use synchronous APIs with HttpClient

Web cmdlets are synchronous by design. 
Asynchronous methods can be used for some reasons, but they do not make this code synchronous.
I already tried to do what you do and it is not a general solution and only complicates the code. All we need to do is stop the cmdlet and for this we don't need to implement CTS in the operations available to us because there are unavailable ones.

**Comment by stevenebutler** [comment]
> > If you have a specific test case that this PR doesn't solve
> 
> You can see in related dotnet issue.
> 
> > It looks like you want to use synchronous APIs with HttpClient
> 
> Web cmdlets are synchronous by design. Asynchronous methods can be used for some reasons, but they do not make this code synchronous. I already tried to do what you do and it is not a general solution and only complicates the code. All we need to do is stop the cmdlet and for this we don't need to implement CTS in the operations available to us because there are unavailable ones.

There do not appear to be any async versions of the methods that don't accept a CTS, and they were changed from synchronousOp(...) to asyncOp(..., cts).GetAwaiter.GetResult() in the patch because WebCmdlets are synchronous. 

The PR includes tests that test the web cmdlets will cancel immediately while the connection is stalled for a variety of response types, including download to file, processing ATOM responses and processing JSON responses which definitely don't work with PS 7.3.3 and work with the PR.

The patch only makes an exception for using CTS when reading from memorystream, since they do not require IO so should terminate within a reasonable time.

 If there's a specific case I've missed please describe it so the PR can be improved to address it (or rejected if it cannot be fixed).

**Comment by stevenebutler** [comment]
Latest forced push expands the tests to cover more scenarios, including HTTPS/HTTP and br, gzip and deflate content-encoding schemes.

**Comment by stevenebutler** [comment]
Synced with changes in master...

**Comment by stevenebutler** [comment]
@adityapatwardhan I'm not sure why it says I asked to remove the other review requests. I had requested you review the change again after I added unit tests for the feature as per your request. If those other people need to review as well, can you add them back to the PR reviewers?

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]

**Review by adityapatwardhan — APPROVED** [review]

**Comment by stevenebutler** [comment]
Hi @adityapatwardhan , thank you for the review. I see the macos build has timed out and is blocking the merge. Is there something I should do to address this? It looks unrelated to my change.

Thanks for removing the additional tag.

**Comment by adityapatwardhan** [comment]
@stevenebutler Thank you for your contribution!

**Comment by daxian-dbw** [comment]
@stevenebutler 
Some of the Ctrl-C tests added in this PR are fragile and have been failing a lot in CIs, one example: https://github.com/PowerShell/PowerShell/pull/19529/checks?check_run_id=12840094279. Can you please take a look and make the tests more reliable? /cc @adityapatwardhan

**Comment by stevenebutler** [comment]
@daxian-dbw  The tests rely on timeouts occurring within about a second of when you'd normally expect them to occur which might be a bit risky if running on heavily subscribed hardware.

The only way I can think of to make them more reliable is to give a larger window for the passing of time vs the expectation that the cancellation will take affect. What is generally considered a reasonable test duration when testing for timeouts?

**Comment by stevenebutler** [comment]
Have created #19532 which increases timeouts but it is failing on macos due to an unrelated test right now.

**Pull request merged**
