### PR TITLE
Fix download links for msi

### PR DESCRIPTION
**Pull request by vors**
Addresses #2522

### CODE REVIEW

**Comment by iSazonov** [comment]
@vors These links are corrected every two weeks!
May be use common link?  [Latest release](https://github.com/PowerShell/PowerShell/releases/latest)

**Comment by andschwa** [comment]
@iSazonov it's been discussed but too many users do not know which installer corresponds to their platform (despite extensive documentation), so this is easier than answering the same question a dozen times.

**Comment by iSazonov** [comment]
Anyone who creates a new release creates a release notes where this information is already present.

**Comment by andschwa** [comment]
Like I said, it's already extensively documented. Unfortunately that does not help users who do not read documentation (nor release notes). There exist enough users (judging by the number of questions I've fielded about exactly this) to warrant this info running up front, immediately available in the readme/front page.

**Comment by iSazonov** [comment]
I can well understand your headache that such questions raise. 😊 
Maybe we should generate the file based on a template?

**Pull request merged**
