### PR TITLE
Improve PSMethod-to-Delegate conversion

### PR DESCRIPTION
**Pull request by daxian-dbw**
## PR Summary

Related to #5618

Two improvements:
1. Avoid unnecessary reflection in `ConvertPSMethodInfoToDelegate`. `PSMethod` already has the `MethodInfo` information with its `adapterData` field.
2. Avoid creating the generic `PSMethod<>` type for `PSMethod` that represents constructors, because constructors cannot be converted to a delegate anyways. In case that the `PSMethod` represents constructors, we use a simple `PSMethod` instance instead.

Also, rename the type `Unit` to `VOID` to make it more readable, since that type represents `typeof(void)`.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by rjmholt — APPROVED** [review]
Looks good to me.

One thing I'm curious about is the `MethodGroup` tuple type. I've seen similar code in [MutableTuple](https://github.com/PowerShell/PowerShell/blob/fb286e6cf8480fe6df8a5a96311d6758e5c2b9f3/src/System.Management.Automation/engine/runtime/MutableTuple.cs) and wonder (1) why we use this and (2) if we document that anywhere. Anyway, that's orthogonal to this PR.

**Comment by daxian-dbw** [comment]
@rjmholt `MethodGroup` is used to generate _fake_ types representing the signatures of method overloads represented by `PSMethod`. You can look at the original PR #5287 for detailed info.

**Review by powercode — COMMENTED** [review]
Nice cleanup!

LGTM

**Review by powercode — APPROVED** [review]

**Comment by rjmholt** [comment]
Looks like an unrelated network test failure:
```
TEST FAILURES
Description: Test-Connection/Ping
Name:        Force IPv4 with implicit PingOptions
message:
Expected exactly '8.8.8.8', but got 0.0.0.0.
stack-trace:
at <ScriptBlock>, /home/travis/build/PowerShell/PowerShell/test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1: line 84
84:             $result.Replies[0].Address              | Should -BeExactly $realAddress
Description: Test-Connection/Ping
Name:        Force IPv4 with explicit PingOptions
message:
Expected exactly '8.8.8.8', but got 0.0.0.0.
stack-trace:
at <ScriptBlock>, /home/travis/build/PowerShell/PowerShell/test/powershell/Modules/Microsoft.PowerShell.Management/Test-Connection.Tests.ps1: line 98
98:             $result1.Replies[0].Address              | Should -BeExactly $realAddress
```

**Comment by daxian-dbw** [comment]
Thanks @rjmholt and @powercode for your reviews!

**Pull request merged**
