### PR TITLE
Move misplaced test file to tests directory

### LINKED ISSUE #14832: Test file in the wrong place
There's a test file at https://github.com/PowerShell/PowerShell/blob/master/src/System.Management.Automation/engine/Modules/ImportProvider.Tests.ps1.

It should be under the `tests/` directory.

### PR DESCRIPTION
**Pull request by MarianoAlipi**
# PR Summary

Fix #14832
Move file `src/System.Management.Automation/engine/Modules/ImportProvider.Tests.ps1` to `test/powershell/Modules/Microsoft.PowerShell.Core/ImportProvider.Tests.ps1`

## PR Context

This pull request is a simple fix to issue #14832 

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by rjmholt — DISMISSED** [review]

**Comment by TravisEz13** [comment]
https://dev.azure.com/powershell/PowerShell/_build/results?buildId=73987&view=logs&j=65e467a7-433b-584d-c8f4-72fcd5732f9d&t=6a14d04a-9a6d-5c41-f839-531117eeb032&l=3618

**Comment by MarianoAlipi** [comment]
I suppose that test wasn't being run so it didn't show any errors before. The `ReproModule` directory it tries to import doesn't exist anywhere in the repository. So I'm thinking there are missing files or the test was only temporary and slipped into the repository. What should we do?

**Comment by rjmholt** [comment]
Looks like the file was added by @iSazonov in https://github.com/PowerShell/PowerShell/pull/11813. @iSazonov what's the right way to make these tests work?

**Comment by iSazonov** [comment]
> Looks like the file was added by @iSazonov in #11813. @iSazonov what's the right way to make these tests work?

It's mystic how it happened :-(

We should replace:
```powershell
    It "Import a PowerShell provider with correct name" {
        $result = & $pwsh -NoProfile -Command "Import-Module -Name $testModulePath; Get-Item ReproModule\SamplePrv::test.txt"
        $result.PSPath | Should -BeExactly "ReproModule\SamplePrv::test.txt"
    }
```
with
```powershell
    It "Import a PowerShell provider with correct name" {
        $result = & $pwsh -NoProfile -Command "Import-Module -Name $testModulePath; (Get-Item ReproModule\SamplePrv::test.txt).PSPath"
        $result | Should -BeExactly "ReproModule\SamplePrv::test.txt"
    }
```

**Review by iSazonov — APPROVED** [review]

**Review by rjmholt — APPROVED** [review]

**Comment by iSazonov** [comment]
@MarianoAlipi Thanks for your contribution!

**Comment by MarianoAlipi** [comment]
Thank you everyone for your help during the whole process! :)

**Pull request merged**
