### PR TITLE
Implement exponent operator

### PR DESCRIPTION
**Pull request by Gimly**
Here's a first working draft of implementation for adding a Power operator, as discussed in issue #3603.

I decided to go with the ** option, as it's, I think, the most common power operator in the different languages that has it. For now, I've implemented only the operator working on numeric values, as a binary operator.

I have tried to follow the same type of implementation as how the multiply operator. It's just a draft and I'm willing to improve it until it's perfect and can me merged.

### CODE REVIEW

**Review by lzybkr — COMMENTED** [review]
General feedback:

* We'll want committee approval for this.
* We could use `^` to be more like VB and some other languages.
* We probably don't need to return anything but `double`
* Precedence for exponentiation is usually higher than multiply
* There are no tests.

Arguments against taking this change:

* C# and C++ don't have this operator, so why would PowerShell
* Increased complexity in teaching for an infrequent operation, `[Math]::Pow()` is terse and descriptive.

**Comment by iSazonov** [comment]
`[Math]` contains many functions - I don't see the point of starting the process of moving them into PowerShell language.

**Comment by RichardSiddaway** [comment]
Agreed that this doesn't seem worth the effort. if the exponential operator is being added why not the square root and trigonometric operators - SIN, COS, TAN etc.  This functionality is readily available through [math] so why add it to PowerShell

**Comment by Gimly** [comment]
While I agree that we already have access relatively easily to pow with the `[Math]::Pow()`, it makes the code much less readable when doing mathematical operations.

```PowerShell
$cSquared = [Math]::Pow($a, 2.0) + [Math]::Pow($b, 2.0)
```
is, in my opinion, much less readable than
```PowerShell
$cSquared = $a^2.0 + $b^2.0
```
Not sure that the fact that C# or C++ doesn't have the operator is that good of an argument, I'm sure a lot of people are missing it in those languages as well. I definitely did at multiple occasion when writing C# code.

But, I also agree that it might just bring more demand for other mathematical operators and I'm not sure if it's really PowerShell's main goal. In the end, the amount of projects who are doing advanced mathematics with PowerShell is probably very low.

Anyway, I did those changes as a small exercise to discover PowerShell's code ans also because the issue was marked with the Hacktoberfest label 😄. It was very instructive for me, so no hurt feelings if you decide that in the end it's not interesting to add this operator. I understood when I started that it was going to create philosophical questioning about the use of the operator (it had already started in the issue).

If you do decide that you'd like to have the operator, I'll be happy to update my code and fix all the issues that @lzybkr gave me in the feedback.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and decided not to add additional math operators.  Some of the concerns:
  - prefer to have one canonical way `Math.Pow()` rather than allowing multiple ways of doing the same thing
  - adding this operator incurs the cost of spending more time reviewing the semantics and setting precedent for other possible operators
  - `Math.Pow()` seems sufficient for the limited expected usage

We thank @Gimly for taking the time working on this, but perhaps pick up a different `Hacktoberfest` issue :)

**Comment by Gimly** [comment]
@SteveL-MSFT thanks, I will definitely try my luck on a different Hacktoberfest issue, hopefully one a bit less controversial 😄.

**Pull request closed without merging**
