### PR TITLE
Update Get-ComputerInfo test to properly test DeviceGuard items.

### PR DESCRIPTION
**Pull request by jeffbi**
This PR builds on #3279

### CODE REVIEW

**Comment by jeffbi** [comment]
How can I find what went wrong with the Travis CI build? It *looks* like it something failed on OS X, but I've been able to run the tests on Windows, Linux, and OS X without errors. The tests are skipped on non-Windows, but none fail.

**Comment by mirichmo** [comment]
It looked like it didn't start. I restarted it to see if it'll run

**Comment by jeffbi** [comment]
@SteveL-MSFT, can you look at this when you have time?

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Review by mirichmo — APPROVED** [review]

**Pull request merged**
