### PR TITLE
Remove notes about `ITuple` changes(#7633) from v6.2.0-preview.1 updates.

### PR DESCRIPTION
**Pull request by stknohg**
## PR Summary

Related #8070, #8077.

The notes of #7633 was already included in PowerShell Core 6.1.0 stable.

Note: We also must update [Release notes of v6.2.0-preview.1](https://github.com/PowerShell/PowerShell/releases/tag/v6.2.0-preview.1).

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by anmenaga — COMMENTED** [review]
Changing change log is probably too late.
But we can manually update description of the v6.2.0-preview.1 release.

**Comment by iSazonov** [comment]
The update is useful for next release.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
Reopen PR to restart CIs.

**Comment by iSazonov** [comment]
@SteveL-MSFT @TravisEz13 Can we fix the change log issue?

**Comment by SteveL-MSFT** [comment]
If the changelog is wrong, we should fix it.  We can ignore the WIP bot since it's clear it doesn't apply to this PR.

**Comment by iSazonov** [comment]
@TravisEz13 Please merge the PR.

**Pull request merged**
