### PR TITLE
Update pester syntax to v4

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

* Update Pester tests to dashed v4 syntax
* Capitalise 'Should' and parameters

## PR Context

Pester documentation for 4.x recommends using Should -Be instead of Should Be syntax.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
- **User-facing changes**
    - [x] Not Applicable
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Comment by xtqqczze** [comment]
CodeFactor issues are unrelated to this PR.

**Comment by xtqqczze** [comment]
Fix #6265

**Comment by iSazonov** [comment]
@xtqqczze It is a huge PR. Please to split it on some small PR. It is easy to fix and review.

**Comment by xtqqczze** [comment]
CodeFactor issues are not new.

**Comment by xtqqczze** [comment]
@iSazonov Removed some commits and rebased, PR is ready for merge.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@xtqqczze  Thanks for your contribution!

**Pull request merged**
