### PR TITLE
Use `List.ConvertAll` instead of LINQ

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

## PR Context

https://docs.microsoft.com/dotnet/api/system.collections.generic.list-1.convertall

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [NA] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [NA] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [NA] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [NA] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [NA] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [NA] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [NA] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [NA] Issue filed: 
        - [NA] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [NA] Issue filed: 
        - [NA] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [NA] Issue filed: 
        - [NA] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [NA] Issue filed:

### CODE REVIEW

**Comment by TravisEz13** [comment]
Do we have performance results before and after for this?

cc @daxian-dbw

**Comment by xtqqczze** [comment]
@TravisEz13 In general, there's not a large performance difference between the two approaches. 

Using `ConvertAll` does avoid an IEnumerable allocation and means we can remove the `using System.Linq`.

```csharp
    private List<int> list = Enumerable.Repeat(10, 10).ToList();
    public List<string> Linq()
    {
        return list.Select(t => t.ToString()).ToList();
    }
    public List<string> ConvertAll()
    {
        return list.ConvertAll(t => t.ToString());
    }
```

https://gist.github.com/xtqqczze/22cfeb3eb34e4ca21f4af87adf4956a5

```
|   Method  |     Mean |   Error |   StdDev |  Gen 0 | Gen 1 | Gen 2 | Allocated | Code Size |
|---------- |---------:|--------:|---------:|-------:|------:|------:|----------:|----------:|
|      Linq | 352.1 ns | 8.89 ns | 25.93 ns | 0.1259 |     - |     - |     528 B |    1313 B |
|ConvertAll | 295.1 ns | 9.09 ns | 26.66 ns | 0.1087 |     - |     - |     456 B |     353 B |
```

**Comment by TravisEz13** [comment]
@daxian-dbw  Can you review?

**Comment by iSazonov** [comment]
I wonder why do you fix only one place? I found some more with `.Select(` pattern.

**Comment by xtqqczze** [comment]
> I wonder why do you fix only one place? I found some more with `.Select(` pattern.

The analyzer I used only found 1 instance of the pattern: `list.Select(d).ToList()`.

All the other locations seem to be `ienumerable.Select(d).ToList()`.

**Comment by iSazonov** [comment]
> The analyzer I used 

Ok :-)

**Review by iSazonov — APPROVED** [review]

**Comment by xtqqczze** [comment]
> > The analyzer I used
> 

[RCS1077](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1077.md)

**Comment by iSazonov** [comment]
> > > The analyzer I used
> 
> [RCS1077](https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1077.md)

It seems it does not cover array.

**Comment by anmenaga** [comment]
Format working group can you review the change?

**Review by anmenaga — APPROVED** [review]
LGTM

**Comment by anmenaga** [comment]
Maintainers reviewed and agreed to merge this.

**Pull request merged**
