### PR TITLE
Remove SemanticVersion from list of KnownTypes for serialization

### LINKED ISSUE #1819: Invoke-Command -Session $s -Command {$PSVersionTable} Fails Due to SemanticVersion
## Steps to reproduce
1. Install PowerShell 6.0.0-alpha.8
2. Register its remoting endpoint
3. Create a session to that endpoint and run Invoke-Command -Session $s -Command {$PSVersionTable}

This is another aspect of #1589 that was not fixed when addressing the original issue. The repro also shows that it works through Enter-PSSession, but not Invoke-Command.

This issue appears to be limited to the serialization & deserialization of SemanticVersion during Invoke-Command calls.
## Expected behavior

The value of $PSVersionTable should be returned.
## Actual behavior

``` powershell
PS F:\GitRepos\PowerShell> $sxs = nsn . -ConfigurationName powershell.6.0.0-alpha.8
PS F:\GitRepos\PowerShell> Invoke-Command -Session $sxs -Command {1+1}
2
PS F:\GitRepos\PowerShell> Invoke-Command -Session $sxs -Command {$psversiontable}
SemanticVersion XML tag is not recognized. Line 1, position 1046.
    + CategoryInfo          : OperationStopped: (localhost:String) [], PSRemotingTransportException
    + FullyQualifiedErrorId : JobFailure
    + PSComputerName        : localhost

PS F:\GitRepos\PowerShell> enter-pssession $sxs
[localhost]: PS C:\Users\mirichmo\Documents> $psversiontable

Name                           Value
----                           -----
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
CLRVersion
GitCommitId                    v6.0.0-alpha.8-44-ga35d6adc631309319fa9f85f142feb9b77e2b5ed
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
```
## Environment data

``` powershell
Name                           Value
----                           -----
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
PSEdition                      Core
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
CLRVersion
GitCommitId                    v6.0.0-alpha.8-44-ga35d6adc631309319fa9f85f142feb9b77e2b5ed
BuildVersion                   3.0.0.0
PSRemotingProtocolVersion      2.3
PSVersion                      6.0.0-alpha
```

### LINKED ISSUE #6448: Export-CliXml - issue with $PSVersionTable xml tag when importing CliXml to psobject .
Ok! Heard me out.  While I was playing around with PowerShell Studio to create a form to display results coming from $PSversionTable in PSCore6 psobjects exported to clixml to then import to a psobject in Windows PowerShell.  

I found out the Import-CliXml will error out in Windows PowerShell with the following message:
```
Import-Clixml : SemanticVersion XML tag is not recognized. Line 81, position 8.
At line:1 char:10
+ $psobj = Import-Clixml -Path c:\Temp\pwshobject602.xml;
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Clixml], XmlException
    + FullyQualifiedErrorId : System.Xml.XmlException,Microsoft.PowerShell.Commands.ImportClixmlCommand
```
Of course, this is not a Windows PowerShell issue as the workaround below works.

WorkAround
-----------------
Via code I had to fix the xml tag;
```
:
 $line.Replace('SemanticVersion', 'Version');
:
```
psverxml_012018-03-21_11-17-46

After fixing the xml tag then my application works. This only happens with the $PSVersionTable.

pss2018_pwshcore_win01_2018-03-21_10-53-04

Steps to reproduce
------------------

```powershell
## - Execute in PSCore 6.0.2:
(Get-Variable PSVersionTable).value.GetEnumerator()| Export-Clixml -Path c:\Temp\pwshobject602.xml;

## - Execute in Windows PowerShell:
$psobj = Import-Clixml  -Path c:\Temp\pwshobject602.xml;
Import-Clixml : SemanticVersion XML tag is not recognized. Line 81, position 8.
At line:1 char:10
+ $psobj = Import-Clixml -Path c:\Temp\pwshobject602.xml;
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Clixml], XmlException
    + FullyQualifiedErrorId : System.Xml.XmlException,Microsoft.PowerShell.Commands.ImportClixmlCommand

```

Expected behavior
-----------------
To import the CliXml to a PSobject without any error.

Actual behavior
---------------
Error: "Import-Clixml : SemanticVersion XML tag is not recognized. Line 81, position 8."

Environment data
----------------

```powershell
## - PSCore6:
PS [156] > $PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.2
PSEdition                      Core
GitCommitId                    v6.0.2
OS                             Microsoft Windows 10.0.17127
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
## PR Summary

PowerShell serialization has a list of known PowerShell types.  When an object is deserialized containing a known type it tries to deserialize the object to that specific type and throws exception if it can't succeed.  SemanticVersion only exists in PSCore6 so when remoting from Windows PowerShell or importing clixml generated from PSCore6 that contains SemanticVersion, it fails.

Fix https://github.com/PowerShell/PowerShell/issues/6448
Fix https://github.com/PowerShell/PowerShell/issues/1819

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
It seems to be not in line with the PowerShell Committee's conclusion in #6448.

**Comment by SteveL-MSFT** [comment]
@iSazonov you are correct, that committee decision was based on an incorrect hypothesis.

**Review by daxian-dbw — APPROVED** [review]
LGTM. This is probably the cleanest way to deal with this issue 🎉

**Comment by daxian-dbw** [comment]
One drawback: when PowerShell Core talks to PowerShell Core, the client side won't have a full-fledged SemanticVersion object deserialized back. So potentially this is a breaking change.

**Comment by HemantMahawar** [comment]
Given it will come back as ```Deseriealized.System.Management.Automation.SemanticVersion (PSObject)``` in both **Windows PowerShell** and **PowerShell Core**, feels like the right fix.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this and agree this is approach

**Review by PaulHigin — APPROVED** [review]
I agree that this is the right change.

**Pull request merged**
