### PR TITLE
Add Alpine Linux support

### PR DESCRIPTION
**Pull request by ghost**
## PR Summary

`sys/sysctl` header is not available in musl-libc based systems and system calls are available without any header inclusion. I have ported the cmake test from CoreFX repo (https://github.com/dotnet/corefx/blob/431475b8/src/Native/Unix/configure.cmake#L560).

Progress towards: #4605

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by kasper3** [comment]
cc @SteveL-MSFT 

This is how i built it:

```sh
docker run -it microsoft/dotnet:2.1-sdk-alpine

# in container
apk update
apk add cmake clang build-base git bash
git clone --recursive https://github.com/kasper3/powershell
cd powershell/src/libpsl-native

cmake -DCMAKE_BUILD_TYPE=Debug .
make -j
```

then, for managed,

```sh
cd ../..
dotnet restore
dotnet publish
```

`dotnet publish` throws error:

```
  Restore completed in 8.86 ms for /powershell/src/powershell-win-core/powershell-win-core.csproj.
DotNetCode/Eventing/EventDescriptor.cs(41,61): error CS0103: The name 'DotNetEventingStrings' does not exist in the current context [/powershell/src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj]
DotNetCode/Eventing/EventDescriptor.cs(46,103): error CS0103: The name 'DotNetEventingStrings' does not exist in the current context [/powershell/src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj]
DotNetCode/Eventing/EventDescriptor.cs(58,63): error CS0103: The name 'DotNetEventingStrings' does not exist in the current context [/powershell/src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj]
DotNetCode/Eventing/EventDescriptor.cs(63,105): error CS0103: The name 'DotNetEventingStrings' does not exist in the current context [/powershell/src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj]
DotNetCode/Eventing/EventProviderTraceListener.cs(45,49): error CS0103: The name 'DotNetEventingStrings' does not exist in the current context [/powershell/src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj]
DotNetCode/Eventing/EventProviderTraceListener.cs(76,45): error CS0103: The name 'DotNetEventingStrings' does not exist in the current context [/powershell/src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj]
DotNetCode/Eventing/EventProvider.cs(627,75): error CS0103: The name 'DotNetEventingStrings' does not exist in the current context [/powershell/src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj]
DotNetCode/Eventing/EventProvider.cs(664,83): error CS0103: The name 'DotNetEventingStrings' does not exist in the current context [/powershell/src/Microsoft.PowerShell.CoreCLR.Eventing/Microsoft.PowerShell.CoreCLR.Eventing.csproj]
```

**Comment by kasper3** [comment]
Following this guide https://github.com/PowerShell/PowerShell/blob/76526c6f1df08c0a55fbae79a7148a4a58805626/docs/building/internals.md, i made a breakthrough. Now stuck with another error (updated previous comment)

**Comment by kasper3** [comment]
Fixed, had to add `touch DELETE_ME_TO_DISABLE_CONSOLEHOST_TELEMETRY` at repo root. Strange requirement 😝

**Comment by SteveL-MSFT** [comment]
Got it working:

```powershell
Name                           Value
----                           -----
PSVersion                      6.0.1
PSEdition                      Core
GitCommitId                    v6.0.1-252-g982dbfe552b41ec3cd9b64f649849e8b942643d6
OS                             Linux 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by kasper3** [comment]
Hey Steve, after `dotnet publish --runtime linux-x64`, what exact command you ran to get into the shell, i am still trying to figure that out 😮

**Comment by SteveL-MSFT** [comment]
@kasper3 I had to use `dotnet publish --configuration Release --runtime linux-x64`.  Also made some changes to some .csproj files, but need to determine if those were actually necessary.  To run use `dotnet run`

**Comment by SteveL-MSFT** [comment]
@kasper3 here's the updated instructions from your list above:

```bash
# remove your last two lines and replace with
cd ../powershell-unix
dotnet publish --configuration Linux --runtime linux-x64
mv libpsl-native.so bin/Linux/netcoreapp2.0
dotnet run -c Linux
```

Perhaps for now, we can have this as a bash script until we have a build available then we can update `build.psm1` to work correctly on Alpine (it makes assumptions about being on Ubuntu)

**Comment by kasper3** [comment]
Thanks, it worked! I will add the build script with instructions in a separate commit today.

**Comment by SteveL-MSFT** [comment]
@kasper3 if you can update the PR description above to use the standard PR template, we can take this one just to get libpsl-native building on Alpine

**Comment by kasper3** [comment]
@SteveL-MSFT, done.

Please note that we are not bound to use that particular docker provided by Microsoft/dotnet, we can use a latest alpine one (or install Alpine 3.7 in VM or even bare-metal) and setup fully functional dotnet sdk like this described here: https://github.com/dotnet/cli/issues/8767. There is one additional thing I had to do (create a nuget.config, before creating the first app, since it's depending on preview2 packages, which are not yet available in nuget). Here is the final setup:

```sh
docker run -it alpine:latest
```

then in container

```sh
apk update
apk add curl libstdc++ libunwind libintl icu-libs openssl

curl -O https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-alpine.3.6-x64.tar.gz
mkdir -p /usr/bin/dotnet
tar -xzvf dotnet-sdk-latest-alpine.3.6-x64.tar.gz  -C /usr/bin/dotnet
export PATH=$PATH:/usr/bin/dotnet
rm dotnet-sdk-latest-alpine.3.6-x64.tar.gz

targetFile="/root/.nuget/NuGet/NuGet.Config"
cat > $targetFile <<-"EOF"
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
 <add key="dotnet-core" value="https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" />
  </packageSources>
</configuration>
EOF
```

Then we can use `dotnet new console` etc. and continue installing `git` and stuff to compiler powershell.

Should we have two scripts `obtain-dotnet-alpine.sh` and `build-pwsh-alpine.sh`? Preferably, those scripts could use Bourne Shell shebang `#!/bin/sh` instead of `bash`, because:

1. there is no `bash`ism in these simple commands
2. as an example, all Unix shell scripts shipped by npm and node.js are `/bin/sh`. .NET Core heavily used bash but now they are slowly converting to sh as well.
3. in latest Ubuntu, default shell is dash, in Alpine default shell is ash, in NetBSD, default shell is csh etc... and all of those require extra installation of `bash`. The only common shell between all kinds of unices is POSIX complaint Bourne Shell.. it gets bit harder to convert existing bash script to bourne shell but we can try not to introduce more `bash`ism than required and stay impartial. We can also try to convert existing .sh files to `bin/sh` at slow pace. ✌️

**Comment by krytarowski** [comment]
`#!/bin/sh` would be nice.

A correction - upstream for tcsh is NetBSD, but the default shell is Almquist Shell (ash / sh). Debian's dash is a fork of NetBSD's ash.

**Comment by TravisEz13** [comment]
dotnet said they fixed `install-dotnet.sh`, but I don't know how long it takes to go into production

**Comment by kasper3** [comment]
@TravisEz13, can't `docker run -it microsoft/dotnet:2.1-sdk-alpine` be used? Or does PowerShell repo can't use docker and requires it to be available in a VM or bare-metal?

**Comment by TravisEz13** [comment]
@kasper3 I'd have to see a working script.
I would recommend you add any custom script to build this in `tools/releaseBuild/images`   The idea is that the build is described in `tools/releaseBuild/build.json`.  The readme in `tools/releaseBuild` describes how to call a build described in `build.json`
If you even just add a docker file that does the build in that folder, I'm happy to refactor it into the build.json

Hopefully, we can get something working in `build.psm1` eventually too.

**Comment by kasper3** [comment]
@TravisEz13, I have assembled the pieces together and added a naive build script for Alpine. I couldn't quite figure out the Docker build image integration. This script clones the repository and build and run pwsh. Here is one way to run it:

```sh
# in windows 10 powershell
git clone https://github.com/kasper3/powershell
cd powershell/tools/releaseBuild/images/microsoft_powershell_alpine3
docker run -it -v $pwd\:/host microsoft/dotnet:2.1-sdk-alpine

# in alpine-dotnet container
/host/build_and_run_pwsh.sh

# after sometime you will enter powershell
```

**Comment by TravisEz13** [comment]
@kasper3 I think I can work with this.  I have some deadlines.  It may take me some time.  If I don't reply my next month, can you ping me?

**Comment by kasper3** [comment]
@TravisEz13, sure thanks!

**Comment by TravisEz13** [comment]
@kasper3 The build command from the root of the repo is `./tools/releaseBuild/vstsbuild.ps1 -Name alpine.3 -ReleaseTag v6.1.0-alpine3`

There are still two things to do:
 - [ ] the package should have the same format as the other packages (should be `powershell-6.0.2-alpine.3-x64.tar.gz`)
 - [ ] the build should be triggered with the release tag ([build.psm1 example](https://github.com/PowerShell/PowerShell/blob/master/build.psm1#L524)

**Comment by kasper3** [comment]
This is a great progress! TIL, thanks.

I was thinking that maybe we could try using a mini rootfs: https://alpinelinux.org/downloads/ in hyperv or vmwhere (it's 1.9 mbs of gz), and test if it works in non-Docker as well. I heard yesterday from musl-libc core team member (@rofl) something in between the lines of "don't just trust that it works on Alpine just because it works on Alpine docker, they have things like `libbacktrace` and `sys/queue` used in docker to make it work with underlying kernel, test on real thing too!", hence my suggestion-cum-curiosity. :)

**Comment by TravisEz13** [comment]
@kasper3 that sound like a great idea to investigate.  I would get this working as is first.  I think if we get those things done since this is an unofficial package, we can merge the PR.

Once, we have released a package, we should produce a docker file.

**Comment by TravisEz13** [comment]
@kasper3   The regex is here: https://github.com/PowerShell/PowerShell/blob/master/tools/packaging/packaging.psm1#L16
but either will work... mine was just an example.  `v6.1.0-preview.1` will be the next tag then after a series of non-stable releases we will eventually get to `v6.1.0`

**Comment by kasper3** [comment]
Thanks. I have made some changes locally and created the tarball with the matching name. The final tarball builds but..

We need to build other native components as well, `pwsh` itself, and maybe https://github.com/PowerShell/psl-omi-provider, https://github.com/Microsoft/omi? We cannot rely on prebuild Linux binaries, the tarball being produced is not distributable.

`libhostfxr.so` and other `.so` files except for the one we built *on Alpine* `libpsl-native.so` are corrupted when we try to consume pwsh from the tarball. `pwsh` itself is corrupted as it was prebuilt against glibc.

The main difference in Alpine Linux and other distros is that it uses different libc, i.e. musl-libc. So we need to compile it from ground up. .NET Team is even considering changing the inheritance of Alpine Linux RID from `unixx64->linuxx64->alpinex64` to `unixx54->alpinex64` or `unixx64->linuxmuslx64->alpninex64` etc. so the fallback RID is not a linuxX64 also known as `GLIBC based Linux` (regular one).

Should we block this PR until then? Is everything that is required to build `pwsh` native executable in the open? It seems like pwshexe project is Windows only in this repo and Linux binaries are coming from somewhere I couldn't figure out.

**Comment by kasper3** [comment]
All the native pieces need to be recompiled on Alpine then package in tarball.

**Comment by SteveL-MSFT** [comment]
@kasper3 my thinking is that this bash script is temporary to produce a working pwsh we can use on Alpine until we can update build.psm1 and packaging.psm1 to produce official Alpine builds regularly, so I wouldn't worry about the OMI aspect for now.  Regarding glibc vs musl, I would defer updating build.psm1/packaging.psm1 until dotnetcore resolves that.

**Comment by rofl0r** [comment]
@kasper3 said:
> yesterday from musl-libc core team member (@rofl0r) something in between the lines of "don't trust that it works on Alpine just because it works on Alpine docker, they have things like libbacktrace and sys/queue used in docker to make it work with underlying kernel, test on real thing too!"

correction, what i actually said was conceptually: 
> "don't trust that it works on **musl libc** just because it works on Alpine docker, they have things like libbacktrace and sys/queue <strike>used in docker to make it work with underlying kernel</strike> **to go the path of least resistance instead of identifying offenders and reporting the issue upstream**, test on real thing too!"

**Comment by TravisEz13** [comment]
@kasper3 my thinking is along the same line as @SteveL-MSFT 's this PR as is should get us there.  I think it's okay to add a new distribution as partially working.  Getting it to the point we can build it in the main build system will open it to more people to contribute, but this PR is an important step... I have the PR blocked with the WIP in the title, but I still think we should fix the two issue and proceed to fix the others.

**Comment by kasper3** [comment]
@TravisEz13, pushed my changes and opened an issue upstream: https://github.com/Microsoft/omi/issues/497. Will try to patch those separately if i get time. :)

@rofl0r, thanks for the correction! :)

**Review by TravisEz13 — APPROVED** [review]

**Review by SteveL-MSFT — APPROVED** [review]
Great contribution!  Thanks!

**Pull request merged**
