### PR TITLE
Update PowerShell to build with .NET Core SDK 2.1.4

### PR DESCRIPTION
**Pull request by iSazonov**
## PR Summary

Update repo to use latest CLI tools.
- Now we can use C# 7.2 features.
- We continue use Runtime 2.0.5

## PR Checklist

Note: Please mark anything not applicable to this PR `NA`.

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [x] Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [NA] User facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - [NA] Issue filed - Issue link:
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
    - [x] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.

### CODE REVIEW

**Review by markekraus — APPROVED** [review]
LGTM

**Comment by bergmeister** [comment]
@markekraus The build contains one failure of an `Invoke-WebRequest` test. Are you aware of this? I assume it's a known issue or a sporadic failure but it's always better to double check.

**Comment by iSazonov** [comment]
CI Appveyor failed twice but CI Travis build passed. 😕

**Comment by iSazonov** [comment]
Locally all web tests passed.

**Comment by markekraus** [comment]
`A task was canceled.` means the time out `-TimeoutSec` was reached (it's at `5` for this specific test) . These kinds of failure randomly pop up from time to time. My guess is that the CI VMs are slow or sleeping. We needed these timeouts before due to the tests relying on out-of-box endpoints. Now that all endpoints are in-box, we can probably remove them all.

**Comment by iSazonov** [comment]
@markekraus Thanks for clarify!

On my notepad the web tests took almost 10 minutes. Some tests took 2-4 seconds with almost zero processor load. I wonder why the tests so slow.
```powershell
 [+] Validates Invoke-RestMethod preserves the authorization header on multiple redirects: MultipleChoices 1.1s
 [+] Validates Invoke-RestMethod preserves the authorization header on multiple redirects: Ambiguous 1.06s
 [+] Validates Invoke-RestMethod preserves the authorization header on multiple redirects: Moved 4.12s
 [+] Validates Invoke-RestMethod preserves the authorization header on multiple redirects: MovedPermanently 4.17s
 [+] Validates Invoke-RestMethod preserves the authorization header on multiple redirects: Found 4.25s
 [+] Validates Invoke-RestMethod preserves the authorization header on multiple redirects: Redirect 4.13s
 [+] Validates Invoke-RestMethod preserves the authorization header on multiple redirects: redirectMethod 4.13s
 [+] Validates Invoke-RestMethod preserves the authorization header on multiple redirects: SeeOther 4.11s
 [+] Validates Invoke-RestMethod preserves the authorization header on multiple redirects: TemporaryRedirect 4.13s
 [+] Validates Invoke-RestMethod preserves the authorization header on multiple redirects: RedirectKeepVerb 4.12s
 [+] Validates Invoke-RestMethod strips the authorization header on various redirects: MultipleChoices 2.11s
 [+] Validates Invoke-RestMethod strips the authorization header on various redirects: Ambiguous 2.12s
```

Have you any thoughts?

**Comment by markekraus** [comment]
I speculate they are slow because they run in a Job thread.

**Comment by iSazonov** [comment]
Should we use runspaces?

**Comment by bergmeister** [comment]
Or maybe [PoshRSJob ](https://github.com/proxb/PoshRSJob) that is optimised for this scenario and brings much better performance?

**Comment by markekraus** [comment]
hmm interesting.. It appears that .NET Core is really slow to redirect with both HttpClient and WebResponse.

I see some marginal improvements running the WebListener in different ways.. but not much. What I really see is a HUGE difference in execution times with the raw .NET APIs between 5.1 and 6.0.1:

```powershell
$uri = 'http://localhost:8083/Redirect/3?Type=MovedPermanently'
Measure-Command {
    $WebRequest = [System.Net.WebRequest]::Create($uri)
    $Response = $WebRequest.GetResponse()
    $ResponseStream = $Response.GetResponseStream()
    $StreamReader = [System.IO.StreamReader]::new($ResponseStream)
    $conetnt = $StreamReader.ReadToEnd()
    $content
    $StreamReader.Close()
    $ResponseStream.Close()
    $Response.Close()
}

Measure-Command {
    $HttpClientHandler = [System.Net.Http.HttpClientHandler]::new()
    $HttpClient = [System.Net.Http.HttpClient]::New($HttpClientHandler)
    $Result = $HttpClient.GetAsync($uri).GetAwaiter().GetResult()
    $Content = $Result.Content.ReadAsStringAsync().GetAwaiter().GetResult()
    $Result.Dispose()
    $HttpClient.Dispose()
    $HttpClientHandler.Dispose()
}
```

from 5.1:

```none
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 2
Ticks             : 23220
TotalDays         : 2.6875E-08
TotalHours        : 6.45E-07
TotalMinutes      : 3.87E-05
TotalSeconds      : 0.002322
TotalMilliseconds : 2.322

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 0
Milliseconds      : 3
Ticks             : 31039
TotalDays         : 3.59247685185185E-08
TotalHours        : 8.62194444444444E-07
TotalMinutes      : 5.17316666666667E-05
TotalSeconds      : 0.0031039
TotalMilliseconds : 3.1039
```

From 6.0.1:

```none
Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 4
Milliseconds      : 20
Ticks             : 40206624
TotalDays         : 4.65354444444444E-05
TotalHours        : 0.00111685066666667
TotalMinutes      : 0.06701104
TotalSeconds      : 4.0206624
TotalMilliseconds : 4020.6624

Days              : 0
Hours             : 0
Minutes           : 0
Seconds           : 4
Milliseconds      : 21
Ticks             : 40217051
TotalDays         : 4.65475127314815E-05
TotalHours        : 0.00111714030555556
TotalMinutes      : 0.0670284183333333
TotalSeconds      : 4.0217051
TotalMilliseconds : 4021.7051
````

That's against the same WebListener (running in a separate console from where I'm testing 6.0.1). What takes 5.1 a few milliseconds takes 6.0.1 several seconds.... I get a similar difference in execution times for other (non-WebListener) redirection endpoints.

I'm now suspecting the issue lies in .NET Core... hooray... 🎉 ☹️ 

In any case.. 4 .x seconds on my pc would definitely go past 5 seconds in CI.

Should we move to runspaces? I vote no. We saw some really strange behavior with HttpListener running in a runspace on macOS. I'm not even close to considering it for WebListener. My quick tests how only marginal perf gain on my local PC.

I really don't have time to submit to this project and constantly open issues with CoreFX.

**Comment by iSazonov** [comment]
> Should we move to runspaces? I vote no.

I agree - we don't get any benefits if the problem in CoreFX.

>I really don't have time to submit to this project AND constantly open issues with CoreFX. 

We are totally dependent on CoreFX. So we're doomed to open cases there again and again. I'll open the case for the problem.

>I stand by my original idea to remove the timeouts as they are no longer needed.

Given that they helped us now I would not removed them, but just increased to 10 sec. Who knows maybe they'll still help us catch other problems. It is also possible that we will be forced to use other external servers for some tests in the future. In any case I would prefer a steered failure and not silent CI hang.

**Comment by daxian-dbw** [comment]
The caches in appveyor.yml and travis.yml need to be flushed because the `dotnet` folder is also part of the cache. I will submit a commit to address that.

**Review by daxian-dbw — APPROVED** [review]

**Comment by daxian-dbw** [comment]
The xUnit tests are hardcoded to target dotnet core 2.0.0, but the dotnet sdk 2.1.4 doesn't ship with 2.0.0 rutnime anymore, so it failed. Update the xUnit tests to use 2.0.5 runtime.

**Comment by iSazonov** [comment]
@daxian-dbw Many thanks for help and merge!

**Pull request merged**
