### PR TITLE
Add -OnlyMatching switch param to Select-String cmdlet

### PR DESCRIPTION
**Pull request by ovidiufelixb**
# PR Summary

The OnlyMatching switch is similar to Raw, in that the cmdlet outputs string objects instead of MatchInfo, but instead of returning the whole matched line, it only returns the actual matched values.
It is equivalent to grep -o.

## PR Context

Implements request from #7712.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [X] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by vexx32** [comment]
@ovidiufelixb Thank you for your contribution!

It looks like we already have a PR open for this specific feature (#10696). Might I suggest you look at one of the other issues marked as `Up For Grabs`? 😊 

https://github.com/PowerShell/PowerShell/issues/8106
https://github.com/PowerShell/PowerShell/issues/7768
https://github.com/PowerShell/PowerShell/issues/7640
https://github.com/PowerShell/PowerShell/issues/5331

(There are many others, these are just some brief suggestions that I think shouldn't be _too_ complicated on the whole, and most of these indicate in the issue threads where to look at for solutions already.)

If you find an issue you'd like to tackle, but aren't sure where to start -- just ask in the issue thread! We're happy to point you in the right direction and help you find any resources you need! 💖

**Comment by ovidiufelixb** [comment]
@vexx32 Sorry, this was actually my first pull request on GitHub and I thought that since #7712 is tagged `Up-For-Grabs`, it is still accepting PRs. I also didn't notice the PR that was already submitted.

So, for future reference: should I tackle only issues that are tagged `Up-For-Grabs` AND that do not have any submitted PRs? Is there anything else that I should maybe take into account?

And finally, in regards to the current PR, should I close it personally?

**Comment by vexx32** [comment]
You're totally fine! 

Perhaps we as the maintainers could try to keep slightly closer tabs on Up-for-Grabs issues and remove the label when someone submits a PR, but I'd have to convene with the others and see what they think. It is a bit of additional overhead, but we may want to be doing that during Hacktoberfest where it's more a possibility that we'll get collisions like this.

In general, it's probably best to comment on the issue and ask -- just in case. 🙂 Usually those PRs will reference the issue and become visible in the issue thread itself. In most cases, authors will comment in the issues themselves and ask if they can take care of it / mention that they're working on it so that folks know. But we're all human, and things can be overlooked! So it doesn't hurt to check, even if you don't see such a comment / PR reference. 

There's a good handful of us keeping a watchful eye, so in most cases we'll jump in with an answer within a day or two at most. I can close this one for now, no worries. 😊

**Comment by ovidiufelixb** [comment]
Alright. Thanks for your help! 🙂

**Pull request closed without merging**
