### PR TITLE
Update Changelog

### PR DESCRIPTION
**Pull request by jshigetomi**
# PR Summary

This pull request updates the `CHANGELOG/preview.md` file to include the changes for the 7.6.0-preview.1 release. The most important changes include breaking changes, general cmdlet updates and fixes, code cleanup, tools, tests, build and packaging improvements, and documentation updates.

Breaking Changes:
* Treat large Enum values as numbers in `ConvertTo-Json` (#20999) (Thanks @jborean93!)

General Cmdlet Updates and Fixes:
* Add error for Get-PSSession -ComputerName on Unix (#21009) (Thanks @jborean93!)
* Resolve symbolic link target relative to the symbolic link instead of the working directory (#15235) (#20943) (Thanks @MatejKafka!)
* Support PSObject wrapped values in ArgumentToEncodingTransformationAttribute (#24555) (Thanks @jborean93!)

Code Cleanup:
* Fix typos in `ShowModuleControl.xaml.cs` (#24248) (Thanks @eltociear!)
* Fix a typo in the build doc (#24172) (Thanks @JayBazuzi!)

Build and Packaging Improvements:
* Deploy Box Update (#24632)

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
  - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
  - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
  - [x] None
  - **OR**
  - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.5/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
    - [ ] Experimental feature name(s): 
- **User-facing changes**
  - [x] Not Applicable
  - **OR**
  - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
  - [x] N/A or can only be tested interactively
  - **OR**
  - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
  - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
  - **OR**
  - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
    - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
      - [ ] Issue filed: 
    - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
      - [ ] Issue filed: 
    - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
      - [ ] Issue filed: 
    - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
      - [ ] Issue filed:

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@jshigetomi The change log PR usually is opened targeting the release branch in Azure DevOps, not in GitHub. Has this changed recently?

**Comment by jshigetomi** [comment]
@TravisEz13 should I target mscodehub instead?

**Comment by jshigetomi** [comment]
> @jshigetomi The change log PR usually is opened targeting the release branch in Azure DevOps, not in GitHub. Has this changed recently?

When I tag a commit for the release, I should tag this merged commit for the CL on upstream, correct?

**Comment by daxian-dbw** [comment]
> When I tag a commit for the release, I should tag this merged commit for the CL on upstream, correct?

No, you just tag the head of the release branch in Azure DevOps. As the last step of a preview release, we need to merge the release branch to GitHub master branch with a merge commit. I can help with that.

**Comment by jshigetomi** [comment]
> > When I tag a commit for the release, I should tag this merged commit for the CL on upstream, correct?
> 
> No, you just tag the head of the release branch in Azure DevOps. As the last step of a preview release, we need to merge the release branch to GitHub master branch with a merge commit. I can help with that.

I s

**Pull request closed without merging**
