### PR TITLE
Add wildcard back to end of tab completion command lookup

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
# PR Summary

Re-add wildcard when searching AST + Missed test case.

## PR Context

In #8109, we removed the line that added a wildcard to the end of the command that was used to match commands in the script AST. This readds that line closer to where it is used.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
@PoshChan please get failures

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 4 failures in `PowerShell-CI-linux`
Error occurred in test script '/home/vsts/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1'
```powershell
At /home/vsts/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1:488 char:104
+ ... t-ScrumData {}; Get-Scrum'; expected = 'Get-ScrumData'; setup $null }
+                                                                  ~
Missing '=' operator after key in hash literal.
at <ScriptBlock>, /home/vsts/work/1/a/bins/publish/Modules/Pester/4.4.4/Pester.psm1: line 847
```
Error occurred in test script '/home/vsts/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1'
```powershell
At /home/vsts/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1:488 char:104
+ ... t-ScrumData {}; Get-Scrum'; expected = 'Get-ScrumData'; setup $null }
+                                                                  ~
Missing '=' operator after key in hash literal.
at <ScriptBlock>, /home/vsts/work/1/a/bins/publish/Modules/Pester/4.4.4/Pester.psm1: line 847
```
Error occurred in test script '/home/vsts/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1'
```powershell
At /home/vsts/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1:488 char:104
+ ... t-ScrumData {}; Get-Scrum'; expected = 'Get-ScrumData'; setup $null }
+                                                                  ~
Missing '=' operator after key in hash literal.
at <ScriptBlock>, /home/vsts/work/1/a/bins/publish/Modules/Pester/4.4.4/Pester.psm1: line 847
```
Error occurred in test script '/home/vsts/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1'
```powershell
At /home/vsts/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1:488 char:104
+ ... t-ScrumData {}; Get-Scrum'; expected = 'Get-ScrumData'; setup $null }
+                                                                  ~
Missing '=' operator after key in hash literal.
at <ScriptBlock>, /home/vsts/work/1/a/bins/publish/Modules/Pester/4.4.4/Pester.psm1: line 847
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 4 failures in `PowerShell-CI-macos`
Error occurred in test script '/Users/vsts/agent/2.149.2/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1'
```powershell
At /Users/vsts/agent/2.149.2/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1:488 char:104
+ ... t-ScrumData {}; Get-Scrum'; expected = 'Get-ScrumData'; setup $null }
+                                                                  ~
Missing '=' operator after key in hash literal.
at <ScriptBlock>, /Users/vsts/agent/2.149.2/work/1/a/bins/publish/Modules/Pester/4.4.4/Pester.psm1: line 847
```
Error occurred in test script '/Users/vsts/agent/2.149.2/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1'
```powershell
At /Users/vsts/agent/2.149.2/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1:488 char:104
+ ... t-ScrumData {}; Get-Scrum'; expected = 'Get-ScrumData'; setup $null }
+                                                                  ~
Missing '=' operator after key in hash literal.
at <ScriptBlock>, /Users/vsts/agent/2.149.2/work/1/a/bins/publish/Modules/Pester/4.4.4/Pester.psm1: line 847
```
Error occurred in test script '/Users/vsts/agent/2.149.2/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1'
```powershell
At /Users/vsts/agent/2.149.2/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1:488 char:104
+ ... t-ScrumData {}; Get-Scrum'; expected = 'Get-ScrumData'; setup $null }
+                                                                  ~
Missing '=' operator after key in hash literal.
at <ScriptBlock>, /Users/vsts/agent/2.149.2/work/1/a/bins/publish/Modules/Pester/4.4.4/Pester.psm1: line 847
```
Error occurred in test script '/Users/vsts/agent/2.149.2/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1'
```powershell
At /Users/vsts/agent/2.149.2/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1:488 char:104
+ ... t-ScrumData {}; Get-Scrum'; expected = 'Get-ScrumData'; setup $null }
+                                                                  ~
Missing '=' operator after key in hash literal.
at <ScriptBlock>, /Users/vsts/agent/2.149.2/work/1/a/bins/publish/Modules/Pester/4.4.4/Pester.psm1: line 847
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, test results were not published for PowerShell-CI-static-analysis at vstfs:///Build/Build/20687

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 4 failures in `PowerShell-CI-windows`
Error occurred in test script 'D:\a\1\s\test\powershell\Host\TabCompletion\TabCompletion.Tests.ps1'
```powershell
At D:\a\1\s\test\powershell\Host\TabCompletion\TabCompletion.Tests.ps1:488 char:104
+ ... t-ScrumData {}; Get-Scrum'; expected = 'Get-ScrumData'; setup $null }
+                                                                  ~
Missing '=' operator after key in hash literal.
at <ScriptBlock>, D:\a\1\s\src\powershell-win-core\bin\Release\netcoreapp2.1\win7-x64\publish\Modules\Pester\4.4.4\Pester.psm1: line 847
```
Error occurred in test script 'D:\a\1\s\test\powershell\Host\TabCompletion\TabCompletion.Tests.ps1'
```powershell
At D:\a\1\s\test\powershell\Host\TabCompletion\TabCompletion.Tests.ps1:488 char:104
+ ... t-ScrumData {}; Get-Scrum'; expected = 'Get-ScrumData'; setup $null }
+                                                                  ~
Missing '=' operator after key in hash literal.
at <ScriptBlock>, D:\a\1\s\src\powershell-win-core\bin\Release\netcoreapp2.1\win7-x64\publish\Modules\Pester\4.4.4\Pester.psm1: line 847
```
Error occurred in test script 'D:\a\1\s\test\powershell\Host\TabCompletion\TabCompletion.Tests.ps1'
```powershell
At D:\a\1\s\test\powershell\Host\TabCompletion\TabCompletion.Tests.ps1:488 char:104
+ ... t-ScrumData {}; Get-Scrum'; expected = 'Get-ScrumData'; setup $null }
+                                                                  ~
Missing '=' operator after key in hash literal.
at <ScriptBlock>, D:\a\1\s\src\powershell-win-core\bin\Release\netcoreapp2.1\win7-x64\publish\Modules\Pester\4.4.4\Pester.psm1: line 847
```
Error occurred in test script 'D:\a\1\s\test\powershell\Host\TabCompletion\TabCompletion.Tests.ps1'
```powershell
At D:\a\1\s\test\powershell\Host\TabCompletion\TabCompletion.Tests.ps1:488 char:104
+ ... t-ScrumData {}; Get-Scrum'; expected = 'Get-ScrumData'; setup $null }
+                                                                  ~
Missing '=' operator after key in hash literal.
at <ScriptBlock>, D:\a\1\s\src\powershell-win-core\bin\Release\netcoreapp2.1\win7-x64\publish\Modules\Pester\4.4.4\Pester.psm1: line 847
```

**Comment by TylerLeonhardt** [comment]
@PoshChan please get failures

**Comment by PoshChan** [comment]
@TylerLeonhardt, your last commit had 1 failures in `PowerShell-CI-linux`
TabCompletion.Miscellaneous completion tests.Input 'function Get-ScrumData {}; Get-Scrum' should successfully complete
```powershell
Expected the actual value to be greater than 0, but got 0.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1: line 593
593:             $res.CompletionMatches.Count | Should -BeGreaterThan 0
```

**Comment by PoshChan** [comment]
@TylerLeonhardt, your last commit had 1 failures in `PowerShell-CI-macos`
TabCompletion.Miscellaneous completion tests.Input 'function Get-ScrumData {}; Get-Scrum' should successfully complete
```powershell
Expected the actual value to be greater than 0, but got 0.
at <ScriptBlock>, /Users/vsts/agent/2.149.2/work/1/s/test/powershell/Host/TabCompletion/TabCompletion.Tests.ps1: line 593
593:             $res.CompletionMatches.Count | Should -BeGreaterThan 0
```

**Comment by PoshChan** [comment]
@TylerLeonhardt, test results were not published for PowerShell-CI-static-analysis at vstfs:///Build/Build/20699

**Comment by PoshChan** [comment]
@TylerLeonhardt, your last commit had 1 failures in `PowerShell-CI-windows`
TabCompletion.Miscellaneous completion tests.Input 'function Get-ScrumData {}; Get-Scrum' should successfully complete
```powershell
Expected the actual value to be greater than 0, but got 0.
at <ScriptBlock>, D:\a\1\s\test\powershell\Host\TabCompletion\TabCompletion.Tests.ps1: line 593
593:             $res.CompletionMatches.Count | Should -BeGreaterThan 0
```

**Comment by TylerLeonhardt** [comment]
There's the proof

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by SteveL-MSFT** [comment]
@TravisEz13 we should take this for next 6.2 servicing release

**Review by rjmholt — APPROVED** [review]

**Comment by TravisEz13** [comment]
@TylerLeonhardt please review PR name.  PR's that change functionality, should be named by the functionality they change.

**Comment by TylerLeonhardt** [comment]
@TravisEz13 LGTM

**Pull request merged**
