### PR TITLE
Update installpsh amazonlinux for container build

### LINKED ISSUE #7903: Syntax error in installpsh-amazonlinux.sh
Typo come from #6849 .

### LINKED ISSUE #7906: Update installpsh-amazonlinux.sh to run on Amazon Linux 2 container build
Due to missing tar and gzip, installpsh-amazonlinux.sh will not run on the container build of amazonlinux 2.

Steps to reproduce
------------------
Run the script and it fails

Expected behavior
-----------------
Install PowerShell

### PR DESCRIPTION
**Pull request by DarwinJS**
## PR Summary

Fix #7906 - add packages tar and gzip so that install will work on amazon linux 2 container image which has minimal packages
Fix #7903  - change "if" to "fi"

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
@DarwinJS Please rebase to get latest commit and add more information in description.

**Review by TravisEz13 — APPROVED** [review]

**Comment by TravisEz13** [comment]
@DarwinJS  Did you look at the CodeFactor issues?

**Comment by DarwinJS** [comment]
@TravisEz13  - I did look at the issues - seems like a lot of refactoring to cleanup long standing syntax.  I would like to just get this small update worked in without touching that much code if that is ok?

**Comment by TravisEz13** [comment]
@bmanikm  Can you review? Failures are unrelated to @DarwinJS's changes

**Review by bmanikm — APPROVED** [review]

**Comment by TravisEz13** [comment]
I restarted all CI's

**Review by adityapatwardhan — APPROVED** [review]

**Pull request merged**
