### PR TITLE
Add PSUserRoot environment variable to control where the current user PowerShell profile is stored and managed

### PR DESCRIPTION
**Pull request by KirkMunro**
# PR Summary

This PR is Windows-only (for now -- if folks want it cross platform, I'm happy to update it).

It adds support for a PSUserRoot user environment variable. If the environment variable is set when PowerShell is launched, the path it defines will be used as the base path for the current user's PowerShell profile. This allows users to move their PowerShell content out of their OneDrive (see linked issue for details) and into some other location where they want that content stored/managed. The PR affects how `$env:PSModulePath` is initialized, how `$profile.CurrentUserCurrentHost` and `$profile.CurrentUserAllHosts` are initialized, and the location where the config file is read from.

A matching PR will need to be submitted against PowerShellGet so that it works with this environment variable when installing modules to the user profile. I'll do that work soon.

Any tooling that works directly with the current user's PowerShell folder will need to take this environment variable into account.

## PR Context

See issue #8069, and in particular, [this comment about the PowerShell Committee's decision on the matter](https://github.com/PowerShell/PowerShell/issues/8069#issuecomment-504124566).

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [X] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [X] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by Jaykul** [comment]
I'm confused. This doesn't seem in the spirit of what @joeyaiello wrote the committee had decided on the issue:

>  we believe the risk of changing the "user PowerShell folder" across versions/editions of PowerShell and downlevel versions of the OS is too high to take the chance
...
>  it might be worth creating an automatic variable in PowerShell that points to the "user PowerShell folder" across platforms.

I would have expected something more like: 
```PowerShell
$ProfileDir = Split-Path $Profile.CurrentUserAllHosts
```

And I would expect it to work the same way _across platforms_ ... why would a feature like this be Windows only?

Instead, you're going ahead with changes it seems like they ruled out, and making it only work on one OS?

**Comment by iSazonov** [comment]
Since this change was not discussed in original issue, concerns different platforms and affects other products this should be designed as an RFC.

**Comment by KirkMunro** [comment]
> This doesn't seem in the spirit of what @joeyaiello wrote the committee had decided on the issue...

@Jaykul I can't speak for @joeyaiello, but I think you're reading what he said wrong. The PowerShell Team believes the risk of changing the "user PowerShell folder" within PowerShell (7) as a change for everyone to be too high to take the chance. He goes on to suggest an automatic variable in PowerShell that points to the user PowerShell folder across platforms, which puts the responsibility on the individual. If they change it, that's their call.

> I would have expected something more like:
>
> $ProfileDir = Split-Path $Profile.CurrentUserAllHosts

The reason I went with an environment variable instead of a PowerShell automatic variable here is simple: PowerShell profiles and configuration information are both read from the PowerShell user profile folder, so it needs to be set _before_ those files are read so that they can be read from the user's desired location. Environment variables are the logical solution for that, so that's how I went.

> And I would expect it to work the same way across platforms ... why would a feature like this be Windows only?

I have a use case for this on Windows. I don't have a use case for this on macOS or Linux (other than consistency). I'm not opposed to making the environment variable available for both environments so that users can move their profiles on any system. My decision to stick with Windows was twofold:

1. It's what was discussed in the issue.
1. When it comes to getting PRs accepted, it has become very clear that a minimalist approach results in less friction...usually.

That said, if we want this to be supported universally, I will be happy to make that change.

> Since this change was not discussed in original issue, concerns different platforms and affects other products this should be designed as an RFC.

This change absolutely was discussed in the original issue. @joeyaiello just closed the issue afterwards without responding to the additional comments that were added about the environment variable approach, but it seems very clear (to me at least) that an environment variable is the right way to go to avoid a chicken-and-egg problem.

As for affecting other products, I have absolutely zero evidence that this will affect other products. I checked the checkbox because in theory it could affect other products, if they're written to use the hardcoded path. Unlike the 6.2.1 and previous scenario, where there is no option for choosing the user profile path to use in PowerShell, and where there is no static property you can look at on some class to see what is chosen (it's just hardcoded internally), this approach gives an environment variable that toolmakers can work with, if they even need to. But as I said, I have no evidence that they need to, and I don't believe the user profile path to be contractual (if it was, why would it be ok that it is being changed between 5.1 and 6.2.1+).

**Comment by ctmcisco** [comment]
I am seeing an issue where I would like to hard remove the PSModulePath location for my Windows Profile but regenerates after launching a new PowerShell Console. Is this something being worked on in PowerShell 7?

**Comment by KirkMunro** [comment]
@ctmcisco: I would share that comment on PR #10300.

**Comment by joeyaiello** [comment]
My intent in #8069 when describing an automatic variable was not to make it settable. I know that sounds like desirable behavior to some people, but I worry greatly about the complexity of having your profile location moved from one place to another. Quoting myself:

> Additionally, migration logic on upgrades (and/or moving/linking to existing folders) is extremely hard to get right 100%, and we don't want to leave users in a broken state

You brought up the point about PowerShellGet needing to be updated, and I worry further about having that logic work between versions of PowerShell where this proposed variable is respected and is not respected.

Quoting @BrucePay: "when you already have 20 knobs to tweak, adding another knob seems undesirable". 

As a workaround, you can detach your home folder from OneDrive, or you can add symlinks to other areas of your filesystem.

And apologies on the mixed language with regard to consensus. It really wasn't my intent in the original statement to give the go-ahead on implementing something. 

@PowerShell/powershell-committee looked over this today, and I don't think it's a path we want to go down for the aforementioned reasons.

**Pull request closed without merging**
