### PR TITLE
WIP: Add string cmdlets that emulate operator functionality on pipeline

### PR DESCRIPTION
**Pull request by FriedrichWeinmann**
## PR Summary

Adds commands that enable string manipulation on the pipeline. Specifically emulates common string operators, as well as frequently used string methods.

New Commands added:

 - Add-String
 - Format-String
 - Get-SubString
 - Join-String
 - Set-String
 - Split-String

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

See also:
https://github.com/PowerShell/PowerShell/issues/6697

### CODE REVIEW

**Comment by FriedrichWeinmann** [comment]
Still needs a corresponding documentation update, specifically command help for the new commands. Do I just add new platyPS compatible markdown files to the command reference in the documentation repository?

**Comment by iSazonov** [comment]
@FriedrichWeinmann Please follow [our RFC process](https://github.com/PowerShell/PowerShell/blob/fc627a1dba69ad839fcb7fe76b9aa4733e2b371f/.github/CONTRIBUTING.md#making-design-changes) - we should get RFC approved by PowerShell Committee before implementing new cmdlets. The RFC should contains design proposal and alternative considerations.

**Comment by iSazonov** [comment]
@FriedrichWeinmann The PR is good for first-time. Now I don't don't want to waste your time and push review comments before we get approved RFC.

Creating RFC is the same - fork RFC repo, create branch, commit, push PR, get and address feedbacks. Minimum time for waiting feedback is one month.

The RFC should contains:
- motivations (addressed scenarios). We need samples what is current expirience, why it is bad and how we want address this. It will be a good base for tests and documentation.
- design proposal. From my experience we do not need small details.
- alternative considerations. For the proposal it can be operators, third-party modules, .Net Core methods, one cmdlet design and so on. We should understand why the proposal is better - UX, performance, resource consumption and so on.

**Comment by FriedrichWeinmann** [comment]
Heya @iSazonov : RFC filed: https://github.com/PowerShell/PowerShell-RFC/pull/127 :)

Thanks for the preliminary feedback on the PR, I'm assuming it's ok to keep it open marked as WIP in the meantime, allowing people to try things out for the sake of the discussion.

That said, if you could tell me how - or rather where - in the end command help should be contributed, that would be great. I'm sure it's written in one of those guides, but it really is a forest of documentation :(

**Comment by BrucePay** [comment]
@iSazonov  I asked @FriedrichWeinmann to file the issue to gauge interest _before_ expending the effort on writing the RFC. Based on our discussions in Germany, he already had substantially implemented things and so now we have code, tests (and documentation?).  But it does need to be reviewed by the committee before proceeding. As far as the RFC goes, I imagine it should be pretty simple - fill in the section on  motivation and the specification part is the code, tests and the documentation - essentially this PR.  (note: If there was much code or if it was complex, I would expect a more detailed specification but it's not. The parameter specifications are longer than the method bodies) But the rest of the committee members will have to agree with that.

**Comment by iSazonov** [comment]
@BrucePay 
>  As far as the RFC goes

We have already received a community feedback that MSFT makes rules and processes and then violate them itself. I believe @joeyaiello and @SteveL-MSFT remember about it. I see no reasons why we should again violate our obligations to the community.

**Comment by BrucePay** [comment]
@iSazonov I am acutely aware of our issues WRT process. And I didn't say that there shouldn't be an RFC, I'm merely pointing out that, because there is working code, the design portion need not be that detailed. The cmdlet signatures are in the code. The behaviour is in the code. And most specifically the tests, which make the behaviour clear, are there as well.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee appreciates the publishing of the RFC.  This PR should not be merged until the RFC is approved and any accepted feedback is addressed in this PR.  Thanks for the contribution!

**Comment by BrucePay** [comment]
Reopening so we can resume making progress on this (sincere apologies to @FriedrichWeinmann  for the delays). And now that we have experimental features, this could be done as an experimental feature so we can get (broader) feedback on the names and functionality. (And @SteveL-MSFT  Is working on some new commands that will make it easier to discover, enable and manage these features.)

**Pull request closed without merging**
