### PR TITLE
WIP: Add UnixSocket to WebCmdlets

### PR DESCRIPTION
**Pull request by CarloToso**
# PR Summary
Untested and in an early stage, it probably won't work yet.
This PR aims to add `-UnixSocket` support to `Invoke-WebRequest` and `Invoke-RestMehtod`

- Switched from `System.Net.HttpClientHandler` to `System.Net.Http.SocketsHttpHandler` to expose `ConnectCallback` 
- Replaced handler options (couldn't find a replacement for `handler.ClientCertificateOptions = ClientCertificateOption.Manual;`, it might no longer be necessary)
- Added `-UnixSocket` parameter

Syntax: 
`curl --unix-socket /var/run/docker.sock http://v1.40/images/json`
`Invoke-WebRequest -Uri "http://v1.40/images/json/" -UnixSocket "/var/run/docker.sock"`

The tests highlight some problems with the `Certificates` -> when using both `-Certificate` and `-SkipCertificateCheck` on Linux ~~I think we'll have to update the 2 failing tests~~

## PR Context
#12060 and #8314 

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by CarloToso** [comment]
I finally had time to test this PR. It works correctly in WSL1 but I'm not able to connect to WSL1 Unix-Sockets server from Windows (this is not a pwsh problem, I have the same problem with curl).

Cattura

**Comment by CarloToso** [comment]
After the latest change the tests work on Windows and MacOS but still fail on Linux. The error originates from the -Certificate parameter.

**Comment by olljanat** [comment]
Looks to be working with `Invoke-RestMethod` also like I expected. This would be very welcome feature to PowerShell:
image

I don't know what is practice here but I would prefer that you squash those commits to one and rebase this against of master.
Then your probably should add some test case to `/test/powershell/Modules/Microsoft.PowerShell.Utility/WebCmdlets.Tests.ps1`

Also does the `-UnixSocket` switch now appear also to Windows version? Most probably it should not or there should be at least proper error message shown for user on that case.

**Comment by iSazonov** [comment]
> Also does the `-UnixSocket` switch now appear also to Windows version? Most probably it should not or there should be at least proper error message shown for user on that case.

Unix sockets are supported on Windows https://devblogs.microsoft.com/commandline/af_unix-comes-to-windows/

**Comment by CarloToso** [comment]
@olljanat I will add some tests after we figure out the failures on linux tests.

**Comment by olljanat** [comment]
@iSazonov are you aware of some real world application which uses unix sockets and is available for Windows?

**Comment by iSazonov** [comment]
> @iSazonov are you aware of some real world application which uses unix sockets and is available for Windows?

I don't know. I guess main motivation was to open easy way to port Unix applications to Windows and develop new cross-platform applications.

**Comment by olljanat** [comment]
@iSazonov sure I get that but @CarloToso asked above testing in Windows so we need find (or build) some app to be able to do so.

**Comment by CarloToso** [comment]
@iSazonov @olljanat Maybe this could be a good starting point https://stackoverflow.com/questions/64713218/is-there-an-af-unix-support-on-windows-for-windows-wsl-interop-on-net-core

**Comment by iSazonov** [comment]
We don't need to have a real application. We can create simple helper app.

**Comment by CarloToso** [comment]
Replaced by https://github.com/PowerShell/PowerShell/pull/19343

**Pull request closed without merging**
