### PR TITLE
Change progress fg & bg colors to provide better contrast

### PR DESCRIPTION
**Pull request by rkeithhill**
# PR Summary

This improves the fg/bg contrast of the progress colors which improves readability in various color schemes.  The current colors are particularly poor in the One Half Dark color scheme.  The screenshots below show the before (left) and after (right) for both the Campbell (default) color scheme on top and the One Half Dark color scheme on the bottom:

image

## PR Context

This addresses a comment I made on issue #10780, that the progress fg/bg contrast is not great particularly for the One Half Dark color scheme.  FWIW I'm not set on these particular colors. It's just that black on yellow provides good contrast in "most" color schemes whereas yellow on dark cyan does not.

We could consider using RGB colors to "fix" the fg/bg progress colors on hosts that `SupportsVirtualTerminal`.  Using `ConsoleColor` indices is somewhat problematic as you can see above.  That would mean the progress colors might not "fit" the current color scheme but OTOH the progress text would have good contrast for better readability. Also, this represents more code change since the current host colors take only ConsoleColors.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by iSazonov** [comment]
I believe it is a task exclusively for MSFT usability engineers.

**Comment by daxian-dbw** [comment]
This is a UX change. Better let's the committee weigh in.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this, ideally the colors should be configurable, but we would not block this PR to make that happen as that is a bigger work item.  We'll follow up with the Accessibility experts to confirm the colors meet requirements but we are open to a change

**Review by SteveL-MSFT — APPROVED** [review]
Confirmed using the Color Contrast Analyzer tool the proposed colors meet accessibility requirements

**Comment by TylerLeonhardt** [comment]
This made changed to ConsoleHost. Why was the first box checked on affecting tooling?

**Comment by iSazonov** [comment]
> Why was the first box checked on affecting tooling?

After these check boxed was added in PR template I ask how we will do the checks and answer was - manually by owners. So I never set the check boxes. 
Make sense to add you to ConsoleHost file owners? Github will automatically add you in reviewer list.

**Comment by TylerLeonhardt** [comment]
> Make sense to add you to ConsoleHost file owners? Github will automatically add you in reviewer list.

I'm fine with this... but I'll let the maintainers decide.

**Comment by iSazonov** [comment]
@SteveL-MSFT @TravisEz13 Can we add @TylerLeonhardt to the file owner list?

**Pull request merged**
