### PR TITLE
Fix powershell to not crash on converting recursive array to bool

### PR DESCRIPTION
**Pull request by PetSerAl**
Fixing #3207

### CODE REVIEW

**Review by lzybkr — APPROVED** [review]

**Comment by lzybkr** [comment]
Code changes look good - we do need the cla to be signed before it can be merged.

**Comment by daxian-dbw** [comment]
@PetSerAl Thanks for your contribution!
I updated the title to reflect the change. It's recommended to have a meaningful PR title describing what changes you made (see the guideline in [CONTRIBUTING.md](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request-submission)).

**Comment by msftgits** [comment]
Hi, I am closing and re-opening this PR to bump the CLA bot. Sorry for the inconvenience!

**Comment by PetSerAl** [comment]
One possible breaking change came to my mind:
```powershell
$a = ,,$false
$b = ,[PSObject](,$false)
!!$a # $true
!!$b # was $false, now is $true
```
So, this PR make PowerShell behavior more consistent in regard to wrapping array into `[PSObject]`. But, is this change in behavior acceptable, @daxian-dbw.

**Comment by daxian-dbw** [comment]
I think the behavior with the fix reflects the original intention of the code. Here is the comment in `"case 1"` before returning `true`:
> // the first element is an array with more than zero elements
> return true;

And as you said, now the conversion is more consistent:
_Before Fix_
```
$true -eq $a
True
$true -eq $b
False
```
_After Fix_
```
$true -eq $a
True
$true -eq $b
True
```
So I think this behavior change is acceptable. @lzybkr any thoughts?

**Comment by lzybkr** [comment]
It's definitely obscure, I'm not worried about the change.

**Pull request merged**
