### PR TITLE
Guard against null or blank path components when adding to module path

### LINKED ISSUE #19875: PowerShell 7.4.0-preview.4 fails to start on Windows PC when disconnected from domain network
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

1. Installed pwsh 7.4.0-preview-4 on a domain joined PC, but the PC was on an external network provided by a mobile hotspot.
2. Tried to launch pwsh-preview after installing

### Expected behavior

```console
PowerShell launches normally and prompt provided.
```

### Actual behavior

```console
PowerShell fails to start with the following message:

The shell cannot be started. A  failure occurred during initialization:
Object reference not set to an instance of an object.
```

Note that if the PC is on the domain network, the preview release starts normally. It does not start if either a different network connection is used that doesn't have access to the domain network, or the network is turned off all together.

I also tested on pwsh 7.3.2 and it works in either state.

I was not able to inspect the exception in the release version as the shell does not stay running. I built a debug version from my working area (that is between preview.3 and preview.4 in terms of code), and found it asserted on the machine in question with the following error:
```
pathToAdd should not be null according to contract of the function.
```

This is being triggered in `GetModulePath` of `ModuleIntrinsics.cs` when it tries to add a path to the module path, but the value it's trying to add is null. 

I tried checking if each of `personalModulePathToUse`, `sharedModulePath` and `systemModulePathToUse` is null before allowing them to be added, and with that change, the debug version of pwsh starts on the machine in question when in the disconnected state, but I'm not clear on what this code is doing with the path indices after adding them so I'm not confident to provide a PR for this.
```


### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.4.0-preview.4
PSEdition                      Core
GitCommitId                    7.4.0-preview.4
OS                             Microsoft Windows 10.0.19044
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by stevenebutler**
Closes #19875 

When MyDocuments folder is blank (e.g. when network drive containing folder is disconnected, or running under local system account) PowerShell crashes on startup. This PR adds some null/blank path checking to strings before they are added to
the module path.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by JamesWTruher — CHANGES_REQUESTED** [review]
please add some validation for this new behavior

**Comment by stevenebutler** [comment]
> please add some validation for this new behavior

@JamesWTruher - the bug was caused by unexpected return data from this API call in ModuleIntrinsics.cs

```csharp
string myDocumentsPath = Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments);
```

To add tests for this in the build we'd either have to have the ability to run under an account where it returns "" or provide some way to simulate the API returning the empty string (e.g. through a layer of indirection controlled by an environment variable). Is this something you'd like to see, or if you have an alternative approach please let me know.

The easiest way I've found to test the impact of this change manually is to use psexec from SysInternals to launch a System account (elevated) command prompt (which returns "" for the API call above). See issue #19875 comments for some screenshots from that testing.

```pwsh
psexec -i -s cmd.exe
```
Then in the system account elevated command prompt start the pwsh executable and observe:

* pwsh-7.4-preview 4 crashes with null pointer exception when starting
* with this PR it starts successfully

I have also tested it manually in the scenario where a domain joined PC with network located MyDocuments is disconnected from the domain network and confirmed it no longer crashes in that scenario either.

I'm not familiar enough with the build environment to know how such a test could be orchestrated. The only alternative would be to use some interfaces and create some C# unit tests but I haven't seen any unit test projects in the source base so don't know if this would be an acceptable approach here.

**Comment by iSazonov** [comment]
@stevenebutler Easiest way is to use a test hook. See https://github.com/PowerShell/PowerShell/blob/55950725683eb35f2ba5d05cb2483a9a8fd7778d/src/System.Management.Automation/engine/Utils.cs#L1532

**Comment by stevenebutler** [comment]
> @stevenebutler Easiest way is to use a test hook. See
> 
> https://github.com/PowerShell/PowerShell/blob/55950725683eb35f2ba5d05cb2483a9a8fd7778d/src/System.Management.Automation/engine/Utils.cs#L1532
> 
> https://github.com/PowerShell/PowerShell/blob/55950725683eb35f2ba5d05cb2483a9a8fd7778d/test/powershell/Host/HostUtilities.Tests.ps1#L74

The issue is the test hook would have to be configured before powershell starts up to trigger the bug because this crash happens long before you get an interactive shell or can run a script. It happens while PowerShell itself is initializing.

Maybe we can start up PowerShell then tweak the test hook and call into the method that crashes in the module intrinsics code and possibly trigger the same exception afterPowerShell has started. I'll look into that possibility.

**Comment by iSazonov** [comment]
> The issue is the test hook would have to be configured before powershell starts up to trigger the bug because this crash happens long before you get an interactive shell or can run a script. It happens while PowerShell itself is initializing.

We could use specific/hidden env variable like `__SuppressAnsiEscapeSequences` or `__PWSH_LOGIN_CHECKED` for turning on the test hook.

**Comment by stevenebutler** [comment]
It's not necessary to use env vars as the code that was failing can be called directly after startup with the test hook set to fake an empty MyDocuments location.

I've added this test, which failed without the patch.

```pwsh
      try {
            [System.Management.Automation.Internal.InternalTestHooks]::SetTestHook('SetMyDocumentsSpecialFolderToBlank', $true)
            [System.Management.Automation.ModuleIntrinsics]::GetModulePath($null, $null, $null)
        }
        finally {
            [System.Management.Automation.Internal.InternalTestHooks]::SetTestHook('SetMyDocumentsSpecialFolderToBlank', $false)
        }
```

**Review by TravisEz13 — CHANGES_REQUESTED** [review]
blocking for security review

**Review by TravisEz13 — COMMENTED** [review]
I think it's good.

**Review by TravisEz13 — APPROVED** [review]
Reviewed with WG-Security and we don't have any concerns

**Comment by daxian-dbw** [comment]
@JamesWTruher Can you please take another look and update your review? Thanks!

**Review by JamesWTruher — APPROVED** [review]
thanks!

**Pull request merged**
