### PR TITLE
Update to latest package references, runtime framework, and SDK

### PR DESCRIPTION
**Pull request by iSazonov**
## PR Summary

Move to sdk2.1.401, runtime 2.1.3 and update package references.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
CI Appveyor failed with "dotnet : A compatible SDK version for global.json version: [2.1.401] from [C:\projects\powershell\global.json] was not found". I don't know how fix this.

Feel free to add commits.

**Review by TravisEz13 — APPROVED** [review]

**Review by TravisEz13 — CHANGES_REQUESTED** [review]
files.wxs is still out of sync

**Comment by TravisEz13** [comment]
the mac CI was failing due to a version number being in the TMPDIR I was setting.  It looks like VSTS has already fixed this issue, so I removed this workaround.

**Comment by iSazonov** [comment]
@TravisEz13 Thanks for help!
I still see the error in CI Appveyor  "dotnet : A compatible SDK version for global.json version: [2.1.401] from [C:\projects\powershell\global.json] was not found" 
I think it is the reason that file.wxs is not synced.
I don't know how fix CI Appveyor.

**Comment by TravisEz13** [comment]
That isn't what's causing it to fail.  See https://ci.appveyor.com/project/PowerShell/powershell/build/v6.1.0-rc.10858/job/e862tmmuqaww98v0#L1735

**Review by TravisEz13 — APPROVED** [review]

**Comment by iSazonov** [comment]
@TravisEz13 Thanks for help!

**Comment by TravisEz13** [comment]
@iSazonov No problem... I used this to test my new code to generate the wxs file changes.

**Pull request merged**
