### PR TITLE
Don't install based on build-id for RPM

### LINKED ISSUE #18498: Packaging conflict between powershell-7.3.0-1.rh.x86_64 and dotnet-apphost-pack-7.0-7.0.0-1.x86_64 on Fedora/RHEL
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

I am on Fedora 36 using official Microsoft repo.
I've installed dotnet-sdk-7.0 (which installes dotnet-apphost-pack as a dependency), but when I try to upgrade powershell (or install it for the first time), I get transaction check error

```
Error: Transaction test error:
  file /usr/lib/.build-id/3a/e57b4bedbff101146eb11e0260bd44b922bb46 from install of powershell-7.3.0-1.rh.x86_64 conflicts with file from package dotnet-apphost-pack-7.0-7.0.0-1.x86_64
```

Considering this belongs to dotnet runtime, I think this is powershell packaging issue specifically.

### Expected behavior

```console
You can install both dotnet-sdk-7.0 and powershell-7.3.0 at the same time
```

### Actual behavior

```console
Both packages try to install the same file, failing transaction test, so I can either install dotnet 7.0 or powershell 7.3.0
```

### Error details

_No response_

### Environment data

```powershell
Name                           Value
----                           -----
PSVersion                      7.3.0
PSEdition                      Core
GitCommitId                    7.3.0
OS                             Linux 6.0.5-200.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Oct 26 15:55:21 UTC 2022
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by TravisEz13**
# PR Summary

Don't install based on build-id for RPM

## PR Context

Fixes #18498 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by TravisEz13** [comment]
manually confirmed that the packages no longer has the build id files:

Older Package:

```
> rpm -q --list powershell-preview.rpm | sls -Pattern '^/usr/lib/\.'
/usr/lib/.build-id
/usr/lib/.build-id/14
/usr/lib/.build-id/14/3cfe905ff96a6c99d751564c189c05096e03c7
```

New package:
```
> rpm -q --list powershell-preview-7.3.0_preview.9-1.rh.x86_64.rpm | sls -Pattern '^/usr/lib/\.'
```

**Review by adityapatwardhan — APPROVED** [review]

**Comment by TetianaPozniakovaClone** [comment]
@TravisEz13 hello, I'm not really familiar with how it all works but I need this fix and couldn't install this `powershell-preview-7.3.0_preview.9-1.rh.x86_64.rpm` version on fedora since it doesn't seem to be available in the package manager. Is there any timelines on the next release or maybe any advice on how to get this preview installed?

**Comment by TravisEz13** [comment]
We release previews on a monthly cadence.  
There is a bot that will update the PR when it is released into preview.
You can follow the 7.3.1 PR (above your comment) for when it will get into 7.3.

**Pull request merged**
