### PR TITLE
Save man files in /usr/share/man instead of /usr/local/share/man

### LINKED ISSUE #13517: powershell .deb violates Debian Policy 9.1.2 (creation of files in /usr/local/ and ignoring readonly failures there)
## Steps to reproduce

```# wget https://github.com/PowerShell/PowerShell/releases/download/v7.0.3/powershell_7.0.3-1.debian.10_amd64.deb
# dpkg -i powershell_7.0.3-1.debian.10_amd64.deb
(Reading database ... 458603 files and directories currently installed.)
Preparing to unpack powershell_7.0.3-1.debian.10_amd64.deb ...
Unpacking powershell (7.0.3-1.debian.10) ...
dpkg: error processing archive powershell_7.0.3-1.debian.10_amd64.deb (--install):
 error creating directory './usr/local/share/man': Read-only file system
Processing triggers for man-db (2.8.5-2) ...
Errors were encountered while processing:
 powershell_7.0.3-1.debian.10_amd64.deb
```

## Expected behavior

package should install

## Actual behavior

package violates Debian pkg policy regarding /usr/local  (both by creating *files* and failing to exit successfully)

https://www.debian.org/doc/debian-policy/ch-opersys.html#site-specific-programs

> As mandated by the FHS, packages must not place any files in /usr/local, either by putting them in the file system archive to be unpacked by dpkg or by manipulating them in their maintainer scripts.

> Since /usr/local can be mounted read-only from a remote server, /usr/local/*/dir/ directories
> must be created and removed by the postinst and prerm maintainer scripts and not be
> included in the .deb archive. These scripts must not fail if either of these operations fail

Here's the files in the package that aren't allowed to be created and should not fail a READONLY condition on /usr/local:
```# dpkg-deb -c powershell_7.0.3-1.debian.10_amd64.deb  | grep /usr/local
drwxr-xr-x 0/0               0 2020-07-15 13:55 ./usr/local/
drwxr-xr-x 0/0               0 2020-07-15 13:55 ./usr/local/share/
drwxr-xr-x 0/0               0 2020-07-15 13:55 ./usr/local/share/man/
drwxr-xr-x 0/0               0 2020-07-15 13:55 ./usr/local/share/man/man1/
-rw-r--r-- 0/0            1907 2020-07-15 13:55 ./usr/local/share/man/man1/pwsh.1.gz
```

## Environment data

N/A

thanks,
--stephen

### PR DESCRIPTION
**Pull request by rzippo**
# PR Summary

This PR fixes #13517, #16679, #19217, #23835.
The man files should go to `/usr/share/man`,  not ` /usr/local/share/man`.
The latter not only is against packaging policies, it also breaks on OSTree-based systems where the `/usr/local/share` location is not writable during package install.

The fix was tested by building a 7.4.2 package (see [this branch](https://github.com/rzippo/PowerShell/tree/fix-man-location-7.4.2)) and installing it on [Aurora-DX](https://getaurora.dev/). 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by SteveL-MSFT** [comment]
Forcing rerun of CI

**Comment by JamesWTruher** [comment]
@rzippo - I'm concerned about MacOS, wouldn't it be better to make this change for Linux only  (especially since brew installs PowerShell in `/usr/local/Cellar')

**Review by JamesWTruher — CHANGES_REQUESTED** [review]
i think this change should only be for Linux as MacOS brew installs in `/usr/local`

**Comment by andyleejordan** [comment]
I agree with Jim. If our Linux packages are installing everything else to /usr/ not /usr/local, then the same should go for the man page. Which correspondingly means that on macOS where the "package manager" (brew) installs to /usr/local it should remain there...which, sidebar, did we never contribute (or did we attempt and it was refused) a formula to brew? I don't see powershell nor pwsh at https://github.com/Homebrew/homebrew-core/tree/master/Formula/p, and I only found our tap https://github.com/PowerShell/Homebrew-Tap/blob/master/Formula/powershell.rb.

**Comment by rzippo** [comment]
I agree with this change for MacOS given your arguments, but I don't have a MacOS system to test with. 

Judging from the rest of the code, `$Environment.IsMacOS` and `$Environment.IsLinux` can be used to distinguish the two cases and assign the correct path to `$ManFile`, so I added code to do this.
Please check that it works as you expect.

**Review by Jack-GitHub520 — APPROVED** [review]

**Review by JamesWTruher — APPROVED** [review]
this looks better

I would be happier to see some validation for this, but that doesn't block this PR.

**Review by adityapatwardhan — APPROVED** [review]
LGTM

**Comment by adityapatwardhan** [comment]
@rzippo Thank you for your contribution!

**Pull request merged**
