### PR TITLE
Replace StringComparision.CurrentCulture with StringComparision.Ordinal

### PR DESCRIPTION
**Pull request by iSazonov**
## PR Summary

Related #8064 

Replace StringComparision.CurrentCulture with StringComparision.Ordinal.

[Best Practices for Using Strings in .NET](https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings)

Not all code base is fixed. There are not obvious cases.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/powershell/8068)

### CODE REVIEW

**Comment by TravisEz13** [comment]
___
*[src/Microsoft.WSMan.Management/WSManConnections.cs, line 143 at r1](https://reviewable.io/reviews/powershell/powershell/8068#-LP8B5tDCYspltliQJ8G:-LP8B5tDCYspltliQJ8H:bm7hvf3) ([raw file](https://github.com/powershell/powershell/blob/c783f75de97f84819a88d959da1e2585a4553b87/src/Microsoft.WSMan.Management/WSManConnections.cs#L143)):*
> ```Smalltalk
>             {
>                 computername = value;
>                 if ((string.IsNullOrEmpty(computername)) || (computername.Equals(".", StringComparison.OrdinalIgnoreCase)))
> ```

I've seen this in many places, perhaps we should have a central place for this code?

**Review by TravisEz13 — COMMENTED** [review]
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/powershell/powershell/8068)* status: :shipit: complete! all files reviewed

**Comment by TravisEz13** [comment]
We probably should fix this one as well:
https://github.com/PowerShell/PowerShell/blob/2f1863a222cb3a40ab2a2f333fc1cb9569102b01/src/System.Management.Automation/engine/parser/SafeValues.cs#L641

**Comment by iSazonov** [comment]
> Hashtable could be culture sensitive in some cases.

@TravisEz13 In the PR I fixed only obvious cases. There are still about 30 unclear cases left. It would be great if MSFT team reviewed them.

> I've seen this in many places, perhaps we should have a central place for this code?

If we should please open a tracking issue and I'll fix this later.

**Review by TravisEz13 — APPROVED** [review]

**Pull request merged**
