### PR TITLE
Make `Start-Job` throw terminating exception when `-RunAs32` is specified in 64-bit pwsh

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Make `Start-Job` throw terminating exception when `-RunAs32` is specified in 64-bit `pwsh`.
To start a 32-bit `pwsh`, you need to have the 32-bit `pwsh` installed.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/4003
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
@daxian-dbw Can you file the bug for documentation?
Did you test the code change on a 32 bit build? We do not run 32 bit in CI.

**Comment by daxian-dbw** [comment]
> Did you test the code change on a 32 bit build? We do not run 32 bit in CI.

Yes, I tested manually on a 32 bit build.

> Can you file the bug for documentation?

Yes, will do now.

**Comment by adityapatwardhan** [comment]
Updated the PR template with the link to the doc issue.

**Review by adityapatwardhan — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
@PoshChan remind me in 65 hours

**Comment by PoshChan** [comment]
@adityapatwardhan, I do not understand: remind me in 65 hours

**Comment by adityapatwardhan** [comment]
@PoshChan Please remind me in 65 hours

**Comment by PoshChan** [comment]
@adityapatwardhan, will remind you in 65 hours

**Comment by vexx32** [comment]
Oh my gosh @steveL-msft you made it to expect to be asked _nicely_? 

That's fantastic! :Joy:

**Comment by SteveL-MSFT** [comment]
@vexx32 Of course!

**Comment by PoshChan** [comment]
@adityapatwardhan, this is the reminder you requested 65 hours ago

**Pull request merged**
