### PR TITLE
Update docs and scripts for beta.6 release

### PR DESCRIPTION
**Pull request by daxian-dbw**

### CODE REVIEW

**Comment by SteveL-MSFT** [comment]
Is this change manual or automated?  Would it make sense (for a separate PR) to have the name of the release stored in a single file that is picked up by all these scripts?

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Comment by daxian-dbw** [comment]
This is a manual change. The file `tools/download.sh` probably will be deleted soon as we have moved to `tools/install-powershell.sh`. According to Travis, the file `download.sh` is kept for now just in case. As for the Dockerfiles, I'm not if it's doable to make them read the name from a file, @TravisEz13 could you please weigh in?

**Comment by daxian-dbw** [comment]
I submitted this PR targeting master branch by mistake. I have rebased the `release` branch against `master`.

**Comment by TravisEz13** [comment]
I still have a case where download.sh is needed, but I plan to fix it and then remove it.

**Comment by TravisEz13** [comment]
I take it back... I didn't need the script in the end, but I should still fix the issue.

**Comment by mirichmo** [comment]
Is a .spelling update needed as well?

**Comment by daxian-dbw** [comment]
No need to update spelling. The Travis CI passed (see CI run details by clicking `'View details'`).

**Pull request merged**
