### PR TITLE
Add `Aliases` to the properties shown up for a parameter in `Get-Help`

### LINKED ISSUE #20787: `Get-Help`: parameter aliases are (again) missing from local help display with `-Full` and `-Parameter`
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

Judging by https://github.com/MicrosoftDocs/PowerShell-Docs/issues/1638#issuecomment-366519989, this was fixed at least at some point in PS Core, but the problem is back.

Only the _online_ versions of the cmdlet help topics list parameter aliases such as `-lp` and `-PSPath` for `-LiteralPath`.

```powershell
# With -Full
Get-Help Get-ChildItem -Full | Out-String -Stream | Select-String '^\s+-LiteralPath' -context 0, 9

# Parameter-individual
Get-Help Get-ChildItem -Parameter LiteralPath
```

### Expected behavior

```console
>     -LiteralPath <System.String[]>
          Specifies a path to one or more locations. The value of LiteralPath is used exactly as it's typed. No characters are interpreted as wildcards. If the path includes escape characters, enclose it in single quotation marks. Single quotation marks tell PowerShell to not interpret any characters as escape sequences.
          
          For more information, see about_Quoting_Rules (../Microsoft.Powershell.Core/About/about_Quoting_Rules.md).
          
          Required?                    true
          Position?                    named
          Default value                None
          Accept pipeline input?       True (ByPropertyName)
          Aliases                      PSPath, LP



-LiteralPath <System.String[]>
    Specifies a path to one or more locations. The value of LiteralPath is used exactly as it's typed. No characters are interpreted as wildcards. If the path includes escape characters, enclose it in single quotation marks. Single quotation marks tell PowerShell to not interpret any characters as escape sequences.
    
    For more information, see about_Quoting_Rules (../Microsoft.Powershell.Core/About/about_Quoting_Rules.md).
    
    Required?                    true
    Position?                    named
    Default value                None
    Accept pipeline input?       True (ByPropertyName)
    Accept wildcard characters?  false
    Aliases                      PSPath, LP
```

### Actual behavior

The `Aliases` line is missing in both cases.

### Error details

_No response_

### Environment data

```powershell
PowerShell 7.4.0
```

### Visuals

_No response_

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #20787

Add `Aliases` to the properties shown up for a parameter in `Get-Help`

**Before the fix:**
image

**After the fix:**
image

## PR Context

See https://github.com/PowerShell/PowerShell/issues/20787#issuecomment-1876157917 for details.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Comment by adityapatwardhan** [comment]
@daxian-dbw Can you add a test for that?

**Review by adityapatwardhan — CHANGES_REQUESTED** [review]
Please add test

**Review by sdwheeler — APPROVED** [review]
LGTM

**Comment by daxian-dbw** [comment]
@adityapatwardhan A test was added. Please take another look when you have time.

**Review by adityapatwardhan — APPROVED** [review]

**Pull request merged**
