### PR TITLE
Remove SupportsShouldProcess from Start-PSBootstrap in build.psm1 (closes #15490)

### LINKED ISSUE #15490: `build.psm1`’s `Start-PSBootstrap` ostensibly supports `ShouldProcess`; doesn’t actually support it
## Steps to reproduce (potentially destructive)

```powershell
git clone https://github.com/PowerShell/PowerShell.git
Set-Location ./PowerShell
Import-Module ./build.psm1
Start-PSBootstrap -WhatIf
```

## Expected behavior

Either of:

- Invocation fails due to unsupported parameter `WhatIf`
- Process is simulated

## Actual behavior

Process proceeds normally

## Environment data

```none
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.11.0-7614-generic #15~1618626693~20.10~ecb25cd-Ubuntu SMP Thu Apr 22 16:00:45 UTC 
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by schuelermine**
# PR Summary

Removes `SupportsShouldProcess` from `Start-PSBootstrap` in `build.psm1`.  
This addresses #15490.

## PR Context

`build.psm1` contains the function `Start-PSBoostrap`. The `CmdletBinding` in it stated that it supports `ShouldProcess`, but this isn’t the case.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by schuelermine** [comment]
I don’t think implementing `ShouldProcess` on this function is doable, as it downloads and executes an external script via `Install-Dotnet`.

**Comment by vexx32** [comment]
@schuelermine This function could simply gate the running of that script behind a ShouldProcess check itself, no?

**Comment by schuelermine** [comment]
True, should I re-add `SupportShouldProcess` and only launch the script then?

**Comment by vexx32** [comment]
Might be worth doing, yeah. Not sure if this function handles other things that would warrant a similar check for those parts as well?

**Comment by schuelermine** [comment]
ok, I will write that when I'm back home (3hrs from now)

**Review by anmenaga — APPROVED** [review]

**Review by daxian-dbw — APPROVED** [review]

**Comment by schuelermine** [comment]
@vexx32 While I am in support of this PR being merged, I have also opened another one w/ an attempt at implementing ShouldProcess. An alternate option, if you will.

**Comment by rjmholt** [comment]
@schuelermine it looks like all the CIs are failing for this PR and not in the master branch, and I can't merge it until CI passes. I took a brief look and it's not entirely clear what's going on, but it does look possibly related to your change (`Start-PSBootstrap` isn't properly bootstrapping .NET 6)

**Comment by schuelermine** [comment]
I don’t think the failing is caused by me—here’s a copy of my reasoning from the commit message:
>I’m not sure why the build would fail — I hadn’t changed anything besides removing the CmdletBindingAttribute parameters…
I’ve checked if build.psm1 or ci.psm1 (which is where the errors semm to be happening) ever mention “WhatIf” or “ShouldProcess” — they don’t.

> ci.psm1’s Invoke-CIBuild seems to be failing because Get-PSOptions (imported from build.psm1) returns $null.
However, this is because of a global variable set at the top of the script, which was there before my changes occurred.

**Review by rkeithhill — APPROVED** [review]
LGTM

**Comment by rkeithhill** [comment]
OK this bothers me - why does the Bootstrap step show passed when it clearly failed.  I just spent weeks fixing a similar issue with the Jenkins durable-task-plugin.  🤦‍♂️

image

Looks like someone will need to update the Action to tweak that `-Confirm:$false` parameter. Then again, the latest update to this PR put back the `ConfirmImpact="High"`.  Maybe there's an interaction between `SupportsShouldProcess` and `ConfirmImpact`?

**Comment by rkeithhill** [comment]
Well this would `splain it:

image

This would be a better impl:

image

Not only does the current impl not fail on missing parameters, it will not fail on a missing command or invalid parameter values:

image

This is **the exact same** set of issues I went through with the `pwsh` step in the Jenkins plugin.  Deja vu!

**Comment by schuelermine** [comment]
I can't look through the code right now, I'm not at my computer right now - but it seems like some function might've called Start-PSBootstrap w/ `-WhatIf:$WhatIfPreference` or something, and then the rest of the code mishandled its failed execution.

**Comment by schuelermine** [comment]
OK, yeah, that's definitely the case - Start-CIInstall has this line:
```powershell
Start-PSBootstrap -Confirm:$false
```

(can't remove it now, will do soon*ish*)

**Comment by schuelermine** [comment]
Oh, I just read that you found that, too. Sorry for making that duplicate observation.

**Comment by schuelermine** [comment]
I think removing ConfirmImpact in build.psm1 and adding a $ConfirmPreference declaration to ci.psm1 is a good solution - gonna do that when I'm home.

**Comment by schuelermine** [comment]
Actually, $ConfirmPreference probably isn't even necessary, since Start-PSBootstrap never calls ShouldProcess or ShouldContinue.  
It might've even been because of the incorrect SupportsShouldProcess declaration that the Confirm:$false parameter was added

**Comment by schuelermine** [comment]
Weird
Screenshot from 2021-06-10 14-14-14

**Comment by rkeithhill** [comment]
Intermittent PSGallery glitch?

**Comment by iSazonov** [comment]
> Intermittent PSGallery glitch?

Yes, I restarted CI 5 minutes later and it passed.

**Pull request merged**
