### PR TITLE
Specify api_surface property for all code quality rules

### PR DESCRIPTION
**Pull request by xtqqczze**
https://github.com/dotnet/roslyn-analyzers/blob/main/docs/Analyzer%20Configuration.md#analyzed-api-surface

### CODE REVIEW

**Comment by iSazonov** [comment]
Why do we need this? The default is already `public`.

**Comment by xtqqczze** [comment]
> Why do we need this? The default is already `public`.

It makes the configuration explicit.

For [CA1801](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1801) and [CA2208](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2208) the default `api_surface` is `all`.

**Comment by iSazonov** [comment]
> For [CA1801](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1801) and [CA2208](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2208) the default `api_surface` is `all`.

All the more reason not to change the default value

**Comment by xtqqczze** [comment]
> > For [CA1801](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca1801) and [CA2208](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2208) the default `api_surface` is `all`.
> 
> All the more reason not to change the default value

This PR doesn't change the default value for any analyzer.

**Review by iSazonov — APPROVED** [review]

**Pull request merged**
