### PR TITLE
Fix whitespace issues

### PR DESCRIPTION
**Pull request by xtqqczze**
Fix some whitespace issues using `dotnet-format`

### CODE REVIEW

**Comment by xtqqczze** [comment]
@iSazonov Please could you merge.

**Comment by xtqqczze** [comment]
Test failures due to HTTP error 503 (Service Unavailable) in package restore. Since these are trivial changes, I will not restart tests.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@xtqqczze Please add new commit and replace `[Fact, TestPriority(11)]` with `[Fact]` to pass CI.
https://github.com/iSazonov/PowerShell/blob/54d3ae20c56b845d12414780cfcfcbc4e4684337/test/xUnit/csharp/test_PSConfiguration.cs#L971
(We merged old PR and get the minor regression.)

**Comment by xtqqczze** [comment]
> @xtqqczze Please add new commit and replace `[Fact, TestPriority(11)]` with `[Fact]` to pass CI.
> https://github.com/iSazonov/PowerShell/blob/54d3ae20c56b845d12414780cfcfcbc4e4684337/test/xUnit/csharp/test_PSConfiguration.cs#L971
> (We merged old PR and get the minor regression.)
> 
> >  GitHub**[iSazonov/PowerShell](https://github.com/iSazonov/PowerShell)**PowerShell for every system! Contribute to iSazonov/PowerShell development by creating an account on GitHub.

Yep looks likes a conflict between #13496 and #13872, `TestPriority` is now named `Priority`.

**Comment by xtqqczze** [comment]
> > @xtqqczze Please add new commit and replace `[Fact, TestPriority(11)]` with `[Fact]` to pass CI.
> > https://github.com/iSazonov/PowerShell/blob/54d3ae20c56b845d12414780cfcfcbc4e4684337/test/xUnit/csharp/test_PSConfiguration.cs#L971
> > (We merged old PR and get the minor regression.)
> 
> Yep looks likes a conflict between #13496 and #13872, `TestPriority` is now named `Priority`.

Fix merged in #14094.

**Comment by iSazonov** [comment]
@xtqqczze Please rebase.

**Comment by xtqqczze** [comment]
@iSazonov Pleases merge.

**Pull request merged**
