### PR TITLE
Enable WebRequestPSCmdlet to not validate HTTPS certificates

### PR DESCRIPTION
**Pull request by ffeldhaus**
Added switch parameter SkipCertificateCheck to WebRequestPSCmdlet to enable Invoke-WebRequest and Invoke-RestMethod to not validate the HTTPS certificate of the server if required.

Implemented as discussed in issue #1945

### CODE REVIEW

**Comment by rkeithhill** [comment]
I would suggest a parameter name of either `NoCertificateCheck`  or `SkipCertificateCheck` as that parameter naming is more common than `Ignore...`.  When naming a parameter, I often look at the output of a command like this:
```powershell
(gcm -type Cmdlet).ParameterSets.Parameters | Group Name | Sort Name 
```

**Comment by alexandair** [comment]
I would suggest to use -SkipCertificateCheck to be consistent with similar parameters: -SkipCACheck, -SkipCNCheck, and -SkipRevocationCheck.

**Comment by halr9000** [comment]
+1 to @alexandair. Great PR, @ffeldhaus!

**Comment by ffeldhaus** [comment]
I renamed the parameter to `SkipCertificateCheck` as suggested. I'm in clarification with my employee regarding the contribution license agreement and will sign it as soon as possible.

**Comment by lzybkr** [comment]
Can you add a test to powershell\test\powershell\Modules\Microsoft.PowerShell.Utility\WebCmdlets.Tests.ps1?

**Comment by GavinEke** [comment]
Awesome work @ffeldhaus as for the test would something like the following be sufficient

    It "Invoke-WebRequest validate skipcertificatecheck option" {

        Invoke-WebRequest -Uri 'https://expired.badssl.com' -SkipCertificateCheck | Should Not Throw
    }

or

    It "Invoke-WebRequest validate skipcertificatecheck option" {

        Invoke-WebRequest -Uri 'https://expired.badssl.com' -SkipCertificateCheck  | Select-Object -ExpandProperty StatusCode | Should Be 200
    }

and the equivalent Invoke-RestMethod under the appropriate describe block.

**Comment by TravisEz13** [comment]
@JamesWTruher Can you comment on @GavinEke's test recommendation?  Is it ok for the tests to depend on an internet resource?

**Comment by alanrenouf** [comment]
Any news on this getting accepted? Would fix some issues for us.

**Comment by lzybkr** [comment]
We'd like to see tests added and the CLA signed.
Some other issues:
* The parameter will exist in PowerShell Core and Windows PowerShell, but the implementation is specific to PowerShell Core. This needs to be addressed first, ideally by adding an implementation for Windows PowerShell.
* We may want multiple parameters, e.g `New-PSSessionOption` has `-SkipCACheck`, `-SkipCNCheck`, and `-SkipRevocationCheck`.

**Comment by ffeldhaus** [comment]
@lzybkr I signed the CLA and added a test. I'm not sure if the tests get executed by running Start-PSPester (or travis or appveyor) as I couldn't find them in the console output. Could you please share more details what is required to implement the parameter for Windows PowerShell?

**Comment by lzybkr** [comment]
By default, Start-PSPester runs tests tagged `CI`. The web tests are tagged `Feature` because they are slow and we don't want them running in CI - that's why you're not seeing the test in the output. You can run `Start-PSPester -Tag Feature` to make sure you run your tests.

I can't really provide specific guidance on how you can implement this functionality on Windows PowerShell - but you should read [this](https://github.com/PowerShell/PowerShell/blob/master/docs/building/windows-full.md) to get started.

@Francisco-Gamino ported these commands to PowerShell Core, so he might be able to help with specifics on Windows PowerShell.

**Comment by ffeldhaus** [comment]
Are there any chances this will get merged before the next release? What needs to be done to merge this pull request?

**Comment by lzybkr** [comment]
We haven't closed on whether or not it's acceptable to add this parameter to PowerShell Core but not Windows PowerShell.  It sounds like people want this capability in Windows PowerShell as well, so we'd prefer that, but if not, you'll need to add `#if CORECLR` around the parameter so that Windows PowerShell doesn't have a parameter with no implementation.

I was also hoping to see some discussion around matching the options of `New-PSSessionOption` - those options most likely exist because they map nicely to wsman options - so it might be more of a question on how useful it is to disable all checks versus certain checks.

**Comment by ffeldhaus** [comment]
I would appreciate it, if this would also be included in Windows PowerShell. Especially for connecting to new REST endpoints it's often necessary to skip the certificate checks. I have several Cmdlets which are able to upload a new certificate via REST, but first I need to be able to accept the self-signed certificate.

In my opinion it would be better to first include the `SkipCertificateCheck` parameter before implementing other parameters. The `SkipCertificateCheck` parameter is a generic solution whereas `-SkipCACheck`, etc. are only useful for specific scenarios.

In the end the most important point is, that it's currently not possible to ignore certificates in PowerShell Core as the workaround available in Windows PowerShell (via `[System.Net.ServicePointManager]`) is not working and thus breaking lot's of Cmdlets which need to be run against REST endpoints with e.g. invalid or self signed certificates.

**Comment by Jaykul** [comment]
For what it's worth, I would vote *against* implementing this pull request. It's too simplistic --and _dangerous_-- to just have a switch that *completely disables* validation checking.

The vast majority of the time, the *right* thing to do is to just disable checking the CA chain (because it's just a self-signed cert), and not disable validation completely. The rest of the time, the right thing to do is to white-list the specific certificate and url combination.

Additionally, this not only disables the check on the initial request, it also automatically disables checking on any additional requests (i.e. if you're redirected, or download additional resources), so if you're hitting an internal website that uses a self-signed cert but then downloads additional content from CDNs with valid certs, you're needlessly disabling that validation, etc...

Additionally, you _really_ should solve it the same way on all the web cmdlets, including Export-ODataEndpoint, etc.

I wrote [a wrapper for these things](https://github.com/Jaykul/Tunable-SSL-Validator) a couple of years ago. It's a little complicated. In fact, it probably goes a little too far in the other direction (too many knobs). But there has to be a better solution than all or nothing.

**Comment by halr9000** [comment]
> [regarding curl] For compatibility reasons, it should be implemented in
the same way in PowerShell.

I don't think this is a good argument when balancing against security
concerns. Otherwise--yes, I would agree.

I vote for Joel's points about use the most-right solution. I believe most
people want the *user-facing behavior* of "skip validation":  allowing self
signed certs to be used. The fact that skipping the CA chain will achieve
this end while still performing some security checks means it's a better
workaround (that I would use often, myself).

If we were designing a feature for a layperson, we'd call it
"-AcceptTheDamnCert", and nobody would care how it's implemented. :)

**Comment by lzybkr** [comment]
We decided to take this change as is without requiring the corresponding changes to Windows PowerShell.

**Comment by bgoldman69** [comment]
Any reason why this is merged but not available yet?  I really hate having to break into CYGWIN from POWERSHELL to do things...

**Comment by SteveL-MSFT** [comment]
@bgoldman69 this has been available for sometime in our alpha releases

**Comment by sbourdeaud** [comment]
Has this been pulled from beta releases then? I'm using the latest beta (7) and there is no SkipCertificateCheck for Invoke-RestMethod in that version...

**Comment by ffeldhaus** [comment]
It's working for me with PowerShell Beta 7 on Mac OS X

```powershell
Florians-MBP:~ ffeldhaus$ powershell 
PowerShell v6.0.0-beta.7
Copyright (C) Microsoft Corporation. All rights reserved.

PS /Users/ffeldhaus/development> Invoke-RestMethod -SkipCertificateCheck -Uri https://expired.badssl.com/    
```

**Comment by GavinEke** [comment]
Works for me using Beta 7 on Windows 10 (1703)

**Comment by sbourdeaud** [comment]
I stand corrected. It's just missing from the get-help output and thus I assumed it wasn't there.

**Comment by iSazonov** [comment]
@sbourdeaud You can see latest docs in https://github.com/PowerShell/PowerShell-Docs repo. Feel free open Issue there if the parameter isn't documented.

**Comment by sbourdeaud** [comment]
Done

**Pull request merged**
