### PR TITLE
Replace win7 runtime with win8 and remove APISets

### PR DESCRIPTION
**Pull request by adityapatwardhan**
# PR Summary

Replace the runtime for builds from win7 to win8 as we are not going to support windows 7 anymore.
Remove APISets which are deprecated.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by ALIENQuake** [comment]
@adityapatwardhan Hi,

Does after merging this PR, Windows 7 won't have any PS 7 LTS version?

**Comment by xtqqczze** [comment]
See dotnet/core#7556

**Comment by iSazonov** [comment]
https://github.com/dotnet/core/issues/7556 says about EOL on Windows 8.1 too.

**Comment by xtqqczze** [comment]
> [dotnet/core#7556](https://github.com/dotnet/core/issues/7556) says about EOL on Windows 8.1 too.

I expect we will maintain support for `win81-x86` and `win81-x64` target platforms due to Windows Server 2012/R2 ESU.

https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#windows-rids
https://learn.microsoft.com/en-us/lifecycle/faq/extended-security-updates

**Comment by daxian-dbw** [comment]
@adityapatwardhan Win8.1 support will end on January 10, 2023, same time as the Win7, so shall we directly use `win10` as the RID?

**Comment by xtqqczze** [comment]
> @adityapatwardhan Win8.1 support will end on January 10, 2023, same time as the Win7, so shall we directly use `win10` as the RID?

But Windows Server 2012 R2 uses the same RIDs and is supported through ESU until October 13, 2026.

**Comment by iSazonov** [comment]
> > @adityapatwardhan Win8.1 support will end on January 10, 2023, same time as the Win7, so shall we directly use `win10` as the RID?
> 
> But Windows Server 2012 R2 uses the same RIDs and is supported through ESU until October 13, 2026.

So right question is about ESU supporting _pwsh 6_ on the Win2012/8 :-)

Although it looks very funny - MSFT spent a year making .Net 7 on Windows 7 and just before the release decided that .Net 7 would not work/supported on Windows 7.

**Review by TravisEz13 — APPROVED** [review]

**Comment by xtqqczze** [comment]
> So right question is about ESU supporting _pwsh 6_ on the Win2012/8 :-)

We don't support PowerShell Core 6 on any platform.

As per documentation, long-term-support for PowerShell is based on the .NET support lifecycle.

**Pull request merged**
