### PR TITLE
CI - Adding toolset for Jenkins Docker Slaves

### PR DESCRIPTION
**Pull request by brycem**
The new tools\jenkinsutils.psm1 module contains a CmdLet for setting up windows Jenkins slaves (Get-DockerDeps), a CmdLet for fetching the current build for a given tag (Get-LatestPs), and a CmdLet for building a Windows Docker Container image that executes the Directives in the new tools\Dockerfile to Invoke-Pester after the container launches.  Failed results fail the container build. tools\.gitignore updated to ignore the WorkSpace generated for the Docker build.

### CODE REVIEW

**Comment by andschwa** [comment]
Hey if you're adding Windows Docker containers, they should probably go with the Linux Docker containers in the `docker` folder.

**Comment by brycem** [comment]
I thought about that but didn't because this template was specialized to run the tests on built bits from the release point and doesn't work unless run from the jenkinsutil.psm1.

**Comment by andschwa** [comment]
@brycem can you please work from a fork?

**Comment by brycem** [comment]
Sorry about that.


Von Outlook für Android gesendet






On Tue, Oct 11, 2016 at 1:39 PM -0700, "Andrew Schwartzmeyer" <notifications@github.com> wrote:





@brycem can you please work from a fork?

**Comment by brycem** [comment]
Closing this PR to work on stable windows Dockerfiles instead.

**Pull request closed without merging**
