### PR TITLE
MSI: Make sure that file components are patchable

### PR DESCRIPTION
**Pull request by TravisEz13**
## PR Summary

MSI: Make sure that file components are patchable
    - avoid changing names and guids of components between builds as this prevents patch generation
        - This required submitting the file generated by heat
    - add code to make sure the generated file is not out of date

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
I wonder - is this implement RFC suggestion for root path `C:\Program Files\PowerShell`?

**Comment by TravisEz13** [comment]
@iSazonov Only partially... During the work to make everything patchable.  The need for the changes in the RFC was discovered.  This does not change the actual install location.  This big change here is to fix the GUIDs for all the file components.  This allows the file components to be patched (using an MSP, which is required by Microsoft Update for Security Patches.) 

After we merge most of the MSI PRs I have pending, I'll submit the main implementation for RFC.  I'll mark it as a WIP until the RFC is done.

**Review by daxian-dbw — APPROVED** [review]

**Comment by iSazonov** [comment]
@TravisEz13 Thanks for clarify. I don't understand how it works - it seems the change links component to root PowerShell directory. Main question is should we review rest components? And whether repair works for such components?

**Comment by TravisEz13** [comment]
I already have and submitted two other PRs for all significant issues.  The main other issue is that in a patch only differences are applied to the original MSI.  We need to remove all references to the specific version numbers from the GUI.  Otherwise, when you are applying the 6.0.3 patch to 6.0.2 MSI, the patch will still say 6.0.2.  Perhaps there is a way to use the actual MSI version at runtime.  I'll have a PR for that sometime after this is merged.

**Pull request merged**
