### PR TITLE
Fix DeviceGuard data being returned from Get-ComputerInfo and Start-Process test failure

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
fix Get-ComputerInfo return of status for DeviceGuard
fix corresponding tests
this is causing one of the failures in our nightly run

### CODE REVIEW

**Comment by jeffbi** [comment]
LGTM

**Comment by SteveL-MSFT** [comment]
CI failure is on Start-Process which is affecting nightly runs.  I'm working on that today.

**Comment by SteveL-MSFT** [comment]
@jeffbi can you formally approve?  thanks!

**Review by jeffbi — APPROVED** [review]

**Comment by SteveL-MSFT** [comment]
@TravisEz13 can you review the test change to Start-Process test?

**Review by TravisEz13 — APPROVED** [review]

**Pull request merged**
