### PR TITLE
fix detection of whether `-LiteralPath` was used to suppress wildcardexpansion for navigation cmdlets

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
Fix https://github.com/PowerShell/PowerShell/issues/5031

### CODE REVIEW

**Review by adityapatwardhan — APPROVED** [review]
LGTM

**Comment by adityapatwardhan** [comment]
@SteveL-MSFT The test 'Remove-Item -LiteralPath should succeed for file with asterisk in name' is failing. Please fix.

**Comment by SteveL-MSFT** [comment]
@adityapatwardhan I only ran it on my Mac, I need to skip it on Windows since asterisk isn't allowed in filename

**Comment by adityapatwardhan** [comment]
@SteveL-MSFT  Please add the test as described in the issue #5031. That should work on Windows as well.

**Comment by SteveL-MSFT** [comment]
@adityapatwardhan added more test variations for the wildcard not finding files scenario

**Pull request merged**
