### PR TITLE
Remove dead code from SemanticVersion class

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Remove dead code from SemanticVersion class. It was added pending the development of  semantic version story but we got no feedback and no progress. Currently we are waiting .Net for the story.

The PR speeds up startup scenario on my laptop up to 50 ms.

## PR Context

Related #14268

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@iSazonov `psobj.Properties.Add` adds the member to `s_instanceMembersResurrectionTable`, which allows PowerShell to retrieve the ETS members for the specific object, the `System.Version result` here, when access that object in PowerShell later. Put it another way, `psobj.Properties.Add` makes PowerShell remember that an instance member is added for the particular object `result`.

This code path shouldn't be removed. It's the reason why you see the following from a `System.Verseion` object.
```
PS C:\> $PSVersionTable.PSCompatibleVersions[-1]

Major  Minor  Build  Revision PSSemVerPreReleaseLabel    PSSemVerBuildLabel
-----  -----  -----  -------- -----------------------    ------------------
7      2      0      -1       preview.1
```

**Comment by daxian-dbw** [comment]
Besides, this particular impact won't affect stable versions, because `PSSemVerPreReleaseLabel` and `PSSemVerBuildLabel` are `null` for stable versions. When profiling, I recommand you to build PowerShell with `-ReleaseTag v7.2.0`, so as to mimic a stable version.

**Comment by iSazonov** [comment]
@daxian-dbw Thanks for clarify!
I was sure that we left this code only as "want get a feedback" and till .Net solution comes.
Based on our experience in PowerShell I shared in .Net proposal to enhance `System.Version` type instead of creating new .Net SemanticVersion class. If this will be implemented in any way we will fall in a breaking change so we can close the PR and add more in our documentation about PowerShell SemanticVersion class.

**Comment by iSazonov** [comment]
> When profiling, I recommand you to build PowerShell with `-ReleaseTag v7.2.0`, so as to mimic a stable version.
 
I see your point but:
1. Modern live cycle development model assumes preview versions is stable enough and works as well as release. Users actively use Preview versions. I believe they shouldn't disappoint users and behave as well as releases.
It also allows us to get reliable performance feedback early on, rather than after the final release.
2. In SemanticVersion context `PSSemVerPreReleaseLabel` is null for stable version but `PSSemVerBuildLabel` could be not null - ex.: if we re-packaged we could increase the build label as SemVer standard says.

**Comment by iSazonov** [comment]
Sources https://github.com/microsoft/ApplicationInsights-dotnet :-)

**Pull request closed without merging**
