### PR TITLE
Style: Remove space after new keyword in implicitly typed array allocation

### PR DESCRIPTION
**Pull request by daxian-dbw**
## PR Summary

Remove space after new keyword in implicitly typed array allocation.
654 issues are fixed.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [x] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]
@daxian-dbw Recently Jason noted that it makes sense to merge Types_Ps1Xml.cs and TypesV3_Ps1Xml.cs (perhaps some files from FormatAndOutput\DefaultFormatters too). I looked this but there are difficulties for me. The merging may speed up startup.

**Comment by daxian-dbw** [comment]
@iSazonov What do you mean by merging them? Having a single `.cs` file that contains the type definitions for both? I don't think that along will affect the perf, so there should be more that Jason wanted.
I did looked at the CPU time trace with the IL assemblies when working on the startup perf, and the huge `yield` methods in those 2 files does take an outstanding amount of the CPU time, over 2%. But the data is from IL assemblies and thus I'm not sure if it's really an issue with crossgen'ed assemblies. I couldn't generate PDBs for crossgen'ed assemblies.

I haven't contact .NET Core team on the crossgen related issues/questions. I moved to something with higher priority.

**Comment by iSazonov** [comment]
Yes, single file. Jason simply mentioned that now there is no reason to have different files. Thanks for clarification about perf.

**Comment by daxian-dbw** [comment]
I will get back to those huge `yield` state-machine methods when switching back to the CPU trace analysis work.

**Pull request merged**
