### PR TITLE
Fix `build.psm1` to not specify both version and quality for `dotnet-install`

### PR DESCRIPTION
**Pull request by tamasvajk**
The latest changes in `dotnet-install` enforce that not both of `version` and `quality` are specified. See the changes in https://github.com/dotnet/install-scripts/commits/main/src/dotnet-install.sh. Specifically [this line](https://github.com/dotnet/install-scripts/commit/d9aa25a5b28497a2d512529c71fe160e4ce62e7f#diff-328f65c23ac5e22ef0b28e2cc343f85c360184e84bb3fbfcf01bec19fea43c6eL1193).

I haven't done any major testing in powershell context, just ran the following on MacOS:
- `./dotnet-install.sh -v 7.0.100-preview.2.22153.17 -q signed` fails
- `./dotnet-install.sh -v 7.0.100-preview.2.22153.17` doesn't fail.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by tamasvajk** [comment]
This is the reason why the following actions were failing: https://github.com/PowerShell/PowerShell/actions/workflows/codeql-analysis.yml

**Comment by SteveL-MSFT** [comment]
Based on https://github.com/dotnet/install-scripts/issues/287 it looks like the expectation is that only --version or --quality should be specified and if both it will error.  However, I don't see a similar change in their PowerShell script.

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Comment by SteveL-MSFT** [comment]
The Linux test is failing on a tab completion test.  I think normally I would recommend that being in a separate PR, but this issue w/ dotnet-install.sh and the tabcompletion issue will need to be taken together to unblock CI.

In ./test/powershell/host/TabCompletion/TabCompletion.Tests.ps1 on line 496, it's checking for a specific ordering of completions and that order appears to have changed.   I don't think the test should rely on the ordering.  So instead, I would recommend changing that line to:

```powershell
        $res.CompletionMatches.CompletionText | Should -Contain 'Position'
```

and do that in this PR.

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Comment by adityapatwardhan** [comment]
It seems it was correct for Windows all along: 

https://github.com/PowerShell/PowerShell/blob/735096bcc1344fa3851dfedecb7f6750250fe8f3/build.psm1#L1901-L1907

**Review by adityapatwardhan — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
Manual backport for 7.2.6 done.

**Pull request merged**
