### PR TITLE
PathUtils: handle escaped -Path correctly

### PR DESCRIPTION
**Pull request by kwkam**
Reopen #7405

# PR Summary

Unescape non-literal, non-glob path before calling
GetUnresolvedProviderPathFromPSPath since it only accepts literal path.

## PR Context

This solve the issue where some commands depending on that method
will treat -Path as literal unintentionally. For example,
```pwsh
Out-File -Path './`[out`].txt' -Append
```
will create a new file named ```"`[out`].txt"``` instead of writing to ```"[out].txt"```.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Review by SteveL-MSFT — DISMISSED** [review]
LGTM

**Comment by daxian-dbw** [comment]
I think we need to think about the current behavior again.
Today, the escaped wildcard pattern is respected when it's used for searching an item with wildcard globbing. However, when creating a new item, the path is used as is.
For example:
```
PS> New-Item [out].txt

    Directory: F:\tmp\modules\temp

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         5/13/2019  9:07 AM              0 [out].txt

PS> Get-Item '.\`[out`].txt'

    Directory: F:\tmp\modules\temp

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         5/13/2019  9:07 AM              0 [out].txt

PS> New-Item '.\`[out`].txt'

    Directory: F:\tmp\modules\temp

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         5/13/2019  9:08 AM              0 `[out`].txt
```
`Out-File` actually follows this convention -- when searching for an existing file, the escaping of the wildcard pattern is respected (because it's used as a wildcard pattern).

```
# The provided path is resolved to "[out].txt" when searching for an existing file ("[out].txt" is an existing file)
PS> "abc" | Out-File -Path '.\`[out`].txt' -Append
PS> Get-Content '.\`[out`].txt'
abc
# Remove the existing file
PS>rm *
# When creating a new file, the path is used as is
PS:78> "abc" | Out-File -Path '.\`[out`].txt' -Append
PS:79> dir

    Directory: F:\tmp\modules\temp

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----         5/13/2019  9:17 AM              5 `[out`].txt
```
This does seem to be confusing -- `Out-File` would operate on files with different names depending on whether the file already exists or not ... But I think we need to think about the convention in general (e.g. should `New-Item` be changed too? what about `Set-Content` which only search for an existing file before creating a new file?) so that the behavior is not contradicting between different cmdlets.

**Comment by daxian-dbw** [comment]
FYI, `Set-Content` and `Add-Content` don't work with paths that contains escaped wildcard characters. Issue opened: https://github.com/PowerShell/PowerShell/issues/9588

**Comment by daxian-dbw** [comment]
Reference my comment on the related issue: https://github.com/PowerShell/PowerShell/issues/9475#issuecomment-491911335
I think this is a general issue that should be well thought and fixed in a wider scope.

**Comment by daxian-dbw** [comment]
As is stated in my comments, the wildcard pattern issue is a general issue that should be well thought and fixed in a wider scope. So I will close this PR.

**Pull request closed without merging**
