### PR TITLE
Enable completion of variables across scriptblock scopes

### PR DESCRIPTION
**Pull request by MartinGC94**
# PR Summary
Enables completion of variables assigned in other scriptblocks like:
`ls | foreach -Begin {$MyVar = "Hello"} -Process {$MyV<Tab>}`
Scriptblocks that are executed as commands with ampersand are explicitly excluded because variables assigned in those are not available outside the scope.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by daxian-dbw** [comment]
The change enables completion on some commands that are not appliable to the assumption, such as `Invoke-Command`, `New-Module`, and `Register-ArgumentCompleter`.

Quick search in a default session shows the following cmdlets that have parameter with the type `ScriptBlock`, some of them do not run the script block in the calling scope. So, it's better to restrict when this completion should be enabled.
```
PS:1> gcm -ParameterType ([scriptblock])

CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Cmdlet          ForEach-Object                                     7.2.11.500 Microsoft.PowerShell.Core
Cmdlet          Invoke-Command                                     7.2.11.500 Microsoft.PowerShell.Core
Cmdlet          Measure-Command                                    7.0.0.0    Microsoft.PowerShell.Utility
Cmdlet          New-Module                                         7.2.11.500 Microsoft.PowerShell.Core
Cmdlet          Register-ArgumentCompleter                         7.2.11.500 Microsoft.PowerShell.Core
Cmdlet          Register-EngineEvent                               7.0.0.0    Microsoft.PowerShell.Utility
Cmdlet          Register-ObjectEvent                               7.0.0.0    Microsoft.PowerShell.Utility
Cmdlet          Set-PSBreakpoint                                   7.0.0.0    Microsoft.PowerShell.Utility
Cmdlet          Set-PSReadLineKeyHandler                           2.3.1      PSReadLine
Cmdlet          Set-PSReadLineOption                               2.3.1      PSReadLine
Cmdlet          Start-Job                                          7.2.11.500 Microsoft.PowerShell.Core
Cmdlet          Trace-Command                                      7.0.0.0    Microsoft.PowerShell.Utility
Cmdlet          Where-Object                                       7.2.11.500 Microsoft.PowerShell.Core
```

**Comment by MartinGC94** [comment]
@daxian-dbw Good point. I've changed it to only work for dot sourced scriptblocks, and arguments to Foreach/Where-Object. What prompted this change was me writing a pester test and being annoyed that a var in BeforeAll was not completable. Can I add third party commands like "BeforeAll" and "BeforeEach" to the whitelist?

**Comment by daxian-dbw** [comment]
> Can I add third party commands like "BeforeAll" and "BeforeEach" to the whitelist?

Sure, I think they should be in the whitelist. You are really solving a pain point here 👍

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Pull request merged**
