### PR TITLE
Use `Needs-Triage` instead of `Issue-Question` for new issues

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Use `Needs-Triage` instead of `Issue-Question` for new issues.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by iSazonov** [comment]
I suggest to set both Needs-Triage and Issue-Question labels for new issues. The same for Issue-Enhancement - add Needs-Triage too.

**Comment by daxian-dbw** [comment]
Good call on adding `Needs-Triage` along with `Issue-Enhancement` for feature request issues.
For bug issues, does it make sense to add `Issue-Question` automatically? In my personal opinion, `Issue-Question` should be applied to those issues that are really just a question, and thus when applying this label, it means the issue has already been triaged.

**Comment by iSazonov** [comment]
> Good call on adding `Needs-Triage` along with `Issue-Enhancement` for feature request issues.
> For bug issues, does it make sense to add `Issue-Question` automatically? In my personal opinion, `Issue-Question` should be applied to those issues that are really just a question, and thus when applying this label, it means the issue has already been triaged.

In the case we should do the some for `Issue-Enhancement` :-)

Currently I set `Issue-Question` for all issues as a _start point_. New process is still not clear for me - who and how should process `Needs-Triage`? We could automatically set only `Needs-Triage` and after triage manually set `Issue-Question` for minor issues, `Issue-Bug` for bugs and `Issue-Enhancement` for new functionality.

**Comment by daxian-dbw** [comment]
`Issue-Enhancement` is auto-set for issues that are opened using the `Feature_Request.md` template. I think that's explicit enough.

> who and how should process

According to the WG doc, the corresponding WG should triage the issue, and `Needs-Triage` label should be removed after the triage.

**Review by TravisEz13 — APPROVED** [review]

**Comment by iSazonov** [comment]
> `Issue-Enhancement` is auto-set for issues that are opened using the `Feature_Request.md` template. I think that's explicit enough.

Currently I have to decrease most of such issues to `Issue-Question` level because they are poorly justified.


> According to the WG doc, the corresponding WG should triage the issue, and `Needs-Triage` label should be removed after the triage.

I would be happy if, from tomorrow, the working group members (who are now exclusively MSFT employees) have been doing this work on a daily basis. But I strongly doubt that it will be so tomorrow. Should I continue this work?

**Comment by daxian-dbw** [comment]
> I would be happy if, from tomorrow, the working group members (who are now exclusively MSFT employees) have been doing this work on a daily basis. But I strongly doubt that it will be so tomorrow. Should I continue this work?

I'm going to do my WG duty starting from today 😄 I strongly believe you should be part of some of the WGs, given that you are a maintainer and also you have been doing the WG work for such a long time!
I left a comment in the WG PR https://github.com/PowerShell/PowerShell/pull/14603/files#r564015516

**Comment by daxian-dbw** [comment]
@iSazonov I will merge this PR for now. Let's continue the process discussion in the WG PR. We will see how it works.

**Comment by daxian-dbw** [comment]
@rjmholt It seems something is wrong with the CI :confused: Maybe just forcefully merge this one?

**Comment by TravisEz13** [comment]
nothing is wrong with CI, just doesn't run on files in this folder.

**Comment by daxian-dbw** [comment]
That's good to know. Then I will just merge this PR.

**Comment by iSazonov** [comment]
Maybe set `Needs-Triage` label on all issues in the repo by script?

**Pull request merged**
