### PR TITLE
Enable CA2211: Non-constant fields should not be visible

### PR DESCRIPTION
**Pull request by xtqqczze**
https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2211

### CODE REVIEW

**Comment by xtqqczze** [comment]
[/home/vsts/work/1/s/src/System.Management.Automation/engine/remoting/fanin/PSSessionConfigurationData.cs(21,28): error CA2211: Non-constant fields should not be visible [/home/vsts/work/1/s/src/System.Management.Automation/System.Management.Automation.csproj]
](https://dev.azure.com/powershell/PowerShell/_build/results?buildId=66918&view=logs&j=ccc846a8-a499-5156-33ea-23b6cc6a058d&t=bfee48ff-ec75-5bb0-34ee-de48375db398&l=47)

**Review by iSazonov — APPROVED** [review]

**Review by PaulHigin — APPROVED** [review]

**Comment by iSazonov** [comment]
@PaulHigin No problem with binary compatibility if we change this?

**Comment by PaulHigin** [comment]
I don't know what you mean.  What has changed except warning suppression?

**Comment by iSazonov** [comment]
@PaulHigin Sorry, my comment was for #14196.

**Pull request merged**
