### PR TITLE
Remove the `ProcessorArchitecture` portion from the full name as it's obsolete

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Remove the `ProcessorArchitecture` portion from the full name as it's obsolete in .NET 7.0
https://learn.microsoft.com/en-us/dotnet/api/system.reflection.assemblyname.processorarchitecture?view=net-7.0

This additional field in the assembly full name started to fail `Assembly.Load` in PowerShell remoting scenario, when starting a remote session. See example failures in the following CI run:
https://dev.azure.com/powershell/PowerShell/_build/results?buildId=110951&view=logs&j=8ff999f7-4a61-5f51-a6a7-d94e9758120c&t=b9d6b495-b227-54e1-c647-304a73968aa2&l=396

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.

### CODE REVIEW

**Comment by iSazonov** [comment]
Should we clean up all code base? I see 13 files with `ProcessorArchitecture`. Ex., we could hide the parameter in cmdlet.

**Comment by daxian-dbw** [comment]
I didn't think that far. This PR is an attempt to resolve the CI test failures in https://github.com/PowerShell/PowerShell/pull/18286, but it seems not sufficient to make those tests work.

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
Clear. We could do the cleanup in follow PR(s).

**Comment by daxian-dbw** [comment]
I have verified that this change will fix the test failures in https://github.com/PowerShell/PowerShell/pull/18286. Will merge this one and rebase the other.

**Pull request merged**
