### PR TITLE
Update PowerShell to build against dotnet 5.0-RC.1

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Update code and project files to build PowerShell against dotnet 5.0-rc.1.

Major changes to code:
- Update `ComRuntimeHelpers.cs` to change the calling convention `stdcall` to `unmanaged`, based on https://github.com/dotnet/runtime/commit/e13f72bfe26ef243fa96e67ec3ee5aa29c294c54#diff-064c99755b7df4413ffd97baf9d833db committed 2 days ago.
- Remove the use of `ReliabilityContractAttribute` and `SecurityPermissionAttribute` as they are obsoleted.
- Suppress the warning `CA1416` because [In .NET 5.0 we have added new attributes to annotate platform-specific APIs](https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1416?view=vs-2019#rule-description).
- Suppress warning about `UTF7` and `BinaryFormatter` with `SYSLIB0011` instead. See [Breaking changes for migration from version 3.1 to 5.0](https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.1-5.0#core-net-libraries).

## Known issues in .NET 5 RC.1

The .NET 5 RC.1 regressions and by-design breaking changes we ran into so far are:

1. Performance regression on Linux and macOS: https://github.com/dotnet/runtime/issues/41739. The fix https://github.com/dotnet/runtime/pull/41820 is made in .NET 5 RC.2
2. `System.Console.TreatControlCAsInput` is backwards in .NET 5 RC.1 on Linux and macOS. Issue: https://github.com/dotnet/runtime/issues/42423. The fix https://github.com/dotnet/runtime/pull/42432 was made in .NET 5 RC.2
3. `System.Console.ReadKey()` returning `Ctrl+J` for `ENTER` on macOS. Issue: https://github.com/dotnet/runtime/issues/42418. The fix https://github.com/dotnet/runtime/pull/42477 was made in .NET 5 RC.2
4. **A by-design breaking change** made in .NET 5 rc.1: Tls1.0 and Tls1.1 were retired from the default on Linux machines where OpenSSL 1.1 and above is used. The .NET PR is dotnet/runtime#40746

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by iSazonov** [comment]
Should we track CA1416 in new issue and fix this later?

**Comment by daxian-dbw** [comment]
@iSazonov I think there is nothing that needs to be fixed. For all the types and APIs that are supported only on Windows, we compile them only for Windows build. Do you spot anything that is not the case?

**Comment by iSazonov** [comment]
> Do you spot anything that is not the case?

I remember we had issues with referencing methods from wrong platform. So we could review the analyzer warnings and maybe use recommended workarounds.

**Comment by daxian-dbw** [comment]
The new attribute doesn't a suggestion, it's like `error CA1416: 'RegistryKey.GetValue(string?)' is supported on 'windows'`.
I randomly reviewed some files failed with the warning and it looks to me they are either guarded in a `if/def` or protected by a runtime check of the OS platform.

But there are lots of failures due to the warning and I surely didn't review them all. So please feel free to open an issue to track , and maybe also review them if you got time. Thanks!

**Comment by iSazonov** [comment]
@daxian-dbw Tracking issue #13647.

**Comment by iSazonov** [comment]
CI Linux fail with "OpenSslCryptographicException: error:141A90B5:SSL routines:ssl_cipher_list_to_bytes:no ciphers available".

Do they disable Tls 1.0 and 1.1 in CI Linux image in OpenSSL?

**Comment by daxian-dbw** [comment]
@iSazonov We are investigating but got nowhere so far :(  How to check if the Tls 1.0 and 1.1 is disabled on Ubuntu?

**Comment by TylerLeonhardt** [comment]
Dropping this here so it's not missed. Ctrl+C doesn't work on macOS

**Comment by benaadams** [comment]
Use single file publish? (also outputs a copy native libs on Windows, should be a single file on Linux though)
```xml
<PublishSingleFile>true</PublishSingleFile>
```

Perhaps assembly trimming? Though that might not work for powershell (as you could invoke apis from script?)
```xml
<PublishTrimmed>true</PublishTrimmed>
<TrimMode>Link</TrimMode>
```
On Windows can include the R2R with the single file to make startup faster (in exchange for size) https://devblogs.microsoft.com/dotnet/customizing-trimming-in-net-core-5/
```xml
<PublishReadyToRun>True</PublishReadyToRun>
```

**Comment by iSazonov** [comment]
> How to check if the Tls 1.0 and 1.1 is disabled on Ubuntu?

I see 3 cases:
- OpenSSL could be compiled without the support. I don't think it is our case.
- The support disabled in OpenSSL config file (min_protocol and -no_tls1, -no_tls1_1 options in the config). We can run the tests locally (WSL2?) and see results. If no problems exist locally it is question for the CI image support team.
- It is a feature in .Net 5.0 - on client side (PowerShell) or/and on server side (our test WebListener). We can check this locally and separately.

**Comment by iSazonov** [comment]
@benaadams 
> Use single file publish? 

We don't use the option today. (I tried locally and catch some issues). And we don't have PowerShell Committee conclusion whether we want to support the single file publish.

> Perhaps assembly trimming?

We don't use this. And you're right this is not acceptable in general. But it could be an option for specific minimal PowerShell distributions.

> On Windows can include the R2R with the single file to make startup faster

Yes, we use the feature. Welcome to investigate and contribute more in the scenario if you want.

**Comment by daxian-dbw** [comment]
@iSazonov We learnt from .NET team that this is a by-design breaking change made in .NET 5 rc.1, which retired Tls1.0 and Tls1.1 from the default on Linux machines where OpenSSL 1.1 and above is used. The .NET PR is https://github.com/dotnet/runtime/pull/40746

**Comment by iSazonov** [comment]
@daxian-dbw Thanks! Do you team to collect such by-design changes? It would be nice to see its in Release notes for 7.1 GA (I hope this reduce "false" feedbacks from PowerShell users and helps adoption to the new PowerShell version.).

**Comment by daxian-dbw** [comment]
@iSazonov The breaking changes will all be documented in https://docs.microsoft.com/en-us/dotnet/core/compatibility/3.1-5.0, though the TSL one is not yet documented.

**Comment by rjmholt** [comment]
After grappling with this issue for some time, I'm going to mark the tests that are currently failing as pending. We now expect the particular command to fail on Linux due to the configuration of both .NET 5 and the test environment, and I think it should be fixed as a patch to RC2. As such I'll open an issue to track fixing the tests and possibly PowerShell's own error messages (although after spending some time looking into it, I'm not sure how we do the latter reliably).

**Comment by SteveL-MSFT** [comment]
@iSazonov, @benaadams regarding single file, we don't want to take such a big change for an RC (which means not in 7.1).  Certainly something we would look at for 7.2.  File trimming would not work for PowerShell as it exists today as PowerShell is a platform for scripts that expect as many APIs as possible.  As Ilya noted, it may be useful when we make more progress on minimal PowerShell where scripts that need .NET APIs would install those assemblies with PowerShellGet 3.x.

**Review by rjmholt — APPROVED** [review]

**Comment by iSazonov** [comment]
What is a milestone should be for the PR and follow PRs?

**Comment by fMichaleczek** [comment]
>  File trimming would not work for PowerShell as it exists today as PowerShell is a platform for scripts that expect as many APIs as possible

@SteveL-MSFT I am not agree when it comes to old API. Why blacklist things when it could be remove at source ?

https://github.com/PowerShell/underhanded-powershell

I don't want this

```
# Windows/v7.1.0-preview.7
[Microsoft.VisualBasic.Interaction]::InputBox("Old stuff ?", "VBonCore", "Yes")
```

Trimming should be study from a security POV and the toolchain update to release at least a minimal edition. A PowerShell.SecureSdk project without distribution binaries is enough. 

A security contest is welcome ! . A rank by binaries file size with minimal binaries command compatibilty.

**Comment by rjmholt** [comment]
> @SteveL-MSFT I am not agree when it comes to old API. Why blacklist things when it could be remove at source ?

Yeah we've discussed that and it's something we're gradually investigating as a sort of "minimal PowerShell".

But what's old to you is required by others -- take anything out and we'll break someone, or at the very least make their migration path significantly more difficult.

But also, my understanding is that trimming is an automatic process based on static code discovery, and PowerShell uses reflection pretty much everywhere. To make trimming work for us, we'd need to build a very large list of APIs we need to preserve from the trimming process.

As I say, it's something we're investigating gradually, since there are a number of large hurdles that we'd need to overcome to make it work.

**Comment by danmosemsft** [comment]
@daxian-dbw thank you for helping find those last issues in RC1 so we could fix in RC2 and avoid shipping them. The more often Powershell can pick up .NET Core, the better for us!

**Pull request merged**
