### PR TITLE
Fix static method invocation type inference

### LINKED ISSUE #7820: Type inference of static method invocations isn't working
Steps to reproduce
------------------

```powershell
$script = '[powershell]::Create().'
$results = TabExpansion2 -inputScript $script -cursorColumn $script.Length
$results.CompletionMatches[0]
```

Expected behavior
-----------------

Returns completion results for an instance member of the `PowerShell` class.

```none
CompletionText ListItemText ResultType ToolTip
-------------- ------------ ---------- -------
Commands       Commands       Property System.Management.Automation.PSCommand Commands { get; set; }
```

Actual behavior
---------------

Nothing is returned.

```none

```

Environment data
----------------

```powershell
> $PSVersionTable
Name                           Value
----                           -----
PSVersion                      6.1.0
PSEdition                      Core
GitCommitId                    6.1.0
OS                             Microsoft Windows 10.0.17134
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

Additional Info
------------

The [`AddMembersByInferredTypesClrType`](https://github.com/PowerShell/PowerShell/blob/4bc22d92df336704e71c4ad22b716a9c22c619a4/src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs#L200) method adds static members as `PSMethod` objects but [`TryGetTypeFromMember`](https://github.com/PowerShell/PowerShell/blob/4bc22d92df336704e71c4ad22b716a9c22c619a4/src/System.Management.Automation/engine/parser/TypeInferenceVisitor.cs#L1230) expects CLR methods as `MethodCacheEntry` objects.

### PR DESCRIPTION
**Pull request by SeeminglyScience**
## PR Summary

Added handling for `PSMethod` objects in `TryGetTypeFromMember`.  This fixes type inference for static method invocations (e.g. `[powershell]::Create()`).

Resolves #7820 

I wasn't able to find any tests for member completion so I added a few as well along with the test case for the resolved issue.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [ ] Not Applicable or can only be tested interactively
    - **OR**
    - [X] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by SeeminglyScience** [comment]
Looking into test failures.  Also will move tests to the type inference section that I missed.  Moving to WIP

**Comment by SeeminglyScience** [comment]
Alright it's ready.  I'm fairly certain that test failure isn't related, but if I'm wrong let me know and I'll look into it.

**Comment by iSazonov** [comment]
@SeeminglyScience Seems test failure is related to your change.

You could add a test from original Issue to TabCompletion.Tests.ps1

**Review by lzybkr — APPROVED** [review]

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
@SeeminglyScience Thanks for your contribution!

**Pull request merged**
