### PR TITLE
Small cleanup CORECLR

### PR DESCRIPTION
**Pull request by CarloToso**

### CODE REVIEW

**Comment by xtqqczze** [comment]
@iSazonov Contributes to #3565?

**Review by iSazonov — APPROVED** [review]

**Review by iSazonov — CHANGES_REQUESTED** [review]
We can remove the file.

**Comment by CarloToso** [comment]
@iSazonov Removed file and folder

**Comment by iSazonov** [comment]
It seems we need to add reference to System.Diagnostics.PerformanceCounter in an csproj.

**Comment by CarloToso** [comment]
> It seems we need to add reference to System.Diagnostics.PerformanceCounter in an csproj.

I still don't have the experience to do that, please do it

**Comment by CarloToso** [comment]
> I guess you need to add:
> 
> ```
>   <ItemGroup>
>     <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="7.0.0-rc.1.22426.10" />
>   </ItemGroup>
> ```
>
> in Microsoft.PowerShell.Commands.Diagnostics.csproj

Done

**Review by iSazonov — APPROVED** [review]

**Review by daxian-dbw — APPROVED** [review]

**Pull request merged**
