### PR TITLE
Import-Module test fixes

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
fix tests where the cmdlet returns longpath
fix symlink test on windows where Target is no longer an array
update loaded assemblies list

# PR Summary

## PR Checklist

- [ ] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [ ] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 10 failures in `PowerShell-CI-macos`
(These are 5 of the failures)

Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1:11 char:30
```
Get-Command Tests.Test Script Lookup Positive Script Info
```powershell
The term 'Resolve-FilePath' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at <ScriptBlock>, /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Core/Get-Command.Tests.ps1: line 231
231:         $results.Definition | Should -BeExactly (Resolve-FilePath $fullPath)

```
Get-Module -ListAvailable with path.Gets all versions by path
```powershell
The term 'Resolve-FilePath' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at <ScriptBlock>, /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Core/Get-Module.Tests.ps1: line 251
251:         $modules[0].Path | Should -BeExactly (Resolve-FilePath $manifestV1Path)

```
Import-Module for Binary Modules.PS should be able to load the executable as a nested module
```powershell
The term 'Resolve-FilePath' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at <ScriptBlock>, /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1: line 221
221:         $location | Should -Be (Resolve-FilePath $exe)

```
Import-Module for Binary Modules.PS should try to load the binary module from a file path with extension: dll
```powershell
The term 'Resolve-FilePath' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at <ScriptBlock>, /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1: line 176
176:         $assemblyLocation | Should -BeExactly (Resolve-FilePath $TestModulePath)

```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 40 failures in `PowerShell-CI-windows`
(These are 5 of the failures)

Dot-source operator is not allowed in modules on locked down systems that export functions with wildcards.Verifies that a classes only module with dot-source and with using directive loads successfully
```powershell
The term 'PublicUsingFn' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Security\ConstrainedLanguageModules.Tests.ps1: line 426
426:                 $result = PublicUsingFn

```
Import trusted manifest files in system lockdown mode.Verifies that trusted manifest with nested modules and no extension module exports explicit function
```powershell
Cannot load the module 'C:\Users\VSSADM~1\AppData\Local\Temp\4865468e-1242-4ec5-ad0c-16ee767aa4ae\ImportTrustedManifestWithNestedModsAndNoExtNoFnExport_System32' because the module nesting limit has been exceeded. Modules can only be nested to 10 levels. Evaluate and change the order in which you are loading modules to prevent exceeding the nesting limit, and then try running your script again.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Security\ConstrainedLanguageModules.Tests.ps1: line 1214
1214:                 $module = Import-Module -Name $manifestFileName -Force -PassThru

```
PowerShellGet - Module tests (Admin).Error occurred in Describe block
```powershell
Exception calling "ShouldContinue" with "2" argument(s): "Object reference not set to an instance of an object."
At D:\a\1\s\src\powershell-win-core\bin\release\netcoreapp3.0\win7-x64\publish\Modules\PowerShellGet\PSModule.psm1:11044 char:9
```
PowerShellGet - Script tests (Admin).Error occurred in Describe block
```powershell
Exception calling "ShouldContinue" with "2" argument(s): "Object reference not set to an instance of an object."
At D:\a\1\s\src\powershell-win-core\bin\release\netcoreapp3.0\win7-x64\publish\Modules\PowerShellGet\PSModule.psm1:11044 char:9
```
#requires -Modules.Loading by name.Successfully runs a script requiring a module on the module path by path
```powershell
The script 'script.ps1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: C:\Users\VSSADM~1\AppData\Local\Temp\2b9c18dc-e2b4-4c0f-89e0-59ea1bad3262\modules\Banana.
at <ScriptBlock>, D:\a\1\s\test\powershell\Language\Scripting\Requires.Tests.ps1: line 136
136:             & $scriptPath | Should -BeExactly $success

```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 10 failures in `PowerShell-CI-linux`
(These are 5 of the failures)

Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1:11 char:30
```
Get-Command Tests.Test Script Lookup Positive Script Info
```powershell
The term 'Resolve-FilePath' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Core/Get-Command.Tests.ps1: line 231
231:         $results.Definition | Should -BeExactly (Resolve-FilePath $fullPath)

```
Get-Module -ListAvailable with path.Gets all versions by path
```powershell
The term 'Resolve-FilePath' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Core/Get-Module.Tests.ps1: line 251
251:         $modules[0].Path | Should -BeExactly (Resolve-FilePath $manifestV1Path)

```
Import-Module for Binary Modules.PS should be able to load the executable as a nested module
```powershell
The term 'Resolve-FilePath' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1: line 221
221:         $location | Should -Be (Resolve-FilePath $exe)

```
Import-Module for Binary Modules.PS should try to load the binary module from a file path with extension: dll
```powershell
The term 'Resolve-FilePath' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Core/Import-Module.Tests.ps1: line 176
176:         $assemblyLocation | Should -BeExactly (Resolve-FilePath $TestModulePath)

```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 2 failures in `PowerShell-CI-macos`
Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1:11 char:30
```
Convert-Path tests.Convert-Path supports pipelined input by property name
```powershell
Expected exactly /tmp/5c85a43d-e658-4d73-b9e8-ba660c7e9461, but got '/tmp/5c85a43d-e658-4d73-b9e8-ba660c7e9461'.
at <ScriptBlock>, /Users/vsts/agent/2.150.0/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Convert-Path.Tests.ps1: line 17
17:         Get-Item -Path $TestDrive | Convert-Path | Should -BeExactly (Resolve-FilePath $TestDrive)
```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 30 failures in `PowerShell-CI-windows`
(These are 5 of the failures)

Dot-source operator is not allowed in modules on locked down systems that export functions with wildcards.Verifies that a classes only module with dot-source and with using directive loads successfully
```powershell
The term 'PublicUsingFn' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Security\ConstrainedLanguageModules.Tests.ps1: line 426
426:                 $result = PublicUsingFn

```
Import trusted manifest files in system lockdown mode.Verifies that trusted manifest with nested modules and no extension module exports explicit function
```powershell
Cannot load the module 'C:\Users\VSSADM~1\AppData\Local\Temp\a405b4b0-b9c3-4f7a-83e5-006036e7eabc\ImportTrustedManifestWithNestedModsAndNoExtNoFnExport_System32' because the module nesting limit has been exceeded. Modules can only be nested to 10 levels. Evaluate and change the order in which you are loading modules to prevent exceeding the nesting limit, and then try running your script again.
at <ScriptBlock>, D:\a\1\s\test\powershell\Modules\Microsoft.PowerShell.Security\ConstrainedLanguageModules.Tests.ps1: line 1214
1214:                 $module = Import-Module -Name $manifestFileName -Force -PassThru

```
PowerShellGet - Module tests (Admin).Error occurred in Describe block
```powershell
Exception calling "ShouldContinue" with "2" argument(s): "Object reference not set to an instance of an object."
At D:\a\1\s\src\powershell-win-core\bin\release\netcoreapp3.0\win7-x64\publish\Modules\PowerShellGet\PSModule.psm1:11044 char:9
```
PowerShellGet - Script tests (Admin).Error occurred in Describe block
```powershell
Exception calling "ShouldContinue" with "2" argument(s): "Object reference not set to an instance of an object."
At D:\a\1\s\src\powershell-win-core\bin\release\netcoreapp3.0\win7-x64\publish\Modules\PowerShellGet\PSModule.psm1:11044 char:9
```
#requires -Modules.Loading by name.Successfully runs a script requiring a module on the module path by path
```powershell
The script 'script.ps1' cannot be run because the following modules that are specified by the "#requires" statements of the script are missing: C:\Users\VSSADM~1\AppData\Local\Temp\737b1f52-161c-48f3-bc47-4c151c498666\modules\Banana.
at <ScriptBlock>, D:\a\1\s\test\powershell\Language\Scripting\Requires.Tests.ps1: line 136
136:             & $scriptPath | Should -BeExactly $success

```

**Comment by PoshChan** [comment]
@SteveL-MSFT, your last commit had 2 failures in `PowerShell-CI-linux`
Send-MailMessage.Error occurred in Describe block
```powershell
Cannot bind argument to parameter 'Path' because it is null.
At /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Utility/Send-MailMessage.Tests.ps1:11 char:30
```
Convert-Path tests.Convert-Path supports pipelined input by property name
```powershell
Expected exactly /tmp/ae4a83b3-55c6-49ef-98ed-a69baa4e6ef6, but got '/tmp/ae4a83b3-55c6-49ef-98ed-a69baa4e6ef6'.
at <ScriptBlock>, /home/vsts/work/1/s/test/powershell/Modules/Microsoft.PowerShell.Management/Convert-Path.Tests.ps1: line 17
17:         Get-Item -Path $TestDrive | Convert-Path | Should -BeExactly (Resolve-FilePath $TestDrive)
```

**Comment by iSazonov** [comment]
Maybe we need to have a fix for long path names in Pester?

**Comment by SteveL-MSFT** [comment]
@iSazonov created https://github.com/pester/Pester/pull/1294

**Review by PaulHigin — APPROVED** [review]

**Comment by SteveL-MSFT** [comment]
@iSazonov we'll remove this workaround when we are able to use a Pester with my change

**Pull request merged**
