### PR TITLE
WIP: Resolve "using type alias = typename"

### LINKED ISSUE #3082: Implement type alias support
The parser has support for type aliases (like a type accelerator), but it's not fully implemented.

The following should work, but reports `Unable to find type [MyMap]`:

```PowerShell
using type MyMap = System.Collections.Generic.Dictionary[string,int]
[MyMap]::new()
```

The following should also work, but reports `This syntax of the 'using' statement is not supported`:

```PowerShell
using type foo = System.Collections.Arraylist
```

### PR DESCRIPTION
**Pull request by IISResetMe**
Fix #3082

# PR Summary

The parsing rules for `using ...` statements already support type alias notation a la:

```powershell
using type MyString = System.String
[string]::Empty -eq [MyString]::Empty
```

This PR:
 - Changes the SemanticChecks visitor to no longer treat [this valid syntax](https://github.com/PowerShell/PowerShell/issues/3082) as a parser error
 - Adds a type alias table to `TypeResolutionState`
 - Adds type alias resolution to `ResolveTypeWithContext()`

<strike>TO FIX:
 - [ ] Tab completion for static members no longer work in PSReadLine</strike>

TO DO:
 - [ ] Tests

## PR Context

This feature might be useful in situations where type name collisions exist between namespaces:

```powershell
using namespace System.Threading
using namespace System.Timers

# Ambiguous type name
[Timer]
```

```powershell
using namespace System.Threading
using type MyTimer = System.Timers.Timer

# System.Threading.Timer
[Timer]
# System.Timers.Timer
[MyTimer]
```

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [X] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by IISResetMe** [comment]
@lzybkr @SteveL-MSFT looks like tab-completion the static member operator on translated type literals doesn't work in PSReadLine:

```powershell
using type mystring = string
[mystring]:: # [TAB] does nothing when PSReadLine is imported
```

This also applies to implicit namespace prefixes:

```powershell
using namespace System.Security.Cryptography.X509Certificates
[X509Certificate]:: # [TAB] does nothing when PSReadLine is imported
```

Is this a known bug, or something I should take into account here? I should note that when I run `Remove-Module PSReadLine`, native tab completion works fine with the translated type literals...

**Comment by SeeminglyScience** [comment]
@IISResetMe 

> Is this a known bug, or something I should take into account here? I should note that when I run `Remove-Module PSReadLine`, native tab completion works fine with the translated type literals...

Do you have a custom PSRL key handler for <kbd>Tab</kbd>? Or a custom `TabExpansion2`? Your second example works for me in PSRL (though I had to fix my custom `TabExpansion2` first)

**Comment by IISResetMe** [comment]
@SeeminglyScience PSRL 2.0.0, no customization of either PSRL nor `TabExpansion2` 😖 

using_psrl

You obviously can't hear it from this gif, but I'm TAB'ing furiously prior to removing PSRL

**Comment by vexx32** [comment]
@IISResetMe @SeeminglyScience I have the same issue with tab-completion when doing `using namespace`... I'm pretty sure I don't have any customizations in TabCompleter2 either.

**Comment by IISResetMe** [comment]
If this is a well-known/accepted issue with PSRL I'll just move ahead without that being a concern, but I've just never noticed this before and was wondering if this is expected and/or on anyones radar :)

**Comment by SeeminglyScience** [comment]
Oh that right.  I thought you meant having the `using namespace ...` line in the same prompt e.g  `using namespace System.Security.Cryptography.X509Certificates; [X509Certificate2]::<tab>` which does work.

Honestly I thought that was by design so profile `using` statements wouldn't affect editor intellisense. Didn't know it worked without PSRL, but it's discussed a little bit in #8281

**Comment by vexx32** [comment]
It'd be nice if that worked, tbh. Intellisense is extremely handy. But yeah, probably out of scope for the PR.

**Comment by iSazonov** [comment]
@powercode Perhaps you could help with the tab completion issue.

**Comment by Jaykul** [comment]
Does it support removing the ambiguity, and not just aliasing another name?

That is, does this work:

```powershell
using namespace System.Threading
using namespace System.Timers
using type Timer = System.Threading.Timer

[Timer]
```

**Comment by IISResetMe** [comment]
@Jaykul yes, this would also make the `TypeResolver` try (and return) explicitly aliased type names before attempting to resolve sing-label type names qualified by `using` namespaces

**Pull request closed without merging**
