### PR TITLE
Webcmdlets add 308 to redirect codes and small cleanup

### PR DESCRIPTION
**Pull request by CarloToso**
# PR Summary
Add 308 to possible redirect codes
Small cleanup of a nested if

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
@CarloToso This change can be very sensitive. We need detailed description of the scenario(s) you are trying to fix.

**Comment by CarloToso** [comment]
The status codes 300,301,302,303,307,308 are redirect codes, and should have similar behaviour.
Before this PR when setting` -MaximumRedirection 0 -SkipHttpErrorCheck` in the WebCmdlets only 301 and 302 (HttpStatusCode.Moved, HttpStatusCode.MovedPermanently and HttpStatusCode.Found) threw this nonterminating error _The maximum redirection count has been exceeded. To increase the number of redirections allowed, supply a higher value to the -MaximumRedirection parameter._
You can check it with this code
`300,301,302,303,307,308 | ForEach-Object {Invoke-WebRequest http://mockbin.org/redirect/$($_)?to=https://mockbin.org/status/200 -MaximumRedirection 0 -SkipCertificateCheck}`

**Review by caligulamaxima — APPROVED** [review]

**Comment by iSazonov** [comment]
@CarloToso While I agree that 308 is redirect code and should be handled in some way I have a concern that the PR changes not one scenario but same ones.

Supporting the HTTP client is a difficult task. We usually compare the behavior with wget. If you can create tests that work the same way for both clients, that would be convincing for reviewers.

**Comment by CarloToso** [comment]
@iSazonov I wrote this small test to compare curl, wget and invoke-webrequest

```ps1
for ($maxredirs = 0; $maxredirs -le 2; $maxredirs++)
{
	Write-Host "MaximumRedirection == $maxredirs" -BackgroundColor Red
	Write-Host "-------------------Invoke-WebRequest-------------------"
	300,301,302,303,307,308 | ForEach-Object {Invoke-WebRequest "http://mockbin.org/redirect/$($_)?to=https://mockbin.org/redirect/302?to=https://mockbin.org/status/200" -Method HEAD -MaximumRedirection $maxredirs -SkipHttpErrorCheck}
	Write-Host "-------------------curl-------------------"
	300,301,302,303,307,308 | ForEach-Object {$x = curl.exe -LI --no-progress-meter "http://mockbin.org/redirect/$($_)?to=https://mockbin.org/redirect/302?to=https://mockbin.org/status/200" --max-redirs $maxredirs; ($x -join"`n").split("`n`n")[-1]}
	Write-Host "-------------------wget-------------------"
	300,301,302,303,307,308 | ForEach-Object {$x = .\wget.exe http://mockbin.org/redirect/$($_)?to=https://mockbin.org/redirect/302?to=https://mockbin.org/status/200 --max-redirect $maxredirs --spider --server-response 2>&1; ($x[0..($x.length-2)] -join"`n").split("Spider mode enabled. Check if remote file exists.")[-1]}
}
```
flags explained
```
curl -> -I == HEAD, -L == follow redirect
wget -> --spider == HEAD
```

It looks like they have similar behaviours:

`$maxredirs = 0`
Iwr ->error on 301 and 302 maximum redirections exceded
curl and wget -> always error maximum redirections exceded

`$maxredirs = 1`
Iwr ->no error
curl and wget -> always error maximum redirections exceded

I wasn't able to parse the maximum redirections exceded error correctly in wget, to visualize it use:
 ```
.\wget.exe http://mockbin.org/redirect/303?to=https://mockbin.org/redirect/302?to=https://mockbin.org/status/200 --max-redirect 0 --spider --server-response
```

I propose we remove the non terminating error from the webcmdlets, because it only appears for 2 status codes, and only for `-MaximumRedirection 0`

**Comment by iSazonov** [comment]
> @iSazonov I wrote this small test to compare curl, wget and invoke-webrequest

Thanks for your investigations! Can you share outputs (or screenshots)? For 308 particularly.

**Comment by CarloToso** [comment]
Invoke-WebRequest (`$maxredirs ->0,1,max`)
iwr0
iwr1
iwr2

Curl (`$maxredirs ->0,1,max`)
curl0
curl1
curl2

Wget (`$maxredirs ->0,1,max`)
wget0
(different code to display the redirections exceeded error)
wget1
wget2

**Review by iSazonov — APPROVED** [review]
LGTM.

**Comment by CarloToso** [comment]
Is something blocking this PR?

**Review by PaulHigin — APPROVED** [review]
LGTM

**Pull request merged**
