### PR TITLE
MacOS test failing for read-host

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
We changed powershell.exe to require -c to execute command

### CODE REVIEW

**Review by daxian-dbw — APPROVED** [review]
I have verified that the test passes with this fix.

**Review by andyleejordan — APPROVED** [review]
LGTM though I would use `-command` over `-c` for consistency.

**Comment by andschwa** [comment]
@SteveL-MSFT it looks like your commit is getting created with `slee@ntdev.microsoft.com`, which I don't think you meant, as it's not associated with your GitHub account.

**Comment by iSazonov** [comment]
It seems we should add the check in ScriptAnalizer.

**Comment by SteveL-MSFT** [comment]
@andschwa yeah, used a different machine, let me see if I can fix that

**Pull request merged**
