### PR TITLE
Fix CA2243: Attribute string literals should parse correctly

### LINKED ISSUE #15625: Add missing `Remove-Alias` HelpUri
The `RemoveAliasCommand` has an empty `HelpUri`.

`Remove-Alias` was added in #5143 so this issue exists since [v6.0.0](https://github.com/PowerShell/PowerShell/releases/tag/v6.0.0).

### PR DESCRIPTION
**Pull request by xtqqczze**
cc: @iSazonov 

* Fix #15625
* Enable [CA2243: Attribute string literals should parse correctly](https://docs.microsoft.com/dotnet/fundamentals/code-analysis/quality-rules/ca2243)

### CODE REVIEW

**Comment by sdwheeler** [comment]
The cmdlet and HelpURI need to be added to the appropriate CSV file in test\powershell\engine\Help\assets\HelpURI.

There are CSV files:
- V2Cmdlets.csv
- V3Cmdlets.csv

I don't know the difference between them, but my guess is that it goes in the V2 file.

**Comment by xtqqczze** [comment]
> The cmdlet and HelpURI need to be added to the appropriate CSV file in test\powershell\engine\Help\assets\HelpURI.
> 
> There are CSV files:
> 
> * V2Cmdlets.csv
> * V3Cmdlets.csv
> 
> I don't know the difference between them, but my guess is that it goes in the V2 file.

@adityapatwardhan Do you know which CSV file the HelpUri should be added to?

**Comment by iSazonov** [comment]
@xtqqczze Please add to V2 file since it is V2 cmdlet.

**Comment by xtqqczze** [comment]
> @xtqqczze Please add to V2 file since it is V2 cmdlet.

Added in 6d147e5.

**Review by iSazonov — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
I think this does not meet the bar backport, but i wanted to have discussion as the issue for this PR was marked backport to 7.1.x

**Pull request merged**
