### PR TITLE
Check SHEmptyRecycleBin retval correctly (#6743)

### PR DESCRIPTION
**Pull request by fowl2**
## PR Summary
`SHEmptyRecycleBin` doesn't use SetLastError but returns a HResult as per MSDN
nb: not compile tested

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` to the beginning of the title and remove the prefix when the PR is ready.
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] User-facing [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed - Issue link:
- **Testing - New and feature**
    - [x] Not Applicable or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Comment by iSazonov** [comment]
@fowl2 Thanks for your contribution! Currently the code is not compiled and the cmdlet absent in PowerShell Core. So I believe we can not accept the change today. See #6778.

**Comment by iSazonov** [comment]
@daxian-dbw @adamdriscoll What is a conclusion? Should we close the PR?

**Comment by daxian-dbw** [comment]
@fowl2 Thanks for your contribution!
Unfortunately, powershell currently doesn't build `ClearRecycleBinCommand.cs`. In general, we don't accept changes to code that doesn't build. Do you mind update your changes to enable `Clear-RecycleBin` in PowerShell Core on Windows platforms?

**Comment by iSazonov** [comment]
Related issue about the cmdlet - #6778 and #6801

**Comment by iSazonov** [comment]
@fowl2 Thanks for your contribution! Sorry that we can not accept it. Welcome back with new contributions!

**Pull request closed without merging**
