### PR TITLE
WIP: Enable IDE0019: InlineAsTypeCheck

### PR DESCRIPTION
**Pull request by xtqqczze**
https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0019

Follow-up to #13333.

### CODE REVIEW

**Comment by xtqqczze** [comment]
Build failures due to duplicated preprocessor directives from codefix, see https://github.com/dotnet/roslyn/issues/37398

**Comment by iSazonov** [comment]
@xtqqczze Please split the PR.

**Comment by xtqqczze** [comment]
This can be looked at again now dotnet/roslyn#37398 is resolved.

**Comment by xtqqczze** [comment]
Superseded by https://github.com/PowerShell/PowerShell/pull/25920.

**Pull request closed without merging**
