### PR TITLE
Replace Ambiguous language for tests from switch to parameter for accuracy

### PR DESCRIPTION
**Pull request by romero126**
# PR Summary

Replace Ambiguous language for pester tests.
Pester tests for Remove-Item used incorrect terminology using switch analogous with Parameter

## PR Context

Modify incorrect terminology, to use `parameter` instead of `switch`.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [x] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by sdwheeler — CHANGES_REQUESTED** [review]
The more proper term would be `parameter` rather than `argument`

**Comment by romero126** [comment]
Hey Sean, I thought the same thing at first. However after looking deeply at the terminology. I decided the term "argument" would be better. Because "parameter" is the "-value" or $variable that gets defined when the argument is passed into the command.

https://www.quora.com/What-is-the-difference-between-argument-and-parameters-in-C

Is there an official consensus that the PowerShell team uses over the conventional comp sci answer?

**Comment by sdwheeler** [comment]
@romero126 In PowerShell and in this example `-Path` is the parameter being tested `$testfilepath` is the argument value being passed.

**Comment by SteveL-MSFT** [comment]
I agree with @sdwheeler here.  `Switch` is definitely wrong.  Reading the name of the test, it's referring to the `Path parameter`.

**Comment by romero126** [comment]
Thank you @sdwheeler and @SteveL-MSFT for the feedback. I would have replied sooner but I got a little busy.

**Comment by iSazonov** [comment]
@sdwheeler Please update your review.

**Review by sdwheeler — APPROVED** [review]

**Comment by iSazonov** [comment]
@romero126 Thanks for your contribution!

**Pull request merged**
