### PR TITLE
Fix PowerShell class definition leaking into another Runspace

### LINKED ISSUE #9313: PowerShell classes leak to other runspaces on macOS
# Steps to reproduce

```powershell
class MyClass {
    # Property: Holds name
    [String] $Name

    # Constructor: Creates a new MyClass object, with the specified name
    MyClass([String] $NewName) {
    # Set name for MyClass
      $this.Name = $NewName
    }

    # Method: Method that changes $Name to the default name
    [void] ChangeNameToDefault() {
      $this.Name = "DefaultName"
    }
  }
[MyClass].GetType()
[PowerShell]::Create().AddScript('[MyClass]::new("ffff")').Invoke()
```

# Expected behavior

Class types should not leak to other runspaces.

# Actual behavior

Type was able to be created in other runspace.
image

# Environment data

```none
Name                           Value
----                           -----
PSVersion                      6.2.0
PSEdition                      Core
GitCommitId                    6.2.0
OS                             Darwin 18.2.0 Darwin Kernel Version 18.2.0: Thu Dec 20 20:46:53 PST 2018; root:xnu-4903.241.1~1/RELEASE_X86_64
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

# Notes

This doesn't repro without _using_ the class in some way (i.e. calling `[MyClass].GetType()`). That part is important.

cc @daxian-dbw who wasn't able to repro this (I assume on Windows? Using PowerShell Core 6.2?)

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #9313

The root problem is that a scope is holding on the shared default `TypeResolutionState` object when there is no PowerShell class defined in the parent chain of the scope, and then the `TypeResolutionState` object is used as a key to cache the found type.
A scope should not hold on to the default `TypeResolutionState` object, but should always refer to the parent's `TypeResolutionState` object when no PowerShell class defined in itself. When a PowerShell class is defined in a scope, a new `TypeResolutionState` will be created for the specific scope.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by TravisEz13** [comment]
@rjmholt Can you review?

**Review by rjmholt — APPROVED** [review]

**Comment by iSazonov** [comment]
What is a design intention - runspaces is boundaries of visibility of c# types, ps classes, objects, modules? 
If before the PR I define a ps class in interactive session and run a job (or foreach -parallel) then after the change the job will does not see the class?

**Comment by daxian-dbw** [comment]
PowerShell class is visible only in the scope that it's defined and the child scopes of that scope. It's a scope thing, just like you define a function.

**Comment by daxian-dbw** [comment]
Actually, @iSazonov brings up a good point and makes me believe this should be included in rc.1. If people started to depend on the wrong behavior, it will be much worse to break it in 7.1.0.

**Pull request merged**
