### PR TITLE
Mark failing CertificateProvider tests as pending

### LINKED ISSUE #6265: Pester tests for Microsoft.PowerShell.Security are using null incorrectly
Several Pester tests for `Microsoft.PowerShell.Security` are incorrectly using `null` instead of `$null`

* Use of `Should not be null` should have used `$null`. Change to `Should -Not -BeNullOrEmpty` and remediate
  example: https://github.com/PowerShell/PowerShell/blob/76526c6f1df08c0a55fbae79a7148a4a58805626/test/powershell/Modules/Microsoft.PowerShell.Security/CertificateProvider.Tests.ps1#L51

* Use of `Get-Item` should be `Get-ChildItem` in cert provider test (#6258). Correcting `$null` check will expose this bug.
 https://github.com/PowerShell/PowerShell/blob/76526c6f1df08c0a55fbae79a7148a4a58805626/test/powershell/Modules/Microsoft.PowerShell.Security/CertificateProvider.Tests.ps1#L50

Discovered while working on #6256

### PR DESCRIPTION
**Pull request by xtqqczze**
# PR Summary

* Fix incorrect null comparison (fix #6265)
* Mark `Get-Item` tests on provider root as pending (TODO: open issue)
* Mark failing CodeSigningCert tests as pending as there are no code signing certificates in environment. (TODO: open issue)

## PR Context

* Fix #6265
* Follow-up to reverted 0feed4ca3e86fcb59d35cd2e622be2c18d0f4cb9 in #11558 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by xtqqczze** [comment]
`PowerShell-CI-static-analysis` failure is unrelated.

**Comment by anmenaga** [comment]
@xtqqczze why those `-Pending:$true` tests start failing after `null` -> `$null` change? Is it a test bug or a product bug?

**Comment by xtqqczze** [comment]
2132f1bf1ea1a0c0048ccf6a246ed0a0abca5a24 see [build 44177](https://dev.azure.com/powershell/PowerShell/_build/results?buildId=44177&view=ms.vss-test-web.build-test-results-tab)

**Comment by xtqqczze** [comment]
81929e4c3cc7973681fe624566433965374a1166 see [build 44177](https://dev.azure.com/powershell/PowerShell/_build/results?buildId=44177&view=results)

**Comment by xtqqczze** [comment]
81929e4c3cc7973681fe624566433965374a1166 see [build 44185](https://dev.azure.com/powershell/PowerShell/_build/results?buildId=44185&view=results)

**Comment by xtqqczze** [comment]
@anmenaga Please see new commits. It appears some of the tested behaviour is undocumented - I will open new issues.

**Review by TravisEz13 — APPROVED** [review]

**Review by andyleejordan — CHANGES_REQUESTED** [review]
I approve the code changes, but we need to resolve the conflicts and open an issue to fix the were-failing now-pending tests (which...being this rather old now, need to be re-tested). That's on us maintainers to get done now.

**Comment by daxian-dbw** [comment]
There was significant changes to the `CertificateProvider.Tests.ps1` file in the past, so it's hard to decide how to resolve the conflicts. Given that, I will close this PR, and only pick those `-Be null` typo fixes to a new PR.

**Pull request closed without merging**
