### PR TITLE
ConvertTo-Json: Treat large enums as numbers

### PR DESCRIPTION
**Pull request by jborean93**
# PR Summary
Remove special handling from Windows PowerShell that treated enum values backed by Int64 and UInt64 as a string. This ensures that all enum types are serialized as a number and are only treated as a string when -EnumsAsStrings is specified.

As requested this is controlled by the new experimental feature `PSSerializeJSONLongEnumAsNumber`.

## PR Context
When using `ConvertTo-Json` with an Int64 or UInt64 enum type the value is converted to a string.

```powershell
enum LongEnum : long {
    LongValue = 1
}

ConvertTo-Json @{key = [LongEnum]::LongValue}
```

The current behaviour is:

```json
{
    "key": "LongValue"
}
```

The behaviour after this PR is:

```json
{
    "key": 1
}
```

Instead this PR removes the extra code that does this as it seems to be from Windows PowerShell days. Even then WinPS can deserialize an Int64 or UInt64 value just fine. This is technically a breaking change but I find the current default is surprising and honestly probably very rare to happen in the real world.

If the user wants to preserve the old behaviour they can set `-EnumsAsStrings` to have the enum be converted to a string like before.

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x]  [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [ ] None
    - **OR**
    - [x] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [x] Experimental feature name(s): `PSSerializeJSONLongEnumAsNumber`
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed: https://github.com/MicrosoftDocs/PowerShell-Docs/pull/10875
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [x] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
I guess it was a workaround exclusively for JS.
The same case https://github.com/dotnet/aspnetcore/issues/52393

I think we should preserve the workaround.

**Comment by jborean93** [comment]
I don't see why we should cater to one language when PowerShell is able to deserialize such numbers. The fact that enums already have a workaround with `-EnumAsStrings` to produce the original output that is done today means people can still get the old behaviour.

**Comment by iSazonov** [comment]
> I don't see why we should cater to one language ...

Me too :-) However, a comment in the code points to an internal case. Only MSFT team can find the history and evaluate the relevance of this old workaround.
/cc @StevenBucher98 @SteveL-MSFT

**Comment by jborean93** [comment]
Just to add more ammunition to the change;

* I’ve never actually seen an enum based on long in the wild before
* We already serialize raw int64 and uint64 values as numbers and not strings so why should these enums be different

**Comment by jborean93** [comment]
Looks like that ASP issue is specific to ASP, serializing a UInt64 works just fine with both `Newtonsoft.Json` and `System.Text.Json`

```powershell
$sb = [System.Text.StringBuilder]::new()
[Newtonsoft.Json.JsonSerializer]::Create().Serialize([System.IO.StringWriter]::new($sb), @{foo=[uint64]'18446744073709551615'})
$sb.ToString()
# {"foo":18446744073709551615}

[System.Text.Json.JsonSerializer]::Serialize[hashtable](@{foo = [uint64]'18446744073709551615'})
# {"foo":18446744073709551615}
```

Python is also fine

```python
import json
json.dumps({"foo": 18446744073709551615})
'{"foo": 18446744073709551615}'
```

**Comment by JamesWTruher** [comment]
> Just to add more ammunition to the change;
> 
>     * I’ve never actually seen an enum based on long in the wild before
> 
>     * We already serialize raw int64 and uint64 values as numbers and not strings so why should these enums be different

PowerShell actually as a few enums based on long (or ulong)

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]
Please put behind an experimental feature

**Comment by jborean93** [comment]
> PowerShell actually as a few enums based on long (or ulong)

There are 1-3 in PowerShell depending on your definitions

```powershell
[System.AppDomain]::CurrentDomain.GetAssemblies().GetTypes() | Where-Object {
    $_.IsSubclassOf([Enum]) -and
    $_.IsVisible -and
    [Enum]::GetUnderlyingType($_) -in @([int64], [uint64])
} | Select-Object FullName, @{
    N='Assembly'
    E={$_.Assembly.GetName().Name}
}, @{
    N='SubType'
    E={[Enum]::GetUnderlyingType($_).Name}
}
```

```
FullName                                                      Assembly                            SubType
--------                                                      --------                            -------
System.Diagnostics.Tracing.EventKeywords                      System.Private.CoreLib              Int64
System.Management.Automation.Tracing.PowerShellTraceKeywords  System.Management.Automation        UInt64
Microsoft.Management.Infrastructure.CimFlags                  Microsoft.Management.Infrastructure Int64
Microsoft.Management.Infrastructure.Options.CimOperationFlags Microsoft.Management.Infrastructure Int64
System.Net.Sockets.IOControlCode                              System.Net.Sockets                  Int64
```

> We still have a concern about how likely this will break users so we recommend putting this behind an experimental feature to also help advertise this change.

I do personally disagree that we really do need to put it behind an experimental feature but I suppose it's a stepping stone to just having it be done by default.

> Please put behind an experimental feature

Any docs on what exactly needs to be done for devs on this?

**Comment by kilasuit** [comment]
@jborean93 the [about_experimental_features doc](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_experimental_features?view=powershell-7.5) shows what needs to be done to add experimental features in code - hope that helps

**Comment by jborean93** [comment]
@SteveL-MSFT I’m unsure how to test things with experimental features, do I just remove the old tests, do I need to set any of the features in the json file (what are they for otherwise)?

**Comment by jborean93** [comment]
https://github.com/MicrosoftDocs/PowerShell-Docs/pull/10875 opened which documents this new experimental feature. Just need guidance on what to do with the existing tests/old behaviour in CI and what the `experimental-feature-*.json` files are for.

**Comment by SteveL-MSFT** [comment]
@jborean93 I believe [build.psm1](https://github.com/PowerShell/PowerShell/blob/master/build.psm1#L670) detects if those json files need to be generated and would be part of your PR

**Comment by jborean93** [comment]
@SteveL-MSFT what about my question about the testing?

**Comment by jborean93** [comment]
I've tried 3 runs but they've all failed with some random test failing that is unrelated so I'm just going to let that failure be. The failures are unrelated to the changes here and without any extra guidance on what to do with the older tests I've just added a skip if the feature is enabled.

**Comment by jborean93** [comment]
@SteveL-MSFT any chance for a re-review.

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Comment by iSazonov** [comment]
@SteveL-MSFT Can we merge?

**Pull request merged**
