### PR TITLE
Replace 'api-ms-win-core-job-12-1-0.dll' with 'Kernell32.dll'

### LINKED ISSUE #6561: Start-Process: Unable to load DLL 'api-ms-win-core-job-12-1-0.dll'
Repro:

Use clean install of Windows 7 SP1 (apparently both x86 and x64 are affected). Then run the following command in PS 6.0.2 ZIP version:

~~~
Start-Process "ipconfig" -ArgumentList "/flushdns" -Wait -NoNewWindow
~~~

Result:

~~~
Start-Process : Unable to load DLL 'api-ms-win-core-job-l2-1-0.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
At line:1 char:1
+ Start-Process -FilePath "C:\7zip\7za.exe" -ArgumentList ("x -oC:\temp ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Start-Process], DllNotFoundException
+ FullyQualifiedErrorId : System.DllNotFoundException,Microsoft.PowerShell.Commands.StartProcessCommand
~~~

PowerShell 6.0.2 x86 zip
Windows 7 b7601 SP1 x86 (modern.ie VM)

Works perfectly fine on Win10 x64.

Also tried 6.1.0-preview1, behaves the same way.

### PR DESCRIPTION
**Pull request by iSazonov**
# PR Summary

Fix #6561

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Comment by iSazonov** [comment]
@adityapatwardhan I removed all links to `api-ms-win-core-job-l2-1-0.dll` and now it works for me on Windows 7.

> should we be removing the definitions from PInvokeDllNames.cs

There is already some unused consts, the list is large and numerated, also we could want to use ApiSets again after Windows 7 EOL. I think we need to keep the consts.

**Comment by daxian-dbw** [comment]
Do we know if things are still working properly on NanoServer and Windows IoT after changing to `kernal32.dll`?

**Comment by iSazonov** [comment]
I can not test on Nano and IoT.
I saw that .Net Core team replaced ApiSets with direct dll names because of many such problems with ApiSets.
See:
https://github.com/dotnet/corefx/commit/75e45da8d7104e7f6b737d552bbc332d14211da8
More: https://github.com/dotnet/corefx/search?q=ApiSets&type=Commits

Also I found https://www.geoffchappell.com/studies/windows/win32/apisetschema/history/sets61.htm where we can see that there is sometimes automapping (for Windows 7).

**Review by adityapatwardhan — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
I have verified that the change works on NanoServer 1903 image.

**Comment by ForNeVeR** [comment]
Hey, shouldn't we remove the corresponding constants from the `PinvokeDllNames` class since they are unused now?

**Comment by iSazonov** [comment]
@ForNeVeR We did not remove the constants because we will revert the change after Windows 7 EOL.

**Comment by ForNeVeR** [comment]
Okay, thanks.

**Pull request merged**
