### PR TITLE
Make OpenCover merge and upload more reliable/usable

### PR DESCRIPTION
**Pull request by adityapatwardhan**
- Delete temporary zip file.
- Remove CodeCov uploading through cygwin.
- Add code to use Invoke-WebRequest to upload to Codecov
- Wait for 1 build to start analysis.
- Do not wait for CI.
- Disable comments in PR.

### CODE REVIEW

**Comment by JamesWTruher** [comment]
>     $_

should this be redirected to the log file?

---
Refers to: test/tools/CodeCoverageAutomation/Start-CodeCoverageRun.ps1:171 in f393084. [](commit_id = f39308479ea21140519a5e17330b01b35baa61c9, deletion_comment = False)

**Comment by adityapatwardhan** [comment]
>     $_

Fixed.

---
In reply to: [276459249](https://github.com/PowerShell/PowerShell/pull/3078#issuecomment-276459249) [](ancestors = 276459249)

---
Refers to: test/tools/CodeCoverageAutomation/Start-CodeCoverageRun.ps1:171 in f393084. [](commit_id = f39308479ea21140519a5e17330b01b35baa61c9, deletion_comment = False)

**Comment by JamesWTruher** [comment]
:shipit:

**Comment by adityapatwardhan** [comment]
@PowerShell/powershell-maintainers This is ready for merge.

**Comment by TravisEz13** [comment]
LGTM, except the title, I changed...

**Pull request merged**
