### PR TITLE
WIP: Enable SA1617: Void return value should not be documented 

### PR DESCRIPTION
**Pull request by xtqqczze**
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1617.md

### CODE REVIEW

**Comment by xtqqczze** [comment]
reopening

**Comment by iSazonov** [comment]
Still draft?

**Comment by xtqqczze** [comment]
> Still draft?

Yes, I will need to manually review every change to ensure important comments are not deleted.

**Comment by xtqqczze** [comment]
Closed, as I have no immediate plans to work on this.

**Comment by iSazonov** [comment]
@xtqqczze Thanks for your efforts! These comments are in bad shape and if you find time to improve them a little in the future I will always support you.

**Comment by xtqqczze** [comment]
@iSazonov Thanks for the encouragement. This work will be easier if we merge #14405.

**Pull request closed without merging**
