### PR TITLE
Remove unused string completion code

### PR DESCRIPTION
**Pull request by MartinGC94**
# PR Summary
Removes unused code for completing members in double quoted strings.
The idea seems to have been that users would have been able to enter a variable, or literal type in a double quoted string and tab complete the member to auto convert it into a subexpression like this:
```
"Hello$MyVar.<Tab> -> "Hello$($MyVar.MyMember)
"Hello[string]::<Tab> -> "Hello$([string]::Empty)
```
But the actual code isn't working.  
An obvious alternative to removing the code would be to fix it but I've never seen anyone request this and it doesn't seem very useful to me.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Comment by iSazonov** [comment]
I'd prefer this work and in `@""` too.

**Comment by MartinGC94** [comment]
@iSazonov (and @fflaten since I see you gave a 👍) do you care about the type literal member completion? Or is it just the variable member completion you would like to see? There wouldn't be any completion for the type literal itself so you would have to enter the whole typename yourself before the member completion would be able to change it to a subexpression.

As for the here-string completion, that's definitely out of scope for now as I'm waiting on my proposed here-string syntax changes to either get merged or rejected.

**Comment by fflaten** [comment]
Variable member completion for me

**Comment by iSazonov** [comment]
I mainly mean that if PowerShell allows code between double quotes, then it would be logical to expect IntelliSense to work exactly the same as in normal mode.

**Comment by MartinGC94** [comment]
@iSazonov Well, that's just the thing. PowerShell doesn't allow that syntax inside strings, you need a subexpression, and inside subexpressions the tab completion works as you would expect. This is just "magic" code that infers that the user probably wants to access a member so it adds the subexpression for the user.

**Review by daxian-dbw — APPROVED** [review]
The changes indicate that the `isQuotedString` parameter is never passed in a `true` value, making all related code not used.
Given that this targets an uncommon scenario, I'm fine with removing the dead code to reduce complexity.

**Comment by SeeminglyScience** [comment]
> The changes indicate that the `isQuotedString` parameter is never passed in a `true` value, making all related code not used. Given that this targets an uncommon scenario, I'm fine with removing the dead code to reduce complexity.

Yeah I'm inclined to agree. Especially since removing the method isn't causing any build errors so we're not missing another invocation (and the compiler wouldn't be calling this with reflection so we're safe there). LGTM

**Review by SeeminglyScience — APPROVED** [review]

**Pull request merged**
