### PR TITLE
Bump PSReadLine from 2.1.0 to 2.2.2

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Bump PSReadLine from 2.1.0 to 2.2.2

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s):

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]

**Comment by iSazonov** [comment]
I hope to get this with Windows monthly update too :-)

**Comment by doctordns** [comment]
@iSazonov is PSReadLine now serviced by Microsoft Update?

**Comment by iSazonov** [comment]
> @iSazonov is PSReadLine now serviced by Microsoft Update?

It is a part of WMF and distributed with Windows PowerShell for years.

**Comment by daxian-dbw** [comment]
@doctordns I guess your question was about the MU support for PowerShell 7.2+. The answer to that is: no, the updates t PSReadLine itself doesn't get pushed through MU, but PowerShell will bundle the latest stable release and the MU for PowerShell will refresh the PSReadLine module.

**Comment by doctordns** [comment]
@daxian. So Windows PowerShell will automatically get updated via MU while PowerShell 7 will not. PowerShell 7 will get updatgecd versions (of PSReadline) when I get an updated version of Powershell 7 (eg 7.2.2 when that ships)?? And when that happens we'll be updated by MU?

**Comment by daxian-dbw** [comment]
> eg 7.2.2 when that ships

This PR was merged in master but not backported. I'm not sure if we are going to backport it for 7.2.2, but it sounds like a good idea :)

> And when that happens we'll be updated by MU?

If we decided to backport this change to 7.2.x, then yes, you will be updated by MU.

**Comment by iSazonov** [comment]
I still don't understand about Windows PowerShell - will we get the update?

**Comment by daxian-dbw** [comment]
We will get updates about Windows PowerShell when there is an update to Windows PowerShell.
Be noted that, anything happens in this repo doesn't affect Windows PowerShell.

**Comment by iSazonov** [comment]
Thanks for clarify! 
(Current PSRL version in Windows is too unfortunate)

**Comment by TravisEz13** [comment]
@PowerShell/powershell-maintainers 
We only take security fixes and regression to LTS.  This is appropriate for 7.3.  Rejecting backport.

**Pull request merged**
