### PR TITLE
Typo in new parameter set

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
# PR Summary

Realized there was a typo in my parameter set name... 

Originally added in https://github.com/PowerShell/PowerShell/pull/8889

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [ ] [Change is not breaking](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **User-facing changes**
    - [ ] Not Applicable
    - **OR**
    - [x] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed: https://github.com/MicrosoftDocs/PowerShell-Docs/issues/3755
- **Testing - New and feature**
    - [x] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
        - [ ] [Add `[feature]` to your commit messages if the change is significant or affects feature tests](https://github.com/PowerShell/PowerShell/blob/master/docs/testing-guidelines/testing-guidelines.md#requesting-additional-tests-for-a-pr)

### CODE REVIEW

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by iSazonov** [comment]
@TylerLeonhardt Please add a reference to PR where we made the typo.

**Comment by TylerLeonhardt** [comment]
Updated the PR description.

I don't think we really need a test to make sure the parametersets are spelled correctly. I don't think that's something we've done much in the past.

I found the typo while I was working on the docs for the original feature and working on the docs offered a good opportunity to double check parametersets and other things are spelled correctly.

**Comment by iSazonov** [comment]
@TylerLeonhardt Thanks for fixing the typo. I'll merge on next week.

**Comment by iSazonov** [comment]
I wonder that 4 reviewers (I too) skipped this in previous PR.

**Review by daxian-dbw — APPROVED** [review]

**Pull request merged**
