### PR TITLE
Rename "namespaces" folder as "providers"

### PR DESCRIPTION
**Pull request by KirkMunro**
# PR Summary

I went looking for code related to providers, and found it surprisingly difficult to find without using an appropriate search term. All PowerShell provider-related code was under a folder called namespaces. I can only guess that "namespaces" was the original name for what eventually became "providers".

At any rate, to set up `System.Management.Automation.csproj` for easier discovery of provider-related code, I renamed the "namespaces" folder as "providers". There are no code changes, just the renaming of a folder and some corresponding changes in `System.Management.Automation.csproj` so that it works the same way with the folder renamed.

## PR Context

This is just some project cleanup to make it easier to find provider-related code in the `System.Management.Automation` project.

## PR Checklist

- [X] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [X] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [X] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [X] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [X] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [X] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [X] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and enumerated concerns in the summary. This may include:
        - Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode (which runs in a different PS Host).
        - Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
        - Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
        - Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).

### CODE REVIEW

**Review by TravisEz13 — APPROVED** [review]

**Comment by iSazonov** [comment]
Will it keep git history?

**Comment by KirkMunro** [comment]
Great question @iSazonov, I had assumed so, but hadn't looked into that.

Basing on what I read online, you can still see history beyond a file rename by using `git log --follow` with individual files. It also seems that GitHub does not support that in their platform yet.

**Comment by iSazonov** [comment]
>  It also seems that GitHub does not support that in their platform yet.

I saw this a day before :-( So I'd prefer to postpone the cosmetic fix. 
Really we have a lot of places where we could move/rename folders and files. But modern IDEs support source references very well and it is not problem to walk through code without debug and find a place of interest ignoring real folder and files names at all.
I never thought about it, but in fact I almost never open files directly - file search and the omnisharp  plugin are the most convenient and fast way for me.

**Comment by KirkMunro** [comment]
I don't feel renames of folders are merely cosmetic, because they aid in discovery, and when working in tools like Visual Studio I'll still use the solution tree and browse to specific parts of the code I'm working with, and `namespaces` is clearly the wrong folder name here.

That said, I agree that since GitHub does not support file history through renames, this should be postponed until such a time that they do.

**Pull request closed without merging**
