### PR TITLE
Fix `#requires -version` for pwsh 7 to include 6.1 and 6.2 in `PSCompatibleVersions`

### LINKED ISSUE #9938: #requires -version 6.2 throws on 7.0.0-preview.1
# Steps to reproduce

Add a #requires version statement with 6.2 to a script and run on 7.0.0-preview.1

```powershell
#requires -version 6.2
```

# Expected behavior

works

# Actual behavior

image

# Environment data

```none

Name                           Value
----                           -----
PSVersion                      7.0.0-preview.1
PSEdition                      Core
GitCommitId                    7.0.0-preview.1
OS                             Darwin 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.…
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### PR DESCRIPTION
**Pull request by bgelens**
# PR Summary

Fixed bug when pwsh 7.x is used and a script has a `#requires -version 6.2`

Updated `PSCompatibleVersions` to include 6.1 and 6.2

## PR Context

Fixes #9938

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/6/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [x] Issue filed: #9938
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [ ] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)

### CODE REVIEW

**Comment by adityapatwardhan** [comment]
@bgelens Thank you for your PR. Could you add tests here: https://github.com/PowerShell/PowerShell/blob/94b6b6f4f7985be7c006c3eb87691992d872142a/test/powershell/Language/Scripting/Requires.Tests.ps1#L3

**Comment by rjmholt** [comment]
The way `#requires -Version` works currently, it doesn't do a version comparison, but instead looks up the version in `$PSVersionTable.PSCompatibleVersions` which is supposed to be a mechanism that keeps track of PowerShell versions that are strictly incompatible with the current runtime. Arguably that mechanism isn't used properly, but it's still the way the logic works currently.

So for that reason, I think the @PowerShell/powershell-committee should review the mechanism of `#requires -Version` in this PR.

But also, if we go down the route of changing that mechanism, we should strip out the for-loop entirely and just do a version comparison.

Otherwise, the change that needs to occur is to add/change the right version in the list here:
https://github.com/PowerShell/PowerShell/blob/29e21470d9e0a6edd163bcff9b1574ccf557b18f/src/System.Management.Automation/engine/PSVersionInfo.cs#L108

**Comment by vexx32** [comment]
Version comparisons aren't expensive, are they? I can't think they'd be too expensive to do. We should just be doing a straight version comparison or we'll keep hitting this.

**Comment by bgelens** [comment]
I'll hold work on this PR until it is decided what path to take.

**Comment by rjmholt** [comment]
> Version comparisons aren't expensive, are they? I can't think they'd be too expensive to do. We should just be doing a straight version comparison or we'll keep hitting this.

Not expensive, but basically we compare the required version against every version the current PowerShell supports. To change this to a simple version > comparison represents a breaking change, so we just need the PowerShell Committee to opine.

**Comment by rkeithhill** [comment]
To avoid breaking change, maybe add a new parameter like `-MininumVersion` or `-SemanticVersion` that would accept semver ranges.

**Comment by SteveL-MSFT** [comment]
@PowerShell/powershell-committee reviewed this.  We don't think we should take a big change in the heuristic for checking compatible versions at this time.  Instead, our recommendation is for now update the compatible array with additions for 6.1 and 6.2.

**Comment by bgelens** [comment]
was on holiday without computer :) I changed the pr to include 6.1 and 6.2 statically defined

**Review by daxian-dbw — APPROVED** [review]

**Review by rjmholt — APPROVED** [review]

**Comment by bgelens** [comment]
Gentle ping 😄 @SteveL-MSFT

**Review by SteveL-MSFT — APPROVED** [review]
LGTM

**Comment by bgelens** [comment]
is this going to be merged?

**Comment by adityapatwardhan** [comment]
@bgelens I have added some tests as I asked earlier. Please have a look.

**Comment by bgelens** [comment]
sorry, that totally slipped my mind when I did the rework for static defined versions.

The test you added only test for 6.1 and 6.2, not 7.0. They should also validate 7.0 and when 7.1 is released the tests have to be updated to deal with the incremented minor version. This is fine but it would be best if the test would fail as soon as the PowerShell minor version is incremented and the test is not updated. I'm thinking about adding a test for 7.1 which should throw, once it doesn't throw, the test will fail and the author would be reminded that the test needs to be updated.

I'll add some more test logic and maybe revise the current once a little bit if that is alright?

Also, we currently have the same issue with PowerShell 6.2
image

Should I create a PR for the 6.2 branch as well?

**Comment by adityapatwardhan** [comment]
@bgelens I like the idea to add a test for 7.1 which expects to throw. Also maybe instead of having a static list of versions, we can use `$PSVersionTable.PSCompatibleVersions` for generating the test cases.

**Comment by bgelens** [comment]
I was thinking the same but, as PSCompatibleVersions list was not updated before, this was the cause of the issue in the first place. So to spot regression, we cannot rely on this method I think. 

Also the current version of PowerShell is now automatically used (based on the assembly version) in this list so we could add the tests for 6.0 until 6.2 statically and autogenerate the list for 7.x. If x is not 0, count down to 0 and add each minor (this assumes that there will never be a jump from PowerShell 7.0 to 7.2 for example). Then, add a minor to test a throw to occur.

**Comment by bgelens** [comment]
@adityapatwardhan I've added tests for PSVersionTable as some of discussed made more sense in that context. I also updated the requires test. Please let me know if they are ok now

**Review by adityapatwardhan — APPROVED** [review]

**Pull request merged**
