### PR TITLE
Fix regression -Tail 0 -Wait

### LINKED ISSUE #20731: PS 7.4.0: "-Tail 0" ignores "-Wait" and immediately stops Get-Content
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)
- [X] Search the existing issues.
- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).
- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://learn.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).

### Steps to reproduce

```
Get-Content -Path "<any file>" -Wait -Tail 0
```

### Expected behavior

```console
PS> Get-Content -Path "<any file>" -Wait -Tail 0
<no file content, waiting for new content>
```

### Actual behavior

```console
PS> Get-Content -Path "<any file>" -Wait -Tail 0
PS> <Get-Content immediately stops>
```

### Error details

_No response_

### Environment data

```powershell
PSVersion: 7.4.0
PSEdition: Core
GitCommitId: 7.4.0
OS: Microsoft Windows 10.0.19044
Platform: Win32NT
PSCompatibleVersions: {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion: 2.3
SerializationVersion: 1.1.0.1
WSManStackVersion: 3.0
```

### Visuals

gc-tail-broken

### PR DESCRIPTION
**Pull request by CarloToso**
# PR Summary
Fixes a regression introduced by #19715; when Get-Content -Wait is used with -Tail 0 wait is ignored

## PR Context
fixes #20731 @mklement0 

## PR Checklist

- [x] [PR has a meaningful title](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
    - Use the present tense and imperative mood when describing your changes
- [x] [Summarized changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] [Make sure all `.h`, `.cpp`, `.cs`, `.ps1` and `.psm1` files have the correct copyright header](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
- [x] This PR is ready to merge and is not [Work in Progress](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---work-in-progress).
    - If the PR is work in progress, please add the prefix `WIP:` or `[ WIP ]` to the beginning of the title (the `WIP` bot will keep its status check at `Pending` while the prefix is present) and remove the prefix when the PR is ready.
- **[Breaking changes](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#making-breaking-changes)**
    - [x] None
    - **OR**
    - [ ] [Experimental feature(s) needed](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/main/reference/7.3/Microsoft.PowerShell.Core/About/about_Experimental_Features.md)
        - [ ] Experimental feature name(s): 
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] [Documentation needed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#pull-request---submission)
        - [ ] Issue filed: 
- **Testing - New and feature**
    - [ ] N/A or can only be tested interactively
    - **OR**
    - [x] [Make sure you've added a new test if existing tests do not effectively test the code changed](https://github.com/PowerShell/PowerShell/blob/master/.github/CONTRIBUTING.md#before-submitting)
- **Tooling**
    - [ ] I have considered the user experience from a tooling perspective and don't believe tooling will be impacted.
    - **OR**
    - [ ] I have considered the user experience from a tooling perspective and opened an issue in the relevant tool repository. This may include:
        - [ ] Impact on [PowerShell Editor Services](https://github.com/PowerShell/PowerShellEditorServices) which is used in the [PowerShell extension](https://github.com/PowerShell/vscode-powershell) for VSCode
        (which runs in a different PS Host).
            - [ ] Issue filed: 
        - [ ] Impact on Completions (both in the console and in editors) - one of PowerShell's most powerful features.
            - [ ] Issue filed: 
        - [ ] Impact on [PSScriptAnalyzer](https://github.com/PowerShell/PSScriptAnalyzer) (which provides linting & formatting in the editor extensions).
            - [ ] Issue filed: 
        - [ ] Impact on [EditorSyntax](https://github.com/PowerShell/EditorSyntax) (which provides syntax highlighting with in VSCode, GitHub, and many other editors).
            - [ ] Issue filed:

### CODE REVIEW

**Review by iSazonov — APPROVED** [review]
It would be great to add tests for `-Wait`.

**Comment by NoMoreFood** [comment]
Since this was an unintended breaking change, it would be great to see this incorporated in 7.4.1.

**Review by SteveL-MSFT — CHANGES_REQUESTED** [review]
Please add a test

**Comment by CarloToso** [comment]
> Please add a test

Done (unrelated test failure)

**Review by SteveL-MSFT — APPROVED** [review]

**Comment by NoMoreFood** [comment]
Disappointingly, looks like this didn't make it to 7.4.1.  Is there still hope for 7.4.2?  Being able to tail a log file like this is very important for adhoc administrator use, and I know I've personally used it scripts that watch log files.

**Comment by iSazonov** [comment]
Will be in 7.4.2.

**Pull request merged**
