### PR TITLE
Removed unused help providers and related classes.

### PR DESCRIPTION
**Pull request by adityapatwardhan**
We do not publish any help content for FAQ, General and Glossary help providers. These were only used in v1 of Powershell.

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@adityapatwardhan Please find appropriate reviewers for your PR.

**Comment by adityapatwardhan** [comment]
@Francisco-Gamino  Can you have a look?

**Comment by SteveL-MSFT** [comment]
@joeyaiello do you have any concerns if we remove support for these help providers?

**Comment by mirichmo** [comment]
I think you meant to add Francisco as a reviewer.

**Comment by Francisco-Gamino** [comment]
@adityapatwardhan : We need to update the update-help schema validation to no longer reference the schemas you are removing. Also, we might need to update the documentation for provider help. Could you please open issues for these? Thanks.

**Review by Francisco-Gamino — APPROVED** [review]

**Comment by adityapatwardhan** [comment]
@Francisco-Gamino I have removed the references to the XSDs that have been removed by this PR.

**Comment by adityapatwardhan** [comment]
@PowerShell/powershell-maintainers This is ready to merge.

**Pull request merged**
